### ISSUE TITLE
tf.maximum does not return nan when inputs contain nan

### ISSUE THREAD

**Issue by meijun** [tensorflow/tensorflow#12659]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux CentOS 7
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 2.7.13
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 8.0/6.0
- **GPU model and memory**: Tesla K40m, 11439MiB
- **Exact command to reproduce**: python main.py

### Describe the problem
`tf.maximum(a, b)` should return `nan` when `a` or `b` contain `nan`. However, it does not at some cases.

### Source code / logs
main.py
```python
import tensorflow as tf
import numpy as np

a = tf.placeholder(dtype=tf.float32)
max_a = tf.maximum(a, 1.)
with tf.Session():
    print max_a.eval(feed_dict={a: np.nan})
```
The output is:
```
1.0
```

**Comment by jart** [comment]
Well that's concerning. What's odd is that if you don't use `feed_dict`, then it actually does return `nan`:

```pycon
>>> tf.Session().run(tf.maximum(np.nan, 1.))
nan
```

What do you think about this @mrry?

**Comment by mrry** [comment]
When I run @meijun's code on my CPU-only workstation, I get the expected result (`nan`). Also, I think @jart's version (which passes `np.nan` as a constant) will end up running on the CPU as part of a constant folding pass.

I suspect the problem might be in the GPU implementation of `tf.maximum()`. This looks like code that hasn't changed for a long time, and is basically a call into Eigen. Perhaps @benoitsteiner knows a potential cause for the discrepancy?

**Comment by yongtang** [comment]
I tends to think the issue comes from using `std::max` as the op. As far as I know, `std::max` is implemented as `(a < b) ? b : a` which does not take into consideration if `a` or `b` is `nan`.

For example, with the following:
```c++
$ cat max.cpp 
#include <algorithm>

int main(int argc, char *argv[])
{
    printf("std::max(1., nan) = %f\n", std::max(1.0, std::numeric_limits<double>::quiet_NaN()));
    printf("std::max(nan, 1.) = %f\n", std::max(std::numeric_limits<double>::quiet_NaN(), 1.0));

    return 0;
}
$ g++ max.cpp
$ ./a.out 
std::max(1., nan) = 1.000000
std::max(nan, 1.) = nan
$ 
```

And in TensorFlow with CPU version:
```python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import numpy as np
>>> 
>>> print tf.Session().run(tf.maximum(np.nan, 1.))
nan
>>> 
>>> print tf.Session().run(tf.maximum(1., np.nan))
1.0
>>> 
>>> a = tf.placeholder(dtype=tf.float32)
>>> max_a = tf.maximum(a, 1.)
>>> with tf.Session():
...     print max_a.eval(feed_dict={a: np.nan})
... 
nan
>>> a = tf.placeholder(dtype=tf.float32)
>>> max_a = tf.maximum(1., a)
>>> with tf.Session():
...      print max_a.eval(feed_dict={a: np.nan})
... 
1.0
>>> 
```

**Comment by yongtang** [comment]
Depending on what the desired output is, the fix might varies.

In C99' math.h there is `fmax` which covers `nan`. However, the behavior is exactly opposite:
http://en.cppreference.com/w/c/numeric/math/fmax
> Error handling
> This function is not subject to any of the error conditions specified in math_errhandling.
> If the implementation supports IEEE floating-point arithmetic (IEC 60559),
> - If one of the two arguments is NaN, the value of the other argument is returned
> - Only if both arguments are NaN, NaN is returned

To achieve the same behavior as `numpy` I think `isnan()` might have to be used even though this is less ideal.

**Comment by yongtang** [comment]
The behavior of `numpy`:
```python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.max([float('1'), float('nan')])
nan
>>> np.max([float('nan'), float('1')])
nan
>>> 
```

**Comment by yongtang** [comment]
On GPU the issue exists as well:
```python
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import numpy as np
>>> 
>>> print tf.Session().run(tf.maximum(np.nan, 1.))
2017-09-15 16:17:47.560456: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-09-15 16:17:47.560956: I tensorflow/core/common_runtime/gpu/gpu_device.cc:965] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.11GiB
2017-09-15 16:17:47.560992: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1055] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
nan
>>> 
>>> print tf.Session().run(tf.maximum(1., np.nan))
2017-09-15 16:18:14.369889: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1055] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
1.0
>>> 
>>> a = tf.placeholder(dtype=tf.float32)
>>> max_a = tf.maximum(a, 1.)
>>> with tf.Session():
...     print max_a.eval(feed_dict={a: np.nan})
... 
2017-09-15 16:18:44.264749: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1055] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
1.0
>>> a = tf.placeholder(dtype=tf.float32)
>>> max_a = tf.maximum(1., a)
>>> with tf.Session():
...   print max_a.eval(feed_dict={a: np.nan})
... 
2017-09-15 16:19:20.710406: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1055] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
1.0
>>> 
```

**Comment by yongtang** [comment]
@mrry @jart @benoitsteiner I do think the issue may need to be addressed one way or another, either stick with `numpy` or stick with `<math.h>`' `fmax()`.

The reason is that `std::max()` is mathematically problematic:
```
std::max(1., nan) != std::max(nan, 1.)

std::max(1., nan) == std::min(1, nan)
```

**Comment by yongtang** [comment]
Actually it seems numpy defined `maximum` and `fmax` for different cases already:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.maximum.html
```
See also
minimum Element-wise minimum of two arrays, propagates NaNs.
fmax    Element-wise maximum of two arrays, ignores NaNs.
amax    The maximum value of an array along a given axis, propagates NaNs.
nanmax  The maximum value of an array along a given axis, ignores NaNs.
```

**Comment by npanpaliya** [comment]
We are also facing same problem with TF's relu operator test case for NaNs on Linux RHEL ppc64le. 
Relu operator computes rectified max which calls Eigen's cwiseMax function. 
The behavior is weird on ppc64le shown by below code snippet-
```
import tensorflow as tf
import numpy as np
#from tensorflow.python.ops import nn_ops

with tf.Session() as sess:
  for i in range(18):
    x = np.zeros(i) + np.nan
    z = tf.nn.relu(tf.constant(x))
#    z = tf.maximum(x, np.zeros(i))
    result = sess.run(z)
    np.isnan(result).all()
    print("For i = %d, result is %s" % (i, result))
```
Output of this on ppc64le:
```
For i = 0, result is []
For i = 1, result is [ nan]
For i = 2, result is [ 0.  0.]
For i = 3, result is [  0.   0.  nan]
For i = 4, result is [ 0.  0.  0.  0.]
For i = 5, result is [  0.   0.   0.   0.  nan]
For i = 6, result is [ 0.  0.  0.  0.  0.  0.]
For i = 7, result is [  0.   0.   0.   0.   0.   0.  nan]
For i = 8, result is [ 0.  0.  0.  0.  0.  0.  0.  0.]
For i = 9, result is [  0.   0.   0.   0.   0.   0.   0.   0.  nan]
For i = 10, result is [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
For i = 11, result is [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  nan]
For i = 12, result is [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
For i = 13, result is [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  nan]
For i = 14, result is [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
For i = 15, result is [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  nan]
For i = 16, result is [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
For i = 17, result is [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  nan]
```
For odd sized array, all elements in output are 0 except last element. And for even sized input array, output contains all zeros. 
On x86, output of same code is
```
For i = 0, result is []
For i = 1, result is [ nan]
For i = 2, result is [ nan  nan]
For i = 3, result is [ nan  nan  nan]
For i = 4, result is [ nan  nan  nan  nan]
For i = 5, result is [ nan  nan  nan  nan  nan]
For i = 6, result is [ nan  nan  nan  nan  nan  nan]
For i = 7, result is [ nan  nan  nan  nan  nan  nan  nan]
For i = 8, result is [ nan  nan  nan  nan  nan  nan  nan  nan]
For i = 9, result is [ nan  nan  nan  nan  nan  nan  nan  nan  nan]
For i = 10, result is [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
For i = 11, result is [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
For i = 12, result is [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
For i = 13, result is [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
For i = 14, result is [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
For i = 15, result is [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
For i = 16, result is [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan
  nan]
For i = 17, result is [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]
```

Which linux architecture this original issue is reported on? And could anyone give any pointers on how to make TF behave similar to numpy. I know underlying implementation of this max operator is in Eigen. I tried modifying Eigen's code too for ppc64le (Altivec/PacketMath.h) but no luck.
Please refer [our issue](https://github.com/tensorflow/tensorflow/issues/11603) for more details.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by npanpaliya** [comment]
Request tensorflow core members to provide some guidance on this issue. I'm also discussing this with Eigen community.

**Comment by mrry** [comment]
(Assigning @benoitsteiner as the most obvious intersection of the TensorFlow core team and Eigen community.)

**Comment by npanpaliya** [comment]
Raised a bug with Eigen Community - http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1494

**Comment by tensorflowbutler** [comment]
A member of the TensorFlow organization has replied after the stat:awaiting tensorflower label was applied.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by smatzek** [comment]
Issue #11603 is similar to this and might well be a dup.
The differences seen in 11603 and here likely come down to the architecture specific implementations of Eigen's PacketMath pmax function.

Per [IEEE-754R](https://msdn.microsoft.com/en-us/library/windows/desktop/jj218760(v=vs.85).aspx#alpha_754_Deviations) the behavior should be:

min(x,QNaN) == min(QNaN,x) == x (same for max)

In practice with std::max we see:
std::max(nan, x) = nan
std::max(x, nan) = x

In Eigen's pmax functions it differs per architecture:

**x86 Eigen PacketMath pmax**
Through Eigen [bug 1373](http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1373) the x86 archs under Eigen/src/Core/arch were changed to match std::max's behavior of always returning the first argument when comparing NaNs.  Previous to this it followed the Intel SIMD intrinsics' behavior of always returning the second argument.

**Cuda Eigen PacketMath pmax**
Float and double are implemented using [fmaxf](http://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__SINGLE.html#group__CUDA__MATH__SINGLE_1g6e7516db46be25c33fb26e203287f2a3) and [fmax](http://docs.nvidia.com/cuda/cuda-math-api/group__CUDA__MATH__DOUBLE.html#group__CUDA__MATH__DOUBLE_1g8f5b0627e6706e432728bd16cb326754) respectively.  Per CUDA's API doc these handle NaNs like this: "If one argument is NaN, returns the numeric argument."

So the Eigen CUDA impl is following IEEE-754R in this respect.

Half math is a bit different and is using > and < operators on the respective halves.

**ALTIVEC (used by ppc64le) Eigen PacketMath pmax**

The pmax functions are implemented using the vec_max intrinsic which follows IEEE-754R and thus returns numeric for numeric vs NaN comparisons.

So to resolve the issue of differing functionality between std::max, x86 Eigen, and CUDA/ALTIVEC Eigen a decision has to be made which behavior is the desired behavior.

The changes under Eigen 1373 were done because it "makes the Eigen Tensor library properly propagate NaNs for the Relu operator, which is performance critical for neural net models."

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 91 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 106 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 121 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 136 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 151 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 166 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 181 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by skye** [comment]
Hi, is this still an issue?

**Comment by smatzek** [comment]
To my knowledge this is still an issue. The ALTIVEC (ppc64le) pmin/pmax functions in Eigen were changed to match x86 behavior, but there is still differing behavior between CPU and GPU calculations with NaNs in min/max.  The CUDA/GPU implementation in Eigen uses CUDA API calls which will give different results from the x86 and ppc64le CPU call as discussed in my comment above.

I believe this CPU-GPU discrepancy needs to be addressed so operations give the same result regardless of the device they run on. It would help if TensorFlow weighed in on which behavior it desires in the Eigen functions / tensor operations and then chime in on http://eigen.tuxfamily.org/bz/show_bug.cgi?id=564.

Once the desired behavior is chosen the appropriate changes can be pushed into the various architecture implementations in Eigen to make them align.

**Comment by skye** [comment]
@rmlarsen are you a good person to look at this, or can you redirect as necessary? Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by harshini-gadige** [comment]
@mrry Could you please look into this issue ?

**Comment by mrry** [comment]
@harshini-gadige This is an issue in Eigen, which is not my area of expertise.

**Comment by smatzek** [comment]
As I've stated previously, it's not so much an issue with Eigen as it is a lack of direction or choice from TensorFlow as to what TensorFlow's preferred behavior is for the min and max operations when it comes to NaNs. Once that is known, it is relatively simple to change the code to be consistent in Eigen.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rmlarsen: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment]
This is a stale issue. Please check the issue with latest TensorFlow. If the issue still persists in the newer version of TF, please feel free to reopen it by providing details about the issue and a standalone code to reproduce the issue. Thanks!

**Comment by ymodak** [comment]
This is fixed with latest version of  TF  version '1.15.0-dev20190821' using cpu as well as gpu accelerator.
```python
import tensorflow as tf
import numpy as np

a = tf.placeholder(dtype=tf.float32)
max_a = tf.maximum(a, 1.)
with tf.Session():
    print(max_a.eval(feed_dict={a: np.nan}))
#prints 
nan
```
Feel free to reopen if still have problems. Thanks!

**Comment by smatzek** [comment]
The problem still exists. I used the latest tf-nightly-gpu container, tensorflow/tensorflow:nightly-gpu-py3.

```
pip list | grep tf
tf-estimator-nightly 1.14.0.dev2019082801
tf-nightly-gpu       1.15.0.dev20190821  
```

Test program:
```python
import tensorflow as tf
import numpy as np

cpu_device='/cpu:0'
gpu_device='/device:GPU:0'

devices = [cpu_device, gpu_device]

for device in devices:
    print('Testing device %s' % device)
    a = tf.placeholder(dtype=tf.float32)
    with tf.device(device):
        max_a = tf.maximum(a, 1.)
        max_b = tf.maximum(1., a)
    with tf.Session():
        print('max(nan, 1.): %s' % max_a.eval(feed_dict={a: np.nan}))
        print('max(1., nan): %s' % max_b.eval(feed_dict={a: np.nan}))
```

Outputs:
```
Testing device /cpu:0
max(nan, 1.): nan
max(1., nan): 1.0
Testing device /device:GPU:0
max(nan, 1.): 1.0
max(1., nan): 1.0
```

So we are still observing the difference which can be described as the CPU implementation following the std::max convention while the GPU op implementation is following IEEE-754R, per my comments here: https://github.com/tensorflow/tensorflow/issues/12659#issuecomment-368129230

If we want standardized behavior out of TensorFlow for this operation it's a matter of determining which behavior is desired and then getting the changes in Eigen. Additional discussion on the pros/cons of std::max vs IEEE-754R behavior and how to support both behaviors via API choice has occured in Eigen bug 564 over the past few months.

**Comment by smatzek** [comment]
@ymodak I do not have the authority to re-open the issue.

**Comment by smatzek** [comment]
This also reproduces in TensorFlow 2.0 at commit https://github.com/tensorflow/tensorflow/tree/b8b60ae09afb3b05dde9f183bac587c7dd437c78 from the r2.0 branch:

```python
import tensorflow as tf
import numpy as np

cpu_device='/cpu:0'
gpu_device='/device:GPU:0'

devices = [cpu_device, gpu_device]

for device in devices:
    print('Testing device %s' % device)
    with tf.device(device):
        print('max(nan, 1.): %s' % tf.maximum(np.nan, 1.))
        print('max(1, nan): %s' % tf.maximum(1., np.nan))
```

Outputs:
```
Testing device /cpu:0
max(nan, 1.): tf.Tensor(nan, shape=(), dtype=float32)
max(1, nan): tf.Tensor(1.0, shape=(), dtype=float32)
Testing device /device:GPU:0
max(nan, 1.): tf.Tensor(1.0, shape=(), dtype=float32)
max(1, nan): tf.Tensor(1.0, shape=(), dtype=float32)
```

**Comment by smatzek** [comment]
One further datapoint. On the Intel MKL TensorFlow build the test program, modified to only test the CPU device, outputs:

```
max(nan, 1.): nan
max(1., nan): 1.0
```

```
conda list | grep tensorflow
tensorflow                1.14.0          mkl_py36h2526735_0    anaconda
tensorflow-base           1.14.0          mkl_py36h7ce6ba3_0    anaconda
tensorflow-estimator      1.14.0                     py_0    anaconda
```

**Comment by jkbjh** [comment]
On 2.2.0-dev20200131 this also happens for sign:

    import tensorflow as tf
    import numpy as np
    print("reduce_max:", tf.reduce_max(tf.fill((1,4,4), float("NaN"))))
    print("sign:", tf.sign(tf.fill((1,4,4), float("NaN"))))

Output:

    reduce_max: tf.Tensor(-inf, shape=(), dtype=float32)
    sign: tf.Tensor(
    [[[0. 0. 0. 0.]
      [0. 0. 0. 0.]
      [0. 0. 0. 0.]
      [0. 0. 0. 0.]]], shape=(1, 4, 4), dtype=float32)

But not on numpy:

    print("np.max:", np.max(tf.fill((1,4,4), float("NaN"))))
    print("np.sign:", np.sign(tf.fill((1,4,4), float("NaN"))))

    np.max: nan
    np.sign: [[[nan nan nan nan]
      [nan nan nan nan]
      [nan nan nan nan]
      [nan nan nan nan]]]

**Comment by sachinprasadhs** [comment]
@meijun , The issue has been fixed in the latest Tensorflow 2.5 version for both CPU and GPU, please find the [gist](https://colab.research.google.com/gist/sachinprasadhs/240087877dd9dbc17ff2077bcf8f6239/untitled.ipynb) here and the below output.
```
import tensorflow as tf
print(tf.__version__)
2.5.0
import numpy as np
print("1. ",tf.maximum(1.,np.nan))
print("2. ",tf.maximum(np.nan,1.))


import numpy as np
print("1. ",tf.maximum(1.,np.nan))
print("2. ",tf.maximum(np.nan,1.))

1.  tf.Tensor(nan, shape=(), dtype=float32)
2.  tf.Tensor(nan, shape=(), dtype=float32)
```

**Comment by smatzek** [comment]
The output above shows `tf.maximum` returning the `nan` regardless of order. This doesn't align with IEEE-754R or the std::max convention see [this comment above](https://github.com/tensorflow/tensorflow/issues/12659#issuecomment-526257969).

What device was used above (CPU or NVIDIA GPU?), if CPU, was Eigen or MKL used?

**Comment by sachinprasadhs** [comment]
@smatzek I have reproduced it in google colab, in both CPU and GPU regardless of nan order the output should return nan for all right as per the issue.

**Comment by austinpagan** [comment]
Are we AGREED that the consensus is max and min should always return NaN if either of the inputs to the function is a NaN?
I still see some suggestions in some places that it should in fact return the non-NaN value...

**Comment by kevint324** [comment]
> Are we AGREED that the consensus is max and min should always return NaN if either of the inputs to the function is a NaN?
> I still see some suggestions in some places that it should in fact return the non-NaN value...

https://numpy.org/doc/stable/reference/generated/numpy.maximum.html
https://pytorch.org/docs/stable/generated/torch.maximum.html

Current behavior makes sense if you look at the numpy and pytorch. 
It make sense to me that everybody aligns to numpy.
