### ISSUE TITLE
Android: Error:(68, 13) Failed to resolve: org.tensorflow:tensorflow-android:+

### ISSUE THREAD

**Issue by anonym24** [tensorflow/tensorflow#13653]
Error:(68, 13) Failed to resolve: org.tensorflow:tensorflow-android:+

Are there some problems with remote repository?

```
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0-beta7'
    }
}

allprojects {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
        maven { url "https://jitpack.io" }
    }
}
```

https://bintray.com/google/tensorflow/tensorflow-android

![screenshot_1](https://user-images.githubusercontent.com/8851301/31483788-91917476-af36-11e7-93cd-d9749967982d.png)

**Comment by anonym24** [comment]
temporary fast solution

download jar file https://ci.tensorflow.org/view/Nightly/job/nightly-android/lastStableBuild/artifact/out/libandroid_tensorflow_inference_java.jar and put to **project_name\app\libs** folder

add `compile files('libs/libandroid_tensorflow_inference_java.jar')` to you app `build.gradle` file

download **libtensorflow_inference.so** for armeabi-v7a (or for other architecture) 
https://ci.tensorflow.org/view/Nightly/job/nightly-android/lastStableBuild/artifact/out/native/libtensorflow_inference.so/armeabi-v7a/libtensorflow_inference.so and put to **project_name\app\src\main\jniLibs\armeabi-v7a** folder

**Comment by rolf-baxter** [comment]
Also getting this problem.

**Comment by vamshikhoslalabs** [comment]
+1

**Comment by themuck** [comment]
Failed to resolve: org.tensorflow:tensorflow-android:+ 

same here...

**Comment by kbsriram** [comment]
My apologies folks - while re-organizing the bintray repository the tensorflow-android aar artifact was incorrectly disconnected from jcenter. We're working to resolve it ASAP.

In the interim, please use the workaround in https://github.com/tensorflow/tensorflow/issues/13653#issuecomment-336038164 or you can temporarily add the tensorflow bintray maven repository  in your build.gradle

```
...
repositories {
  jcenter()
  maven {
    url 'https://google.bintray.com/tensorflow'
  }
  ...
```

**Comment by vclteam** [comment]
This solution help to compile, but unfortunately the speech demo is not working

**Comment by vamshikhoslalabs** [comment]
Same here helps to compile, but TF Detect is crashing.

**Comment by asimshankar** [comment]
@vclteam @vamshikhoslalabs : Could you elaborate a bit on the speech demo not working? For example, can you share some device logs that might shed some light on why the demo may be crashing?

@andrewharp FYI

**Comment by MusaMahmood** [comment]
"Caused by: java.lang.RuntimeException: Native TF methods not found; check that the correct native libraries are present in the APK." 
Same error on all apps built with [this workaround](https://github.com/tensorflow/tensorflow/issues/13653#issuecomment-336038164)

**Comment by anonym24** [comment]
@asimshankar 
native libraries:
https://ci.tensorflow.org/view/Nightly/job/nightly-android/lastStableBuild/artifact/out/native/libtensorflow_inference.so/

**Comment by asimshankar** [comment]
@anonym24 : I didn't quite follow your comment. Could you elaborate on what you meant? Are you able to run the speech demo?

It seems @MusaMahmood got things working after placing `libtensorflow_inference.so` in the right folder.

So at this point, I'm a bit confused about whether anyone is having a problem with the speech demo ( @anonym24 @vclteam @vamshikhoslalabs )

If so, please feel free to file a separate issue so we can keep this one focused on the binaries being available in jcenter (as per https://github.com/tensorflow/tensorflow/issues/13653#issuecomment-336145329 )

Thanks.

**Comment by anonym24** [comment]
guys, if you use _tensorflow example project_ (not yours)
you have to check the correct path for native libraries:

for newly created projects in Android Studio it is **project_name\app\src\main\jniLibs\armeabi-v7a**

for _tensorflow example project_ it is **project_name\libs\armeabi-v7a** (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android)

projects overrides default path in `build.gradle` file:  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/build.gradle#L53

`def nativeOutDir = 'libs/' + cpuType`

**Comment by andrewharp** [comment]
Rather than dealing with individual native .so files, it should be easier just to use the [AAR itself](https://ci.tensorflow.org/view/Nightly/job/nightly-android/lastSuccessfulBuild/artifact/out/tensorflow.aar), which includes native libs for 32 and 64 bit architectures. Then just import it according to [these instructions](https://stackoverflow.com/questions/29826717/how-to-import-a-aar-file-into-android-studio-1-1-0-and-use-it-in-my-code) on SO:
```
To import a .aar library:
Go to File>New>New Module
Select "Import .JAR/.AAR Package" and click next.
Enter the path to .aar file and click finish.
Go to File>Project Structure (Ctrl+Shift+Alt+S).
Under "Modules," in left menu, select "app."
Go to "Dependencies tab.
Click the green "+" in the upper right corner.
Select "Module Dependency"
Select the new module from the list.
```

**Comment by drpngx** [comment]
It looks like this is solved.

**Comment by abedi19** [comment]
please let me know when this issue was fixed.

**Comment by kbsriram** [comment]
The original issue was missing android artifacts from jcenter, leading to compile failures like
 `Failed to resolve: org.tensorflow:tensorflow-android:+`

This issue was fixed over Sunday/Monday (Oct 15th/16th 2017) and at this point all tensorflow-android aar versions should accessible from jcenter again.

**Comment by abedi19** [comment]
so what do we do know. If we compile should it work know automatically.

**Comment by imaoldboy** [comment]
I got this when run the speech demo:
 Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: Shape must be rank 1 but is rank 0 for 'Mfcc' (op: 'Mfcc') with input shapes: [16000,0,257], [].

**Comment by imaoldboy** [comment]
@asimshankar, I got this when run the speech demo:
Caused by: java.io.IOException: Not a valid TensorFlow Graph serialization: Shape must be rank 1 but is rank 0 for 'Mfcc' (op: 'Mfcc') with input shapes: [16000,0,257], [].

**Comment by andrewharp** [comment]
@imaoldboy libtensorflow_demo.so is an optional library, so there is no issue due to it being missing (it only contains object tracking and accelerated image color conversion code).

libtensorflow_inference.so is the one that contains TensorFlow itself. Are you depending on `org.tensorflow:tensorflow-android:+` and still seeing this issue? Can you tell what version of the TF native library you're getting?

**Comment by imaoldboy** [comment]
@andrewharp I just download the code from github.com and follow the instruction of "https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android#building-in-android-studio-using-the-tensorflow-aar-from-jcenter"

**Comment by imaoldboy** [comment]
I give up this android speech demo stuff。

**Comment by andrewharp** [comment]
@imaoldboy We put compiled native libs for x86 into the AAR, but it's not tested as thoroughly so it wouldn't be too surprising if you ran into issues using an emulator.

The versioning issues we were having earlier should be resolved now, so you might try clearing your gradle caches to force it to download the latest AAR.

**Comment by dnpawate** [comment]
tensorflow / tensorflow
Code  Issues 1,308  Pull requests 199  Projects 0  Pulse
Jump to bottom Open
[tensorflow] Android studio doesn't fetch setUseNNAPI #17924
@dnpawate
dnpawate opened this issue 
about 2 hours ago 
in build.gradle below dependency will not download
latest file of ./tensorflow/contrib/lite/java/src/main/java/org/tensorflow/lite/Interpreter.java

dependencies {
compile 'org.tensorflow:tensorflow-lite:+'
}

Hence we are getting unresolved symbol for new API setUseNNAPI

as gradle unable to download new API as below

/** Turns on/off Android NNAPI for hardware acceleration when it is available. */
public void setUseNNAPI(boolean useNNAPI) {
if (wrapper != null) {
wrapper.setUseNNAPI(useNNAPI);
} else {
throw new IllegalStateException("NativeInterpreterWrapper has already been closed.");
}
}

**Comment by thesunbird** [comment]
Nightly Android builds at https://ci.tensorflow.org/view/Nightly/job/nightly-android/lastStableBuild/artifact/out/libandroid_tensorflow_inference_java.jar seem to have vanished. Getting not found error. Anyone know where they moved to?

**Comment by gunan** [comment]
ci.tensorflow.org has been deprecated for a while.
It looks like we missed migrating this build.
@petewarden do we have an equivalent of this build in the new system?
What would be the best way to deliver the binaries for this?
