### ISSUE TITLE
Failed to synchronise stop event.

### ISSUE THREAD

**Issue by ramanmohan** [tensorflow/tensorflow#15915]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.4
- **Python version**: 3.6.3
- **Bazel version (if compiling from source)**: 0.9.0
- **GCC/Compiler version (if compiling from source)**:  5.4.0 
- **CUDA/cuDNN version**: 9.1/7.0.5
- **GPU model and memory**: GT 750M 2GB
- **Exact command to reproduce**: Run the custom program.

### Describe the problem
Trying to train a simple 5 layer model with 3.7million parameters that are trainable which would occupy around 1.5GB VRAM, the training fails instantly at the very first epoch. People who had similar error claimed that it was fixed in cuDNN 7.0.5 from this thread [#14363](https://github.com/tensorflow/tensorflow/issues/14363) . But this update isn't fixing the crash. I've posted the error log below:

### Source code / logs
```
Total params: 3,714,788
Trainable params: 3,714,788
Non-trainable params: 0
_________________________________________________________________
2018-01-06 21:58:27.567991: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:892] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-01-06 21:58:27.568491: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Found device 0 with properties: 
name: GeForce GT 750M major: 3 minor: 0 memoryClockRate(GHz): 0.967
pciBusID: 0000:01:00.0
totalMemory: 1.95GiB freeMemory: 1.60GiB
2018-01-06 21:58:27.568526: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1120] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: GeForce GT 750M, pci bus id: 0000:01:00.0, compute capability: 3.0)
Train on 646 samples, validate on 162 samples
Epoch 1/20
2018-01-06 21:58:30.447458: E tensorflow/stream_executor/cuda/cuda_driver.cc:1080] failed to synchronize the stop event: CUDA_ERROR_ILLEGAL_INSTRUCTION
2018-01-06 21:58:30.447529: E tensorflow/stream_executor/cuda/cuda_timer.cc:54] Internal: error destroying CUDA event in context 0x5650223aede0: CUDA_ERROR_ILLEGAL_INSTRUCTION
2018-01-06 21:58:30.447572: E tensorflow/stream_executor/cuda/cuda_timer.cc:59] Internal: error destroying CUDA event in context 0x5650223aede0: CUDA_ERROR_ILLEGAL_INSTRUCTION
2018-01-06 21:58:30.447629: F tensorflow/stream_executor/cuda/cuda_dnn.cc:2964] failed to set stream for cudnn handle: CUDNN_STATUS_MAPPING_ERROR
Aborted (core dumped)

```

**Comment by shivaniag** [comment]
@ramanmohan Did you try the steps suggested by @cliffwoolley from the thread #14363. 
Also adding @juliebernauer for any updates.

**Comment by juliebernauer** [comment]
@ramanmohan Please follow steps described in #14363 indeed. On our side it is fixed but happy to have a look into this if it fails in the NGC container. Thanks @shivaniag.

**Comment by ramanmohan** [comment]
I tried everything mentioned in the thread [#14363](https://github.com/tensorflow/tensorflow/issues/14363). I have TensorFlow 1.4.1 installed on my Ubuntu 16.04 along with CUDA 9.1 and cuDNN 7.0.5. I am using a Nvidia GeForce GT 750M.

It is still throwing the same error. @shivaniag  @juliebernauer

**Comment by blzq** [comment]
I'm having the same issue with the same GPU (GT 750M), using Arch Linux with Tensorflow 1.4.1, CUDA 9.1 and cuDNN 7.0.5, so perhaps it's an issue with this particular hardware.

**Comment by juliebernauer** [comment]
@ramanmohan @blzq Can you confirm you are using the container?

**Comment by blzq** [comment]
Using the container there's an additional message, which doesn't appear otherwise:

`I tensorflow/core/common_runtime/gpu/gpu_device.cc:1093] Ignoring visible gpu device (device: 0, name: GeForce GT 750M, pci bus id: 0000:01:00.0, compute capability: 3.0) with Cuda compute capability 3.0. The minimum required Cuda capability is 3.5.`

I assume this means that the GPU cannot be used?

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Awaiting TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging TensorFlower: It has been 14 days with no activity and the `awaiting tensorflower` label was assigned. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @tatianashp: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tatianashp** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
