### ISSUE TITLE
Output of Inceptionv3 slim 2016 tflite model is problematic

### ISSUE THREAD

**Issue by freedomtan** [tensorflow/tensorflow#16851]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: N/A, this is a bug report of a tflite model released by Google
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any one
- **TensorFlow installed from (source or binary)**: both
- **TensorFlow version (use command below)**: after TF Lite released
- **Python version**: both
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: N/A
- **Exact command to reproduce**: see descriptions below

It seems the output of the [inceptionv3 slim 2016 tflite model released by google](https://storage.googleapis.com/download.tensorflow.org/models/tflite/inception_v3_slim_2016_android_2017_11_10.zip) is problematic. I'll create another issue later. If you run [label_image for tflite](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/examples/label_image/label_image.md), you'll get

```bash
> ./label_image -m inceptionv3_slim_2016.tflite
Loaded model inceptionv3_slim_2016.tflite
resolved reporter
invoked 
average time: 1009.48 ms 
8.06111: 653 military uniform
6.19022: 668 mortarboard
5.83456: 401 academic gown
5.26993: 835 suit
4.80701: 855 theater curtain
```

If you convert InceptionV3 yourself, 
```bash
> curl http://download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz \
 | tar -C /tmp -xzf -
> bazel run --config=opt   //tensorflow/contrib/lite/toco:toco --  \
--input_file=/tmp/inception_v3_2016_08_28_frozen.pb  \
--output_file=/tmp/inceptionv3.tflite   --input_format=TENSORFLOW_GRAPHDEF \
--output_format=TFLITE   --inference_type=FLOAT   --input_shape=1,299,299,3 \
--input_array=input   --output_array=InceptionV3/Predictions/Reshape_1
```

and push the /tmp/inceptionv3.tflite to your android devices, then you can see expected results like

```bash
> ./label_image -m inceptionv3.tflite             
Loaded model inceptionv3.tflite
resolved reporter
invoked 
average time: 1020.93 ms 
0.496246: 653 military uniform
0.0764156: 668 mortarboard
0.0535454: 401 academic gown
0.030444: 835 suit
0.0191629: 855 theater curtain
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by freedomtan** [comment]
updated for the template

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gargn: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gargn: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gargn: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @gargn: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by meghna1301** [comment]
Hi, I am getting following error while trying to run label_image ( tensorflow lite ) with inception tflite model. Any idea what is going wrong ?

./label_image -m inceptionv3_slim_2016.tflite
Loaded model inceptionv3_slim_2016.tflite
resolved reporter
tensorflow/contrib/lite/kernels/concatenation.cc:74 t->dims->data[d] != t0->dims->data[d] (17 != 18)
Failed to allocate tensors!
Segmentation fault (core dumped)

**Comment by freedomtan** [comment]
@meghna1301: I can reproduce your problem with master branch. I don't know what happened. I guess some changes to TF Lite runtime broke files converted by old TOCO. You should create another issue I think.

**Comment by meghna1301** [comment]
@freedomtan : Thanks so much. When I tried with release branch, it worked perfectly. So, looks like that this issue came after last release ( 1.8).
Just FYI:
I was able to run MobileNet float model on master, however numbers were quite different than what I observed with release branch.

Log with master:
=================  
./label_image -m mobilenet_v1_1.0_224.tflite -c 100
Loaded model mobilenet_v1_1.0_224.tflite
resolved reporter
invoked 
average time: **1329.38 ms** 
0.859921: 905 window screen
0.057294: 829 strainer
0.0220685: 557 fire screen
0.0208552: 812 space heater
0.0097825: 795 shower curtain
==============
log with r1.8 -
==============
./label_image -m mobilenet_v1_1.0_224.tflite -c 1000
nnapi error: unable to open library libneuralnetworks.so
Loaded model mobilenet_v1_1.0_224.tflite
resolved reporter
initialized 
initialization time: 4.703 ms 
invoked 
average time: **12.9061 ms** 
0.479888: 534 dishrag
0.318539: 825 stole
0.101559: 912 wool
0.0152032: 412 apron
0.013553: 540 doormat

**Comment by freedomtan** [comment]
@andrefaraujo yes, for c != 1, when TF Lite runtime is used (NN API runtime is not used), prediction is meaningless. But, I think what @meghna1301  asked is performance. I haven't checked it yet.

@meghna1301 which platform you used to run this?

**Comment by shashishekhar** [comment]
There was a bug in the schema where the default values of dilation width and height factors were set to 0 instead of 1. This incorrect value will cause the slow kernel to be selected. 
This got fixed with recent update to [schema](https://github.com/tensorflow/tensorflow/commit/e41e70ed9827b81a07c42f68def80f3f61b70375#diff-16ca4f2738c3598cf9b1d79b45eed593)
This should be fixed on master now.

**Comment by zhengnianqing** [comment]
I use my own model  which has the op:concatenation in tflite on ios.When I use the function of "ResizeInputTensor" to resize the input,the similar problem happens,the error is  
"tensorflow/contrib/lite/kernels/concatenation.cc:74 t->dims->data[d] != t0->dims->data[d] (20 != 14).Failed to allocate tensors".
My tensorflow is r1.10?? How can I do?

**Comment by gargn** [comment]
@zhengnianqing Please file a new issue and provide reproducible steps. Include the code that calls the interpreter and the model file if possible.

**Comment by davlhd** [comment]
@zhengnianqing did you open a new issue? I am facing the same problem

**Comment by zhengnianqing** [comment]
No,but I am still facing  the same problem. I think It is brecause when converting the model to tflite,the model recordes some parameters that can not be changed, That's just my guess.You can open a new issue.

**Comment by Elites2017** [comment]
@davlhd @meghna1301 Where did you guys find the right config file for the mobilenet_v1_1.0_224 or which config file did you use? Because when I try to run the training with the other config files, it gives me an error of: ValueError: No variables to save

**Comment by davlhd** [comment]
@Elites2017 I used a cutom model

**Comment by Elites2017** [comment]
Ok. Did you successfully convert it to .tflite? Which custom model did you use?

**Comment by davlhd** [comment]
It converted but it tells me that
`concatenation.cc:74 t->dims->data[d] != t0->dims->data[d] (100 != 50) "Failed to allocate tensors"`
Its a proprietary model.

**Comment by Elites2017** [comment]
@davlhd Could you please give me a link to the config file or the pipeline file you edited to config it to train it?

**Comment by davlhd** [comment]
I am sorry I can't

**Comment by Elites2017** [comment]
@davlhd Could you please give me a link to the config file or the pipeline file you edited to config it to train it?

**Comment by Elites2017** [comment]
ok

> 
> 
> I am sorry I can't

Ok

**Comment by gargn** [comment]
@davlhd @Elites2017 Can you create new issues with as much information as you can provide to reproduce your issue. Preferably include the code you are using to call the model, the command you are using to convert the model, and any other general information you can provide. If you can provide your model with dummy weights that would also be helpful.
