### ISSUE TITLE
MKL_DNN is built during non-mkl builds.

### ISSUE THREAD

**Issue by gunan** [tensorflow/tensorflow#17816]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: 
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 14.04
- **TensorFlow installed from (source or binary)**:
Source
- **TensorFlow version (use command below)**:
master after 1.7
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
0.11
- **GCC/Compiler version (if compiling from source)**:
does not matter
- **CUDA/cuDNN version**:
n/a
- **GPU model and memory**:
n/a
- **Exact command to reproduce**:
```
bazel test --test_tag_filters=-no_oss,-oss_serial,-gpu,-benchmark-test -k --copt='-march=skylake-avx512' - //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/...
```

### Describe the problem
I expected to see some test failures, or some other build failures. no MKL code should be compiled with the above command.

### Source code / logs
```
ERROR: /home/kbuilder/.cache/bazel/_bazel_kbuilder/9a46bec5c8e82ceb5b4b229201d44d70/external/mkl_dnn/BUILD:3:1: Couldn't build file external/mkl_dnn/_objs/mkl_dnn/external/mkl_dnn/src/cpu/ref_lrn.pic.o: C++ compilation of rule '@mkl_dnn//:mkl_dnn' failed (Exit 1): clang failed: error executing command 
  (cd /home/kbuilder/.cache/bazel/_bazel_kbuilder/9a46bec5c8e82ceb5b4b229201d44d70/execroot/org_tensorflow && \
  exec env - \
    PATH=/bin:/usr/bin \
    PORTSERVER_ADDRESS=@unittest-portserver \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/usr/bin/python \
    PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
    TF_NEED_CUDA=0 \
    TF_NEED_OPENCL_SYCL=0 \
    TF_PYTHON_CONFIG_REPO=@org_tensorflow//third_party/toolchains/cpus/py \
  /usr/local/bin/clang -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/local/bin -B/usr/bin -fcolor-diagnostics -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections -DGEMMLOWP_ALLOW_SLOW_SCALAR_FALLBACK '-march=skylake-avx512' '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/external/mkl_dnn/_objs/mkl_dnn/external/mkl_dnn/src/cpu/ref_lrn.pic.d '-frandom-seed=bazel-out/k8-opt/bin/external/mkl_dnn/_objs/mkl_dnn/external/mkl_dnn/src/cpu/ref_lrn.pic.o' -fPIC -iquote external/mkl_dnn -iquote bazel-out/k8-opt/genfiles/external/mkl_dnn -iquote external/bazel_tools -iquote bazel-out/k8-opt/genfiles/external/bazel_tools -isystem external/mkl_dnn/include -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/include -isystem external/mkl_dnn/src -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src -isystem external/mkl_dnn/src/common -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src/common -isystem external/mkl_dnn/src/cpu -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src/cpu -isystem external/mkl_dnn/src/cpu/xbyak -isystem bazel-out/k8-opt/genfiles/external/mkl_dnn/src/cpu/xbyak -isystem external/bazel_tools/tools/cpp/gcc3 -fexceptions -fopenmp -no-canonical-prefixes -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/mkl_dnn/src/cpu/ref_lrn.cpp -o bazel-out/k8-opt/bin/external/mkl_dnn/_objs/mkl_dnn/external/mkl_dnn/src/cpu/ref_lrn.pic.o)
external/mkl_dnn/src/cpu/ref_lrn.cpp:20:10: fatal error: 'c_types_map.hpp' file not found
#include "c_types_map.hpp"
```

@tatianashp Could you add our Intel contacts to this issue?

**Comment by tatianashp** [comment]
Adding @agramesh1

**Comment by agramesh1** [comment]
@tatianashp thanks for letting us know, will look at it.

**Comment by mahmoud-abuzaina** [comment]
@gunan I am trying to reproduce this issue. Do you think it is related to clang or it can be reproduced by gcc?

**Comment by gunan** [comment]
I think the problem is mostly about mkl-DNN being included in BUILD rules when it is disabled. So it should not be compiler specific.
The compilation failure is just a symptom of the problem, I think.

**Comment by gunan** [comment]
But I think gcc should reproduce the issue.

**Comment by mahmoud-abuzaina** [comment]
Ok, I think I am able to reproduce it with gcc.

**Comment by mahmoud-abuzaina** [comment]
@gunan I created this PR #17934 which I think will fix this issue.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @jart: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tatianashp** [comment]
The issue have been resolved.

**Comment by xingao267** [comment]
Hi,

I'm seeing this failure with Bazel 0.12.0rc2 (probably Bazel head as well). Here is my build info:

System information
Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Debian 8
TensorFlow installed from (source or binary):
Source
TensorFlow version (use command below):
commit 7535f6beb7ba95bf54e1513b0c2c51b844a7a49f
Python version:
2.7.9
Bazel version (if compiling from source):
0.12.0rc2 (https://releases.bazel.build/0.12.0/rc2/index.html)
GCC/Compiler version (if compiling from source):
does not matter
CUDA/cuDNN version:
n/a
GPU model and memory:
n/a
Exact command to reproduce:
bazel test -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/contrib/... -//tensorflow/core:platform_setround_test -//tensorflow/go:test -//tensorflow/java:pom -//tensorflow/python/estimator:export_test

Describe the problem
Bazel tried to build @mkl_dnn and source code is not found.

Source code / logs
ERROR: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/mkl_dnn/BUILD:11:1: C++ compilation of rule '@mkl_dnn//:mkl_dnn' failed (Exit 1)
In file included from external/mkl_dnn/src/cpu/jit_avx2_convolution.cpp:20:
In file included from external/mkl_dnn/src/cpu/jit_avx2_convolution.hpp:23:
In file included from external/mkl_dnn/src/cpu/cpu_reducer.hpp:23:
external/mkl_dnn/src/common/mkldnn_thread.hpp:23:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
INFO: Elapsed time: 4.468s, Critical Path: 1.82s
FAILED: Build did NOT complete successfully

Can someone try this with Bazel 0.12.0rc2?

**Comment by tatianashp** [comment]
The PR just went through. Please try again in a day or so. If you still see error messages please reopen this issue.

**Comment by xingao267** [comment]
I just executed the same command with Tensorflow head at b874783ccdf4cc36cb3546e6b6a998cb8f3470bb. I'm still seeing the same error with Bazel 0.12.0rc2:

ERROR: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/mkl_dnn/BUILD:11:1: C++ compilation of rule '@mkl_dnn//:mkl_dnn' failed (Exit 1)
In file included from external/mkl_dnn/src/cpu/jit_uni_batch_normalization.cpp:22:
external/mkl_dnn/src/common/mkldnn_thread.hpp:23:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.

I don't see to have permission to reopen the issue.

**Comment by meteorcloudy** [comment]
@xingao267 Does the problem happen with Bazel 0.11.0?

**Comment by meteorcloudy** [comment]
Is `@mkl_dnn` supposed to be used for some targets?

**Comment by xingao267** [comment]
Just tried the same command with Bazel 0.11.1, it also failed. The log is 

ERROR: /root/.cache/bazel/_bazel_root/68a62076e91007a7908bc42a32e4cff9/external/mkl_dnn/BUILD:11:1: C++ compilation of rule '@mkl_dnn//:mkl_dnn' failed (Exit 1)
In file included from external/mkl_dnn/src/cpu/cpu_reorder.cpp:23:
In file included from external/mkl_dnn/src/cpu/jit_reorder.hpp:27:
In file included from external/mkl_dnn/src/cpu/simple_reorder.hpp:25:
external/mkl_dnn/src/common/mkldnn_thread.hpp:23:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^~~~~~~
1 error generated.
INFO: Elapsed time: 266.949s, Critical Path: 52.28s

Is some of the targets run trying to use @mkl_dnn?

**Comment by meteorcloudy** [comment]
@xingao267 , So this isn't a regression in Bazel 0.12.0, we should fix the dependency somewhere in TensorFlow

**Comment by mahmoud-abuzaina** [comment]
I am looking at this issue..

**Comment by mahmoud-abuzaina** [comment]
@xingao267 can you test again with this PR #18401 ?

**Comment by xingao267** [comment]
@mahmoud-abuzaina I tested it with Bazel 0.12.0rc3 and Bazel 0.11.1, and it builds.
