### ISSUE TITLE
Bug: CPU/Eigen fp16 matmul kernel fails on AVX512 systems

### ISSUE THREAD

**Issue by jbobba** [tensorflow/tensorflow#18676]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
('v1.8.0-rc0-561-g075fbb59d7', '1.8.0-rc0')
- **Python version**: 
Python 2.7.12
- **Bazel version (if compiling from source)**:
Build label: 0.11.0
- **GCC/Compiler version (if compiling from source)**:
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
- **CUDA/cuDNN version**:
NA
- **GPU model and memory**:
NA
- **Exact command to reproduce**:
bazel test --config=opt  -s //tensorflow/python/kernel_tests:batch_matmul_op_test

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

bazel test --config=opt  -s //tensorflow/python/kernel_tests:batch_matmul_op_test
On machines with AVX512, batch_matmul_op_test fails. Most likely culprit is Eigen's fp16 matmul running on CPU.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

======================================================================
FAIL: testBatchMatmulOp_float16_False_True_True (__main__.BatchMatmulOpTest)
----------------------------------------------------------------------

AssertionError: 
Not equal to tolerance rtol=0.0976562, atol=0.0976562
Mismatched value: a is different from b.
(mismatch 25.8125%)
 x: array([[[ 7532.,  8860.,  6856., ...,  6372.,  8070.,  8264.],
        [10400.,  9840.,  7188., ...,  8360.,  7640.,  9010.],
        [ 8172.,  6590.,  3046., ...,  7400.,  6224.,  7656.],...
 y: array([[[ 7824.,  8156.,  6804., ...,  6372.,  8064.,  8264.],
        [10140., 11500.,  8380., ...,  8360.,  7644.,  9010.],
        [ 8080.,  7964.,  5756., ...,  7404.,  6224.,  7656.],...

----------------------------------------------------------------------
Ran 4 tests in 0.681s

FAILED (failures=1)
not close where =  (array([0, 0, 0, ..., 9, 9, 9]), array([ 0,  0,  0, ..., 63, 63, 63]), array([ 4,  8, 10, ..., 10, 12, 13]))
not close lhs =  [ 6570.  7150.  7024. ...  8530.  7310. 10290.]
not close rhs =  [ 5820.  5290.  9060. ... 10680.  6480.  9280.]
not close dif =  [ 748. 1864. 2032. ... 2152.  832. 1008.]
not close tol =  [ 568.5  516.5  884.5 ... 1043.   633.   906. ]
dtype = float16, shape = (10, 64, 30)

**Comment by poxvoculi** [comment]
@benoitsteiner is this expected behavior?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 37 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 52 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jbobba** [comment]
Awesome! Thanks @markdryan.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jbobba** [comment]
Fixed with update to newer Eigen.

**Comment by markdryan** [comment]
@jbobba Could you re-open this?  The Eigen patch ( https://bitbucket.org/eigen/eigen/pull-requests/407/fix-the-packet16h-version-of-ptranspose/diff ) that fixes the issue hasn't been merged into Eigen yet and so is not included in the recent tensorflow Eigen update.  We need to get the patch merged and then do another Eigen update before this issue can be closed.

**Comment by jbobba** [comment]
@markdryan are you sure? I dont see the test failure anymore, so I assumed that the fix went in.

**Comment by markdryan** [comment]
@jbobba Yes.  I just pulled the latest master and retested.  batch_matmul_op_test is still failing for me.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 17 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by markdryan** [comment]
The patch has now been merged in Eigen.  The bug will be fixed by the next Eigen update.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @benoitsteiner: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
