### ISSUE TITLE
TensoRT SSD layers

### ISSUE THREAD

**Issue by Davidnet** [tensorflow/tensorflow#18744]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1. It must be a bug, a feature request, or a significant problem with documentation (for small docs fixes please send a PR instead).
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes I have create a custom class to load tensorflow zoo object detection models
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux xenial
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**:
1.7
- **Python version**: 2.7 
- **Bazel version (if compiling from source)**: 0.10
- **GCC/Compiler version (if compiling from source)**: 4
- **CUDA/cuDNN version**: 7 tegra
- **GPU model and memory**: jetson tx2
- **Exact command to reproduce**:

### Describe the problem

TensorRT with any kind of SSD models is breaking tensorflow because of the ones layer not implemented. Any guideline on how to implement. 
### Source code / logs

using frozen_graph.pb of mobilnet and fastrcnn
Traceback (most recent call last):
  File "tests/trt_od.py", line 107, in <module>
    minimum_segment_size = 2,
  File "/home/nvidia/Documents/tfinterface/tfinterface/estimator/getters.py", line 38, in get
    return cls(model_path, *args, **kwargs)
  File "tests/trt_od.py", line 53, in __init__
    **trt_ops
  File "/home/nvidia/.local/lib/python2.7/site-packages/tensorflow/contrib/tensorrt/python/trt_convert.py", line 115, in create_inference_graph
    int(msg[0]))
tensorflow.python.framework.errors_impl.NotFoundError: No attr named 'index_type' in NodeDef:
         [[Node: ones = Fill[T=DT_INT32](strided_slice_14, ones/Const)]]
         [[Node: ones = Fill[T=DT_INT32](strided_slice_14, ones/Const)]]
.

**Comment by ouceduxzk** [comment]
I guess you need to implement the tensorrt layer for ssd with NVPlugin, then try to integrate into tf

**Comment by ouceduxzk** [comment]
@Davidnet  I did not understand what you said, basically tensorrt support layers that tf have, but if tensorflow does not have, if you still want to use tensorrt, you can use the plugin feature to impl yourself.

**Comment by Davidnet** [comment]
@ouceduxzk From what I understood from this [article](https://devblogs.nvidia.com/tensorrt-integration-speeds-tensorflow-inference/) if there are layers or operations in the graph that are not implemented in tensorrt, they are normally executed in tensorflow, so that layer should be executed normally in tensorflow right ?

**Comment by rajatmonga** [comment]
@samikama Could you please take a look.

**Comment by samikama** [comment]
@Davidnet,

I am closing this since we can't handle SSD networks yet. When we switch to TRT4.0, support for SSD will increase.

Sami

**Comment by 4rshdeep** [comment]
Is this supported now? I am facing the following error when I tried to create tensorrt optimized graph using
`trt_graph = trt.create_inference_graph(graph_def, ['num_detections', 'detection_boxes', 'detection_scores', 'detection_classes'], max_batch_size=batch_size, precision_mode=precision_mode)` for ssd_mobilenet_v1_coco from object detection model zoo.


```tensorflow.python.framework.errors_impl.NotFoundError: No attr named 'identical_element_shapes' in NodeDef:
	 [[Node: Preprocessor/map/TensorArray_1 = TensorArrayV3[clear_after_read=true, dtype=DT_FLOAT, dynamic_size=false, element_shape=<unknown>, tensor_array_name=""](Preprocessor/map/TensorArrayUnstack/strided_slice)]] for 'Preprocessor/map/TensorArray_1' (op: 'TensorArrayV3') with input shapes: [].
```

**Comment by aaroey** [comment]
Just to clarify, this seems to be a bug in the tf-trt integration, where it include some nodes in the trt subgraph which caused the problem. In general, the integration should not put the node into the segment before the it is confident enough to handle it. This issue will hopefully be fixed by #19871. Meanwhile we're still finding the root cause, so I'm reopening this one.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aaroey: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by UmerImran** [comment]
Hi @aaroey  @samikama 
I am still getting the same error although I built tensorflow Master a few days ago from source.
I am using TensorRT 4.0, Cuda 9.0, Cudnn 7.1.4

tensorflow.python.framework.errors_impl.NotFoundError: No attr named 'index_type' in NodeDef:
	 [[{{node MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones}} = Fill[T=DT_INT32](MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/Reshape, MultipleGridAnchorGenerator/Meshgrid/ExpandedShape/ones/Const)]]

Any guideline for it?
Regards

**Comment by anhtu812** [comment]
Hi @aaroey @samikama
I am still getting the same error although i built tensorflow v1.10.1 from source.
tensorflow.python.framework.errors_impl.NotFoundError: No attr named 'index_type' in NodeDef:
         [[Node: model_1/forward_1_batchnorm/ones_like = Fill[T=DT_FLOAT](model_1/forward_1_batchnorm/ones_like/Shape, model_1/forward_1_batchnorm/ones_like/Const)]]

**Comment by samikama** [comment]
@anhtu812 sometimes between different TF versions schema change and frozen graph needs to be updated. Did you freeze the graph with same tensorflow or are you loading it from a file saved by an earlier revision? If it is the second case, could you please try loading and saving frozen graph def to update it to current schema? If not, some fixes might have missed 1.10 cutoff and may require you to try master.

**Comment by anhtu812** [comment]
thanks @samikama, i re-freeze  with new version tensorflow, it have not this error.
