### ISSUE TITLE
Why is reading a CSV file with a TextLineDataset and decode_csv so slow?

### ISSUE THREAD

**Issue by recolgan** [tensorflow/tensorflow#18784]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: 1.7.0
- **Python version**: 3.6.0
- **Bazel version (if compiling from source)**: N/A
- **GCC/Compiler version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 9.0.176/7.0.7
- **GPU model and memory**: Titan X (12 GB)
- **Exact command to reproduce**: See below

I have a dataset saved on an SSD as a moderately large (~7 million line) .csv file. It's small enough to load into memory, but large enough that it takes a couple minutes to read the entire file into a NumPy array, and I don't always need the entire thing. This seemed like a perfect use case for tf.data.TextLineDataset.

I attempted to use it similarly to as demonstrated in the documentation with the tf.decode_csv and tf.data.Dataset.map functions, as shown in the code below, but I'm finding it to be unreasonably slow to fetch batches from the TextLineDataset. Of course I'd expect it to be slower than if the data has already been read into memory. But if I compare the total time to read the entire thing into a NumPy array in memory first and process it as a TensorSliceDataset vs. creating a TextLineDataset and reading batches that way, the former is many times faster. 

Am I missing something, or is this an issue with TextLineDataset and/or tf.decode_csv?

```
def make_tld(csv_filename, header_lines, delim, batch_size):
    dataset = tf.data.TextLineDataset(filenames=csv_filename).skip(header_lines)

    def parse_csv(line):
        cols_types = [[]] * num_cols_  # all required
        columns = tf.decode_csv(line, record_defaults=cols_types, field_delim=delim)
        return tf.stack(columns)

    dataset = dataset.map(parse_csv).batch(batch_size)
    return dataset


def make_tsd(csv_filename, header_lines, delim, batch_size):
    with open(csv_filename, "r") as f:
        lines = f.readlines()

    data_shape = (len(lines) - header_lines, len(lines[header_lines].strip().split(delim)))
    data = np.empty(shape=data_shape, dtype=np.float32)

    for idx, line in enumerate(lines[header_lines:]):
        columns = [float(el) for el in line.strip().split(delim)]
        data[idx, :] = np.array(columns)

    dataset = tf.data.Dataset.from_tensor_slices(data).batch(batch_size)
    return dataset


if __name__ == "__main__":
    batch_size_ = 100

    tld_start = datetime.datetime.now()
    tld = make_tld(csv_filename_, header_lines_, delim_, batch_size_)
    tld_next = tld.make_one_shot_iterator().get_next()
    with tf.Session() as tld_sess:
        tld_sess.run(tf.global_variables_initializer())
        try:
            while True:
                tld_out = tld_sess.run(tld_next)
        except tf.errors.OutOfRangeError:
            print("Done")
    tld_end = datetime.datetime.now()
    print("TextLineDataset: " + str(tld_end - tld_start))

    tsd_start = datetime.datetime.now()
    tsd = make_tsd(csv_filename_, header_lines_, delim_, batch_size_)
    tsd_next = tsd.make_one_shot_iterator().get_next()
    with tf.Session() as tsd_sess:
        tsd_sess.run(tf.global_variables_initializer())
        try:
            while True:
                tsd_out = tsd_sess.run(tsd_next)
        except tf.errors.OutOfRangeError:
            print("Done")
    tsd_end = datetime.datetime.now()
    print("TensorSliceDataset: " + str(tsd_end - tsd_start))
```

Output:
```
Done
TextLineDataset: 0:11:24.675474
Done
TensorSliceDataset: 0:02:12.061404
```

**Comment by reedwm** [comment]
/CC @mrry can you take a look?

**Comment by mrry** [comment]
Reassigning this one to @rachellim, who has been making improvements to CSV performance lately (and some that landed recently should help with this, if you'd like to try the nightly build).

**Comment by rachellim** [comment]
Thanks Derek! 

@recolgan, I'd be interested in knowing how much the recent changes (in the nightly build) help. Specifically, we merged a change that speeds up text -> float parsing significantly. I'm assuming you're reading float data? (assumption based on your defaults being `[[]]`, which tf interprets as float32 if i'm not mistaken) What's `num_cols_` in your case?

**Comment by recolgan** [comment]
Yup, it's float data (in E-notation with 10 digits, e.g. 1.273661858e+02, but casting to float32 is fine). num_cols_ is 11. 

With tf-nightly-gpu from pypi (which says it's version 1.8.0-dev20180330), the results are pretty much the same:
```
Done
TextLineDataset: 0:11:00.005571
Done
TensorSliceDataset: 0:02:11.366419
```

**Comment by rachellim** [comment]
Can you try `pip install --upgrade tf-nightly-gpu` to pull a later version of tensorflow? Looking at the version number, it seems out of date (20180330 - the changes were only made on 4/20). You should have a version number like `tf-nightly-gpu 1.9.0.dev20180426`

**Comment by recolgan** [comment]
Weird, I just did the install today, but in a Conda environment, so maybe that had something to do with it. Anyway, with 1.9.0-dev20180426 installed via native pip3, I get the following:

```
Done
TextLineDataset: 0:06:13.424233
Done
TensorSliceDataset: 0:02:17.663664
```

So, much better, but still not as fast as it ought to be...

**Comment by rachellim** [comment]
Thanks for the update, and for reporting this -- agreed that it's still slower than we would like. This example will be helpful as we work on improving performance for text datasets; I'll update this space as we make progress.

**Comment by rachellim** [comment]
Oh, one more thing, @recolgan -- can you try applying `batch` before `map`? So the code should look like:

```
def make_tld(csv_filename, header_lines, delim, batch_size):
    dataset = tf.data.TextLineDataset(filenames=csv_filename).skip(header_lines)

    def parse_csv(line):
        cols_types = [[]] * num_cols_  # all required
        columns = tf.decode_csv(line, record_defaults=cols_types, field_delim=delim)
        return tf.stack(columns)

    dataset = dataset.batch(batch_size).map(parse_csv).
    return dataset
```

I expect this to speed things up significantly, because the `map` function has significant overhead. In your original example, the map function is applied to each line of the input file. When the data batched first, the map function is applied to a whole batch at a time, i.e. there are 100x fewer `map` operations being run. Let me know how this affects things. 

You can read more about this optimization in the [tensorflow input pipeline performance guide ](https://www.tensorflow.org/versions/master/performance/datasets_performance) (Look for "Map and Batch")

**Comment by recolgan** [comment]
Ah, cool. Now (with 1.9.0-dev20180429) we're down to 2:59 for TextLineDataset/map, compared to 1:50 for TensorSliceDataset, and 8:12 with TextLineDataset/map under 1.7.0.

Thanks for the help @rachellim!

**Comment by recolgan** [comment]
Should also add that on a 12-core workstation adding num_parallel_calls=12 to the map call brings it down to 46 seconds, and .prefetch(1) after that brings it down to 31.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rachellim: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @rachellim: It has been 46 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
