### ISSUE TITLE
Tensorflow lite interpreter->AllocateTensors() fails with  it->size != alloc.size (15840 != 0)

### ISSUE THREAD

**Issue by cogmeta** [tensorflow/tensorflow#19026]
=### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Raspberry Pi 3
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.7.0
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
0.10.0
- **GCC/Compiler version (if compiling from source)**:
g++ 6.3.0
- **CUDA/cuDNN version**:
None
- **GPU model and memory**:

- **Exact command to reproduce**:

### Describe the problem

I was able to build tensorflow-lite.a lib and test out examples without any problem. However, when i tried loading my own model (converted from frozen .pb graph), I get following error. function interpreter->AllocateTensors()  fails for some reason. Not able to understand why?

tensorflow/contrib/lite/simple_memory_arena.cc:82 it->size != alloc.size (15840 != 0)

**Comment by cogmeta** [comment]
Loaded model foo.tflite
resolved reporter
construct interpreter
tensors size: 15
nodes size: 5
inputs: 1
input(0) name: input
0: MatMul_bias, 48, 1, 0, 0
1: Reshape, 15680, 1, 0, 0
2: add, 48, 1, 0, 0
3: fc1/MatMul_bias, 512, 1, 0, 0
4: fc1/Relu, 512, 1, 0, 0
5: fc1/W/transpose, 2007040, 1, 0, 0
6: fc2/MatMul_bias, 512, 1, 0, 0
7: fc2/Relu, 512, 1, 0, 0
8: fc2/W/transpose, 65536, 1, 0, 0
9: fc3/MatMul_bias, 512, 1, 0, 0
10: fc3/Relu, 512, 1, 0, 0
11: fc3/W/transpose, 65536, 1, 0, 0
12: final_fc/transpose, 6144, 1, 0, 0
13: input, 15840, 1, 0, 0
14: labels_softmax, 48, 1, 0, 0
input: 13
number of inputs: 1
number of outputs: 1
tensorflow/contrib/lite/simple_memory_arena.cc:82 it->size != alloc.size (15840 != 0)
Segmentation fault

**Comment by cogmeta** [comment]
(gdb) print alloc
$7 = (const tflite::ArenaAlloc &) @0x72a440: {offset = 0, size = 0}

**Comment by cogmeta** [comment]
Disabling check at simple_memory_arena.cc:82 - TF_LITE_ENSURE_EQ(context, it->size, alloc.size); 
does not help.  interpreter->Invoke() throws an error 

Program received signal SIGSEGV, Segmentation fault.
0x0000000000561a6d in tflite::tensor_utils::PortableMatrixBatchVectorMultiplyAccumulate (matrix=0x7ffff68e14c4, m_rows=128, 
    m_cols=3920, vector=0x0, n_batch=1, result=0x7fb4c0, result_stride=1)
    at tensorflow/contrib/lite/kernels/internal/reference/portable_tensor_utils.cc:65
65              *result_in_batch += *matrix_ptr++ * *vector_in_batch++;

**Comment by cogmeta** [comment]
This looks more like a model issue. I tried with different model and it works fine.

**Comment by cogmeta** [comment]
The simple_arena code is riddled with bugs. I was trying another models and it screws up memory after few interpreter invocations. Can we fully test the simple_arena code?

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 15 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 30 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 45 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 60 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by cogmeta** [comment]
Not worth the wait. closing it.

**Comment by tatianashp** [comment]
cc @aselle, @martinwicke

**Comment by aselle** [comment]
I think this is now resolved. Could you try a nightly or build from source. In particular, make sure whatever verison you use has this
https://github.com/tensorflow/tensorflow/commit/85c518b8d306204cd7111f321a4b7b204fc554f4
Unfortunately, this is not in r1.9, so you'll need to use master or the nightly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @andrehentz: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by aselle** [comment]
Thanks for closing the issue. Did it actually work for you? We'd love to hear.

**Comment by ankmathur96** [comment]
@aselle , I get this issue still, but with different parameters. 

RuntimeError: tensorflow/lite/simple_memory_arena.cc:96 it->size != alloc.size (-595591168 != 411041792)

I'm trying to run on a Raspberry Pi with a Resnet-18 - should I open a new issue?
