### ISSUE TITLE
Logo is imprecise

### ISSUE THREAD

**Issue by LucaRonin** [tensorflow/tensorflow#1922]
In Tensorflow logo, the left arm of the T looks like 2 units long, while the right arm is 1 unit long. So, if I am not mistaken, the shadow should look different (asymmetrical).

![tensorflow](https://cloud.githubusercontent.com/assets/695274/14502882/c8289650-01ad-11e6-8cb6-69b4b3052edc.jpg)

**Comment by yaroslavvb** [comment]
What if the light-sources are asymmetrical, and the backplane is slanted?

**Comment by LucaRonin** [comment]
@yaroslavvb I didn't think about it. 

Or maybe the T is not a shadow at all but just a painting on the backplane ;)

**Comment by caisq** [comment]
Maybe the light source doesn't have parallel rays.

**Comment by martinwicke** [comment]
It's a very complex lighting setup, that's for sure. I think it can only be explained by participating media.

**Comment by prb12** [comment]
I think this is best summarized as 'by design'. ;-)
Feel free to discuss further in one of the community forums, but I'd like to close this issue.

**Comment by manugarri** [comment]
i love this issue.

**Comment by ndbroadbent** [comment]
I "fixed" it, but the original one actually looks better.

![fixed-tensorflow](https://user-images.githubusercontent.com/139536/36914932-81f1c7cc-1e81-11e8-81f9-b05382e81777.png)

**Comment by Quintanedu** [comment]
I made my own version, but with only one unit long arms.
I also fixed the shadow, but i´m sorry, I only saved the shadowless version
![36251074_10214088121176146_2614555053607878656_n](https://user-images.githubusercontent.com/40668801/42043955-fbb838a2-7af7-11e8-9795-7f890e871d13.png)

**Comment by destinyzs** [comment]
you guys are so cute. ;-)

**Comment by SirJAKfromSpace** [comment]
![tensorflow1](https://user-images.githubusercontent.com/23219242/46945748-82544500-d097-11e8-9216-1fae65d0dcc6.png)
When your Tensorflow project doesn't satisfy your CS faculty due to *aesthetic* logo design

**Comment by sunzhonghui** [comment]
![tensorflow_log](https://user-images.githubusercontent.com/17609963/54351255-0f70e980-468a-11e9-8200-23ca0eff26d7.gif)

**Comment by alxfed** [comment]
@ndbroadbent , you forgot to draw the projection to the 'floor' of your logo, which will be 'F' too.
