### ISSUE TITLE
Aborted (core dumped) while running tftrt test case with tensorflow 1.9.0-rc1

### ISSUE THREAD

**Issue by kimbaol** [tensorflow/tensorflow#20139]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.9.0-rc1
- **Python version**: 
both 2.7 and 3.5
- **Bazel version (if compiling from source)**:
0.11.1
- **GCC/Compiler version (if compiling from source)**:
5.4.0
- **CUDA/cuDNN version**:
cuda 9.0 / cuDNN7.0
- **GPU model and memory**:
TitanXp 12G
- **Exact command to reproduce**:
env TEST_TMPDIR=/tmp/bazel n=1 TF_NEED_GCP=0 TF_NEED_HDFS=1 \
    TF_NEED_S3=0 TF_ENABLE_XLA=1 TF_NEED_GDR=1 TF_NEED_VERBS=1 \
    TF_NEED_JEMALLOC=1 \
    TF_NEED_OPENCL=0 TF_NEED_CUDA=1 TF_NEED_MPI=0 \
    PYTHON_BIN_PATH=/usr/bin/python3 \
    PYTHON_LIB_PATH=/usr/local/lib/python3.5/dist-packages \
    TF_NEED_OPENCL_SYCL=0 \
    CC_OPT_FLAGS="-march=native" \
    TF_CUDA_VERSION=9.0 \
    CUDA_TOOLKIT_PATH=/usr/local/cuda \
    GCC_HOST_COMPILER_PATH=/usr/bin/gcc \
    TF_CUDNN_VERSION=7 \
    TF_CUDA_CLANG=0 \
    TF_SET_ANDROID_WORKSPACE=false \
    CUDNN_INSTALL_PATH=/usr/lib/aarch64-linux-gnu/ \
    TF_NEED_KAFKA=0 \
    TF_NEED_TENSORRT=1 \
    TF_NCCL_VERSION=2 \
    NCCL_INSTALL_PATH=/usr/local/nccl2/ \
    TENSORRT_INSTALL_PATH=/usr/lib/x86_64-linux-gnu/ \
    TF_CUDA_COMPUTE_CAPABILITIES=6.1  ./configure 

bazel build -c opt --copt=-mavx --copt=-mavx2  \
--copt=-mfma --copt=-mfpmath=both --copt=-msse4.2 \
--config=cuda --config=mkl --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=0" \
//tensorflow/tools/pip_package:build_pip_package

build_pip_package then pip3 install 

python3 tensorflow/tensorflow/contrib/tensorrt/test/test_tftrt.py

### Describe the problem
I built tensorflow from source with above script, there is no problem with git branch r1.8, after I checked out to branch r1.9 and rebuilt, tftrt test case will crash.

### Source code / logs
root@5f4922d0faef:~/share/tensorflow/tensorflow/contrib/tensorrt/test# python test_tftrt.py 
2018-06-20 06:58:51.032087: F tensorflow/core/framework/op.cc:55] Non-OK-status: RegisterAlreadyLocked(op_data_factory) status: Already exists: Op with name _ScopedAllocator
Aborted (core dumped)

**Comment by robbysun** [comment]
Same here:

**System information**
Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
Yes (but the crash happens before it even reaches my code)
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Linux Ubuntu 16.04
TensorFlow installed from (source or binary):
source
TensorFlow version (use command below):
1.9.0-rc0
Python version:
2.7
Bazel version (if compiling from source):
0.14.1
GCC/Compiler version (if compiling from source):
5.4.0
CUDA/cuDNN version:
cuda 9.0 / cuDNN7.1.4
GPU model and memory:
GTX1070 8G
Exact command to reproduce:
import tensorflow.contrib.tensorrt
Describe the problem
There was no problem with git branch r1.8 on another PC, but on this PC with branch r1.9 the 'import' causes the crash.
![import-tensorflow-contrib-tensorrt-as-trt-crash](https://user-images.githubusercontent.com/5282003/41799731-6c1af57e-7627-11e8-85a5-c64c2ac91748.png)

Source code / logs
2018-06-22 13:43:56.537067: F tensorflow/core/framework/op.cc:55] Non-OK-status: RegisterAlreadyLocked(op_data_factory) status: Already exists: Op with name _ScopedAllocator
Aborted (core dumped)

For whatever it's worth, when the crash first happened, there was a pop-up window with the message "Sorry the application Python 2.7 has stopped unexpected". I took a screenshot of the "JournalErrors" section. The error seemed to be related to a file under /etc/udev/rules.d, so I removed that file and rebooted. Now I am still seeing the crash and core dump, but the pop-up window no longer appears.

**Comment by robbysun** [comment]
The nVidia device driver version is 384.130

**Comment by mabrowning** [comment]
Same with:

Ubuntu 18.04
gcc 7.3.0
bazel  0.15.0
Tensorflow r1.9 rc1
CUDA 9.2
cuDNN 7.1.4
TensorRT 4

**Comment by tensorflowbutler** [comment]
Nagging Assignee @aselle: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by kimbaol** [comment]
It seems this issue is fixed in master branch, but haven't been merged into r1.9 branch.

**Comment by jiarenyf** [comment]
I meet the same error in tf1.9 ...

**Comment by aselle** [comment]
@zheng-xq, @gunan, should we make a tf1.9.1 to fix this?

**Comment by aaroey** [comment]
This was an issues caused by not having enough test coverage on the integration. Tests are being added to prevent this from happening in the future. Meanwhile we decided not to do a patch release for r1.9, so would you please try to build from master before 1.10 is out?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by aaroey** [comment]
1.10 is released and this particular problem is fixed there.

**Comment by mhsszm** [comment]
2019-05-05 18:30:24.660685: I tensorflow/core/grappler/devices.cc:51] Number of eligible GPUs (core count >= 8): 1
2019-05-05 18:30:25.215100: I tensorflow/contrib/tensorrt/convert/convert_nodes.cc:2853] Segment @scope 'resnet_v1_50/', converted to graph
2019-05-05 18:30:25.334662: W tensorflow/contrib/tensorrt/convert/convert_graph.cc:724] Can't determine the device, constructing an allocator at device 0
*** Error in `python': munmap_chunk(): invalid pointer: 0x00007ffe6e056190 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f21cc53c7e5]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x1a8)[0x7f21cc549698]

**Comment by aaroey** [comment]
Hi @mhsszm, could you provide a repro for your case? And do you mind filing a new issue? Thanks.

**Comment by yurkovak** [comment]
Still seeing this problem with 1.12.0-rc2 built from source.
```
2020-09-13 12:33:59.042299: F tensorflow/core/framework/op.cc:55] Non-OK-status: RegisterAlreadyLocked(op_data_factory) status: Already exists: Op with name TRTEngineOp
Aborted (core dumped)
```
