### ISSUE TITLE
Tensorflow micro build fail: fatal error: 'NEON_2_SSE.h' file not found

### ISSUE THREAD

**Issue by torntrousers** [tensorflow/tensorflow#23440]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac
- TensorFlow installed from (source or binary): source
- TensorFlow version: latest git

**Describe the problem**

Following the instructions here: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/experimental/micro#getting-started

```
make -f tensorflow/lite/experimental/micro/tools/make/Makefile test
tensorflow/lite/experimental/micro/tools/make/gen/osx_x86_64/bin/tensorflow/lite/experimental/micro/micro_error_reporter.test_target tensorflow/lite/experimental/micro/tools/make/gen/osx_x86_64/bin/tensorflow/lite/experimental/micro/micro_interpreter.test_target tensorflow/lite/experimental/micro/tools/make/gen/osx_x86_64/bin/tensorflow/lite/experimental/micro/micro_mutable_op_resolver.test_target tensorflow/lite/experimental/micro/tools/make/gen/osx_x86_64/bin/tensorflow/lite/experimental/micro/simple_tensor_allocator.test_target tensorflow/lite/experimental/micro/tools/make/gen/osx_x86_64/bin/tensorflow/lite/experimental/micro/kernels/depthwise_conv.test_target tensorflow/lite/experimental/micro/tools/make/gen/osx_x86_64/bin/tensorflow/lite/experimental/micro/kernels/fully_connected.test_target tensorflow/lite/experimental/micro/tools/make/gen/osx_x86_64/bin/tensorflow/lite/experimental/micro/kernels/softmax.test_target
g++ -O3 -DNDEBUG --std=c++11 -g -DTF_LITE_STATIC_MEMORY -I. -Itensorflow/lite/experimental/micro/tools/make/../../../../../ -Itensorflow/lite/experimental/micro/tools/make/../../../../../../ -Itensorflow/lite/experimental/micro/tools/make/downloads/ -Itensorflow/lite/experimental/micro/tools/make/downloads/gemmlowp -Itensorflow/lite/experimental/micro/tools/make/downloads/flatbuffers/include -I -I/usr/local/include -c tensorflow/lite/experimental/micro/kernels/depthwise_conv.cc -o tensorflow/lite/experimental/micro/tools/make/gen/osx_x86_64/obj/tensorflow/lite/experimental/micro/kernels/depthwise_conv.o
In file included from tensorflow/lite/experimental/micro/kernels/depthwise_conv.cc:16:
./tensorflow/lite/c/builtin_op_data.h:144:9: warning: empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
typedef struct {
        ^
./tensorflow/lite/c/builtin_op_data.h:147:9: warning: empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
typedef struct {
        ^
./tensorflow/lite/c/builtin_op_data.h:217:9: warning: empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
typedef struct {
        ^
./tensorflow/lite/c/builtin_op_data.h:220:9: warning: empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
typedef struct {
        ^
./tensorflow/lite/c/builtin_op_data.h:259:9: warning: empty struct has size 0 in C, size 1 in C++ [-Wextern-c-compat]
typedef struct {
        ^
In file included from tensorflow/lite/experimental/micro/kernels/depthwise_conv.cc:18:
./tensorflow/lite/kernels/internal/common.h:42:10: fatal error: 'NEON_2_SSE.h' file not found
#include "NEON_2_SSE.h"
         ^~~~~~~~~~~~~~
5 warnings and 1 error generated.
make: *** [tensorflow/lite/experimental/micro/tools/make/gen/osx_x86_64/obj/tensorflow/lite/experimental/micro/kernels/depthwise_conv.o] Error 1
```

Before that there is another error about BZL_FILE_PATH but I've used the fix in https://github.com/tensorflow/tensorflow/pull/23424 to get past that.

Could this NEON_2_SSE.h problem also be due the the move out of contrib?

**Comment by petewarden** [comment]
Looking into it more deeply, this actually looks like a problem with particular x86 architectures that existed before the move. I wasn't able to reproduce it on my machine, but I've checked in this change which I hope should fix it:
https://github.com/tensorflow/tensorflow/commit/4e81d6cc877ba4a56196bbdd8d4e09ab7f7b8412

Can you give it a try and let me know? Thanks!

**Comment by tensorflowbutler** [comment]
Nagging Assignee @petewarden: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by petewarden** [comment]
Thanks for the report, and sorry for the slow response! I believe this is now fixed in the head of TF, so closing, but please reopen if it's still an issue.

**Comment by aallan** [comment]
It's still an issue in the projects provided as a set of pre-generated projects at https://drive.google.com/open?id=1cawEQAkqquK_SO4crReDYqf_v7yAwOY8.
