### ISSUE TITLE
ERROR: Unrecognized option: --input_file=/Users/jyy/model/frozen_inference_graph.pb

### ISSUE THREAD

**Issue by wangyongqi** [tensorflow/tensorflow#23550]
Hello, I trained the ". pb" file on the cloud server through ssdmobilenet. Now I want to convert it into tflite format, but it failed, and the following error occurred. This is my code. Who can help me? Thank you.

bazel run --config=opt tensorflow/contrib/lite/toco:toco --input_file=/Users/jyy/model/frozen_inference_graph.pb --input_format=TENSORFLOW_GRAPHDEF --output_format=TFLITE --output_file=/Users/jyy/wechat_model/wechat.lite --inference_type=FLOAT --input_type=FLOAT --input_arrays=input --output_arrays=predictions --input_shapes=1,224,224,3
ERROR: Unrecognized option: --input_file=/Users/jyy/model/frozen_inference_graph.pb

**Comment by PINTO0309** [comment]
@wangyongqi 
The official tutorial is below.
https://www.tensorflow.org/lite/convert/cmdline_examples

If you do not mention environmental information, no one can answer accurately.
[example] OS, Hardware, Tensorflow version, pip or source build

**Comment by wangyongqi** [comment]
@PINTO0309 sorry,I seem to have found the reason. At present, there are few OPS officially supported by tflite, so many complex models can not run on tflite. At present, only the mobilenet model has been successfully converted. Inception V3, ssd-mobilenet and other models can not be successfully converted by toco, because the op used in the model does not support it. I use the ssd-mobilenet model.What do you mean?

**Comment by PINTO0309** [comment]
@wangyongqi
The error message was "Unrecognized option: --input_file".
However, according to the official tutorial, it seems that you specified a .pb file with the option "--graph_def_file".
By the way, the official tutorial is not a "toco" binary.
I do not know the type of script you solved, but it was good that the problem was resolved.

**Comment by harshini-gadige** [comment]
@wangyongqi  Feel free to close this issue if it is resolved. Also please post any questions(if you have) on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since if it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by wangyongqi** [comment]
@harshini-gadige okay，I know. Thanks.

**Comment by moyans** [comment]
when I use  mobile_ssd， this erro `Unrecognized option: --input_file=` still exist @wangyongqi
