### ISSUE TITLE
How can I convert custom pb file to tflite?

### ISSUE THREAD

**Issue by fkjpn1204** [tensorflow/tensorflow#24138]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:-
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):1.15.0
- Python version:2.7.12
- Bazel version (if compiling from source):0.19.2
- GCC/Compiler version (if compiling from source):-
- CUDA/cuDNN version:-
- GPU model and memory: no GPU / 8GB memory(VM)

I tried to convert frozen & custom .pb file(Specifically, SSD) to .tflite with toco tools.
but I get some error & core dump.(below)

*convert command & results is below:******************************************************************
$   (path)/.local/bin/toco 
--input_file=(path)/ssd1.pb   
--output_file=(path)/ssd2.tflite 
--input_format=TENSORFLOW_GRAPHDEF  
 --output_format=TFLITE 
--input_shape=1,300,300,3 
--input_array=input_13   
--output_array=predictions/concat 
--input_data_type=FLOAT   
--inference_type=FLOAT 
--allow_custom_ops
2018-12-04 11:39:52.856924: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: Prod
2018-12-04 11:39:52.857097: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: Prod
2018-12-04 11:39:52.857156: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: Prod
2018-12-04 11:39:52.857214: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: Prod
2018-12-04 11:39:52.857271: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: Prod
2018-12-04 11:39:52.857389: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: Prod
2018-12-04 11:39:52.857474: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: Prod
2018-12-04 11:39:52.857533: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: Prod
2018-12-04 11:39:52.857586: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: Prod
2018-12-04 11:39:52.857638: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: Prod
2018-12-04 11:39:52.857720: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: StridedSlice
2018-12-04 11:39:52.857784: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: StridedSlice
2018-12-04 11:39:52.857878: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: StridedSlice
2018-12-04 11:39:52.857976: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: StridedSlice
2018-12-04 11:39:52.858055: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: StridedSlice
2018-12-04 11:39:52.858156: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: StridedSlice
2018-12-04 11:39:52.858226: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: StridedSlice
2018-12-04 11:39:52.858287: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: StridedSlice
2018-12-04 11:39:52.858337: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: StridedSlice
2018-12-04 11:39:52.858382: I   tensorflow/contrib/lite/toco/import_tensorflow.cc:1057] Converting   unsupported operation: Exp
2018-12-04 11:39:52.862297: I   tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39]   Before general graph transformations: 309 operators, 499 arrays (0 quantized)
2018-12-04 11:39:53.124941: F   tensorflow/contrib/lite/toco/graph_transformations/propagate_fixed_sizes.cc:785]   Check failed: crops_data[1] == 0 (5 vs. 0)
Coredump
*************************************************************************************************************

*model summarize is below:(trained environmental is keras. and I converted .json & .h5 to .pb)**********
$   bazel-bin/tensorflow/tools/graph_transforms/summarize_graph   
 --in_graph=(path)/ssd1.pb

Found 1 possible inputs: (name=input_13,   type=float(1), shape=[?,300,300,3])
No variables spotted.
Found 1 possible outputs:   (name=predictions/concat, op=ConcatV2)
Found 25824093 (25.82M) const   parameters, 0 (0) variable parameters, and 0 control_edges
Op types used: 189 Const, 73 Identity,   33 BiasAdd, 31 Conv2D, 21 Relu, 19 Pack, 19 StridedSlice, 19 Shape, 13   Reshape, 10 Prod, 6 Tile, 6 ExpandDims, 5 MaxPool, 4 ConcatV2, 2 Sum, 2 Mul,   2 MatMul, 1 RealDiv, 1 Sub, 1 Square, 1 SpaceToBatchND, 1 Exp, 1 Rsqrt, 1   Placeholder, 1 Pad, 1 BatchToSpaceND, 1 Mean, 1 Maximum, 1 Max
To use with   tensorflow/tools/benchmark:benchmark_model try these arguments:
bazel run   tensorflow/tools/benchmark:benchmark_model --   
--graph=(path)/ssd1.pb --show_flops   --input_layer=input_13 
--input_layer_type=float   --input_layer_shape=-1,300,300,3 --output_layer=predictions/concat
**************************************************************************************************************

How can I convert pb file to tflite?
or Is Tensorflow lite unsupported this problem still now?
or process of convert pb file has something wrong?
    (because I feel that the number of output_layer is small...)

**Comment by ymodak** [comment]
It looks like you have some tflite unsupported ops in your model. Please refer [TensorFlow Lite & TensorFlow Compatibility Guide](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/tf_ops_compatibility.md#tensorflow-lite--tensorflow-compatibility-guide)

**Comment by fkjpn1204** [comment]
Thanks for your answer.
I confirmed the Compatibility Guide.

If my model included unsupported function , How I convert pb to tflite?
Should I reprogramming code without unsupported function?(...I don't have confidence to realize it) 
or Should I abandon converting ? (...Implement on mobile as tensorflow-moblile(=pb))
or Should I wait support?
Which reaction do you think best?

**Comment by ymodak** [comment]
Adding @liyunlu0618 She may know more.

**Comment by liyunlu0618** [comment]
Please take a look at this and give it a try:
https://www.tensorflow.org/lite/using_select_tf_ops

This is an effort meant for expanding the op support in tflite. In theory it should be able to convert any tensorflow op. It's still in a 'preview' phase and let us know any issue you run into. Thanks!

**Comment by liyunlu0618** [comment]
1. Can you try again with tflite_convert instead of toco?
2. Remove the "--allow_custom_ops" flag.

**Comment by fkjpn1204** [comment]
Sorry to late replying the advise.
1. I couldn't use "tflite_covert" command . (because of my tensorflow version 1.5.1(<1.9)?)
2. using toco command and removing " --allow_custom_ops ", result was same.(happened core dump)

I will confirm how to use the "tflite_convert" command and confirm that it can be changed.
If there is progress, we will post again.

**Comment by fkjpn1204** [comment]
I could convert pb file to tflite file by using "tflite_convert" command.
Initially, the "tflite_convert" command wasn't recognized, but the "tflite_convert" command was recognized by updating tensorflow version from 1.5 to 1.9.

The terminal display when conversion successfully is shown below.
$ (path) tflite_convert \
--output_file=(path)/ssd2.tflite
--graph_def_file=(path)/ssd1.pb
--input_arrays=input_13
--output_arrays=predictions/concat
--allow_custom_ops=True

2018-12-26 15:37:34.772285: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2

Thanks to liyunlu & ymodak !!

**Comment by fkjpn1204** [comment]
<Converting QUANTIZED MODEL>
By the way... I want to convert to quantized model, but I couldn't convert...
Therefore, updating tensorflow version from 1.9 to 1.10 , simple model converted to quantized model without problem.

but custom model(SSD) couldn't convert to quantized model.
bellow error was happen.
Do you know the solution?

#command 
$ (path) tflite_convert 
--output_file=(path)/ssd2.tflite
--graph_def_file=(path)/ssd1.pb
--input_arrays=input_13
--output_arrays=predictions/concat
--allow_custom_ops=True
--inference_type=QUANTIZED_UINT8
--mean_values=128
--std_dev_values=127
--default_ranges_min=0
--default_ranges_max=6

--tflite_convert:error:argument --allow_custom_ops: ignored explicit argument "True"

**Comment by fkjpn1204** [comment]
By the way... I want to convert to quantized model. 
but custom model(SSD) couldn't convert to quantized model.
bellow error was happen.
Do you know the solution?

#command
$ (path) tflite_convert
--output_file=(path)/ssd2.tflite
--graph_def_file=(path)/ssd1.pb
--input_arrays=input_13
--output_arrays=predictions/concat
--allow_custom_ops=True
--inference_type=QUANTIZED_UINT8
--mean_values=128
--std_dev_values=127
--default_ranges_min=0
--default_ranges_max=6

#result
2018-12-27 10:34:14.675240: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last): 
File "/home/.local/bin/tflite_convert", line 11, in <module>sys.exit(main())
File"/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 370, in main app.run(main=run_main, argv=sys.argv[:1])
File "/home/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run_sys.exit(main(argv))
File"/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 366, in run_main_convert_model(tflite_flags)
File"/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 143, in _convert_model output_data = converter.convert()
File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 374, in convert dump_graphviz_video=self.dump_graphviz_video)
File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 246, in toco_convert input_data.SerializeToString())
File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 106, in toco_convert_protos (stdout, stderr))

RuntimeError: TOCO failed see console for info.
2018-12-27 10:34:16.679149: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679266: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679313: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679355: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679401: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679508: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679566: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679631: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679692: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679742: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.687343: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 307 operators, 497 arrays (0 quantized)
2018-12-27 10:34:16.692008: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 307 operators, 497 arrays (0 quantized)
2018-12-27 10:34:16.847001: I tensorflow/contrib/lite/toco/graph_transformations/identify_dilated_conv.cc:161] Identified sub-network emulating dilated convolution.
2018-12-27 10:34:16.847101: I tensorflow/contrib/lite/toco/graph_transformations/identify_dilated_conv.cc:209] Replaced with Dilated Conv2D op outputting "fc6/convolution".
2018-12-27 10:34:16.973428: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 121 operators, 271 arrays (1 quantized)
2018-12-27 10:34:16.976343: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 118 operators, 269 arrays (1 quantized)
2018-12-27 10:34:16.978081: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 96 operators, 220 arrays (1 quantized)
2018-12-27 10:34:16.979551: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 96 operators, 220 arrays (1 quantized)
2018-12-27 10:34:16.980254: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before default min-max range propagation graph transformations: 96 operators, 220 arrays (1 quantized)
2018-12-27 10:34:16.981095: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After default min-max range propagation graph transformations pass 1: 96 operators, 220 arrays (1 quantized)
2018-12-27 10:34:16.982101: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before quantization graph transformations: 96 operators, 220 arrays (1 quantized)
2018-12-27 10:34:16.982162: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv1_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:16.982244: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv1_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:16.982911: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv2_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:16.984138: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv2_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:16.986618: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv3_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:16.991730: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv3_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.001478: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv3_3/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.011443: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.031214: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.070534: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_3/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.109856: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv5_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.149394: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv5_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.188472: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv5_3/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.227761: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array fc6/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.311359: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array fc7/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.329462: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv6_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.333997: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv6_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.353890: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv7_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.355148: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv7_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.360063: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv8_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.360758: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_3_norm/conv4_3_norm_gamma lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.360814: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv8_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.365651: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_3_norm_mbox_conf/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.370659: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array fc7_mbox_conf/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.390781: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv6_2_mbox_conf/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.401131: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv7_2_mbox_conf/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.406407: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv8_2_mbox_conf/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.411938: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_3_norm_mbox_loc/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.412961: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array fc7_mbox_loc/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.419789: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv6_2_mbox_loc/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.421751: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv7_2_mbox_loc/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.422763: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv8_2_mbox_loc/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.423781: F tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:461] Unimplemented: this graph contains an operator of type (Unsupported TensorFlow op: Prod) for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).
Aborted (core dumped)

None

**Comment by fkjpn1204** [comment]
By the way... I want to convert to quantized model.
but custom model(SSD) couldn't convert to quantized model.
bellow error was happen.
Do you know the solution?

#command
$ (path) tflite_convert
--output_file=(path)/ssd2.tflite
--graph_def_file=(path)/ssd1.pb
--input_arrays=input_13
--output_arrays=predictions/concat
--allow_custom_ops    *"True" is not neccessary
--inference_type=QUANTIZED_UINT8
--mean_values=128
--std_dev_values=127
--default_ranges_min=0
--default_ranges_max=6

#result
2018-12-27 10:34:14.675240: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
Traceback (most recent call last):
File "/home/.local/bin/tflite_convert", line 11, in sys.exit(main())
File"/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 370, in main app.run(main=run_main, argv=sys.argv[:1])
File "/home/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run_sys.exit(main(argv))
File"/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 366, in run_main_convert_model(tflite_flags)
File"/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/tflite_convert.py", line 143, in _convert_model output_data = converter.convert()
File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/lite.py", line 374, in convert dump_graphviz_video=self.dump_graphviz_video)
File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 246, in toco_convert input_data.SerializeToString())
File "/home/.local/lib/python2.7/site-packages/tensorflow/contrib/lite/python/convert.py", line 106, in toco_convert_protos (stdout, stderr))

RuntimeError: TOCO failed see console for info.
2018-12-27 10:34:16.679149: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679266: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679313: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679355: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679401: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679508: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679566: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679631: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679692: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.679742: I tensorflow/contrib/lite/toco/import_tensorflow.cc:1096] Converting unsupported operation: Prod
2018-12-27 10:34:16.687343: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 307 operators, 497 arrays (0 quantized)
2018-12-27 10:34:16.692008: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 307 operators, 497 arrays (0 quantized)
2018-12-27 10:34:16.847001: I tensorflow/contrib/lite/toco/graph_transformations/identify_dilated_conv.cc:161] Identified sub-network emulating dilated convolution.
2018-12-27 10:34:16.847101: I tensorflow/contrib/lite/toco/graph_transformations/identify_dilated_conv.cc:209] Replaced with Dilated Conv2D op outputting "fc6/convolution".
2018-12-27 10:34:16.973428: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 1: 121 operators, 271 arrays (1 quantized)
2018-12-27 10:34:16.976343: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 2: 118 operators, 269 arrays (1 quantized)
2018-12-27 10:34:16.978081: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After general graph transformations pass 3: 96 operators, 220 arrays (1 quantized)
2018-12-27 10:34:16.979551: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before pre-quantization graph transformations: 96 operators, 220 arrays (1 quantized)
2018-12-27 10:34:16.980254: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before default min-max range propagation graph transformations: 96 operators, 220 arrays (1 quantized)
2018-12-27 10:34:16.981095: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] After default min-max range propagation graph transformations pass 1: 96 operators, 220 arrays (1 quantized)
2018-12-27 10:34:16.982101: I tensorflow/contrib/lite/toco/graph_transformations/graph_transformations.cc:39] Before quantization graph transformations: 96 operators, 220 arrays (1 quantized)
2018-12-27 10:34:16.982162: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv1_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:16.982244: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv1_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:16.982911: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv2_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:16.984138: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv2_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:16.986618: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv3_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:16.991730: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv3_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.001478: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv3_3/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.011443: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.031214: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.070534: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_3/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.109856: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv5_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.149394: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv5_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.188472: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv5_3/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.227761: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array fc6/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.311359: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array fc7/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.329462: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv6_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.333997: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv6_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.353890: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv7_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.355148: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv7_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.360063: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv8_1/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.360758: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_3_norm/conv4_3_norm_gamma lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.360814: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv8_2/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.365651: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_3_norm_mbox_conf/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.370659: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array fc7_mbox_conf/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.390781: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv6_2_mbox_conf/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.401131: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv7_2_mbox_conf/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.406407: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv8_2_mbox_conf/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.411938: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv4_3_norm_mbox_loc/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.412961: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array fc7_mbox_loc/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.419789: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv6_2_mbox_loc/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.421751: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv7_2_mbox_loc/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.422763: W tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:87] Constant array conv8_2_mbox_loc/kernel lacks MinMax information. To make up for that, we will now compute the MinMax from actual array elements. That will result in quantization parameters that probably do not match whichever arithmetic was used during training, and thus will probably be a cause of poor inference accuracy.
2018-12-27 10:34:17.423781: F tensorflow/contrib/lite/toco/graph_transformations/quantize.cc:461] Unimplemented: this graph contains an operator of type (Unsupported TensorFlow op: Prod) for which the quantized form is not yet implemented. Sorry, and patches welcome (that's a relatively fun patch to write, mostly providing the actual quantized arithmetic code for this op).
Aborted (core dumped)

None

**Comment by liyunlu0618** [comment]
Your model needs to be trained with quantization for this conversion to work. This process will add the missing min/max to the tensors, as complained in the error message.

If you do not have to run quantized inference, we have another [post-training optimization tools](https://www.tensorflow.org/lite/performance/post_training_quantization) that doesn't require retraining your model. Please check it out and see if it applies.

**Comment by fkjpn1204** [comment]
In my case, I interpreted that it is necessary to retrain the model under the condition of quantization.
( Because SSD model includes custom operations.) 
How can I retrain the model with the keras library? do you know?
or because of can't use keras library,  have to retrain the model with tensorflow ? (without keras library)

If possible , I would like to convert the current 32-bit model to an 8-bit model...
(but SSD model include custom operations , so it can't convert..... Is my understanding correct?)

**Comment by liyunlu0618** [comment]
We don't support quantization aware training with keras yet...

Your understanding is correct. Currently we don't have a well supported way to do quantization aware training with a model containing custom ops and convert it...

**Comment by fkjpn1204** [comment]
Since I was able to convert SSD model to tensorflow mobile format 8bit model(pb), I will use that model.
And I compare the speed of the 8bit model and the speed of the 32bit model, but it is a little disappointing that there has been almost no change.(Validate with smartphone)
If I could convert to 8bit model of tensorflow lite format, can it speed up..?

Anyway, since the conversion from pb to tflite which was an agenda has been solved, close the comment. (Remaining: Convert custom model to tensorflow lite format 8bit model(.tflite(8bit-custom))

liyunlu0618 Thank you for your comment.

**Comment by an1018** [comment]
> Please take a look at this and give it a try:
> https://www.tensorflow.org/lite/using_select_tf_ops
> 
> This is an effort meant for expanding the op support in tflite. In theory it should be able to convert any tensorflow op. It's still in a 'preview' phase and let us know any issue you run into. Thanks!

@liyunlu0618 Hi, I have a question, you said using target_ops can convert any tensorflow op, but there is still wrong.
#tf version
  1.14

#command
$ (path) tflite_convert
--output_file=densenet.tflite
--graph_def_file=densenet.pb
--input_arrays=input_1
--output_arrays=ctc/ExpandDims
--allow_custom_ops
--target_ops=TFLITE_BUILTINS,SELECT_TF_OPS

#result
Traceback (most recent call last):
  File "/home/anaconda3/bin/toco_from_protos", line 11, in <module>
    sys.exit(main())
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 59, in main
    app.run(main=execute, argv=[sys.argv[0]] + unparsed)
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/anaconda3/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/anaconda3/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/anaconda3/lib/python3.6/site-packages/tensorflow/lite/toco/python/toco_from_protos.py", line 33, in execute
    output_str = tensorflow_wrap_toco.TocoConvert(model_str, toco_str, input_str)
Exception: TensorFlow Lite currently doesn't support control flow ops: Merge, Switch.
Looking forward your replace!Thanks

**Comment by DragonicVoid22** [comment]
instead of posting things that do not work at all why not just post something that works 200%

**Comment by reborn2266** [comment]
> I could convert pb file to tflite file by using "tflite_convert" command.
> Initially, the "tflite_convert" command wasn't recognized, but the "tflite_convert" command was recognized by updating tensorflow version from 1.5 to 1.9.
> 
> The terminal display when conversion successfully is shown below.
> $ (path) tflite_convert
> --output_file=(path)/ssd2.tflite
> --graph_def_file=(path)/ssd1.pb
> --input_arrays=input_13
> --output_arrays=predictions/concat
> --allow_custom_ops=True
May I know how you came up with these parameters?


> 
> 2018-12-26 15:37:34.772285: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> 
> Thanks to liyunlu & ymodak !!

**Comment by reborn2266** [comment]
> I could convert pb file to tflite file by using "tflite_convert" command.
> Initially, the "tflite_convert" command wasn't recognized, but the "tflite_convert" command was recognized by updating tensorflow version from 1.5 to 1.9.
> 
> The terminal display when conversion successfully is shown below.
> $ (path) tflite_convert
> --output_file=(path)/ssd2.tflite
> --graph_def_file=(path)/ssd1.pb
> --input_arrays=input_13
> --output_arrays=predictions/concat
> --allow_custom_ops=True
> 
> 2018-12-26 15:37:34.772285: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> 
> Thanks to liyunlu & ymodak !!

May I know how you come up with these settings?  Thanks,
> --input_arrays=input_13
> --output_arrays=predictions/concat

**Comment by butterfly-coder** [comment]
> I could convert pb file to tflite file by using "tflite_convert" command.
> Initially, the "tflite_convert" command wasn't recognized, but the "tflite_convert" command was recognized by updating tensorflow version from 1.5 to 1.9.
> 
> The terminal display when conversion successfully is shown below.
> $ (path) tflite_convert
> --output_file=(path)/ssd2.tflite
> --graph_def_file=(path)/ssd1.pb
> --input_arrays=input_13
> --output_arrays=predictions/concat
> --allow_custom_ops=True
> 
> 2018-12-26 15:37:34.772285: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
> 
> Thanks to liyunlu & ymodak !!

Hi, @fkjpn1204 
You converted pb to tflite with custom ops - ImageExtractPatches.

**Comment by mcabie3098** [comment]
Someone deleted the colab that converts .pb to .tflite that helps me a lot, and now I'm looking for it, looks like they deleted it, Can I have a copy of that one again please.
