### ISSUE TITLE
DistributionStrategy and Keras models: support for sample_weight_mode

### ISSUE THREAD

**Issue by pawarrick** [tensorflow/tensorflow#24226]
**System information**
- TensorFlow version (you are using): master (Nov. 30, 2018)
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
When using a DistributionStrategy with a Keras model that includes sample_weights, a 'NotImplemented' exception is thrown.  For example,

 ```
    strategy = mirrored_strategy.MirroredStrategy()
     model.compile(loss='categorical_crossentropy',
                     optimizer=opt,
                     metrics=['accuracy'],
                     weighted_metrics=['accuracy'],
                     sample_weight_mode='temporal',
                     distribute=strategy)
```

The exception originates in tensorflow/python/keras/engine/training.py
      
```
 if sample_weight_mode:
	        raise NotImplementedError('sample_weight_mode is not supported with '
	                                  'DistributionStrategy.')
```

Can this be supported or can you give an estimated timeline?

Many thanks

**Will this change the current api? How?**
No.  It looks like the API should support this.

**Who will benefit with this feature?**
Anyone using keras models with sample_weights in a DistributedStrategy mode.

**Any Other info.**

**Comment by harshini-gadige** [comment]
@pawarrick  Currently adding this feature is not in the immediate radar(as there are many other prioritized features in the pipeline). Hence marking this as Contributions Welcome.
As you mentioned above, if you would like to contribute for the same please open a PR and link the PR # here.

**Comment by pawarrick** [comment]
@fchollet Hi François, this is the issue I mentioned to you today.
Thanks again for chatting

**Comment by pawarrick** [comment]
@shivam13juna, I have not seen any note of work being done on this, so I think your contribution would be most welcome

**Comment by guptapriya** [comment]
Thanks @shivam13juna , please go ahead and contribute. We don't have anyone working on this in the near future.

**Comment by a6802739** [comment]
@hgadig @guptapriya Is there anyone still working on here? If not, maybe I could have a try for this, but I hope could get some reference first. Thanks!

**Comment by guptapriya** [comment]
We don't have anyone working on this currently, so please feel free. 
We also recently discovered a bug in the regular sample weights with keras when using distribution strategy. Specifically, sample_weights are being set to `None` here, but this should happen only in the case they are not present:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/distribute/distributed_training_utils.py#L579

You will have to fix this bug first before you can get sample_weight_mode working. Would you be interested in first fixing that bug and then adding new support for sample weight mode?

cc @anj-s

**Comment by a6802739** [comment]
@guptapriya, Thanks. I'd like to fix the bug first. Is there any issue linked to the bug you describe abov?Or could you please help describe bug with much more  details.

**Comment by tanzhenyu** [comment]
Seems we should make it supported. @pawarrick Do you need sample weight to be inside the canonical dataset when you do model.fit(dataset), or you want it to be a separate dataset such as model.fit(data_dataset, sample_weight_dataset)?

**Comment by pawarrick** [comment]
@tanzhenyu with no DistributionStrategy, it works fine "inside the canonical dataset" doing model.fit(dataset), so supporting it the same way would be excellent.

**Comment by visionscaper** [comment]
I'm interested to know if progress has been made with enabling `sample_weight_mode` for distribution strategies. If no progress has been made, what is the method is advised to deal with variable length outputs?

**Comment by guptapriya** [comment]
sample_weights have been fixed, but afaik, there is no progress on sample_weight_mode=temporal support.

**Comment by visionscaper** [comment]
Thanks for the comment @guptapriya, temporal weighting is what I need, so this saddens me a bit.

**Comment by guptapriya** [comment]
My hope is that we would add support for it sometime in the next few
months. We welcome contributions as well.

**Comment by visionscaper** [comment]
@guptapriya I noticed that in commit 3782019ca739f2b00f1f1990d737e7be65e09df9 support was added for "temporal sample weight mode in non-graph networks". Does that affect this issue? Just wondering.

**Comment by visionscaper** [comment]
@guptapriya Ah, I see that `sample_weight_mode` is still not supported with `tf.distribute.Strategy` in the r2.0 branch.

https://github.com/tensorflow/tensorflow/blob/c75bb66a99ad45e5a3c9fc4625c8abeb705520b5/tensorflow/python/keras/engine/training.py#L1461

What is the current status of this issue? Do you have any insights in how to proceed (how to fix it)?

**Comment by guptapriya** [comment]
Current status is that this is still not supported. 
However, we have made some progress recently on unifying keras execution with and without distribution strategy. This means that we should be able to provide this functionality sooner than later.
@tomerk @qlzh727 - do you have any insight into when the new execution path may support sample weight mode?

**Comment by tomerk** [comment]
I believe @pavithrasv has integrated sample_weight_mode into the unified path (although I'm not sure if she tested it with distribution strategies or not). You can go ahead and try the nightlies to see if it fixes it for you.

If it does we may still be able to cherrypick it into 2.0, or it may have to wait until a followup release.

**Comment by visionscaper** [comment]
@guptapriya @tomerk Thanks for your replies. Apparently @pavithrasv added "support for sample weight mode in v2 single execution path" through commit 9f30dc6211ac2531f98e1516f23bcb995d7a15c2. However, looking in to the latest version of `training.py` in the `master` branch, using `sample_weight_mode` is still not supported:

https://github.com/tensorflow/tensorflow/blob/2123cb71b81c92e08a9210d80b5974df5292878b/tensorflow/python/keras/engine/training.py#L1500

Further [`temporal_sample_weights_correctness_test.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/temporal_sample_weights_correctness_test.py) does not contain any tests related to distributed training strategies (as far as I could tell).

@tomerk Do you suggest, based on the above, that if I would remove the code that raises a `NotImplementedError`, when I use `sample_weight_mode` with a distribution strategy, it might work now?

**Comment by tomerk** [comment]
That method only runs in the older execution path that we will be removing soon once the new path supports everything the old path used to (it currently supports everything except for target_tensors & hdf5 matrix inputs & scipy sparse tensors)

If you run the nightly now sample_weight_mode shouldn't trigger the old path anymore so `_validate_compile_param_for_distribution_strategy` will no longer be run.

That said, it may or may not work with distribution strategies yet, but trying it is worth a shot. Please let us know how it goes if you do!

**Comment by visionscaper** [comment]
Hi @tomerk, @pavithrasv, to my surprise, after some fiddling to adapt my code to Tensorflow 2.0, temporal sample weighting works with the `MirroredStrategy`!

Please see my [Tensorflow Keras issues tests repo](https://github.com/visionscaper/tf-issues) that I use to investigate what features from the original Keras work in `tf.keras` and which don't.

You can run this test and see it in action yourself:

```
python3 tests/tf20_keras/tests.py TestIssuesTFKeras.test_multi_gpu_float32_no_masking_no_dropout_noise_shape_sample_weight_mode
```

To run the test above you need to have the dependencies in [`requirements_tensorflow20_keras_env.txt`](https://github.com/visionscaper/tf-issues/blob/master/requirements_tensorflow20_keras_env.txt) installed, also see the [`README.md`](https://github.com/visionscaper/tf-issues/blob/master/README.md).

**Comment by visionscaper** [comment]
@pavithrasv No, I didn't need to change anything related to the MirroredStrategy. And, yes, I used the very latest nightly (2 days ago):

```
$ pip list | grep tf-nightly
tf-nightly-gpu-2.0-preview       2.0.0.dev20190824   
```

**Comment by djo-koconi** [comment]
Hi @visionscaper  @tomerk and everyone.

Do you know by any chance does some distributed strategy supports target_tensors now?
I am unable to use multi gpu training as my model can only compile with use of target_tensors.

**Comment by tomerk** [comment]
Hi djo-koconi@, due to their degree of required technical complexity and relatively niche use cases, target_tensors have actually been removed entirely in recent versions of tensorflow  unless you're running legacy code with eager disabled + compat.v1 apis

The recommended way to achieve the same effect as target_tensors is to override your model's training step to pass the target into the model at training time.

This thread from fchollet@ demonstrates what overriding train_step looks like (in this case for training GANs, but the idea remains the same):
https://mobile.twitter.com/fchollet/status/1250622989541838848

We are also working on guides that will go more into detail in how to go about overriding different components of the training/evaluation loops to handle unique training workflows.

**Comment by djo-koconi** [comment]
Thank you very much @tomerk .
I finally managed to overcome using target_tensors the issue by using tf-nightly.

Just now my model now trains slower on 2 gpus compared to using single gpu which makes another unexpected issue.

**Comment by kiddyboots216** [comment]
sample_weight_mode still seems incompatible with any distributed strategy
