### ISSUE TITLE
Complete support for building C++ API on windows using Bazel

### ISSUE THREAD

**Issue by guikarist** [tensorflow/tensorflow#24885]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.11.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Feature: Correctly use Bazel to build Tensorflow C++ API on Windows.

Current state: Now we can build Tensorflow C++ API on Windows using Bazel by `bazel build //tensorflow:libtensorflow_cc.so` (I even wrote a [script](https://github.com/guikarist/tensorflow-windows-build-script) to do this). However, there are some problems:

1. [necessary symbols are not exported](https://github.com/tensorflow/tensorflow/blob/ac4d3682939dac303082097d25ebda805409acde/tensorflow/BUILD#L521) and [#23542](https://github.com/tensorflow/tensorflow/issues/23542)
1. The built libraries have `.so` extensions which are not for Windows platform, although after being renamed to `.dll` the dynamic libraries can be used.
1. There is no information about how to use built third-party `.a` files.

**Will this change the current api? How?**

Yes. The API may become `//tensorflow:libtensorflow_cc.dll`.

**Who will benefit with this feature?**

1. Everyone who wants to build Tensorflow C++ API on Windows.
1. Everyone who wants to use the latest Tensorflow C++ API on Windows (the last version of C++ API which can be built officially on Windows is 1.10.0).

**Any Other info.**
No.

**Comment by skye** [comment]
FYI @gunan @allenlavoie @asimshankar

**Comment by gunan** [comment]
@meteorcloudy for windows build guidelines.
I think in another issue there was a guide we could use.
@lamberta for docs updates.

**Comment by meteorcloudy** [comment]
I'm working on this, will send a solution in the next two days.

**Comment by meteorcloudy** [comment]
@guikarist Can you tell me how do people usually use the `tensorflow.dll` ? In Bazel build or in CMake or some other way?

**Comment by guikarist** [comment]
@meteorcloudy 

> @guikarist Can you tell me how do people usually use the `tensorflow.dll` ? In Bazel build or in CMake or some other way?

Typically we use `tensorflow.dll` in our own project. For example, I add the directory of Tensorflow source files (`*.h` and `*.cc`) into **Additional Include Directories**  and then add `tensorflow.dll` into linker setting in **Visual Studio**.

We just want to use Tensorflow as part of our own project. Although there is a way to do this by building with Bazel, it is not compatible with Visual Studio (even with Windows). So dynamic/static libraries are better.

**Comment by meteorcloudy** [comment]
@guikarist I hope https://github.com/tensorflow/tensorflow/pull/24963 could fix the dynamic linking issue.
For a static TensorFlow C library, because Bazel never has the ability to build a static library that contains all its dependencies, we cannot do it right now. But it would be fixed in future when C++ rules can be written in Starlark. (https://github.com/bazelbuild/bazel/issues/4570)

**Comment by Cory-Kramer** [comment]
@meteorcloudy We use a similar workflow to what @guikarist described. If there were pre-build Windows binaries that would be great. Otherwise we have no opposition to building from source, as long as there is a canonical process to do so.

**Comment by meteorcloudy** [comment]
@Cory-Kramer  With https://github.com/tensorflow/tensorflow/pull/24963, you can do it just by 
`bazel build --config=opt //tensorflow:tensorflow.dll`
We'll also release prebuilt libraries soon.

**Comment by guikarist** [comment]
@meteorcloudy 
Brilliant for your work!
So, what about the third-party libraries? Will they still be built to `*.a` files? I have no idea how deal with these files to be honest.

**Comment by meteorcloudy** [comment]
What do you mean by "third-party libraries"? Do you mean a static library for TensorFlow that you can link to?

**Comment by guikarist** [comment]
@meteorcloudy 
I mean just their literal meaning which is corresponding to libraries in `third_party` directory. Some of them is necessary for using Tensorflow on Windows.

**Comment by meteorcloudy** [comment]
Ah, I see. `tensorflow.dll` itself doesn't depend on any third party libraries at runtime. If you want to use them in your project, I think you can just build them with Bazel and add the static library (extension is `.lib` on Windows) to your project.

**Comment by guikarist** [comment]
@meteorcloudy 
You mean build them one by one outside Tensorflow source?

**Comment by meteorcloudy** [comment]
Well, if you build the TensorFlow pip package, I'm sure they will also be built, then you can find them under `bazel-bin/third_party`

**Comment by asimshankar** [comment]
My understanding is that `tensorflow.dll` will (statically) link in all the dependencies needed for TensorFlow, so you do not need to build individual dependencies and package them one-by-one.

**Comment by guikarist** [comment]
@asimshankar 

This is what command `tree -L 2` outputs (using WSL) in `bazel-bin/` which is built by the former `bazel build //tensorflow:libtensorflow_cc.so`:

```
.
├── external
│   ├── boringssl
│   ├── com_google_absl
│   ├── com_googlesource_code_re2
│   ├── double_conversion
│   ├── farmhash_archive
│   ├── fft2d
│   ├── gif_archive
│   ├── grpc
│   ├── highwayhash
│   ├── jpeg
│   ├── jsoncpp_git
│   ├── lmdb
│   ├── nsync
│   ├── org_sqlite
│   ├── png_archive
│   ├── protobuf_archive
│   ├── snappy
│   └── zlib_archive
├── result-0.txt
├── result.txt
└── tensorflow
    ├── c
    ├── cc
    ├── contrib
    ├── core
    ├── liblibtensorflow_cc.so.exp
    ├── liblibtensorflow_cc.so.ifso
    ├── libtensorflow_cc.so
    ├── libtensorflow_cc.so-2.params
    ├── libtensorflow_cc.so.runfiles
    ├── libtensorflow_cc.so.runfiles_manifest
    ├── stream_executor
    └── tools

27 directories, 7 files

```

So do you mean it is correct to directly link `libtensorflow_cc.so` (which is indeed `libtensorflow_cc.dll`)? Then I can use third-party dependencies besides Tensorflow?

[What we used to do with Tensorflow](https://github.com/tensorflow/tensorflow/issues/24885#issuecomment-454801655) is:

> Typically we use tensorflow.dll in our own project. For example, I add the directory of Tensorflow source files (*.h and *.cc) into Additional Include Directories and then add tensorflow.dll into linker setting in Visual Studio.
>
> We just want to use Tensorflow as part of our own project. Although there is a way to do this by building with Bazel, it is not compatible with Visual Studio (even with Windows). So dynamic/static libraries are better.
>
> Update:
> I use tensorflow_cc.dll rather than tensorflow.dll more exactly.

In terms of third-party dependencies, we build them outside the Tensorflow project. And use them just like what we do with Tensorflow. Because we have no idea how to deal with `*.a` files. For example, it is `bazel-bin/external/jpeg`:

```
jpeg
├── _objs
│   ├── jpeg
│   │   ├── jaricom.o
│   │   ├── jcapimin.o
│   │   ├── jcapistd.o
│   │   ├── jcarith.o
│   │   ├── jccoefct.o
│   │   ├── jccolor.o
│   │   ├── jcdctmgr.o
│   │   ├── jchuff.o
│   │   ├── jcinit.o
│   │   ├── jcmainct.o
│   │   ├── jcmarker.o
│   │   ├── jcmaster.o
│   │   ├── jcomapi.o
│   │   ├── jcparam.o
│   │   ├── jcphuff.o
│   │   ├── jcprepct.o
│   │   ├── jcsample.o
│   │   ├── jctrans.o
│   │   ├── jdapimin.o
│   │   ├── jdapistd.o
│   │   ├── jdarith.o
│   │   ├── jdatadst.o
│   │   ├── jdatasrc.o
│   │   ├── jdcoefct.o
│   │   ├── jdcolor.o
│   │   ├── jddctmgr.o
│   │   ├── jdhuff.o
│   │   ├── jdinput.o
│   │   ├── jdmainct.o
│   │   ├── jdmarker.o
│   │   ├── jdmaster.o
│   │   ├── jdmerge.o
│   │   ├── jdphuff.o
│   │   ├── jdpostct.o
│   │   ├── jdsample.o
│   │   ├── jdtrans.o
│   │   ├── jerror.o
│   │   ├── jfdctflt.o
│   │   ├── jfdctfst.o
│   │   ├── jfdctint.o
│   │   ├── jidctflt.o
│   │   ├── jidctfst.o
│   │   ├── jidctint.o
│   │   ├── jidctred.o
│   │   ├── jmemmgr.o
│   │   ├── jmemnobs.o
│   │   ├── jquant1.o
│   │   ├── jquant2.o
│   │   └── jutils.o
│   └── simd_none
│       └── jsimd_none.o
├── libjpeg.a
├── libjpeg.a-2.params
├── libsimd_none.a
└── libsimd_none.a-2.params

3 directories, 54 files

```

**Comment by guikarist** [comment]
> Well, if you build the TensorFlow pip package (or tensorflow.dll) with Bazel, I'm sure they will also be built, then you can find them under `bazel-bin/third_party`

@meteorcloudy When I build `libtensorflow_cc.so`, the third-party libraries are built, too (in `bazel-bin/external` which is same as the output directory of `//tensorflow/tools/pip_package:build_pip_package`).

What confuses me is the extensions of these libraries. I will try [what @asimshankar said](https://github.com/tensorflow/tensorflow/issues/24885#issuecomment-454829156).

**Comment by meteorcloudy** [comment]
@guikarist Oh, right, it should be `bazel-bin/external` instead of `bazel-bin/third_party`. All those dependencies are statically linked in the shared library (DLL), so you don't need them at runtime.

**Comment by guikarist** [comment]
@meteorcloudy Then, what about compiling? I think source codes of these dependencies are needed.

**Comment by meteorcloudy** [comment]
@guikarist I think what you need are the header files of those dependencies?
Maybe this could help:
https://stackoverflow.com/questions/42898577/list-of-headers-to-use-tensorflow-c-api-using-libtensorflow-cc-so

**Comment by nartes** [comment]
@meteorcloudy, will your solution provide an interface BUILD file?
1. The following targets are enough for now to be build, [1](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD#L515), [2](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/BUILD#L550):
  - //tensorflow:libtensorflow_cc.so
  - //tensorflow:install_headers;
2. But there's no standalone wrapping interface library neither for Bazel, nor for CMake. An example for CMake [3](https://github.com/Microsoft/vcpkg/pull/5222/files#diff-b1465f91cff230939224b1de329368a0R1), some simple example from bazel documentation [4](https://docs.bazel.build/versions/master/cpp-use-cases.html#adding-dependencies-on-precompiled-libraries);
3. vcpkg port proposal for tensorflow-cc [5](https://github.com/Microsoft/vcpkg/pull/5222/files#diff-eab36df6075256c6494aa137da1a9c1cR34).
4. Do you need some assistance in testing?

**Comment by meteorcloudy** [comment]
@nartes That sounds a good idea. But I'm not very familiar which headers should be included for the shared library. 
@gunan Do you know anyone could help on this?

**Comment by MIKOCHAO** [comment]
rename the .so to .dll, it does not work for me

**Comment by guikarist** [comment]
@MIKOCHAO Try [my script](https://github.com/guikarist/tensorflow-windows-build-script), bro.

**Comment by rounakskm** [comment]
@guikarist I successfully ran the following commands:
bazel build //tensorflow:libtensorflow_cc.so
bazel build --config=opt //tensorflow:tensorflow.dll

Now how do It in my own Visual Studio project. Which directories should I add into Additional Include Directories? There are a lot of directories with .h files.
And will I need to copy the tensorflow.dll or tensorflow:libtensorflow_cc.so (renamed to tensorflow:libtensorflow_cc.dll) file to the visual studio project directory?

Thank you

**Comment by guikarist** [comment]
@rounakskm First of all, `//tensorflow:tensorflow.dll` target is for C API. And this is a [wiki about how to use the built results](https://github.com/guikarist/tensorflow-windows-build-script/wiki/Using-the-built-results), where I have published a script (a gist). Then you should add the sources to `Additional Include Directories` and `tensorflow_cc.lib` to `linker` (I don't remember the exact name). Don't forget to add sources of the third party in `$sourceDir\bazel-source\external\`.

**Comment by rounakskm** [comment]
How do I get the required symbols to avoid linker errors. 
I am getting an unresolved external symbol error:

error LNK2001: unresolved external symbol "class tensorflow::Status __cdecl tensorflow::LoadSavedModel(struct tensorflow::SessionOptions const &,class tensorflow::RunOptions const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::unordered_set<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::hash<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,struct std::equal_to<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > const &,struct tensorflow::SavedModelBundle * const)" (?LoadSavedModel@tensorflow@@YA?AVStatus@1@AEBUSessionOptions@1@AEBVRunOptions@1@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV?$unordered_set@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@U?$hash@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@U?$equal_to@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@6@QEAUSavedModelBundle@1@@Z)

**Comment by rounakskm** [comment]
Hello,
@Steroes I did what you mentioned. But the linker errors are not going.

I think it has to do with the fact that I am using TF 2.0 and the modifications in the BUILD file are different.
I added the missing symbols to the tf_exported_symbols_mscv.lds and ran the build again but that does not solve my linking errors. I get the same symbols as missing.

Some background on how I ran the build->
For TF 2.0 BUILD file I cannot use the git -diff file with the changes mentioned in (#22047 (comment)).
So I made the required changes manually (line 538 and 661 in this case), added the tf_exported_symbols.lds with my missing symbols and ran the bazel build //tensorflow:tensorflow_cc.

Line 558 of the tensorflow/BUILD file in r2.0 branch has the following:
add win_def_file for tensorflow_cc
win_def_file = select({
# We need this DEF file to properly export symbols on Windows
"//tensorflow:windows": ":tensorflow_filtered_def_file",
"//conditions:default": None,
}),

But I cant figure out the syntax of adding the tf_exported_symbols_mscv.lds
Please help

**Comment by guikarist** [comment]
@rounakskm No any other similar code blocks? If so, this trick may not work on TF 2.0.

**Comment by rounakskm** [comment]
No the other part of tf_cc_shared object is the same.
With minor changes. Like name =libtensorflow_cc has been changed to name = tensorflow_cc. 

But the # add win_def_file for tensorflow_cc comment and section below is new.

**Comment by MPROXX** [comment]
I'm a bit confused: I'm trying to build tensorflow for C++ too but should I follow @guikarist 's or @meteorcloudy 's way?

**Comment by rounakskm** [comment]
You can use  @guikarist 's  script. It will be easier. and Depending on the version check the tensorflow/BUILD file in the tensorflow repo directory and patch it

**Comment by MPROXX** [comment]
@rounakskm thanks!!!

**Comment by MPROXX** [comment]
I tried executing //tensorflow:libtensorflow_cc.so via @guikarist 's script and I guess it worked
but the PS-script that extracts the tensorflow library is looking for liblibtensorflow_cc.so.ifso which I dont have
Its also looking for header-files in /core but I dont have any
I have following files and directories:
<c>
<cc>
<contrib>
<core>
<libtensorflow_cc.so.runfiles>
<stream_executor>
<tools>
-libtensorflow_cc.so
-libtensorflow_cc.so.if.exp
-libtensorflow_cc.so.if.lib
-libtensorflow_cc.so.runfiles_manifest
-libtensorflow_cc.so-2.params

why am I missing the files?
did I miss a step?

**Comment by guikarist** [comment]
Which version did you used?
@MPROXX

**Comment by MPROXX** [comment]
@guikarist I chose Tensorflow v1.13.1
sry for the late reply, it was a busy week

**Comment by MPROXX** [comment]
@rounakskm what do you mean by "patching" the tensorflow/BUILD file?

**Comment by guikarist** [comment]
> @guikarist I chose Tensorflow v1.13.1
> sry for the late reply, it was a busy week

I am sorry that I didn't test the built results of `v1.13.1` of which I just tested building. Maybe renaming `libtensorflow_cc.so.if.lib` to `xxx.lib` works.

**Comment by MPROXX** [comment]
> 
> 
> > @guikarist I chose Tensorflow v1.13.1
> > sry for the late reply, it was a busy week
> 
> I am sorry that I didn't test the built results of `v1.13.1` of which I just tested building. Maybe renaming `libtensorflow_cc.so.if.lib` to `xxx.lib` works.

It's ok it's ok, thanks for your effort and your support!!
I'll try that and come back here to report whether it was successful!

**Comment by MPROXX** [comment]
Alright, I renamed libtensorflow_cc.so.if.lib to tensorflow_cc.lib
I tried making a project in Visual Studio,
I added **...\source\bazel-source\external** and  **...\bin\tensorflow\include** to Additional Include Directories
and also ...\bin\tensorflow\lib to Additional Library Directories

then I created a quick main.cpp:
`#include "main.h"
#include <tensorflow/cc/ops/standard_ops.h>
//#include <tensorflow/core/framework/graph.pb.h> cant be found, I dont have protobuf
#include <tensorflow/core/graph/graph.h>
#include <tensorflow/core/framework/tensor.h>
#include <tensorflow/core/lib/core/status.h>
#include <tensorflow/core/platform/env.h>
//#include <tensorflow/core/protobuf/config.pb.h> cant be found, I dont have protobuf
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/public/session_options.h>
#include <tensorflow/core/util/command_line_flags.h>

main::main()
{}

main::~main()
{}
`

compiled it and it doesnt find any of the header-files:
`Error (active)	E1696	cannot open source file "tensorflow/cc/ops/array_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/core/framework/tensor.pb.h"	
Error (active)	E1696	cannot open source file "absl/strings/str_cat.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/candidate_sampling_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/control_flow_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/data_flow_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/image_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/io_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/linalg_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/logging_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/lookup_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/math_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/nn_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/no_op.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/parsing_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/random_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/sparse_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/state_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/string_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/training_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/user_ops.h"	
.....`
the list goes further

I'm not sure where and how to install protobuf during the building process of tensorflow or why those
.pb.h-files are missing
Maybe the missing header-files are the result of renaming the wrong tensorflow_cc.lib?
Or are my project settings in including the library to my project in Visual Studio wrong?

**Comment by MPROXX** [comment]
@guikarist 
I renamed libtensorflow_cc.so.if.lib to tensorflow_cc.lib
I've made a project in Visual Studio
I added **...\source\bazel-source\external** and **...\bin\tensorflow\include** to Additional Include Directories
I added **...\bin\tensorflow\lib** to Additional Library Directories

I made a quick main.cpp:
`#include "main.h"
#include <tensorflow/cc/ops/standard_ops.h>
//#include <tensorflow/core/framework/graph.pb.h> missing, I dont have protobuf
#include <tensorflow/core/graph/graph.h>
#include <tensorflow/core/framework/tensor.h>
#include <tensorflow/core/lib/core/status.h>
#include <tensorflow/core/platform/env.h>
//#include <tensorflow/core/protobuf/config.pb.h> missing, I have no protobuf
#include <tensorflow/core/public/session.h>
#include <tensorflow/core/public/session_options.h>
#include <tensorflow/core/util/command_line_flags.h>

main::main()
{}

main::~main()
{}
`

I build it and it doesnt find the headers:
`Error (active)	E1696	cannot open source file "tensorflow/cc/ops/array_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/core/framework/tensor.pb.h"	
Error (active)	E1696	cannot open source file "absl/strings/str_cat.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/candidate_sampling_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/control_flow_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/data_flow_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/image_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/io_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/linalg_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/logging_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/lookup_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/math_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/nn_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/no_op.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/parsing_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/random_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/sparse_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/state_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/string_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/training_ops.h"	
Error (active)	E1696	cannot open source file "tensorflow/cc/ops/user_ops.h
...."	`
the list goes further

I'm not sure where and how to install protobuf during the build process of tensorflow yet
Am I missing the header-files because I renamed the wrong tensorflow_cc.lib?
Are my project settings for including the library wrong?

**Comment by MPROXX** [comment]
Its interesting, regardless of which TF version I try to build (I tried 1.11.0 this time), I never get the same files as mentioned above after building

**Comment by aSmallsheep** [comment]
build the headers for C API is：bazel build :install_headers:
I have build .dll and .lib by ：
bazel build --config=opt --config=cuda //tensorflow:tensorflow_cc.dll（for dll）
bazel build --config=opt --config=cuda //tensorflow:tensorflow_cc_dll_import_lib(for lib)
How to build headers for C++ API and how to use those in VS2015?

**Comment by sitting-duck** [comment]
I made a README explaining how I built the tensorflow .lib and .dll files for the Tensorflow C++ APIp on Windows. The tutorial is step by step and starts at the very beginning, so you may have to scroll down past steps you have already done, like checking your hardware, installing Bazel etc.
Here is the url: https://github.com/sitting-duck/stuff/tree/master/ai/tensorflow/build_tensorflow_1.14_source_for_Windows

Probably you will want to scroll all the way down to this part:
https://github.com/sitting-duck/stuff/tree/master/ai/tensorflow/build_tensorflow_1.14_source_for_Windows#step-7-build-the-dll

It shows how to pass command to create .lib and .dll.

Then to test your .lib you should link into your c++ project,

Then it will show you how to identify and fix the missing symbols using the TF_EXPORT macro

I am actively working on making this tutorial better so feel free to respond to my comment here or email: ashley.tharp@gmail.com with feedback or if you are confused on a particular part. :)

**Comment by danperazzo** [comment]
@guikarist , could you send please a sample program from you build of tensorflow? I have used it to build tensorflow, have used the correct files and linkers in microsoft visual studio 2017. However, It does not seem to work since the "tensorflow/core/framework/graph.pb.h" file is missing on most tutorial that I find. For testing, I have been using this tutorial: https://medium.com/@mohamedtamer92/tensorflow-how-to-export-freeze-models-with-python-api-and-deploy-object-detection-models-with-a6bbb74afe1c

**Comment by omatai** [comment]
> 
> 
> @Cory-Kramer With #24963, you can do it just by
> `bazel build --config=opt //tensorflow:tensorflow.dll`
> We'll also release prebuilt libraries soon.

Has anything replaced this? When I try the bazel command above on r2.3 source, I get "ERROR: config value opt is not defined in any .rc file". I also do not see any evidence of prebuilt libraries :-( Has there been a 2.0+ release with prebuilt libraries for Windows? Anything released in the 1.x series?

**Comment by omatai** [comment]
Further to above, in building r2.3 out of the box on Windows, it seems like one (at least) needs to change --config=opt to -c opt:
    bazel build -c opt //tensorflow:tensorflow.dll
