### ISSUE TITLE
Tensorflow Import Error (numpy.core.multiarray failed to import)

### ISSUE THREAD

**Issue by geoJaSON** [tensorflow/tensorflow#25942]
Trying to import Tensorflow in iPython while in an conda environment. An issue with Numpy seems to be breaking the import. I have uninstalled and reinstalled numpy and tensorflow (CPU) using Pip commands within the environment. Thanks everyone

*System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow version: 1.13
- Python version: 3.7.2
- Installed using virtualenv? pip? conda?: pip install --upgrade tensorflow

In [1]: import tensorflow
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: DLL load failed: The specified module could not be found.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
~\AppData\Local\conda\conda\envs\objectdetection\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core._multiarray_umath failed to import
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
ImportError: numpy.core.umath failed to import
2019-02-20 07:42:30.475025: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr

**Comment by Lauler** [comment]
Take a look at #559 . Usually this seems to happen when you have had an older version of numpy installed somewhere. pip isn't always to be trusted when upgrading and installing new packages. 

I got the same exact error in one conda env where I had a previous tensorflow version installed and tried to install a new one. It was easily solved by starting a new conda environment and installing everything from scratch. But you can look in to the referenced issue and try with manually deleting numpy installations.

**Comment by ymodak** [comment]
In addition to @Lauler 's suggestion, Python 3.7 is supported in TensorFlow 1.13.0-rc2 build.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by 8bitmp3** [comment]
In case this is still an issue for some users, it happened with TensorFlow 1.13.1:
```
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import
```
Upgrading numpy from 1.15.4 to 1.16.4 in a virtual environment with `pip3 install --upgrade numpy` can fix it.

**Comment by nikzzastic** [comment]
Didn't worked. Still same issue and kernel dies once I try importing tensorflow

**Comment by zanwei234** [comment]
maybe  installed tensorflow-gpu first and tensorflow after that 
just uninstall the later one or reinstall only one version can repair this issue

**Comment by jrosseel** [comment]
Broken again in numpy 1.17.0

**Comment by nikzzastic** [comment]
I also think the same

**Comment by mikeyEcology** [comment]
I had the same problem and this worked for me:
`````
pip uninstall numpy
pip install -U numpy
`````

**Comment by shivanarayana** [comment]
![image](https://user-images.githubusercontent.com/10083536/80094568-1bfd8c00-8584-11ea-8e93-a21e1faa4c63.png)

**Comment by shivanarayana** [comment]
i am getting numpy but unable to use cv2

please help

**Comment by avrajsri** [comment]
Try This...
Run this Code One by One...

pip uninstall numpy
pip install numpy==1.19.3

**Comment by justinelock** [comment]
**pip install numpy==1.19.3** is ok, it works

**Comment by Amir22010** [comment]
finally something works of me 1.19.3
