### ISSUE TITLE
tensorboard server: base_url support

### ISSUE THREAD

**Issue by haraldschilly** [tensorflow/tensorflow#2602]
### What have you tried?

Running the tensorboard service through a proxy server, which does map a subdirectory to the tensorboard server' root.
### Desired outcome

By providing a way to specify a `base_url`, the server would understand how to treat incoming requests in such a situation. e.g. `://server/subdir/tensorboard/` → `://server/`

**Comment by danmane** [comment]
Hi haraldschilly,

Can you give an example of exactly how TensorBoard misbehaves in your setup? I.e. what requests does the frontend make that 404?

Overall, this seems like a nice candidate for a pull request.

**Comment by haraldschilly** [comment]
Hi, I can describe you my specific use case. It's about the online service https://cloud.sagemath.com where you're essentially running programs in a managed linux environment. When this tensorboard is being started, you cannot access it directly, but through a http proxy. I.e. in the anaconda environment, where tensorflow is being installed,

```
$ tensorboard --port=7878 --logdir=.
Starting TensorBoard b'16' on port 7878
(You can navigate to http://0.0.0.0:7878)
```

Then I go to https://cloud.sagemath.com/xxxx-xxxx-project-uuid-xxx-xxx/port/7878/ which causes requests to be mapped to the service running in the project on port 7878.

and the page shows this:

```
Error response

Error code: 404

Message: Not Found.

Error code explanation: 404 - Nothing matches the given URI.
```

and in the terminal is that:

```
WARNING:tensorflow:IOError [Errno 2] No such file or directory: '/projects/anaconda3/lib/python3.5/site-packages/tensorflow/tensorboard/xxxx-xxxx-xxxx-xxxx/port/7878' on path /projects/anaconda3/lib/python3.5/site-packages/tensorflow/tensorboard/xxxx-xxxx-xxxx-xxxx/port/7878
10.244.5.3 - - [02/Jun/2016 15:23:11] code 404, message Not Found
10.244.5.3 - - [02/Jun/2016 15:23:11] "GET /xxxx-xxxx-xxxx-xxxx/port/7878/ HTTP/1.1" 404 -
```

**Comment by zhaojunz** [comment]
I hope the problem is fixed by this diff: https://github.com/tensorflow/tensorflow/commit/c0fc1b998ddbc838a479e295dfd9c0ad75d28f48 though I haven't really tried it out yet.

**Comment by bitfusion-brian** [comment]
I am trying to proxy TB and am running into this issue as well. I'm gonna work on a fix in for this.  I'm not sure if I'm gonna switch everything to relative url's, or use the --base-url option to prepend the urls. I have to dig into the code first. Any suggestions welcome.

**Comment by wannabesrevenge** [comment]
@haraldschilly the latest tensorboard source uses all relative URLs. You can use a proxy with tensorboard if you remove the base path before proxying.

example:

Let's say you have a proxy located at `www.server.example`, you have a path defined for Tensorboard like so: `http://www.server.example/base/path/` , and your Tensorboard server is listening at `192.0.0.20:6006`

You want to make sure your proxy forwards `http://www.server.example/base/path/` to `http://192.0.0.20:6006/`. When you call the URL, `http://www.server.example/base/path/`, from the client (firefox, chrome, etc), you need to make sure you have a `/` on the end of the path, or else the relative URLs will chop off the last bit of the path.

**Comment by berthoug** [comment]
Hi,
I'm also trying to have the tensorboard running behind a proxy and the relative URLs works for most of it except /data/logdir and /data/runs which seems to still have an absolute path. I did my run with the tensorflow-1.1.0rc2-cp27, should I use another version of tensorflow?

**Comment by chihuahua** [comment]
I have migrated this issue to tensorflow/tensorboard#69 because TensorBoard has moved into its own repository (outside of tensorflow/tensorflow).
