### ISSUE TITLE
BaseCollectiveExecutor::StartAbort Invalid argument: Upper bound check fail is reported with CollectiveAllReduceStrategy

### ISSUE THREAD

**Issue by PangHua** [tensorflow/tensorflow#26725]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  CentOS Linux release 7.4.1708 (Core)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): ('v1.13.1-0-g6612da8951', '1.13.1')
- Python version: 2.7
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: Tesla P100, 16G

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**
When running transformer within the tensor2tensor library with CollectiveAllReduceStrategy via little customized change for distributed training in t2t only, it reported below error:

INFO:tensorflow:Graph was finalized.
WARNING:tensorflow:From /home/xh/tf-1.13.1/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
INFO:tensorflow:Restoring parameters from /home/xh/datasets/t2t_train_enzh_multi-gpu-ok/translate_enzh_wmt32k/transformer-transformer_base/model.ckpt-179000
2019-03-14 15:30:36.585213: I tensorflow/core/distributed_runtime/master_session.cc:1192] Start master session 4c2e055e28f41c2f with config: device_filters: "/job:worker/task:0" device_filters: "/job:worker/task:0" gpu_options { per_process_gpu_memory_fraction: 0.95 } allow_soft_placement: true graph_options { optimizer_options { global_jit_level: OFF } rewrite_options { scoped_allocator_optimization: ON scoped_allocator_opts { enable_op: "CollectiveReduce" enable_op: "CollectiveReduce" enable_op: "CollectiveReduce" enable_op: "CollectiveReduce" } } } experimental { collective_group_leader: "/job:worker/replica:0/task:0" }
WARNING:tensorflow:From /home/xh/tf-1.13.1/lib/python2.7/site-packages/tensorflow/python/training/saver.py:1070: get_checkpoint_mtimes (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file utilities to get mtimes.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Initialize strategy
INFO:tensorflow:Saving checkpoints for 179000 into /home/xh/datasets/t2t_train_enzh_multi-gpu-ok/translate_enzh_wmt32k/transformer-transformer_base/model.ckpt.
2019-03-14 15:32:18.009875: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally
2019-03-14 15:32:28.447121: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:101] Filling up shuffle buffer (this may take a while): 387 of 512
2019-03-14 15:32:31.537519: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:140] Shuffle buffer filled.
2019-03-14 15:32:31.695275: W tensorflow/core/common_runtime/base_collective_executor.cc:203] BaseCollectiveExecutor::StartAbort Invalid argument: Upper bound check fail for input 1 from node training/gradients/transformer/parallel_0_5/transformer/transformer/symbol_modality_32610_512_1/softmax/concat_grad/Slice_7 to node scoped_allocator_concat_232 input bounds = [0x7fb060a84f00, 0x7fb060e7ff00] backing_tensor bounds = [0x7faf8da62700, 0x7faf8fe35700]
	 [[{{node scoped_allocator_concat_232}}]]
2019-03-14 15:32:31.708208: W tensorflow/core/common_runtime/base_collective_executor.cc:203] BaseCollectiveExecutor::StartAbort Invalid argument: Upper bound check fail for input 1 from node training/gradients/transformer/parallel_0_5/transformer/transformer/symbol_modality_32610_512_1/softmax/concat_grad/Slice_7 to node scoped_allocator_concat_232 input bounds = [0x7fb060a84f00, 0x7fb060e7ff00] backing_tensor bounds = [0x7faf8da62700, 0x7faf8fe35700]
	 [[{{node scoped_allocator_concat_232}}]]
	 [[{{node _send_add_1_0}}]]
InvalidArgumentError: InvalidA...ntError()

**Describe the expected behavior**
What does above error log mean, and is there any way to fix it? thanks.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by isaacnoble** [comment]
Also seeing this bug when using tf.contrib.distribute.CollectiveAllReduceStrategy, any information on what it means?

**Comment by vishald527** [comment]
Any update on this issue? Even I am facing the exact same error. @isaacnoble @jvishnuvardhan

**Comment by byronyi** [comment]
Ping @poxvoculi; looks like a ScopeAllocator issue.

**Comment by vishald527** [comment]
@poxvoculi by any chance did you get time to look into this issue? @byronyi any workaround you can suggest for this?

**Comment by byronyi** [comment]
Pinging @dubey too

**Comment by fhdbbk** [comment]
Even I'm facing the same issue. Do update us as soon as you find a solution.

**Comment by IamShivamJaiswal** [comment]
Even I'm facing the same with tensorflow version=1.11 Python=3.6

**Comment by dubey** [comment]
Thanks for filing the issue.  [`589fb0dfdb`](https://github.com/tensorflow/tensorflow/commit/589fb0dfdb694d6318784e1523672fc2833b736d) fixed a similar issue in `ScopedAllocator`.  Can you try running with a nightly build and let us know if you still see this bug?  If yes, please also post instructions on how to reproduce.

**Comment by vishald527** [comment]
> Thanks for filing the issue. [`589fb0dfdb`](https://github.com/tensorflow/tensorflow/commit/589fb0dfdb694d6318784e1523672fc2833b736d) fixed a similar issue in `ScopedAllocator`. Can you try running with a nightly build and let us know if you still see this bug? If yes, please also post instructions on how to reproduce.

Hi @dubey ,

I have a constraint where I need to work on conda tensorflow v1.11 

Following are the steps to reproduce the error with tensorflow v1.11
1. Run the worker1.ipynb on node 1 
[worker1.zip](https://github.com/tensorflow/tensorflow/files/3062532/worker1.zip)

2. Run the worker2.ipynb on node 2 
[worker2.zip](https://github.com/tensorflow/tensorflow/files/3062533/worker2.zip)

Note: Do modify the TF_Config variable according to your cluster specs in both the jupyter files

You will get errors [https://gist.github.com/vishald527/5c464addba66188625ea0088853db970](url) and [https://gist.github.com/vishald527/4c06f908651cae57b8a9f72996ea834d](url) on node 1 and 2 respectively.

After making the changes as suggested in [https://github.com/tensorflow/tensorflow/commit/f10b00558de87020554c9c0512537dab96dba918](url) re-run the jupyter files.

Now you will get this [https://gist.github.com/vishald527/616c1dc32f20d8226d712f4552b025fa](url) error on node 1 and this [https://gist.github.com/vishald527/d47696e61c3f31f4d3063ff48dffaea7](url) log on node 2.

Post making the changes suggested here [https://github.com/tensorflow/tensorflow/commit/e692dda4c8b199555e2fa32132a7784e0893c870](url) re-run the jupyter files.

Now you will get this [https://gist.github.com/vishald527/b1a0d7cb436f70902594dbd742701794](url) error on node 1 and this [https://gist.github.com/vishald527/6dc8b8719b4a67e0ee6dabd3a61ad779](url) on node 2.

We even tried building tensorflow v1.11 after making the changes you had suggested here [https://github.com/tensorflow/tensorflow/commit/589fb0dfdb694d6318784e1523672fc2833b736d](url), but we are again getting the same Upper/Lower bound check fail error on both nodes.

Request you to please suggest what fixes are to be done in tensorflow v1.11 to get rid of this error and get CollectiveAllReduceStrategy up and running.

**Comment by byronyi** [comment]
@vishald527 I am not a member of the TF team but I believe they do not accept bugfix for experimental features, a.k.a. those in the contrib folder.

`CollectiveAllReduceStrategy` was an experimental feature in r1.11, so you probably need to cherry pick the bugfix patches, and backport them to r1.11. I am not sure how hard it is though.

Please correct me if I am wrong.

**Comment by vishald527** [comment]
@byronyi got your point but how to get a patch for this particular error? i am getting this error in v1.11 and the person who raised this issue got the same error in v1.13.
The patch for this error which @dubey had mentioned above didn't work.

Also, do we say that currently tensorflow does not support a stable multi node gpu based synchronous distributed training strategy at all?

**Comment by byronyi** [comment]
> @byronyi got your point but how to get a patch for this particular error? i am getting this error in v1.11 and the person who raised this issue got the same error in v1.13.
> The patch for this error which @dubey had mentioned above didn't work.

I do not know. I would suggest you to upgrade your TF version.

> Also, do we say that currently tensorflow does not support a stable multi node gpu based synchronous distributed training strategy at all?

It depends on your definition to "stable". It was an experimental feature in r1.11, it is still an experimental feature right now. Use it at your own risk.

**Comment by vishald527** [comment]
> I do not know. I would suggest you to upgrade your TF version.

TF v1.13 already has the same error and TF v2.0 does not have this strategy..so not sure which TF version you are suggesting to upgrade.

> It depends on your definition to "stable". It was an experimental feature in r1.11, it is still an experimental feature right now. Use it at your own risk.

By stable I meant a strategy which would at least start synchronous distributed training on a multiple node gpu based system. Currently we are in a situation where we don't have a single strategy which even starts distributed training on multiple nodes synchronously. Please do correct me if I am wrong.

Also is there any method you are aware of by which we can run distributed training on gpu based multiple node system?

**Comment by byronyi** [comment]
> TF v1.13 already has the same error and TF v2.0 does not have this strategy..so not sure which TF version you are suggesting to upgrade.

CollectiveAllReduce is exposed as `tf.distribute.experimental.MultiWorkerMirroredStrategy` in TF 2.0. See [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/distribute/collective_all_reduce_strategy.py#L48) for details.

> Also is there any method you are aware of by which we can run distributed training on gpu based multiple node system?

Apart from `MultiWorkerMirroredStrategy`, you could try `ParameterServerStrategy` as well. They are both in the `tf.distribute.experimental` subpackage.

**Comment by vishald527** [comment]
> CollectiveAllReduce is exposed as tf.distribute.experimental.MultiWorkerMirroredStrategy in TF 2.0. See here for details.

TF 2.0 i guess requires CUDA 10 and I have CUDA 9.2 installed. Upgrading CUDA is not an option for me right now and that is why I need help on fixing this reported issue for TF 1.11/1.13. Any pointers on who might be able to help resolving this issue?

> Apart from MultiWorkerMirroredStrategy, you could try ParameterServerStrategy as well. They are both in the tf.distribute.experimental subpackage.

ParameterServerStrategy is an asynchronous technique. I am looking for a synchronous one.

**Comment by byronyi** [comment]
> TF 2.0 i guess requires CUDA 10 and I have CUDA 9.2 installed. Upgrading CUDA is not an option for me right now and that is why I need help on fixing this reported issue for TF 1.11/1.13. Any pointers on who might be able to help resolving this issue?

You could recompile your TF using CUDA 9.2.

**Comment by vishald527** [comment]
> You could recompile your TF using CUDA 9.2.

Will try that too.

@dubey any luck on finding the cause and fix for this issue?

**Comment by dubey** [comment]
Apologies for the delay, this was a bit tricky to debug and fix.  I just submitted [`a3d2ee6`](https://github.com/tensorflow/tensorflow/commit/a3d2ee6ada53fdfde96a76d635c721629acb9582) which should fix the bounds check failure.  Let us know if it works for you.

**Comment by vishald527** [comment]
@dubey do I need to make both the code changes you had given and then try or only the latest one?

**Comment by dubey** [comment]
I'd recommend patching both changes.

**Comment by royxue** [comment]
@dubey 
I used a recent built(6 days ago) `nightly-gpu` docker image, this error still exists

**Comment by dubey** [comment]
@royxue thanks for the update.  Can you post the error message you get with the recent image, as well as instructions to reproduce the error?

**Comment by royxue** [comment]
I will try run again with the most recent docker image, and get back to you the result

**Comment by royxue** [comment]
@dubey Here is the logs.
I slightly modified the TF object detection. And run the collective allreduce strategy with 4 workers (1 gpu per worker) on k8s.

```
2019-04-24 03:09:04.405555: W tensorflow/core/common_runtime/base_collective_executor.cc:215] BaseCollectiveExecutor::StartAbort Invalid argument: Upper bound check fail for input 1 from node gradients/AddN_20 to node scoped_allocator_concat_100_16 input bounds = [0x7fdbfcfb0f00, 0x7fdbfcff8f00] backing_tensor bounds = [0x7fdbea25fd00, 0x7fdbea2f7900]
	 [[{{node scoped_allocator_concat_100_16}}]]
	 [[global_norm/global_norm_G6542]]
2019-04-24 03:09:04.405608: E tensorflow/core/common_runtime/ring_alg.cc:279] Aborting RingReduce with Invalid argument: Upper bound check fail for input 1 from node gradients/AddN_20 to node scoped_allocator_concat_100_16 input bounds = [0x7fdbfcfb0f00, 0x7fdbfcff8f00] backing_tensor bounds = [0x7fdbea25fd00, 0x7fdbea2f7900]
	 [[{{node scoped_allocator_concat_100_16}}]]
	 [[global_norm/global_norm_G6542]]
2019-04-24 03:09:04.405617: W tensorflow/core/common_runtime/base_collective_executor.cc:215] BaseCollectiveExecutor::StartAbort Invalid argument: Upper bound check fail for input 1 from node gradients/AddN_20 to node scoped_allocator_concat_100_16 input bounds = [0x7fdbfcfb0f00, 0x7fdbfcff8f00] backing_tensor bounds = [0x7fdbea25fd00, 0x7fdbea2f7900]
	 [[{{node scoped_allocator_concat_100_16}}]]
	 [[global_norm/global_norm_G6542]]
2019-04-24 03:09:04.405728: E tensorflow/core/common_runtime/ring_alg.cc:279] Aborting RingReduce with Invalid argument: Upper bound check fail for input 1 from node gradients/AddN_20 to node scoped_allocator_concat_100_16 input bounds = [0x7fdbfcfb0f00, 0x7fdbfcff8f00] backing_tensor bounds = [0x7fdbea25fd00, 0x7fdbea2f7900]
	 [[{{node scoped_allocator_concat_100_16}}]]
	 [[global_norm/global_norm_G6542]]
2019-04-24 03:09:04.405741: W tensorflow/core/common_runtime/base_collective_executor.cc:215] BaseCollectiveExecutor::StartAbort Invalid argument: Upper bound check fail for input 1 from node gradients/AddN_20 to node scoped_allocator_concat_100_16 input bounds = [0x7fdbfcfb0f00, 0x7fdbfcff8f00] backing_tensor bounds = [0x7fdbea25fd00, 0x7fdbea2f7900]
	 [[{{node scoped_allocator_concat_100_16}}]]
	 [[global_norm/global_norm_G6542]]
2019-04-24 03:09:04.405823: W tensorflow/core/framework/op_kernel.cc:1455] OP_REQUIRES failed at collective_ops.cc:223 : Invalid argument: Upper bound check fail for input 1 from node gradients/AddN_20 to node scoped_allocator_concat_100_16 input bounds = [0x7fdbfcfb0f00, 0x7fdbfcff8f00] backing_tensor bounds = [0x7fdbea25fd00, 0x7fdbea2f7900]
	 [[{{node scoped_allocator_concat_100_16}}]]
	 [[global_norm/global_norm_G6542]]
2019-04-24 03:09:04.405885: W tensorflow/core/framework/op_kernel.cc:1455] OP_REQUIRES failed at collective_ops.cc:223 : Invalid argument: Upper bound check fail for input 1 from node gradients/AddN_20 to node scoped_allocator_concat_100_16 input bounds = [0x7fdbfcfb0f00, 0x7fdbfcff8f00] backing_tensor bounds = [0x7fdbea25fd00, 0x7fdbea2f7900]
	 [[{{node scoped_allocator_concat_100_16}}]]
	 [[global_norm/global_norm_G6542]]
2019-04-24 03:09:04.408029: W tensorflow/core/common_runtime/base_collective_executor.cc:215] BaseCollectiveExecutor::StartAbort Invalid argument: Upper bound check fail for input 1 from node gradients/AddN_20 to node scoped_allocator_concat_100_16 input bounds = [0x7fdbfcfb0f00, 0x7fdbfcff8f00] backing_tensor bounds = [0x7fdbea25fd00, 0x7fdbea2f7900]
	 [[{{node scoped_allocator_concat_100_16}}]]
Traceback (most recent call last):
  File "/models/object_detection/model_main.py", line 127, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python2.7/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/models/object_detection/model_main.py", line 123, in main
    tf.estimator.train_and_evaluate(estimator, train_spec, eval_specs[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/training.py", line 464, in train_and_evaluate
    estimator, train_spec, eval_spec, _TrainingExecutor)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/distribute/estimator_training.py", line 290, in train_and_evaluate
    session_config=run_config.session_config)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/distribute/distribute_coordinator.py", line 853, in run_distribute_coordinator
    task_id, session_config, rpc_layer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/distribute/distribute_coordinator.py", line 360, in _run_single_worker
    return worker_fn(strategy)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/distribute/estimator_training.py", line 252, in _worker_fn
    hooks=hooks)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 362, in train
    loss = self._train_model(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1152, in _train_model
    return self._train_model_distributed(input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1215, in _train_model_distributed
    self._config._train_distribute, input_fn, hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1325, in _actual_train_model_distributed
    saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1402, in _train_with_estimator_spec
    estimator_spec, worker_hooks, saving_listeners)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1348, in _train_with_estimator_spec_distributed
    _, loss = mon_sess.run([estimator_spec.train_op, estimator_spec.loss])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 754, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1252, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1353, in run
    raise six.reraise(*original_exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1338, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1411, in run
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/monitored_session.py", line 1169, in run
    return self._sess.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 948, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1171, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_run
    run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1368, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Upper bound check fail for input 1 from node gradients/AddN_20 to node scoped_allocator_concat_100_16 input bounds = [0x7fdbfcfb0f00, 0x7fdbfcff8f00] backing_tensor bounds = [0x7fdbea25fd00, 0x7fdbea2f7900]
	 [[{{node scoped_allocator_concat_100_16}}]]
	 [[global_norm/global_norm_G6542]]
```

**Comment by dubey** [comment]
Can you provide a bare minimum test case that reproduces this error?

For some context, the scoped allocator is a static optimization that converts multiple collective all-reduce ops in to a single all-reduce.  In this optimization, we pre-allocate a buffer that is large enough to hold all the inputs to the all reduce.  We add an attribute to each OpKernel whose output takes part in this all-reduce indicating that the output should be assigned from a slice of this pre-allocated buffer.  The bounds check failure is a runtime error that indicates that the OpKernel somehow circumvented this process and used a different buffer.

[`a3d2ee6`](https://github.com/tensorflow/tensorflow/commit/a3d2ee6ada53fdfde96a76d635c721629acb9582) fixed the case when an OpKernel calls `set_output` instead of `allocate_output`.

In this example, it looks like the input to the all-reduce comes from an AddN op.  I tried a small test case which fuses 2 ops using the scoped allocator whose inputs are both AddN, but my test case passed.

**Comment by byronyi** [comment]
It’s not AddN, the node name is common for gradients that feed into training ops (GradientDescent etc.) 

Would it be possible for this to be an interfering case between scoped allocator and some other graph rewrites?

**Comment by royxue** [comment]
@dubey 
I was checking the solution yesterdays. If I started training from a checkpoint, this error happened. But is I started training from scratch this error will not happen. However the training process will hang up after the graph is initialized. Im thinking this is may caused by the conflicts between `slim.argscope`(object detection api used) and `distributed strategy`. As mentioned, the strategy do not support deprecated `slim` api.

**Comment by guptapriya** [comment]
Is this resolved or is it still an issue?

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
