### ISSUE TITLE
Weird behavior of tf.Variable.assign in a tf.Dataset.map callback function

### ISSUE THREAD

**Issue by prclibo** [tensorflow/tensorflow#27507]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX Mojave
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): pip3.7
- TensorFlow version (use command below): 1.13.1
- Python version: 3.7.2
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: Running the CPU version
- GPU model and memory: NA

You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

I was trying using a Variable to track a seed number in Dataset. Because I want my model to resume training with the same training order as before break if I can checkpoint the variable.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

A minimal code is like:

```
import tensorflow as tf

seed = tf.Variable(0, dtype=tf.int64, trainable=False,
    use_resource=True)
def eject(x):
    seed.assign(x) 
    return {'seed': seed, 'x': x}

dataset = tf.data.Dataset.range(10000)
dataset = dataset.map(eject, num_parallel_calls=1)

iterator = dataset.make_initializable_iterator()

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(iterator.initializer)
    next_element = iterator.get_next()

    for i in range(10):
        fetches = sess.run(next_element)
        print(fetches)

```

**Describe the expected behavior**

The expected print should be 0-9 for both `x` and `seed`. 

**Describe the current behavior**

But the output of `seed` does not stays the same and changes over different executions. The output is like:

```
{'seed': 0, 'x': 0}
{'seed': 1, 'x': 1}
{'seed': 2, 'x': 2}
{'seed': 2, 'x': 3}
{'seed': 4, 'x': 4}
{'seed': 4, 'x': 5}
{'seed': 6, 'x': 6}
{'seed': 7, 'x': 7}
{'seed': 7, 'x': 8}
{'seed': 8, 'x': 9}
```

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
I could reproduce the issue with TF1.13.1 and TF1.12. Thanks!

**Comment by jvishnuvardhan** [comment]
@prclibo We need to initialize the seed also. Please check the code below

import tensorflow as tf

seed = tf.Variable(0, dtype=tf.int64, trainable=False,
    use_resource=True)
def eject(x):
    seed.assign(x) 
    return {'seed': seed, 'x': x}

dataset = tf.data.Dataset.range(10000)
dataset = dataset.map(eject, num_parallel_calls=1)

iterator = dataset.make_initializable_iterator()

with tf.Session() as sess:
    sess.run(seed.initializer)
    sess.run(tf.global_variables_initializer())
    sess.run(iterator.initializer)
    next_element = iterator.get_next()

    for i in range(10):
        fetches = sess.run(next_element)
        print(fetches)
Please let me know what you think? Thanks!

**Comment by prclibo** [comment]
@jvishnuvardhan Thanks for the remind.

Though below is not related to this question itself. But I found that `seed` is included in `tf.global_variables()`, so is it necessary to separately initialize `seed` besides `tf.global_variables_initializer()`?

```
import tensorflow as tf

seed = tf.Variable(0, dtype=tf.int64, trainable=False,
    use_resource=True, name='ssss')
def eject(x):
    seed.assign(x) 
    return {'seed': seed, 'x': x}

dataset = tf.data.Dataset.range(10000)
dataset = dataset.map(eject, num_parallel_calls=1)

iterator = dataset.make_initializable_iterator()

print(tf.global_variables())

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(iterator.initializer)
    next_element = iterator.get_next()

    for i in range(10):
        fetches = sess.run(next_element)
        print(fetches)
```

This will output `global_variables [<tf.Variable 'ssss:0' shape=() dtype=int64>]`

**Comment by jvishnuvardhan** [comment]
@prclibo Looks like this was an issue which was resolved in tf-nightly. Could you try running it in Google colab with !pip install tf-nightly. I don't see any issue with tf-nightly. Please let me know how it progress and close the issue if it was resolved by tf-nightly. Thanks!

**Comment by prclibo** [comment]
@jvishnuvardhan @muddham 
See https://colab.research.google.com/drive/1DzTvOJRXYUk0CSjvGa11ewmjTP7VJ1kF

The issue did not happen in my very limited tests.

Also could you please take a look at #28043 . It seems a similar problem but not fixed in tf-nightly.

**Comment by jvishnuvardhan** [comment]
@prclibo I will close this issue as it was resolved in tf-nightly. We will resolve the other issue there. Thanks!
