### ISSUE TITLE
AUTHORS references non-existent file

### ISSUE THREAD

**Issue by pocc** [tensorflow/tensorflow#28036]
**Describe the documentation issue**

The [AUTHORS](https://github.com/tensorflow/tensorflow/blob/master/AUTHORS) file references a CONTRIBUTORS files, but no `CONTRIBUTORS` or `CONTRIBUTORS.md` file exists:

```
# This file is distinct from the CONTRIBUTORS files.
# See the latter for an explanation.
```

If CONTRIBUTORS is some where else, this should be made explicit in AUTHORS.

**We welcome contributions by users. Can you submit a PR?**

This is a question for maintainers and a PR is not yet appropriate.

**Comment by predator4hack** [comment]
Hi, may I know what exactly do we need to add in CONTRIBUTORS.md and can I work on this?

**Comment by jvishnuvardhan** [comment]
@pocc The [AUTHORS](https://github.com/tensorflow/tensorflow/blob/master/AUTHORS) file is only consists of authors only.  Contributors list is provided in the release notes. For `TF2.4` version, [here](https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0) is the list of contributors. Thanks!

I am closing this issue as this was already resolved. Thanks!

**Comment by pocc** [comment]
The documentation on the AUTHORS file is still wrong. It mentions a CONTRIBUTORS **file**, however, it means to reference a CONTRIBUTORS list that is provided on new releases.

AUTHORS file should be updated to reflect this information.
