### ISSUE TITLE
Non-OK-status: CudaLaunchKernel Internal: invalid configuration argument

### ISSUE THREAD

**Issue by xinsu626** [tensorflow/tensorflow#30665]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.14.0
- Python version: 3.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 9.2, V9.2.148
- GPU model and memory: two gpus, GTX 1080 Ti, each 11178MiB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I am trying to run the follow sample code(keras tensorflow backend) my my GPU

```
left = Input(shape=(128, 3072), dtype='float32', name='Input-Left')
right = Input(shape=(128, 3072), dtype='float32', name='Input-Right')
lstm = Bidirectional(LSTM(units=768,
                          activation='tanh'),
                      name='Bidirectional-LSTM')
l_lstm = lstm(left)
r_lstm = lstm(right)
subtracted = Subtract(name='Subtract')([l_lstm, r_lstm])
abs_subtracted = Lambda(function=backend.abs)(subtracted)
mul = Multiply(name='multiplication')([l_lstm, r_lstm])
concat = concatenate([abs_subtracted, mul])
output = Dense(units=1)(concat)
model = Model(inputs=[left, right],
              outputs=output)
model = multi_gpu_model(model, gpus=2)
model.compile(loss='mean_squared_error',
              optimizer='Adam',
              metrics=['acc'])
import numpy as np
x1 = np.random.rand(100, 128, 3072)
x2 = np.random.rand(100, 128, 3072)
y = np.random.rand(100)
model.fit(x = [x1, x2],
         y=y,
         epochs=10)
```

**Describe the expected behavior**

expected it run normally without error.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

When I ran the code on my GPUs, I got the following error, However, if I uninstall tensorflow-gpu, there was no error, but I can only use cpu.

```
Using TensorFlow backend.
2019-07-12 15:38:28,543 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-07-12 15:38:28,552 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

2019-07-12 15:38:28,552 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.

2019-07-12 15:38:29,759 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4185: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.

2019-07-12 15:38:29,837 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.

2019-07-12 15:38:29,840 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2019-07-12 15:38:29.856975: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-07-12 15:38:29.860863: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-07-12 15:38:29.974060: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:29.976417: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:29.977100: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x97d2a40 executing computations on platform CUDA. Devices:
2019-07-12 15:38:29.977112: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-07-12 15:38:29.977117: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): GeForce GTX 1080 Ti, Compute Capability 6.1
2019-07-12 15:38:29.978574: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3696330000 Hz
2019-07-12 15:38:29.979175: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x984ed80 executing computations on platform Host. Devices:
2019-07-12 15:38:29.979185: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-07-12 15:38:29.980287: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:29.980881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:01:00.0
2019-07-12 15:38:29.980907: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:29.981642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties: 
name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
pciBusID: 0000:02:00.0
2019-07-12 15:38:29.981842: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-07-12 15:38:29.982531: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-07-12 15:38:29.983173: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-07-12 15:38:29.983363: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-07-12 15:38:29.984149: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-07-12 15:38:29.984728: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-07-12 15:38:29.985920: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-07-12 15:38:29.985961: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:29.986728: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:29.987487: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:29.988224: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:29.988948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0, 1
2019-07-12 15:38:33.252621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-07-12 15:38:33.252666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1 
2019-07-12 15:38:33.252672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N Y 
2019-07-12 15:38:33.252677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   Y N 
2019-07-12 15:38:33.253003: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:33.253769: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:33.254223: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:33.254958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10054 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-07-12 15:38:33.255392: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-07-12 15:38:33.255840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10054 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
2019-07-12 15:38:33.714112: F ./tensorflow/core/kernels/random_op_gpu.h:227] Non-OK-status: CudaLaunchKernel(FillPhiloxRandomKernelLaunch<Distribution>, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: invalid configuration argument
Aborted (core dumped)
```

**Comment by ravikyram** [comment]
I tried reproducing issue with the provided code ,but i am unable to reproduce .Will it be possible to provide minimal code snippet which can reproduce the reported issue.Thanks

**Comment by xinsu626** [comment]
@ravikyram Thanks. I was able to solve the issue. I think it is compatibility issue between tensorflow-gpu and cuda.

- CUDA 10.1 and Tensorflow-gpu 1.14: No Error
- CUDA 9.2 and Tensorflow-gpu 1.14: CudaLaunchKernel error.
- CUDA 9.2 and Tensorflow-gpu 1.12: No Error.

**Comment by ravikyram** [comment]
@xinsu626 
I am closing this issue as it was resolved.Thanks!

**Comment by skeydan** [comment]
Sorry for commenting on a closed issue, but reg.

> CUDA 10.1 and Tensorflow-gpu 1.14: No Error

Did you compile 1.14 manually against CUDA 10.1? As per the documentation and from experience

```
2019-07-19 21:26:32.698745: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory
2019-07-19 21:26:32.698819: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory
2019-07-19 21:26:32.698888: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory
2019-07-19 21:26:32.698928: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory
2019-07-19 21:26:32.698996: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory
2019-07-19 21:26:32.699039: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory
2019-07-19 21:26:32.701819: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2019-07-19 21:26:32.701833: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
```

neither 1.14 nor the nightly, nor the nightly-tf2-preview, work with CUDA 10.1...

@ravikram could you please reopen this?

Many thanks!

**Comment by xinsu626** [comment]
@skeydan Hi, 

Sorry I just checked my server and the CUDA version is 10.0(`Cuda compilation tools, release 10.0, V10.0.130`) instead of 10.1.

I didn't compile 1.14 manually. I used pip to install it. `python3.6 -m pip install tensorflow-gpu`. I also ran the code below with CUDA 10.0 and tensorflow 1.14, and there was no error.

```
import numpy as np
from keras.layers import Input, Bidirectional, LSTM, Subtract, Lambda, Multiply, concatenate, Dense
from keras.utils import multi_gpu_model
from keras.models import Model
import keras.backend as backend

x1 = np.random.rand(100, 128, 3072)
x2 = np.random.rand(100, 128, 3072)
y = np.random.rand(100)

left = Input(shape=(128, 3072), dtype='float32', name='Input-Left')
right = Input(shape=(128, 3072), dtype='float32', name='Input-Right')
lstm = Bidirectional(LSTM(units=768,
                          activation='tanh'),
                     name='Bidirectional-LSTM')
l_lstm = lstm(left)
r_lstm = lstm(right)
subtracted = Subtract(name='Subtract')([l_lstm, r_lstm])
abs_subtracted = Lambda(function=backend.abs)(subtracted)
mul = Multiply(name='multiplication')([l_lstm, r_lstm])
concat = concatenate([abs_subtracted, mul])
output = Dense(units=1)(concat)
model = Model(inputs=[left, right],
              outputs=output)
model = multi_gpu_model(model, gpus=2)
model.compile(loss='mean_squared_error',
              optimizer='Adam',
              metrics=['acc'])
model.fit(x=[x1, x2],
          y=y,
          epochs=10)
```

**Comment by ravikyram** [comment]
@skeydan 
Can you please go through the comments of xinsu626 and let us know still if you want us to reopen this issue. Thanks!

**Comment by skeydan** [comment]
@ravikyram thanks for asking, @xinsu626 thanks for clarifying!

We have a similar-looking issue here https://github.com/rstudio/keras/issues/843 and I'm now passing on the recommendation to use TF 1.14 with CUDA 10.0 to evade the problem. 

If  it's okay with you, I might ask to reopen at a later time in case that issue persists even in  the recommended configuration. Thanks!

**Comment by sdll** [comment]
Had the same issue with 4 workers, each with 2 Tesla K80s, on the AI Platform. Not sure whether this is a CUDA problem, since it is not reproducible: launching another job worked well.

**Comment by sivakumaranandan** [comment]
To use w/ CUDA10.1, please use the tf-nightly version. 
Command to install: pip install tf-nightly.

**Comment by mrhu919** [comment]
> _请确保这是一个错误。根据我们的[GitHub政策](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md)，我们仅解决[GitHub上的](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md)代码/文档错误，性能问题，功能请求和构建/安装问题。标记：bug_template_
> 
> **系统信息**
> 
> * 我是否编写了自定义代码（与使用TensorFlow提供的股票示例脚本相反）：
> * 操作系统平台和发行版（例如，Linux Ubuntu 16.04）：Linux Ubuntu 16.04
> * 如果问题发生在行动装置上，则行动装置（例如iPhone 8，Pixel 2，Samsung Galaxy）：
> * 从（源或二进制）安装TensorFlow：二进制
> * TensorFlow版本（使用下面的命令）：1.14.0
> * Python版本：3.6
> * Bazel版本（如果从源代码编译）：
> * GCC /编译器版本（如果从源代码编译）：
> * CUDA / cuDNN版本：9.2，V9.2.148
> * GPU型号和内存：两个GPU，GTX 1080 Ti，每个11178MiB
> 
> 您可以使用我们的环境捕获
> [脚本](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)收集一些此类信息。
> 您还可以通过以下方式获取TensorFlow版本：1. TF 1.0：`python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`2. TF 2.0：`python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
> 
> **描述**
> 我正在尝试在我的GPU中运行以下示例代码（keras tensorflow backend）**的当前行为**
> 
> ```
> left = Input(shape=(128, 3072), dtype='float32', name='Input-Left')
> right = Input(shape=(128, 3072), dtype='float32', name='Input-Right')
> lstm = Bidirectional(LSTM(units=768,
>                           activation='tanh'),
>                       name='Bidirectional-LSTM')
> l_lstm = lstm(left)
> r_lstm = lstm(right)
> subtracted = Subtract(name='Subtract')([l_lstm, r_lstm])
> abs_subtracted = Lambda(function=backend.abs)(subtracted)
> mul = Multiply(name='multiplication')([l_lstm, r_lstm])
> concat = concatenate([abs_subtracted, mul])
> output = Dense(units=1)(concat)
> model = Model(inputs=[left, right],
>               outputs=output)
> model = multi_gpu_model(model, gpus=2)
> model.compile(loss='mean_squared_error',
>               optimizer='Adam',
>               metrics=['acc'])
> import numpy as np
> x1 = np.random.rand(100, 128, 3072)
> x2 = np.random.rand(100, 128, 3072)
> y = np.random.rand(100)
> model.fit(x = [x1, x2],
>          y=y,
>          epochs=10)
> ```
> 
> **描述预期的行为**
> 
> 预期它可以正常运行而不会出现错误。
> 
> **重现问题的代码**
> 提供可重现的测试用例，这是产生问题所必需的最低要求。
> 
> **其他信息/日志**
> 包括有助于诊断问题的任何日志或源代码。如果包括回溯，请包括完整的回溯。大型日志和文件应附加。
> 
> 当我在GPU上运行代码时，出现以下错误，但是，如果我卸载tensorflow-gpu，则没有错误，但是我只能使用cpu。
> 
> ```
> Using TensorFlow backend.
> 2019-07-12 15:38:28,543 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:517: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
> 
> 2019-07-12 15:38:28,552 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:74: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.
> 
> 2019-07-12 15:38:28,552 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4138: The name tf.random_uniform is deprecated. Please use tf.random.uniform instead.
> 
> 2019-07-12 15:38:29,759 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4185: The name tf.truncated_normal is deprecated. Please use tf.random.truncated_normal instead.
> 
> 2019-07-12 15:38:29,837 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:133: The name tf.placeholder_with_default is deprecated. Please use tf.compat.v1.placeholder_with_default instead.
> 
> 2019-07-12 15:38:29,840 From /home/.local/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:3445: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
> Instructions for updating:
> Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
> 2019-07-12 15:38:29.856975: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-07-12 15:38:29.860863: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
> 2019-07-12 15:38:29.974060: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:29.976417: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:29.977100: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x97d2a40 executing computations on platform CUDA. Devices:
> 2019-07-12 15:38:29.977112: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): GeForce GTX 1080 Ti, Compute Capability 6.1
> 2019-07-12 15:38:29.977117: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (1): GeForce GTX 1080 Ti, Compute Capability 6.1
> 2019-07-12 15:38:29.978574: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3696330000 Hz
> 2019-07-12 15:38:29.979175: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x984ed80 executing computations on platform Host. Devices:
> 2019-07-12 15:38:29.979185: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
> 2019-07-12 15:38:29.980287: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:29.980881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
> pciBusID: 0000:01:00.0
> 2019-07-12 15:38:29.980907: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:29.981642: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 1 with properties: 
> name: GeForce GTX 1080 Ti major: 6 minor: 1 memoryClockRate(GHz): 1.683
> pciBusID: 0000:02:00.0
> 2019-07-12 15:38:29.981842: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
> 2019-07-12 15:38:29.982531: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
> 2019-07-12 15:38:29.983173: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
> 2019-07-12 15:38:29.983363: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
> 2019-07-12 15:38:29.984149: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
> 2019-07-12 15:38:29.984728: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
> 2019-07-12 15:38:29.985920: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
> 2019-07-12 15:38:29.985961: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:29.986728: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:29.987487: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:29.988224: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:29.988948: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0, 1
> 2019-07-12 15:38:33.252621: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2019-07-12 15:38:33.252666: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 1 
> 2019-07-12 15:38:33.252672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N Y 
> 2019-07-12 15:38:33.252677: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 1:   Y N 
> 2019-07-12 15:38:33.253003: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:33.253769: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:33.254223: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:33.254958: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10054 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1)
> 2019-07-12 15:38:33.255392: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2019-07-12 15:38:33.255840: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 10054 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080 Ti, pci bus id: 0000:02:00.0, compute capability: 6.1)
> 2019-07-12 15:38:33.714112: F ./tensorflow/core/kernels/random_op_gpu.h:227] Non-OK-status: CudaLaunchKernel(FillPhiloxRandomKernelLaunch<Distribution>, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: invalid configuration argument
> Aborted (core dumped)
> ``when I explore multi_gpu_model in keras, I have a same problem, can you tell me how to settle this .

**Comment by manpython-ti** [comment]
i am also getting the same error and not able to resolve it if I m running the following code:
import tensorflow as tf
import numpy as np
model=tf.keras.Sequential()
model.add(tf.keras.layers.Dense(64,activation='relu'))
model.add(tf.keras.layers.Dense(64,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))
model.compile(optimzer='Adam',
             loss='categorical_crossentropy',
             metrics=['accuracy'])
data=np.random.random((1000,32))
labels=np.random.random((1000,10))
model.fit(data,labels,batch_size=32,epochs=3)<-----------     

""   after this I m getting error::"""

2019-11-28 11:04:06.964863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1650 major: 7 minor: 5 memoryClockRate(GHz): 1.56
pciBusID: 0000:01:00.0
2019-11-28 11:04:06.971063: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-28 11:04:06.976492: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-28 11:04:06.979274: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-28 11:04:06.984074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-11-28 11:04:06.986746: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-11-28 11:04:06.992165: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 3023 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-11-28 11:04:08.220421: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1650 major: 7 minor: 5 memoryClockRate(GHz): 1.56
pciBusID: 0000:01:00.0
2019-11-28 11:04:08.227433: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-28 11:04:08.233568: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-28 11:04:08.235936: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-28 11:04:08.241661: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-11-28 11:04:08.250926: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-11-28 11:04:08.256356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/device:GPU:0 with 3023 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-11-28 11:04:16.908225: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1650 major: 7 minor: 5 memoryClockRate(GHz): 1.56
pciBusID: 0000:01:00.0
2019-11-28 11:04:16.915702: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-28 11:04:16.921282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-28 11:04:16.927152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1650 major: 7 minor: 5 memoryClockRate(GHz): 1.56
pciBusID: 0000:01:00.0
2019-11-28 11:04:16.947245: I tensorflow/stream_executor/platform/default/dlopen_checker_stub.cc:25] GPU libraries are statically linked, skip dlopen check.
2019-11-28 11:04:16.952123: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-11-28 11:04:16.954761: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-11-28 11:04:16.962555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-11-28 11:04:16.977982: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-11-28 11:04:16.996614: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3023 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5)
2019-11-28 11:04:17.374983: **F .\tensorflow/core/kernels/random_op_gpu.h:227] Non-OK-status: GpuLaunchKernel(FillPhiloxRandomKernelLaunch<Distribution>, num_blocks, block_size, 0, d.stream(), gen, data, size, dist) status: Internal: invalid device function**

**Comment by manpython-ti** [comment]
please help if anyone can resolve this 
i  using Tensorflow version =2.0
have installed tensorfloe-gpu with pip
CUDA version is 10.0
python version is 3.6x

**Comment by wogong** [comment]
Same eoor here, my environment:
tensorfloe-gpu 2.0 installed with pip
CUDA version is 9.2/10.0
python version is 3.6.9

**Comment by zoldaten** [comment]
tf-nightly-gpu - install. they fixed that.

**Comment by llan-ml** [comment]
After reinstall tensorflow-gpu==2.0.0 in a clean environment, the issue disappears.
