### ISSUE TITLE
RAM usage during fit() on a tf.keras model

### ISSUE THREAD

**Issue by noodlez04** [tensorflow/tensorflow#31312]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: conda repository
- **TensorFlow version (use command below)**: 2.0.1
- **Python version**: 3.7.3
- **CUDA/cuDNN version**: CUDA 10, cuDNN 7.6
- **GPU model and memory**: GeForce GTX 1050 Ti, 4 GB memory

### Describe the problem
Situation: running the `fit` command on a `tf.keras` model.
Problem: When running on CPU, the `fit` command takes ~25MB. When running on GPU, it takes **~970MB**.

### Source code / logs
Use the following code, in a script called `test.py`:
```
from memory_profiler import profile
from tensorflow import keras
import tensorflow as tf
import numpy as np


@profile
def test():
    optimizer = keras.optimizers.Adam(lr=1e-3)
    loss = keras.losses.BinaryCrossentropy()

    model = keras.models.Sequential()
    model.add(keras.layers.Flatten())
    model.add(keras.layers.Dense(1))

    model.compile(loss=loss, optimizer=optimizer, metrics=['acc'])

    num_samples = 1280
    batch_size = 64

    inputs = np.random.uniform(size=(num_samples, 100, 100, 3)).astype(np.float32)
    targets = np.random.randint(0, 2, size=(num_samples, 1)).astype(np.int32)

    history = model.fit(inputs, targets, epochs=3, validation_data=(inputs, targets))

test()
```

and use the following commands, in an environment with tensorflow-gpu and **memory_profiler**:
`export CUDA_VISIBLE_DEVICES=0; python -m memory_profiler test.py`
`export CUDA_VISIBLE_DEVICES="-1"; python -m memory_profiler test.py`

The outputs I get:
```
Line #    Mem usage    Increment   Line Contents
================================================
     9    249.9 MiB    249.9 MiB   @profile
    10                             def test():
    11    249.9 MiB      0.0 MiB       optimizer = keras.optimizers.Adam(lr=1e-3)
    12    249.9 MiB      0.0 MiB       loss = keras.losses.BinaryCrossentropy()
    13                             
    14    252.6 MiB      2.7 MiB       model = keras.models.Sequential()
    15    252.6 MiB      0.0 MiB       model.add(keras.layers.Flatten())
    16    252.6 MiB      0.0 MiB       model.add(keras.layers.Dense(1))
    17                             
    18    252.9 MiB      0.3 MiB       model.compile(loss=loss, optimizer=optimizer, metrics=['acc'])
    19                             
    20    252.9 MiB      0.0 MiB       num_samples = 1280
    21    252.9 MiB      0.0 MiB       batch_size = 64
    22                             
    23    399.6 MiB    146.6 MiB       inputs = np.random.uniform(size=(num_samples, 100, 100, 3)).astype(np.float32)
    24    399.6 MiB      0.0 MiB       targets = np.random.randint(0, 2, size=(num_samples, 1)).astype(np.int32)
    25                             
    26   1383.0 MiB    983.5 MiB       history = model.fit(inputs, targets, epochs=3, validation_data=(inputs, targets))
```
```
Line #    Mem usage    Increment   Line Contents
================================================
     9    249.8 MiB    249.8 MiB   @profile
    10                             def test():
    11    249.8 MiB      0.0 MiB       optimizer = keras.optimizers.Adam(lr=1e-3)
    12    249.8 MiB      0.0 MiB       loss = keras.losses.BinaryCrossentropy()
    13                             
    14    252.6 MiB      2.7 MiB       model = keras.models.Sequential()
    15    252.6 MiB      0.0 MiB       model.add(keras.layers.Flatten())
    16    252.9 MiB      0.3 MiB       model.add(keras.layers.Dense(1))
    17                             
    18    252.9 MiB      0.0 MiB       model.compile(loss=loss, optimizer=optimizer, metrics=['acc'])
    19                             
    20    252.9 MiB      0.0 MiB       num_samples = 1280
    21    252.9 MiB      0.0 MiB       batch_size = 64
    22                             
    23    399.5 MiB    146.6 MiB       inputs = np.random.uniform(size=(num_samples, 100, 100, 3)).astype(np.float32)
    24    399.5 MiB      0.0 MiB       targets = np.random.randint(0, 2, size=(num_samples, 1)).astype(np.int32)
    25                             
    26    429.3 MiB     29.8 MiB       history = model.fit(inputs, targets, epochs=3, validation_data=(inputs, targets))
```

**Moreover**, when I try to use the InceptionV3 model, I get the following results:
RAM used when training on GPU, using the `fit` method: 13.4 GB
RAM used when training on GPU, using a custom training loop: 943 MB
RAM used when training on CPU, using the `fit` method: 13 GB
RAM used when training on CPU, using a custom training loop: 582 MB

**Comment by noodlez04** [comment]
might be related to #30443

**Comment by BeWe11** [comment]
I am experiencing the same problem. Similar to https://github.com/tensorflow/tensorflow/issues/30443, the first epoch is very slow (probably because of data loading) and the memory usage increases constantly after every batch. The other epochs run quickly and memory is stable. Calling the `model.fit` method seems to cache the data into memory (even though RAM caching was never explicitly turned on).

**Comment by HongtaoYang** [comment]
Same issue here. Using `model.fit` results in surprisingly high usage of RAM, I couldn't even start training before running out of memory. Then I tried using `model.train_on_batch` hoping it would not have the problem because only one batch is presented at a time, but sadly the same issue. I'm using `tf.data.Dataset` with keras model for training.

The same model can be trained using custom training loop with no problem. Just wondering if there is a solution yet?

**Comment by TKassis** [comment]
I have the same issue. No problems running the exact same script with TF 1.14, but with TF 2.0 RAM usage keeps increasing with each epoch until my Jupyter Notebook freezes.

**Comment by GarryGelade** [comment]
Same issue as well. I am using Keras 2.2.4, CPU and python 3.7.4 under Windows 10.
```
model = Sequential()
# Encoder       
model.add(LSTM(32, activation='relu', input_shape =(timesteps, n_features ), return_sequences=True))
model.add(LSTM(16, activation='relu', return_sequences=False))
model.add(RepeatVector(timesteps))
# Decoder
model.add(LSTM(16, activation='relu', return_sequences=True))
model.add(LSTM(32, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(n_features)))
```
data.shape
(23764, 20, 2)
model.fit(data, data,       
          epochs=num_epochs, 
          batch_size = 32)
```
I have 16GB of memory, and usage creeps up with each epoch. If I'm lucky I can train 30 epochs, which uses 97% of memory. With more epochs, it generally gets out of memory altogether.
Is there a decent workaround until they fix this?

**Comment by engineerByNature** [comment]
I am facing the same problem with ResNet50 from keras applications. In the first epoch my 16GB memory is rapidly exceeded. Tried tensorflow 1.14 and tensorflow-gpu 1.14. Also, decreasing the batch size tremendously did not help. So far only facing the issues with models from applications.

**Comment by juan-carvajal** [comment]
I have the same problem, memory usage is increasing after every call to fit. I don't know if this has to do with the callbacks history object,but after around 20-30 calls to fit, all RAM is used (I have 16 GB).

**Comment by engineerByNature** [comment]
> I am facing the same problem with ResNet50 from keras applications. In the first epoch my 16GB memory is rapidly exceeded. Tried tensorflow 1.14 and tensorflow-gpu 1.14. Also, decreasing the batch size tremendously did not help. So far only facing the issues with models from applications.

Update: Tried TF 2.0.0 and it does not show this issue.

**Comment by GarryGelade** [comment]
Update: I also tried updating to TF 2.0.0. Memory usage of my 16GB tops out at 98%, after 9 out of 30 epochs but seems to stabilise there, dropping to 96-97% and then going up again, but not exceeding 98%.  Seems kind of close to the brink, but it went through.

**Comment by leoffx** [comment]
I'm facing the same issue, but using TF 2.0 alpha works for me. Using the latest release spends all 25 GB of RAM on Google Colab, but with alpha it barely uses 3 GB.

**Comment by gabehope** [comment]
Any progress on this? I'm having the same issue with the current release of TF 2.0 in Colab, memory usage increases dramatically every epoch until the runtime crashes. I'm running an implementation of Wide ResNet.

**Comment by phemmer** [comment]
Don't know if I'm experiencing the same issue, or a different one, but I've also just started encountering an issue with Tensorflow sucking up all available RAM. However for me the trigger was a system upgrade.

I was using Fedora 29 with Tensorflow 2.1.0, and everything worked fine. I then upgraded to Fedora 31, same exact code and Tensorflow version, and now `model.fit` sucks down all the system memory (~29gb) and OOMs. And it does this without making it through a single epoch. In fact it doesn't appear to make it through a single batch, as the keras progress indicators never show up.
The last thing that shows is `Epoch 1/30`

**Comment by phemmer** [comment]
Well after spending the entire day trying to get Tensorflow to build from source, my memory issue is resolved.
When I was experiencing the issue I described earlier (`model.fit` consuming all available memory), I was using the 2.1.0 package from pip. After building Tensorflow from source (same version, 2.1.0) the issue has gone away, and Tensorflow is operating normally again.

**Comment by dishkakrauch** [comment]
I still got this error when I'm running .fit method in jupyter notebook, it's same even for notebooks in kaggle kernels. Have anybody solve this issue?

**Comment by dishkakrauch** [comment]
> Any progress on this? I'm having the same issue with the current release of TF 2.0 in Colab, memory usage increases dramatically every epoch until the runtime crashes. I'm running an implementation of Wide ResNet.
> 
> EDIT: I diagnosed my actual issue. Seems Python's garbage collection was not getting run before Colab ran out of memory. Forcing garbage collection with `gc.collect()` at every epoch solves the problem. Good excuse for me to learn how Python decides when to run garbage collection :).

How do you use garbage collector at each epoch? Can you share code or something?

**Comment by dishkakrauch** [comment]
> Well after spending the entire day trying to get Tensorflow to build from source, my memory issue is resolved.
> When I was experiencing the issue I described earlier (`model.fit` consuming all available memory), I was using the 2.1.0 package from pip. After building Tensorflow from source (same version, 2.1.0) the issue has gone away, and Tensorflow is operating normally again.
> 
> So my guess is just some sort of incompatibility with some version of a library the pip package was built with, vs what Fedora 31 ships with.

That's not okay when pip stable tensorflow version is not actually stable.
Hope somebody from Google team note anything about it.

**Comment by gabehope** [comment]
> > Any progress on this? I'm having the same issue with the current release of TF 2.0 in Colab, memory usage increases dramatically every epoch until the runtime crashes. I'm running an implementation of Wide ResNet.
> > EDIT: I diagnosed my actual issue. Seems Python's garbage collection was not getting run before Colab ran out of memory. Forcing garbage collection with `gc.collect()` at every epoch solves the problem. Good excuse for me to learn how Python decides when to run garbage collection :).
> 
> How do you use garbage collector at each epoch? Can you share code or something?

I just ran it in a Keras callback. Still not really sure why this was necessary, haven't had a chance to dig into what was happening, but it solved my issue. 

Minimal example (based on tutorial: [https://www.tensorflow.org/guide/keras/custom_callback](https://www.tensorflow.org/guide/keras/custom_callback)):

`
import tensorflow as tf
import gc

class MyCustomCallback(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs=None):
    gc.collect()

...
_ = model.fit(x_train, y_train, ...
          callbacks=[MyCustomCallback()])
`

**Comment by dishkakrauch** [comment]
> > > Any progress on this? I'm having the same issue with the current release of TF 2.0 in Colab, memory usage increases dramatically every epoch until the runtime crashes. I'm running an implementation of Wide ResNet.
> > > EDIT: I diagnosed my actual issue. Seems Python's garbage collection was not getting run before Colab ran out of memory. Forcing garbage collection with `gc.collect()` at every epoch solves the problem. Good excuse for me to learn how Python decides when to run garbage collection :).
> > 
> > 
> > How do you use garbage collector at each epoch? Can you share code or something?
> 
> I just ran it in a Keras callback. Still not really sure why this was necessary, haven't had a chance to dig into what was happening, but it solved my issue.
> 
> Minimal example (based on tutorial: https://www.tensorflow.org/guide/keras/custom_callback):
> 
> `
> import tensorflow as tf
> import gc
> 
> class MyCustomCallback(tf.keras.callbacks.Callback):
> def on_epoch_end(self, epoch, logs=None):
> gc.collect()
> 
> ...
> _ = model.fit(x_train, y_train, ...
> callbacks=[MyCustomCallback()])
> `

Okay, thank you. I thought I was talking about another way for garbage collector. I use callbacks in my models. Gonna try to cure my tensorflow issue as you did.

**Comment by dishkakrauch** [comment]
> > > Any progress on this? I'm having the same issue with the current release of TF 2.0 in Colab, memory usage increases dramatically every epoch until the runtime crashes. I'm running an implementation of Wide ResNet.
> > > EDIT: I diagnosed my actual issue. Seems Python's garbage collection was not getting run before Colab ran out of memory. Forcing garbage collection with `gc.collect()` at every epoch solves the problem. Good excuse for me to learn how Python decides when to run garbage collection :).
> > 
> > 
> > How do you use garbage collector at each epoch? Can you share code or something?
> 
> I just ran it in a Keras callback. Still not really sure why this was necessary, haven't had a chance to dig into what was happening, but it solved my issue.
> 
> Minimal example (based on tutorial: https://www.tensorflow.org/guide/keras/custom_callback):
> 
> `
> import tensorflow as tf
> import gc
> 
> class MyCustomCallback(tf.keras.callbacks.Callback):
> def on_epoch_end(self, epoch, logs=None):
> gc.collect()
> 
> ...
> _ = model.fit(x_train, y_train, ...
> callbacks=[MyCustomCallback()])
> `

Didn't help anyway)

**Comment by yhliang2018** [comment]
The issue is similar to #35030, so you may check the detailed analysis there. Basically, the root cause is that  `tf.convert_to_tensor` is making a copy when called on NumPy Arrays, leading more memory usage in `model.fit()`.

We are working on the fix now. Please stay tuned. Thanks.

**Comment by dishkakrauch** [comment]
> The issue is similar to #35030, so you may check the detailed analysis there. Basically, the root cause is that `tf.convert_to_tensor` is making a copy when called on NumPy Arrays, leading more memory usage in `model.fit()`.
> 
> We are working on the fix now. Please stay tuned. Thanks.

So should I use tensorflow dataset instead of numpy dataset and there will no be memory leak? I'm asking about tensorflow 2.1.0 stable version.

**Comment by phemmer** [comment]
In my case, where I was having memory issues with the PIP version but compiled worked fine, I was using tf.data.Dataset, not numpy. So there may be more than one leak going around.

On February 8, 2020 3:07:56 AM EST, Dmitry Kravchuk <notifications@github.com> wrote:
>> The issue is similar to #35030, so you may check the detailed
>analysis there. Basically, the root cause is that
>`tf.convert_to_tensor` is making a copy when called on NumPy Arrays,
>leading more memory usage in `model.fit()`.
>> 
>> We are working on the fix now. Please stay tuned. Thanks.
>
>So should I use tensorflow dataset instead of numpy dataset and there
>will no be memory leak? I'm asking about tensorflow 2.1.0 stable
>version.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/tensorflow/tensorflow/issues/31312#issuecomment-583714439

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dishkakrauch** [comment]
> In my case, where I was having memory issues with the PIP version but compiled worked fine, I was using tf.data.Dataset, not numpy. So there may be more than one leak going around.
> […](#)
> On February 8, 2020 3:07:56 AM EST, Dmitry Kravchuk ***@***.***> wrote: > The issue is similar to #35030, so you may check the detailed analysis there. Basically, the root cause is that `tf.convert_to_tensor` is making a copy when called on NumPy Arrays, leading more memory usage in `model.fit()`. > > We are working on the fix now. Please stay tuned. Thanks. So should I use tensorflow dataset instead of numpy dataset and there will no be memory leak? I'm asking about tensorflow 2.1.0 stable version. -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#31312 (comment)](https://github.com/tensorflow/tensorflow/issues/31312#issuecomment-583714439)
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

I'll try tensorflow dataset class instead of numpy. Thx.

**Comment by atangfan** [comment]
Similar leakage case while using tf.data.Dataset on Colab.

**Comment by jvishnuvardhan** [comment]
@noodlez04 I think this was resolved in recent `tf-nightly`. I ran your code in `GPU` and fit took 57.86 MB. [Here is a gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/ecf67b62788981093e5941943c33fe95/untitled876.ipynb) with GPU using `tf-nightly`.

When I ran same code in CPU with `tf-nightly`, fit took 17.77 MB. Please take a look at the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/864028e369e9f32ded61804fed2d55b6/untitled877.ipynb). Thanks!

Please close the issue if this was resolved for you. Thanks!

**Comment by yhliang2018** [comment]
As it's already fixed, let's close this bug. Feel free to reopen it if needed.

**Comment by lidless-vision** [comment]
this bug has returned in tf 2.3.0

**Comment by nihir27** [comment]
> The issue is similar to #35030, so you may check the detailed analysis there. Basically, the root cause is that `tf.convert_to_tensor` is making a copy when called on NumPy Arrays, leading more memory usage in `model.fit()`.
> 
> We are working on the fix now. Please stay tuned. Thanks.

@yhliang2018 This conversion happens in TF 2.2 when NumPy arrays are passed to `model.fit()`. https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/python/keras/engine/data_adapter.py#L265

**Comment by ASRodrigo1** [comment]
I had the same problem today, using tensorflow-gpu==2.0.0
My solution was very simple:
`pip uninstall tensorflow-gpu==2.0.0`
and
`pip install --user tensorflow-gpu==1.14.0`

**Comment by markodjordjic** [comment]
@nihir27 Hi. Are there any updates on this issue? Essentially no training process can be completed while this is not resolved.

**Comment by yhliang2018** [comment]
@lidless-vision @nihir27 @markodjordjic What TF version do you use? Could you try tf-nightly? If this issue still exists in tf-nightly, would you provide a small colab example for repro? So we can investigate the problem.

**Comment by markodjordjic** [comment]
@yhliang2018 any TF upwards 2.0.0. The gist to what you are referring to is nowhere near a hp tuning process which can produce memory leak.

**Comment by yhliang2018** [comment]
Yeah, TF2.0.0 does have this issue, and it should be fixed in the following versions (unless there is regression in some later version). So you may try the latest stable version(2.3.0) or tf-nightly which should have no such memory leak.

**Comment by markodjordjic** [comment]
@yhliang2018 every version upwards from 2.0.0 has exactly the same issue and there is a lot of people talking about it around GH however no progress is being made.

**Comment by markodjordjic** [comment]
@yhliang2018 I have opened new issue: https://github.com/tensorflow/tensorflow/issues/43627

**Comment by markodjordjic** [comment]
@yhliang2018 However I think it just creates clutter like many other issues that have the same underlying problem, and have stayed unresolved, or someone has made a statement that version X.X is working, while it is not.

**Comment by markodjordjic** [comment]
@yhliang2018 thanks for responding, but what is really needed is that someone pushes for this.

**Comment by markodjordjic** [comment]
@yhliang2018 TF2.3.0 is not working, just to confirm.
algo-1-eprqd_1  | Fitting fold: 0 
algo-1-eprqd_1  | memory used: 2072.0
algo-1-eprqd_1  | Fitting fold: 0 
algo-1-eprqd_1  | memory uses: 2097.0
algo-1-eprqd_1  | Fitting fold: 0 
algo-1-eprqd_1  | memory uses: 2104.0
algo-1-eprqd_1  | Fitting fold: 0 
algo-1-eprqd_1  | memory uses: 2114.0
algo-1-eprqd_1  | Fitting fold: 0 for estimator: FFD AEN, with HP: (Dep.: 3, wid.: 26, red.:0.2, epo.:50)
. . .
algo-1-eprqd_1  | memory used: 2188.0

**Comment by yhliang2018** [comment]
> @noodlez04 I think this was resolved in recent `tf-nightly`. I ran your code in `GPU` and fit took 57.86 MB. [Here is a gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/ecf67b62788981093e5941943c33fe95/untitled876.ipynb) with GPU using `tf-nightly`.
> 
> When I ran same code in CPU with `tf-nightly`, fit took 17.77 MB. Please take a look at the [gist here](https://colab.sandbox.google.com/gist/jvishnuvardhan/864028e369e9f32ded61804fed2d55b6/untitled877.ipynb). Thanks!
> 
> Please close the issue if this was resolved for you. Thanks!

According to this comment, we thought this issue was fixed. It might not be true in the following stable versions, sorry about it.

I will look into the issue #43627 and keep you updated on the progress.

**Comment by markodjordjic** [comment]
@yhliang2018 Thank you.

**Comment by gioxc88** [comment]
any update on this on any suggestion on a particular tf version which does not have this issue?

**Comment by ml118** [comment]
Have the same problem. using model.fit() bit it stops at epoch 18 while loading the dlls. The committed RAM stacks too high.

**Comment by markodjordjic** [comment]
@ml118 and @gioxc88 Thank you for keeping this topic alive. It is sad that this issue is not yet resolved. The only workaround I was able to find is to avoid the usage of ``model.fit`` methods and run a custom training process as described in:

https://www.tensorflow.org/guide/keras/writing_a_training_loop_from_scratch

There is also the issue #43627 that is not attended at all, and most likely connected to this issue.

**Comment by gioxc88** [comment]
I'll also link this other one which I opened a a few weeks ago [#45592](https://github.com/tensorflow/tensorflow/issues/45592)

**Comment by markodjordjic** [comment]
@gioxc88 Yup. That's the same issue. Incredible how wide spread the problem is, and it is still persisting; not being attended to.

**Comment by ml118** [comment]
@markodjordjic Thanks for sending the link about implementing the training from scratch. Seems like i have no other solution and has to try this out.

**Comment by markodjordjic** [comment]
@ml118 You're welcome. I'm glad if I can be of assistance, especially since TF is not doing anything. I need to add a note, that the problem will not be completely removed, but it will be reduced to the point that training is possible. Also, it is recommended to remove all the unnecessary objects like the ``keras.model`` at the first point possible, and subsequently use ``gc.collect()`` and ``tf.keras.backend.clear_session()``. Let me know how this works out for you.

**Comment by ml118** [comment]
@markodjordjic first i will try to expand the paging file (i am on Win10) and see if that helps. It isnt possible to use gc.collect() and tf.keras.backend.clear_session() in model.fit, right? So doing the training from scratch will be my last solution. But i will try it if expanding the paging file wont help. And chare my results here for sure :)

**Comment by lefnire** [comment]
I've worked with this issue for years now, there's truly no solution. Good luck on your tests, but don't have high hopes. The workaround is really simple: just have your training phase in a dedicated script, call it as a shell command `os.process # or whatever`, save weights in that script and load them post-train in the calling script.

**Comment by ml118** [comment]
@lefnire Oh ok. You mean something like `model.fit()` for 10 epochs. Then safe model, load again and continue for another 10 epochs? Or did you write the training from scratch and then calling it whit a shell command?

**Comment by markodjordjic** [comment]
@lefnire Have you tried to use:

https://www.tensorflow.org/guide/keras/writing_a_training_loop_from_scratch

It has solved the problem for me. I was able to complete numerous quite lengthy training jobs on AWS without ever needing to go into saving and restoring model weights in between the (certain number of) epochs.

**Comment by markodjordjic** [comment]
@ml118 There is no advantage in running the training from scratch with a shell command. Simply run the script for a training job from scratch, delete objects, ``gc.collect()`` them, and clear the session. An increase in memory will be minimal.

**Comment by lefnire** [comment]
Ah, I guess my situation's a bit different. I serve a model for inference, which can online-train new data. Since it's forever-on, mem-leak is a show-stopper eventually. So what I do is:

* run.py -> receives jobs, runs inference or training
* train.py -> training only. saves model after done
* inference.py -> inference only, can be imported & called directly from run.py

run.py: if it needs to train, it calls `os.subprocess('./train.py')` (I can't remember actual syntax) which will save the model after completion. The os call is blocking, so it knows when it's done; no coordination necessary. Then inference.py loads the model before use each time. 

Kinda complex sounding, but it's really simple. TL;DR: put training in a separate script. Point being when the script dies, all RAM is re-claimed. Maybe not what you're looking for in your situation. @markodjordjic man alive, I've tried every possible combo of `clear_session()` `gc.collect()` etc, I've tried so many variants of that, don't know how you got it working but I'm cashed out 😓

**Comment by markodjordjic** [comment]
@lefnire Many thanks for sharing the details of your approach. I find it very useful for OL training. The case here was for off-line training (especially dockerized via AWS) and the secret of success was to drop the use of `model.fit()` an switch completely to training jobs from scratch. This minimized the consumption of RAM after every epoch, and allowed for training to finish.

**Comment by ml118** [comment]
I raies the paging file and got to Epoch 26. Its an improvement, not very good, but better. Another thought i have is just train for 20 Epochs. Safe the model, load it again and train for another 20 Epochs with the same training/validation split. This should also work, right?

**Comment by markodjordjic** [comment]
@ml118 I have already given my best advice, and an example of what worked for me. And that is training from scratch without using ``model.fit()`` method, described here:

https://www.tensorflow.org/guide/keras/writing_a_training_loop_from_scratch

After ending all the epochs, you should clear session, delete model, and ``gc.collect()``.

If you wish to use any other approach (eg. going for 20 epochs, saving, restoring, etc.) that is up to you. I have no information about that, and I cannot give any advice, except that it is unnecessary and cumbersome, especially since the training from scratch works.

**Comment by rschiewer** [comment]
Any updates on this issue? I implemented a large and complex network inheriting from keras.Model, so of course it uses the builtin fit method. After some testing, I wanted to scale my experiments up and it looks like this is absolutely impossible with this bug. I'll try to go for the training loop from scratch solution, but I'm somewhat suprised that this issue still seems to persist in tf version 2.4.1.

**Comment by rschiewer** [comment]
Update: I used a combination of the workarounds recommended by @gabehope and @markodjordjic with success. I can use `model.fit()` with the following callback:

```
class MyCustomCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        gc.collect()
        tf.keras.backend.clear_session()
```

Memory leaks seem to be still present, but very minor. I can train my model now.

**Comment by paweller** [comment]
Thanks to everyone who was persistently pushing for this issue to not get inactive. As basically everyone who uses TensorFlow 2.x.x and the built-in functions like **model.fit()** I was experiencing the **following issues**:
1. **Loads of RAM usage** even though I am running NVIDIA GeForce RTX 2080 TI GPUs.
2. Very **slow training**.
3. Some kind of **memory leakage** (feels like it was somewhat linear).

All of these three issues have been fixed by the **solution** posted by @rschiewer (https://github.com/tensorflow/tensorflow/issues/31312#issuecomment-813944860) and by **adding `run_eagerly=True`** in the **`model.compile()`** function.

Hope this might help others, too.

**Comment by rschiewer** [comment]
Using `run_eagerly=True` like @paweller suggests fixes the memory leak for me without any other action needed. **However, as far as I'm aware it completely removes the benefit of graph optimizations and should mean a noticeable performance hit**. For my application, it did. 

Two findings if yout don't want to use `run_eagerly=True`:

1. I tried to use tmalloc with no change regarding the memory leak. 
2. I'm currently not able to find the related issue here on github, but I read elswhere that the problem might come from using the builtin relu activation function in one or more layers. My workaround is to use `activation=None` and add a ReLu activation layer after each of my layers. While this increases clutter and sounds more than a bit esoteric, it eliminated memory leakage in my project without the need for other measures. I'm running my code in graph mode.

**Comment by bersbersbers** [comment]
@rschiewer you may mean #46475 and/or #46661.

**Comment by paweller** [comment]
> **However, as far as I'm aware it completely removes the benefit of graph optimizations and should mean a noticeable performance hit**.

@rschiewer: How does it make sense then that my training times per epoch decreased siginificantely to about 1/3 of what they were before? Or may that be caused by the `ClearMemory` callback? I cannot imagine it does but I might be wrong. Anyways, I will give your finding 2. a try as I am indeed using ReLU as the activation function for all my convolutional layers. I will let you know what it did for me.

Thanks to @bersbersbers for providing the related issue links.

**Comment by rschiewer** [comment]
@bersbersbers Yes exactly, it's [#46475](https://github.com/tensorflow/tensorflow/issues/46475). Thanks for mentioning it here!

@paweller I'd be a lucky man if I understood how tensorflow graph mode really works. If your training runs faster in eager mode,  there's maybe something going wrong during the generation of the optimized graph. According to my experience, using graph mode is usually faster than not using it. But I've also sunken more than a few hours into debugging cryptic autograph errors, more than once without final success. So you might be better off with the eager execution mode, which just works.

**Comment by paweller** [comment]
I have now tried putting the activation function as an additional layer and changing it from `ReLU` to `LeakyReLU`. It solved the memory leak for me as well. I also tried training on a different machine. Here it does not make a difference in performance whether I use `run_eagerly=True` or not. Epoch times stay the same regardless (the model is a small one with only four convolutional, one dense and one lambda layer).

**Comment by UntotaufUrlaub** [comment]
I am not a 100% sure about this topic, but it seems the latests gpu docker image fixed the leakage problem for me.

**Comment by wissambenhaddad** [comment]
@UntotaufUrlaub which version is it please ?

**Comment by UntotaufUrlaub** [comment]
@wissambenhaddad I used `FROM tensorflow/tensorflow:latest-gpu`.
So i guess the latest version available back in May. Sadly I got no clue how to tell the exact tag of it today.

**Comment by graille** [comment]
I'm using Tensorflow 2.9.1 with Python 3.9 and the memory leak is still present

**Comment by fperezgamonal** [comment]
Hello all,

I've also run into this problem while training a Siamese network with a custom training and testing step (inheriting from `tf.keras.Model`) and using `model.fit()`. I faced this exact problem with at least 3 Tensorflow versions (2.6, 2.8 and 2.9).

I tried several of the solutions proposed in previous posts:

- Run `gc.collect()` and  `K.clear_session()` in a Keras callback (reduced the memory leak but ended up crashing after more epochs).
- Move the activation operations to their own layers (e.g.: `tf.keras.layers.ReLU` instead of using the `activation` parameter in Conv2D). I appreciated no difference.

I must mention that I did not try passing `run_eagerly=True` to `model.compile()` fearing the performance impact it may have.
Finally, what work for me was to instead implement a custom training loop as suggested above. Although, there is more code, you gain customisation and a little bit of performance by individually wrapping the training and validation steps in `@tf.function`.

I understand it may be a hard to solve issue because it may be caused by a combination of factors, but seeing how many developers are facing the same problems, I think more attention and time are necessary to fix it.

**Comment by chongxiaoc** [comment]
See similar large memory leakage issues in TF 2.6 when calling keras fit() function with tensorflow dataset.

**Comment by blackyang** [comment]
an issue like this is a great example why TF lost the battle to PyTorch (there are other reasons as well) :)

**Comment by cmantas** [comment]
I'm seeming a similar pattern unfortunately, IDK why this issue is closed.
* Mac M1 pro
* tensorflow-macos  2.9.2
* tensorflow-metal   0.5.1

I tried
* running `gc.collect()`, `k.clear_session()` on my Sequence generator class (helped, but did not solve it)
* using a separate `Activation` layer (didn't work)
* `model.compile(..` with `run_eagerly=True` (I'm not sure if it helped, but it did not solve it)

I haven't figured out how to try`tcmalloc` on my mac.

**Comment by NikhielRahulSingh** [comment]
this is still an issue in October 2023, I am building an image classifier and it keeps crashing

**Comment by justalge** [comment]
> this is still an issue in October 2023, I am building an image classifier and it keeps crashing

what version of keras and tensorflow do you use? probably I have the same problem with keras 2.6.0 and tf 2.6.2

**Comment by CarloNicolini** [comment]
I can confirm the problem is still present.
Running Tensorflow 2.12.0 as the backend of NVidia Merlin (a recommender models framework) on a A10 GPU with 24GB of VRAM, and I see random patterns of crash.
Sometimes the crash happens in the middle of epoch 3, sometimes just epoch 1 etc...
Memory stays almost constant but at some point....💥 it explodes and very long Cuda OOM errors are displayed.

I am trying now all the solutions and hope it will disappear:

1. compile mode with eager=False
2. reset state callback at end of each epoch by means of the `ClearMemory` callback as described above.

**Comment by mihaimaruseac** [comment]
2.12 is too old, won't get updated anymore. Can you try on a more recent version, please?
