### ISSUE TITLE
tf.summary.histogram broken in tf-nightly-gpu-2.0-preview

### ISSUE THREAD

**Issue by ialdencoots** [tensorflow/tensorflow#31365]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.0.0-dev20190806
- Python version: 2.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Calling `tf.summary.histogram` on a non eager tensor results in an exception: ```OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.```

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.
```
import tensorflow as tf
inputs = tf.keras.layers.Input(shape=(300,))
tf.summary.histogram("in", inputs)
```

**Comment by gowthamkpr** [comment]
Similar to the issue #31091

**Comment by gowthamkpr** [comment]
Re produced this issue. Please find the colab notebook [here](https://colab.sandbox.google.com/gist/gowthamkpr/8fe198df1611ed750d2a98e4ab6f6b1a/untitled76.ipynb)

**Comment by jvishnuvardhan** [comment]
@ialdencoots The second line in your code `tf.summary.histogram` is expecting a real numeric tensor as an input but you are providing non-eager tensor `tf.keras.layers.Input`. In the TF website, it was clearly mentioned that 

`values: A real numeric Tensor. Any shape. Values to use to build the histogram`

The following with a numeric tensor works well
```
import tensorflow as tf
# inputs = tf.keras.layers.Input(shape=(300,))
inputs=tf.constant([1.,2.,3.,4.,5.,6.])
tf.summary.histogram("in", inputs)
```
I am closing the issue as it was resolved. Thanks!

**Comment by ialdencoots** [comment]
Do you mean to tell me you can't get summary statistics for any tensor that is the result of an operation of a tensor fed into a graph? So basically weights are the only tensors you can get histograms for? If that's not a bug, it's definitely functionality that ought to exist.

**Comment by jvishnuvardhan** [comment]
@ialdencoots All I am saying is the function `tf.summary.histogram` can take only numerical tensor by design. `Input()` is used to instantiate a Keras graph tensor whereas `tf.summary.histogram` takes only a numerical tensor. `weights` are not the only tensors that can get histogram. Please check an [example](https://www.tensorflow.org/guide/tensorboard_histograms#some_more_distributions) from TF website where it uses results of an operation of a tensor fed into a graph. Please let me know whether it helped you or not. Thanks!

**Comment by ialdencoots** [comment]
Yeah, ok @jvishnuvardhan , that was just a minimal example. Say you have an arbitrary graph with inputs and you want to calculate literally anything and get a histogram of it. The error still persists.
```
import tensorflow as tf
inputs = tf.keras.layers.Input(shape=(300,))
mult = 3 * inputs
tf.summary.histogram("hist", mult)
```
Do you mean to tell me that `mult` is not a numerical tensor?

**Comment by jvishnuvardhan** [comment]
@ialdencoots Still `mult` is a graph tensor which cannot be given as input to `tf.summary.histogram`. Please check my implementation that works without any issue. Please let me know if you have any comments. Thanks!
```
!pip install tf-nightly-2.0-preview
import tensorflow as tf
inputs = tf.keras.layers.Input(shape=(300,))
mult = 3 * inputs
# mult = tf.keras.layers.Lambda(lambda x:3*x)(inputs) # you could do this also
model=tf.keras.Model(inputs=inputs, outputs=mult)
mult_from_model=model(tf.random.uniform(minval=-1,maxval=1,shape=(300,),dtype=tf.float32))
tf.summary.histogram("hist", mult_from_model)
```

**Comment by ialdencoots** [comment]
Ok, so histogram can't be called on anything internal to a model? If I want to check the distribution of tensors in internal layers, I have to produce a model with multiple outputs?

**Comment by carlthome** [comment]
This problem persists in 2.0! Is the only way of getting out summaries to TensorBoard with tf.keras to avoid the functional API and use model subclassing instead?

The subclassing API has subpar support in other parts of the TensorFlow ecosystem so I'd prefer to stick with the functional API if possible.
