### ISSUE TITLE
Error loading tensorflow

### ISSUE THREAD

**Issue by javiersempere** [tensorflow/tensorflow#31725]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.14.0
- **Python version**: 3.7
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 10.1 - 10.1
- **GPU model and memory**: Nvidia Quadro K5000 - 4Gb
- **Exact command to reproduce**: import tensorflow as tf

### Describe the problem
Error loading Tensorflow. Does not provide a clue about which DLL is failing to initialize.

### Source code / logs
> import tensorflow as tf
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL).
Failed to load the native TensorFlow runtime.

Calling from a program:
>python style.py
Traceback (most recent call last):
  File "C:\Users\Javier\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\Javier\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\Javier\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL).
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "style.py", line 9, in <module>
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Program Files\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Program Files\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: Error en una rutina de inicialización de biblioteca de vínculos dinámicos (DLL).
Failed to load the native TensorFlow runtime.

**Comment by littlemountainman** [comment]
Solved here #13715

**Comment by javiersempere** [comment]
> Solved here #13715

I cannot see the solution. Cuda/Cudnn seems to be working fine. Can you help on the troubleshooting steps?

**Comment by littlemountainman** [comment]
In conclusion, install this https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by ymodak** [comment]
TF 1.13 and above support cuda 10.0. Please rollback to cuda 10.0
See https://www.tensorflow.org/install/gpu#software_requirements
Also update your environment paths to cuda 10

**Comment by javiersempere** [comment]
I did rollback to cuda 10.0 and the paths. The problem persists.

**Comment by oanush** [comment]
> I did rollback to cuda 10.0 and changed the paths. The problem persists.
> 
> Is there a way to troubleshoot the issue and see what DLL is causing the error?

Open ...\Lib\site-packages\tensorflow\python\_pywrap_tensorflow_internal.pyd use D[ependency Walker](http://www.dependencywalker.com/), it will show you the DLL dependency tree, you will find which DLL cause the problem. You can then install the needed CUDA or vcredist version, or add some path to system variable.

Here is the dependency tree look like:
![58224686-43831d80-7d51-11e9-9610-9fa5820ffa7e](https://user-images.githubusercontent.com/52397990/63266893-8e5bf500-c2ae-11e9-96ec-8377ee2de4a3.png)

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
