### ISSUE TITLE
TPUStrategy.make_dataset_iterator does not work for a Dataset created by tf.data.Dataset.from_generator

### ISSUE THREAD

**Issue by tsc2017** [tensorflow/tensorflow#32712]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab default environment
- TensorFlow installed from (source or binary): Colab  default
- TensorFlow version (use command below): 1.14
- Python version: Python 3

**Describe the current behavior**
I first create a Dataset with an iterator, then create a TPU iterator with the Dataset. After that, the iterator is used as the second input of `TPUStrategy.experimental_run`. As I run the output of `experimental_run`,  an error occurs:
```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1340       return self._call_tf_sessionrun(
-> 1341           options, feed_dict, fetch_list, target_list, run_metadata)
   1342 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1428         self._session, options, feed_dict, fetch_list, target_list,
-> 1429         run_metadata)
   1430 

AbortedError: Session 5c40387f44056164 is not found.

During handling of the above exception, another exception occurred:

AbortedError                              Traceback (most recent call last)
<ipython-input-7-b0bded0c272b> in <module>()
     18     # Custom training loop
     19     session.run(train_iterator_init)
---> 20     session.run(dist_train)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    948     try:
    949       result = self._run(None, fetches, feed_dict, options_ptr,
--> 950                          run_metadata_ptr)
    951       if run_metadata:
    952         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1171     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1172       results = self._do_run(handle, final_targets, final_fetches,
-> 1173                              feed_dict_tensor, options, run_metadata)
   1174     else:
   1175       results = []

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1348     if handle is None:
   1349       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1350                            run_metadata)
   1351     else:
   1352       return self._do_call(_prun_fn, handle, feeds, fetches)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1368           pass
   1369       message = error_interpolation.interpolate(message, self._graph)
-> 1370       raise type(e)(node_def, op, message)
   1371 
   1372   def _extend_graph(self):

AbortedError: Session 5c40387f44056164 is not found.
```
**Describe the expected behavior**
Run without error.
**Code to reproduce the issue**
```
import os
import pprint
import tensorflow as tf
import numpy as np
resolver = tf.contrib.cluster_resolver.TPUClusterResolver('grpc://' + os.environ['COLAB_TPU_ADDR'])
tf.contrib.distribute.initialize_tpu_system(resolver)
strategy = tf.contrib.distribute.TPUStrategy(resolver)

def my_generator():
    for i in range(100):
      x = np.random.rand(28,28).astype('float32')
      y = np.zeros([], dtype='int32')
      yield x,y

def train_fn(inputs):
    return inputs[0]

with strategy.scope():
  config = tf.ConfigProto()
  config.allow_soft_placement = True
  cluster_spec = resolver.cluster_spec()
  if cluster_spec:
    config.cluster_def.CopyFrom(cluster_spec.as_cluster_def())
  print('Starting training...')
  # Do all the computations inside a Session (as opposed to doing eager mode)
  with tf.Session(target=resolver.master(), config=config) as session:  
    #train_dataset = tf.data.Dataset.from_tensor_slices((x_train, y_train)).batch(8, drop_remainder=True)
    train_dataset = tf.data.Dataset.from_generator(my_generator, ('float32', 'int32'), ([28,28], [])).batch(8, drop_remainder=True)
    train_iterator = strategy.make_dataset_iterator(train_dataset)
    train_iterator_init = train_iterator.initialize()
    dist_train = strategy.experimental_run(train_fn, train_iterator).values

    # Custom training loop
    session.run(train_iterator_init)
    session.run(dist_train)
```
This snippet of code is a simplified version of  [this Colab notebook](https://colab.research.google.com/github/tensorflow/docs/blob/r2.0rc/site/en/tutorials/distribute/tpu_custom_training.ipynb).  The original `tf.data.Dataset.from_tensor_slices` works fine but  `tf.data.Dataset.from_generator` fails.

At the same time, I provide a [Colab notebook](https://colab.research.google.com/drive/1SNCAPKRcF_9XCSunRYvb6rGWkOcrweuN) for reproducing this issue.

**Comment by ravikyram** [comment]
I have tried on colab with TF version 1.14 and was able to reproduce the issue.However i tried reproducing the issue with TF 1.15.0-rc1 and seeing the below error. 
`NotFoundError: Op type not registered 'RebatchDataset' in binary running on n-f4303a18-w-0. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.`.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/11adb2b7180fb825bfa006b303f0cfcd/untitled210.ipynb).Thanks!

**Comment by guptapriya** [comment]
@rxsang does from_generator work with TPUStrategy at all? 

Also, from the error in https://github.com/tensorflow/tensorflow/issues/32712#issuecomment-533975396, it seems that TPU binary for 1.15 is not yet updated, is that the case?

**Comment by Ely-S** [comment]
I'm encountering this same issue with TF 1.15 on TPU v3. Are there any workarounds?

**Comment by rxsang** [comment]
tf.data.Dataset.from_generator is not supported in TPU because TPU is a 2 VM setup, where the TPU worker is a C++ binary which cannot execute python functions. @jsimsa who raised the discussion about this topic recently.

**Comment by jsimsa** [comment]
@lindong28 was your CL to fix the issue merged?

**Comment by lindong28** [comment]
@jsimsa Are you referring to patch that places all PyFunc op on the coordinator's address space? That fix has been committed in https://github.com/tensorflow/tensorflow/commit/7bfb8380a7c09603259f49027374a4faf4199ad2. However this patch will only be included in the next TF release 2.2.0 which is scheduled to have branch cut on 2/26.

**Comment by jsimsa** [comment]
@tsc2017 would you be able to try if your program work with a nightly release of TF which should include the above fix?

**Comment by tsc2017** [comment]
@jsimsa 
In the following, I provide two notebooks for testing:
[custom code](https://colab.research.google.com/drive/1Jf43Aq8LtGxUD5QSMGp4KJJnoUdYGiF-)
[keras](https://colab.research.google.com/drive/1kOb4jzlpYsSf-0hv1Rs7_4SGTNini0LK)
However, I am not able to test them as I have difficulties in importing tf-nightly in Colab.

**Comment by lindong28** [comment]
Just FYI, by adding "!pip install tf-nightly==2.2.0.dev20200131", the error changed from "No registered 'PyFunc' OpKernel for 'CPU' devices compatible with node" (see [this](https://colab.sandbox.google.com/drive/1Jf43Aq8LtGxUD5QSMGp4KJJnoUdYGiF-#scrollTo=KtHGmqEtvMZa)) to "End of sequence" (see [this](https://colab.sandbox.google.com/drive/1WikNeKoOxq09DaYJMXI1W1hd8f06wnzc#scrollTo=dp9njklCaBG8)).

**Comment by tsc2017** [comment]
This bug still exists on 2.2.0-rc2(see [this notebook](https://colab.research.google.com/drive/1Jf43Aq8LtGxUD5QSMGp4KJJnoUdYGiF-)):

NotFoundError: From /job:worker/replica:0/task:0:
No registered 'PyFunc' OpKernel for 'CPU' devices compatible with node {{node PyFunc}}

**Comment by nicosacco** [comment]
I'm struggling with the same issue using tf 2.2.0. My dataset is too large for use tf.data.Dataset.from_tensor_slices, so, any workaround to this problem with TPU and generators would be very helpful.

**Comment by frankchn** [comment]
@nicosacco The recommended way here is to preprocess your data separately and write them out into TFRecord files, which you can then store on GCS. TPUs can parallelize GCS reads very quickly.
