### ISSUE TITLE
TFLite_Micro: Implementing version 3 of convolutional layers for Post-training fully-integer quantization

### ISSUE THREAD

**Issue by antofara** [tensorflow/tensorflow#33606]
**System information**
- TensorFlow version (you are using): 2.0.0, up to date with master
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
By following the second part of the tutorial on [Post-training integer quantization](https://www.tensorflow.org/lite/performance/post_training_integer_quant),  thus providing also a representative dataset and setting
```python
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8
```
the resulting converted model is fully quantized, including inputs and outputs.
However, if there are convolutions operations in the model, the converted versions will be "Version 3", which is not currently supported by Tflite for Microcontrollers, as shown in all_ops_resolver.cc lines 22 and 30
```c++
  AddBuiltin(BuiltinOperator_DEPTHWISE_CONV_2D, Register_DEPTHWISE_CONV_2D());
 ...
 AddBuiltin(BuiltinOperator_CONV_2D, Register_CONV_2D());
```

**Will this change the current api? How?**
The current tflite micro api will be changed by including support to fully quantized convolutional layers as currently happens in TFLite
**Who will benefit with this feature?**
Everyone who wants to deploy fully quantized convolutional layers on a microcontroller without floating point support (or in all those situations where due to energy constraints, FPU cannot be used)
**Any Other info.**

**Comment by njeffrie** [comment]
I've been working on updating the reported op versions for each operator.  We currently do support version 3 of conv2d, which is reflected in a CL I created yesterday.  That CL should fix this issue.

**Comment by antofara** [comment]
Hi @njeffrie, sorry I am not sure I fully got it. Is this change merged with the master or I find it as pull request somewhere? Because at the moment, despite in conv.cc and depthwise_conv.cc there are the EvalQuantizedPerChannel fuctions, it still does not work. If I try to manually register also version 3 by modifying all_ops_resolver.cc as follows
```python
AddBuiltin(BuiltinOperator_DEPTHWISE_CONV_2D, Register_DEPTHWISE_CONV_2D(),1,3);
```
it crashes at Line 233 of micro/kernels/all_ops_resolver.cc
```python
TF_LITE_ENSURE_STATUS(CalculateOpData(context, node, params, width, height,
                                        filter_width, filter_height, data_type,
                                        &data));
```

**Comment by njeffrie** [comment]
Sorry for the delay - it's currently an internal change awaiting review.  I plan to land it early next week.  Can you paste the entire error log?  I would like to dig into the error you're seeing once you make the change to AddBuiltin.

**Comment by rockyrhodes** [comment]
I believe this change has been merged.  Could you retry your model @antofara ?

**Comment by antofara** [comment]
@rockyrhodes 
In all_ops_resolver both BuiltinOperator_DEPTHWISE_CONV_2D and BuiltinOperator_CONV_2D are still registered as version 1, thus MicroMutableOpResolver::FindOp still returns, as expected, nullptr.
If I enforce it by modifying all_ops_resolver, registering version 3 of both operators, the program executes until 
`TfLiteStatus invoke_status = registration->invoke(&context_, &node);`
(micro_interpreter.cc:254)
and then it exits because invoke_status is kTfLiteError

**Comment by rockyrhodes** [comment]
Sorry, you're right.  The change to all_ops_resolver is still stuck here at Google in code review.  I'll work with @njeffrie to get it submitted.

**Comment by antofara** [comment]
@rockyrhodes 
It seems that the change has been pushed, thanks! Can I close this issue?
