### ISSUE TITLE
Failed on runtime - image not found

### ISSUE THREAD

**Issue by RazaGR** [tensorflow/tensorflow#34237]
**System information**
- macOS Mojave 10.14.6
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2
- Python version: 3.7
- Installed using virtualenv? no
- Bazel version (if compiling from source): bazel release 0.29.1
- GCC/Compiler version (if compiling from source):g++ -v = Apple clang version 11.0.0 (clang-1100.0.33.12)
- CUDA/cuDNN version: none
- GPU model and memory: no gpu

**problem**
I installed Tensorflow from source and used below command to compile my cpp file, It compiled successfully
`/usr/bin/g++  /var/www/cpp/main.cpp -std=c++17 -L /Users/raza/development/tensorflow/bazel-bin/tensorflow/ -l tensorflow_framework -l tensorflow_cc -l protobuf  -I /Users/raza/development/tensorflow -I /Users/raza/development/tensorflow/bazel-bin/tensorflow -I /Users/raza/development/tensorflow/bazel-genfiles -I /Users/raza/development/tensorflow/bazel-tensorflow/external/com_google_protobuf/src -I /Users/raza/development/tensorflow/bazel-tensorflow/external/com_google_absl -I /Users/raza/development/tensorflow/bazel-tensorflow/external/eigen_archive -o /var/www/cpp/main --debug -v`

But when I run `./main` I see below error:
```
dyld: Library not loaded: @rpath/libtensorflow_framework.2.dylib
  Referenced from: /private/var/www/cpp/./main
  Reason: image not found
```

**Any other info / logs**
I see under my path I have this library ~/development/tensorflow/bazel-bin/tensorflow and also other files with similiar names: 
```
$ls
__init__.py                         core                                libtensorflow_cc.so.2.0.0           stream_executor
__init__.py.original                libtensorflow.so                    libtensorflow_framework.2.0.0.dylib tools
_api                                libtensorflow.so.2                  libtensorflow_framework.2.dylib     virtual_root.__init__.py
c                                   libtensorflow.so.2.0.0              libtensorflow_framework.dylib
cc                                  libtensorflow_cc.so                 lite
compiler                            libtensorflow_cc.so.2               python
```
and output of `otool -L libtensorflow_cc.so`
```
$ otool -L libtensorflow_cc.so
libtensorflow_cc.so:
        @rpath/libtensorflow_cc.so.2 (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
        @rpath/libtensorflow_framework.2.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1673.126.0)
        /System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.41.2)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1673.126.0)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

and
```
$otool -L libtensorflow_framework.2.dylib
libtensorflow_framework.2.dylib:
        @rpath/libtensorflow_framework.2.dylib (compatibility version 0.0.0, current version 0.0.0)
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 800.7.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1673.126.0)
        /System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59306.41.2)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1281.0.0)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1673.126.0)
        /usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

**Comment by RazaGR** [comment]
I was able to solve this issue by copying `libtensorflow_framework.2.dylib` and `libtensorflow_cc.so` from my TensorFlow build directory to the same directory as my executable.

I must also add that C/C++ integration docs are missing or incomplete, so for a new user, it takes a huge time to understand how to build and link properly all the libraries. I hope it gets easier in the future.

**Comment by RazaGR** [comment]
I am re-opening this issue, thought it was fixed but no. here is my code:
```
#include "tensorflow/cc/client/client_session.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/tensor.h"
#include "tensorflow/core/platform/env.h"
#include "tensorflow/core/public/session.h"


#include <iostream>
using namespace std;
using namespace tensorflow;
using namespace tensorflow::ops;


int main(int argc , char *argv[])
{

    Scope root = Scope::NewRootScope();
    // 2x2 matrix
    auto a = Const(root, { {1, 2}, {2, 4} });
    // 2x2 matrix
    auto b = Const(root, { {2, 2}, {1, 1} });
    // a x b
    auto m = MatMul(root, a, b);
    ClientSession session(root);
    std::vector<tensorflow::Tensor> outputs;
    auto t = session.Run({m}, &outputs);
    return 0;
}

```

and the error it is producing with build command:

```
$ g++ -g  /var/www/cpp/main.cpp -std=c++17 -l tensorflow_framework -l tensorflow_cc -l protobuf -I /var/www/cpp/include -I /var/www/cpp/include/tensorflow -L /usr/local/lib -I /var/www/cpp/include/tensorflow/core -o /var/www/cpp/main --debug -all_load -v
Apple clang version 11.0.0 (clang-1100.0.33.12)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.14.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -emit-obj -mrelax-all -disable-free -disable-llvm-verifier -discard-value-names -main-file-name main.cpp -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -fno-strict-return -masm-verbose -munwind-tables -target-sdk-version=10.14 -target-cpu penryn -dwarf-column-info -debug-info-kind=standalone -dwarf-version=4 -debugger-tuning=lldb -ggnu-pubnames -target-linker-version 520 -v -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I /var/www/cpp/include -I /var/www/cpp/include/tensorflow -I /var/www/cpp/include/tensorflow/core -I/usr/local/include -stdlib=libc++ -internal-isystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1 -Wno-framework-include-private-from-public -Wno-atimport-in-framework-header -Wno-extra-semi-stmt -Wno-quoted-include-in-framework-header -std=c++17 -fdeprecated-macro -fdebug-compilation-dir /private/var/www/cpp -ferror-limit 19 -fmessage-length 155 -stack-protector 1 -mdarwin-stkchk-strong-link -fblocks -fencode-extended-block-signature -fregister-global-dtors-with-atexit -fobjc-runtime=macosx-10.14.0 -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o /var/folders/cl/z5blm1lj4591dtbsxn0xj8km0000gn/T/main-567ff5.o -x c++ /var/www/cpp/main.cpp
clang -cc1 version 11.0.0 (clang-1100.0.33.12) default target x86_64-apple-darwin18.7.0
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/local/include"
ignoring nonexistent directory "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /var/www/cpp/include
 /var/www/cpp/include/tensorflow
 /var/www/cpp/include/tensorflow/core
 /usr/local/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)
End of search list.
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -no_deduplicate -dynamic -arch x86_64 -all_load -macosx_version_min 10.14.0 -syslibroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -o /var/www/cpp/main -L/usr/local/lib /var/folders/cl/z5blm1lj4591dtbsxn0xj8km0000gn/T/main-567ff5.o -ltensorflow_framework -ltensorflow_cc -lprotobuf -L/usr/local/lib -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib/darwin/libclang_rt.osx.a
Undefined symbols for architecture x86_64:
  "tensorflow::ClientSession::ClientSession(tensorflow::Scope const&)", referenced from:
      _main in main-567ff5.o
  "tensorflow::ClientSession::~ClientSession()", referenced from:
      _main in main-567ff5.o
  "tensorflow::ClientSession::Run(std::__1::vector<tensorflow::Output, std::__1::allocator<tensorflow::Output> > const&, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) const", referenced from:
      _main in main-567ff5.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by RazaGR** [comment]
There is some improvment, I found that I had to force link library in my build command:
` $ g++ -g  /var/www/cpp/main.cpp -std=c++17 -l tensorflow_framework -l tensorflow_cc -l protobuf -I /var/www/cpp/include -I /var/www/cpp/include/tensorflow -L /usr/local/lib -I /var/www/cpp/include/tensorflow/core -o /var/www/cpp/main --debug -all_load -v -force_load /usr/local/lib/libtensorflow_cc.dylib`

and I did a test with this:

```
int main(int argc , char *argv[])
{

    Session* session;
    Status status = NewSession(SessionOptions(), &session);
    if (!status.ok()) {
        cout << status.ToString() << "\n";
        return 1;
    }
    cout << status.ToString() << "\n";

    return 0;
}

```
which returned the output `OK`, so Tensorflow C++ API seems to be working with above code, But when I used `ClientSession` it doesn't even compile (using same build command above):

```
int main(int argc , char *argv[])
{

    Scope root = Scope::NewRootScope();
    // 2x2 matrix
    auto a = Const(root, { {1, 2}, {2, 4} });
    // 2x2 matrix
    auto b = Const(root, { {2, 2}, {1, 1} });
    // a x b
    auto m = MatMul(root, a, b);
    ClientSession session(root);
    std::vector<tensorflow::Tensor> outputs;
    auto t = session.Run({m}, &outputs);
    return 0;
}
```

above code generates this error when compiling:
```
Undefined symbols for architecture x86_64:
  "tensorflow::ClientSession::ClientSession(tensorflow::Scope const&)", referenced from:
      _main in main-65f237.o
  "tensorflow::ClientSession::~ClientSession()", referenced from:
      _main in main-65f237.o
  "tensorflow::ClientSession::Run(std::__1::vector<tensorflow::Output, std::__1::allocator<tensorflow::Output> > const&, std::__1::vector<tensorflow::Tensor, std::__1::allocator<tensorflow::Tensor> >*) const", referenced from:
      _main in main-65f237.o
ld: symbol(s) not found for architecture x86_64
```

**Comment by RazaGR** [comment]
@ymodak @oanush 
I tried to build with `--config=monolithic `
`bazel build -c opt --config=monolithic --verbose_failures //tensorflow:libtensorflow_cc.so`

but the same `Undefined symbols for architecture x86_64:` error occurs.

Then in my .cpp build command I included `g++ .... -undefined dynamic_lookup` , which caused my program to compile without displaying any error, But when I run the program` ./main` I see this:
```
dyld: lazy symbol binding failed: Symbol not found: __ZN10tensorflow13ClientSessionC1ERKNS_5ScopeE
  Referenced from: /private/var/www/cpp/./main
  Expected in: flat namespace

dyld: Symbol not found: __ZN10tensorflow13ClientSessionC1ERKNS_5ScopeE
  Referenced from: /private/var/www/cpp/./main
  Expected in: flat namespace

[1]    95005 abort      ./main
```

**Comment by MarcinSkoczylasSH** [comment]
This problem is still happening. This is not fixed, please do not close not fixed bugs.
