### ISSUE TITLE
AutoCastVariable.assign returns wrapped variable instead of casted version

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#34332]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0, 2.1-nightly
- Python version: 3.7

**Describe the current behavior**

`AutoCastVariable` variable forwards `assign` and `scatter` to the underlying `float32` variable:
https://github.com/tensorflow/tensorflow/blob/cee2a43b8184e92ba26ec0e3d6e00a3f8ca6e3c8/tensorflow/python/keras/mixed_precision/experimental/autocast_variable.py#L187-L188
Thus, the return value of `assign` methods with `read_value=True` is a normal `tf.Variable` and not an `AutoCastVariable`. This means that calculations directly depending on the assign operation, might run in `float32` instead of `float16`, or am I missing something?

**Describe the expected behavior**
`AutoCastVariable.assign*` should return an `AutoCastVariable` variable instead `tf.Variable` so that the `dtype` is preserved.

@reedwm Is this intended behaviour?

**Code to reproduce the issue**
```python
import tensorflow as tf
from tensorflow.python.keras.mixed_precision.experimental import autocast_variable

var = tf.Variable(0., dtype=tf.float32)
var = autocast_variable.AutoCastVariable(var)

with tf.compat.v1.get_default_graph()._enable_auto_casting_variables(tf.float16):
    assert var.dtype == tf.float16
    # assign should return an AutoCastVariable but returns tf.Variable
    var_assign = var.assign(5.)
    assert not isinstance(var_assign, autocast_variable.AutoCastVariable)
    assert var_assign.dtype == tf.float32
```

**Comment by ravikyram** [comment]
I have tried on colab with TF version 2.0 ,2.1.0-dev20191111 and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/4f70bc0621bc1d362ed8d465b7cb054a/untitled377.ipynb). Thanks!

**Comment by reedwm** [comment]
The current behavior was intended, but on second thought, I think you are right and that this behavior is incorrect. I previously incorrectly believed `Variable.assign` returned a tensor, not a Variable, and wanted the returned tensor to have the same dtype as the input tensor (float32).

Luckily, this issue occurs relatively rarely. AutoCastVariables act identically to Variables outside `Layer.call`, and inside `Layer.call`, variables are rarely assigned to. Still, the current behavior is very confusing and so this should be fixed.

@alextp, do you know what the purpose of the  [`_UnreadVariable`](https://github.com/tensorflow/tensorflow/blob/2692ea8ec1953e42952597adb5b5099181a679b2/tensorflow/python/ops/resource_variable_ops.py#L1806) is, which is returned from [`ResourceVariable.assign`](https://github.com/tensorflow/tensorflow/blob/2692ea8ec1953e42952597adb5b5099181a679b2/tensorflow/python/ops/resource_variable_ops.py#L799)? Why not simply return the ResourceVariable? Do you think I should I create a `_UnreadAutoCastVariable` subclass?

**Comment by lgeiger** [comment]
@reedwm Thanks for taking a look.

The reason why I am looking deeper at the implementation of `AutoCastVariable` is because we are in the process of subclassing `tf.Variable` in https://github.com/larq/larq/issues/306 with the goal to have a `QuantizedVariable` that can be used to define arbitrary fake quantizations like binary or ternary  quantization which would allow easy research on extreme quantization. For this we are looking closely at the implementation of `AutoCastVariable`.

@reedwm @alextp Do you think it makes sense to have a more formalized way to easily subclass `tf.Variable` or `tf.Tensor` in userland? It seams this already happens in a few places (e.g. `AutoCastVariable` or #34379) and would allow quite powerful use cases.

**Comment by alextp** [comment]
@reedwm the purpose of `_UnreadVariable` is allowing code like `x = tf.assign_add(x, foo); x = tf.assign_add(x, bar)` which was possible with ref variables and so to ease the transition to resource variables I made `_UnreadVariable`

@lgeiger I'm with you, I really don't like how complex variables are right now. I think if you control the variable creation site I recommend instead of subclassing variable you implement a tf.Module which implements the variable interface and has a tf.register_tensor_conversion_function for itself (so it can be implicitly cast to a tensor). If you cannot control the variable creation site I mostly recommend the same thing but you might want to use a variable_creation_scope to intercept variable creation and return your custom class. Just make sure to use the underlying creator when creating the variables inside your fake-variable.

Re subclassing tensors, the answer is an emphatic no. We need to have Tensor be a C type (at least in eager mode) for performance in many places, as eventually tensors will have to be passed to kernels.

**Comment by reedwm** [comment]
> The reason why I am looking deeper at the implementation of AutoCastVariable is because we are in the process of subclassing tf.Variable in larq/larq#306

I think having an implementation similar to `AutoCastVariable` is the way to go. I agree it would be nice to have a more formalized way to subclass `tf.Variable` but it currently doesn't exist unfortunately.

> I think if you control the variable creation site I recommend instead of subclassing variable you implement a tf.Module

@alextp, I would still recommend subclassing tf.Variable. I used to subclass Trackable, but I switched to tf.Variable in 74c52531846cc10a63fb244966ab6bfd000af747 as many parts of the code have isinstance checks on tf.Variable. DistributedVariable also subclasses Variable for a similar reason. And tf.Module has some extraneous properties that don't make a lot of sense on a Variable, such as `Module.trainable_variables`.

> the purpose of _UnreadVariable is allowing code like x = tf.assign_add(x, foo); x = tf.assign_add(x, bar) 

Ah I see, returning an `_UnreadVariable` instead of `self` allows this to properly work with Sessions and Graphs, which don't have automatic control dependencies. Otherwise, if `self` is returned, the variable assignment might not run.

I could fix this by copying or subclassing `_UnreadVariable`. I could also just return `self`, which has slightly incorrect semantics when Sessions/Graphs are used with `tf.compat.v1`. I'll try to think of a better solution, especially considering QuantizedVariable will have the same issue. I'm pretty sure DistributedVariables also has this issue.

**Comment by lgeiger** [comment]
Thanks a lot for the insights. It would be cools if we could come up with a simple solution for this.

**Comment by lgeiger** [comment]
> I could fix this by copying or subclassing `_UnreadVariable`. I could also just return `self`, which has slightly incorrect semantics when Sessions/Graphs are used with `tf.compat.v1`

@reedwm Since `AutoCastVariable` just wraps an other variable, what about returning a new instance wrapping the `_UnreadVariable` returned by the assign op. Would something like the following work?
```python
def assign(self, value, use_locking=None, name=None, read_value=True):
    op_or_var = self._variable.assign(value, use_locking, name, read_value)
    if read_value:
        return AutoCastVariable(op_or_var)
    return op_or_var
```

**Comment by reedwm** [comment]
I think that would work, and is very simple. I didn't think of that before. Thanks for the suggestion!

Do you want to implement it for AutoCastVariable? If not, I'd be happy to.

**Comment by lgeiger** [comment]
> I think that would work, and is very simple.

Great!

> Do you want to implement it for AutoCastVariable? If not, I'd be happy to.

:+1: Will send a PR and add some tests once TensorFlow finished compiling on my machine.

**Comment by lgeiger** [comment]
I opened a small PR: #34779

**Comment by lgeiger** [comment]
#34779 doesn't fully close this issue since Distribution Strategy is not fully supported yet: https://github.com/tensorflow/tensorflow/pull/34779#discussion_r353481035

**Comment by reedwm** [comment]
You're right, reopening.

Once Distribution Strategy returns a variable from `DistributionVariable.assign`, this issue can be fixed.

**Comment by lgeiger** [comment]
:+1: Thanks for the help with debugging

**Comment by jvishnuvardhan** [comment]
@lgeiger Is this still an issue? Can you please check with `tf-nightly` and let us know. Thanks!

**Comment by reedwm** [comment]
This is still an issue. The `tf.distribute.Strategy` team is working on a way to return a variable from `DistributionVariable.assign` and until then, this issue cannot be fully fixed.

**Comment by lgeiger** [comment]
@jvishnuvardhan Sorry for the late response. Indeed this is still an issue in the latest nightly. Here is an updated code example for the distribution case:
```python
import tensorflow as tf
from tensorflow.python.keras.mixed_precision.experimental import autocast_variable
from tensorflow.python.distribute import strategy_combinations

strategy_combinations.set_virtual_cpus_to_at_least(3)
with tf.distribute.MirroredStrategy(['/cpu:1', '/cpu:2']).scope():
    var = tf.Variable(0., dtype=tf.float32)
    var = autocast_variable.AutoCastVariable(var)

    with tf.compat.v1.get_default_graph()._enable_auto_casting_variables(tf.float16):
        assert var.dtype == tf.float16
        # assign should return an AutoCastVariable but returns tf.Variable
        var_assign = var.assign(5.)
        assert not isinstance(var_assign, autocast_variable.AutoCastVariable)
        assert var_assign.dtype == tf.float32
```

**Comment by bhack** [comment]
Can we close this?

**Comment by lgeiger** [comment]
> Can we close this?

This is still a problem, but now only in graph mode. Before the problem existed in eager mode as well. Here is some update code using the new API:
```python
import tensorflow as tf
from tensorflow.python.keras.mixed_precision import autocast_variable
from tensorflow.python.distribute import strategy_combinations
tf.compat.v1.disable_eager_execution()

strategy_combinations.set_virtual_cpus_to_at_least(3)
with tf.distribute.MirroredStrategy(['/cpu:1', '/cpu:2']).scope():
    var = tf.Variable(0., dtype=tf.float32)
    var = autocast_variable.AutoCastVariable(var)
    with autocast_variable.enable_auto_cast_variables(tf.float16):
        assert tf.identity(var).dtype == tf.float16
        # assign should return an AutoCastVariable but returns tf.Variable
        var_assign = var.assign(5.)
        assert isinstance(var_assign, autocast_variable.AutoCastVariable)
        assert tf.identity(var).dtype == tf.float16
```

**Comment by lgeiger** [comment]
> Can we close this?

This is still an issue in the latest nightly, but now only shows up in non eager mode. Before this happened in both execution contexts. Here is some updated code that reproduces the failure with the new API:
```python
import tensorflow as tf
from tensorflow.python.keras.mixed_precision import autocast_variable
from tensorflow.python.distribute import strategy_combinations
tf.compat.v1.disable_eager_execution()

strategy_combinations.set_virtual_cpus_to_at_least(3)
with tf.distribute.MirroredStrategy(['/cpu:1', '/cpu:2']).scope():
    var = tf.Variable(0., dtype=tf.float32)
    var = autocast_variable.AutoCastVariable(var)
    with autocast_variable.enable_auto_cast_variables(tf.float16):
        assert tf.identity(var).dtype == tf.float16
        # assign should return an AutoCastVariable but returns tf.Variable
        var_assign = var.assign(5.)
        assert isinstance(var_assign, autocast_variable.AutoCastVariable)
        assert tf.identity(var).dtype == tf.float16
```

**Comment by bhack** [comment]
@lgeiger Do you think that you could add this with a minimal refactoring as a [DISABLED test](https://github.com/google/googletest/blob/master/docs/advanced.md#temporarily-disabling-tests)?

**Comment by lgeiger** [comment]
> Do you think that you could add this with a minimal refactoring as a DISABLED test?

@bhack These cases are already covered in [`tensorflow/python/keras/mixed_precision/autocast_variable_test.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/mixed_precision/autocast_variable_test.py).

In fact I just opened #49856 earlier today to enable the distribution strategy tests in eager mode which have been fixed.

**Comment by reedwm** [comment]
This is a good idea, but I personally don't think it's worth the infrastructure complexity of running DISABLED tests to check whether a bug is fixed. Typically if a bug is fixed, someone will write a corresponding unit test. This bug is an exception, but even so, it was not fully fixed (it still doesn't work with distribution strategies in graph mode).

**Comment by bhack** [comment]
@reedwm I have an initial draft proposal about this internally, please ping me if you are interested.

>  Typically if a bug is fixed, someone will write a corresponding unit test.

But we still have some good side effects with DISABLED bug. 

Just to mention a few of these:

- Better triage. We will have some good proxy of the final test (the one when  "a bug is fixed, someone will write a corresponding unit test")
- We for sure a more isolated code gist to reproduce the bug specially over time (some tickets stay open for months, years).
- We don't need to periodically ping and review all the old tickets about reproducibility with master or with last release often with an not so isolated gist or without the original submitter/subscribers availability.
- We could run this on tf-nightly wheels.
- If we exclude some complex env we could run these test on Github Action directory or Selfhosted Github Action runners.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this issue, as you are using an older version of tensorflow(1.x) which is officially considered as end of life. We recommend that you upgrade to 2.4 or later version and let us know if the issue still persists in newer versions. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, Please open a new issue for any help you need against 2.x, and we will get you the right help.

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
