### ISSUE TITLE
Golang tensorflow no longer builds due to bad import in saved_model.go

### ISSUE THREAD

**Issue by noj-richards** [tensorflow/tensorflow#34580]
A recent change (Change-Id: Iefdf75ed88f54d97a0a7d210f5a42f3123205bf2) has broken an import in file tensorflow/blob/master/tensorflow/go/saved_model.go

tfpb "github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework"

**Comment by gadagashwini** [comment]
@noj-richards, Please provide the exact sequence of commands / steps that you executed before running into the problem. Also include Tensorflow version. Thanks!

**Comment by noj-richards** [comment]
Version is as 'master' with Change-id: Iefdf75ed88f54d97a0a7d210f5a42f3123205bf2

To reproduce simply try and import tf.SavedModel,

e.g:

import (
	tf "github.com/tensorflow/tensorflow/tensorflow/go"
)

//Config Config

//CNN CNN
type CNN struct {
	model               *tf.SavedModel

This will produce the error:

../../../../../github.com/tensorflow/tensorflow/tensorflow/go/saved_model.go:25:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework" in any of:
        /usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework (from $GOROOT)
        /Users/jonrichards/code/go/src/github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework (from $GOPATH)

**Comment by AaronReboot** [comment]
Confirmed we're having the same prob. Had to revert to commit `36ef4264270e3815ea4b485a52e35e26e43e2112` in order to build

**Comment by jcolson** [comment]
is this also causing this failure?

```
go get github.com/tensorflow/tensorflow/tensorflow/go

package github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework" in any of:
	/usr/local/Cellar/go/1.13.4/libexec/src/github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework (from $GOROOT)
	/Users/xxxxx/go/src/github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework (from $GOPATH)

```

**Comment by AaronReboot** [comment]
> is this also causing this failure?
> 
> ```
> go get github.com/tensorflow/tensorflow/tensorflow/go
> 
> package github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework" in any of:
> 	/usr/local/Cellar/go/1.13.4/libexec/src/github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework (from $GOROOT)
> 	/Users/xxxxx/go/src/github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core/framework (from $GOPATH)
> ```

Indeed. That's a simpler minimal example of the prob!

**Comment by yutkin** [comment]
I'm faced with this issue too. During the building of the Docker image, got

```
Step 7/10 : RUN go get github.com/tensorflow/tensorflow/tensorflow/go
 ---> Running in aa0d0a73e640
package github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core" in any of:
	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core (from $GOROOT)
	/go/src/github.com/tensorflow/tensorflow/tensorflow/go/genop/internal/proto/github.com/tensorflow/tensorflow/tensorflow/go/core (from $GOPATH)
```

**Comment by kahlil29** [comment]
What's the recommended way to install the go lang tensorflow binding now that this bug has been identified? Is there any fix in the works?

**Comment by mothukuriv** [comment]
any fix for this issue

**Comment by kahlil29** [comment]
Wow this issue has been completely ignored. It's been almost 2 months! 😡 
It's an installation problem, ffs. Not some `nice to have` or `enhancement` feature. 
And the workaround is extremely hacky and not at all pleasant.

**Comment by yohaiaz** [comment]
anyone can help please. trying go get 
go get github.com/tensorflow/tensorflow/tensorflow/go

getting an error "cannot find package..."

what i'm doing wrong ?

**Comment by jhseu** [comment]
Fixed as of https://github.com/tensorflow/tensorflow/commit/4221d1aa4d20ada495771528bb13ca786d0bdbe0

**Comment by jhseu** [comment]
(As a sidenote, please follow the instructions on the Go README which differs slightly from the documentation on tensorflow.org. I'll work on updating the official docs):
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md

**Comment by yutkin** [comment]
I still have this issue:
```
Step 8/9 : RUN go get -d github.com/tensorflow/tensorflow/tensorflow/go
 ---> Running in c8a1c8c24a33
package github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto" in any of:
	/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto (from $GOROOT)
	/root/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto (from $GOPATH)
The command '/bin/sh -c go get -d github.com/tensorflow/tensorflow/tensorflow/go' returned a non-zero code: 1
```

**Comment by noj-richards** [comment]
Yes, Think this is still an issue:

../../../../../github.com/tensorflow/tensorflow/tensorflow/go/saved_model.go:24:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto" in any of:
        /usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto (from $GOROOT)
        /Users/xxxx/code/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto (from $GOPATH)

../../../../../github.com/tensorflow/tensorflow/tensorflow/go/saved_model.go:24:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto" in any of:
        /usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto (from $GOROOT)

**Comment by umbrellary** [comment]
I have this issue too:

go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto
../gopath/pkg/mod/github.com/tensorflow/tensorflow@v2.2.0+incompatible/tensorflow/go/saved_model.go:24:2: module github.com/tensorflow/tensorflow@latest found (v2.2.0+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto
make: *** [release] Error 1

**Comment by mkanakis** [comment]
Hi, 

I am experience the issue as well, any updates?

Running the following command:
```
go get -d github.com/tensorflow/tensorflow/tensorflow
```

Produces the following output:

```
package github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
	/home/marios/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
```

**Comment by jdoucy** [comment]
Go packages depends on the C lib which is using 1.15 Tensorflow version, go get is trying to get the last 2.2.0.

There is a workaround described here => https://github.com/tensorflow/tensorflow/issues/23257#issuecomment-433751410

On my side I use a go.mod file with 
`require github.com/tensorflow/tensorflow v1.15.0`
and it worked 🙌

**Comment by amalbala** [comment]
Same problem here, checked my C lib is 2.2.0 but when try to use the go code:

```
go: finding module for package github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto
/home/antonio/go/pkg/mod/github.com/tensorflow/tensorflow@v2.2.0+incompatible/tensorflow/go/saved_model.go:24:2: module github.com/tensorflow/tensorflow@latest found (v2.2.0+incompatible), but does not contain package github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto

```

Unfortunatelly I can not dowgrade to TF 1.15

**Comment by jobale** [comment]
Same problem here. Following command:
`go get -d github.com/tensorflow/tensorflow/tensorflow/go`
 produce:
`package github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto" in any of:
	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto (from $GOROOT)
	/home/joceran/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto (from $GOPATH)
`
Following command:
`go generate github.com/tensorflow/tensorflow/tensorflow/go/op`
produce:
`google/protobuf/any.proto: File not found.
google/protobuf/duration.proto: File not found.
tensorflow/core/protobuf/autotuning.proto:10:1: Import "google/protobuf/any.proto" was not found or had errors.
tensorflow/core/protobuf/autotuning.proto:11:1: Import "google/protobuf/duration.proto" was not found or had errors.
tensorflow/core/protobuf/autotuning.proto:61:3: "google.protobuf.Duration" is not defined.
tensorflow/core/protobuf/autotuning.proto:74:3: "google.protobuf.Any" is not defined.
../genop/main.go:17: running "bash": exit status 1
go/src/github.com/tensorflow/tensorflow/tensorflow/go/op/generate.go:17: running "go": exit status 1
`
I tried with tensorflow r2.1 (git checkout r2.1) and the `go get -d...` error disappear. Unfortunately to test the subsequent `go generate` command I need to compile libtensorflow.so.2 against tensorflow v2.1.0 (mine is compiled against tensroflow 2.2.0 of course). 
I add to this that it's quite annoying to have to compile libtensorflow v2 and above. Why is it not distributed anymore like libtensorflow v1.15 ? It was really convenient that way. (Not a fan of the ever changing bazel version for each tensorflow release).

**Comment by kyungtae** [comment]
Is there any official progress on this?

**Comment by sdeoras** [comment]
running into this error for TF v2.3.1. is there a way to generate this package?
```
└─ $ ▶ go test github.com/tensorflow/tensorflow/tensorflow/go
saved_model.go:25:2: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto" in any of:
	/home/sdeoras/go/src/github.com/tensorflow/tensorflow/tensorflow/go/vendor/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (vendor tree)
	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOROOT)
	/home/sdeoras/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/protobuf/for_core_protos_go_proto (from $GOPATH)
```
