### ISSUE TITLE
ModuleNotFoundError tensorflow.python' is not a package

### ISSUE THREAD

**Issue by R0b4** [tensorflow/tensorflow#34722]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 Home
- TensorFlow version (use command below): 2.0
- Python version: 3.6.7 and 3.7.4

**Describe the current behavior**
When trying to import Tensorflow using this line:
`import tensorflow as tf`

I get this error:

> Traceback (most recent call last):
  File "singlestock/code.py", line 1, in <module>
    import tensorflow as tf
  File "D:\documenten\programs\Python\3.6.7\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "D:\documenten\programs\Python\3.6.7\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python.tools'; 'tensorflow.python' is not a package

**Describe the expected behavior**
I shouldn't get this error. I should just be able to import tensorflow and then use it.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

This is the code which doesn't work for me:
I've tried this in python 3.7 and 3.6.
```
import tensorflow as tf

tensor = tf.convert_to_tensor([[1, 2, 3, 4], [2, 3, 4, 5]], tf.int32)
print("hello")
```

I don't think the issue is in the code though, but I have no idea what the problem could be.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

error:
> Traceback (most recent call last):
  File "singlestock/code.py", line 1, in <module>
    import tensorflow as tf
  File "D:\documenten\programs\Python\3.6.7\lib\site-packages\tensorflow\__init__.py", line 98, in <module>
    from tensorflow_core import *
  File "D:\documenten\programs\Python\3.6.7\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
ModuleNotFoundError: No module named 'tensorflow.python.tools'; 'tensorflow.python' is not a package

code:
```
import tensorflow as tf

tensor = tf.convert_to_tensor([[1, 2, 3, 4], [2, 3, 4, 5]], tf.int32)
print("hello")
```

**Comment by oanush** [comment]
@R0b4 ,
Please try reinstalling Tensorflow by
Uninstall tensorflow:
`pip uninstall tensorflow`

Then reinstall it:
`pip install tensorflow`
Also refer this [link](https://stackoverflow.com/questions/41415629/importerror-no-module-named-tensorflow-python).
Thanks!

**Comment by R0b4** [comment]
I already tried this. I also tried installing it in different versions of python (3.7.4, 3.6.7, 3.6.6). This didn't work.

**Comment by R0b4** [comment]
I just found something out. Tensorflow apparently does work when importing it in the console like this:
```
PS C:\Users\user> py
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> print(tf.constant([1, 2, 3, 4]))
2019-12-02 14:39:53.575123: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
>>>
```

But it doesn't work when executing a file like this:
`py folder/code.py`

**Comment by oanush** [comment]
@R0b4 ,
can you please make sure that both python and tensorflow are installed in the same path where you are trying to execute `py folder/code.py` ?Thanks!

**Comment by alexander-travov** [comment]
@R0b4,
I had the same problem when I unimaginatively named file for tutorial I was following ``csv.py``.

It broke the execution of ``example.py`` tutorial, that was in the same directory.

After renaming ``csv.py`` problem resolved.

**Comment by R0b4** [comment]
Apparently alexander was right. The problem was the name, so this begs the question why can't i name my script "code.py"?

**Comment by alexander-travov** [comment]
@R0b4 Both csv.py and code.py are modules from python standard library. Placing modules with the same names in current working directory messes tensorflow importing.

**Comment by oanush** [comment]
@R0b4 ,
Is the solution provided by @alexander-travov  resolves the issue ?Please close the issue if it is works fine.Thanks!

**Comment by Usama-Zafar** [comment]
faced the same problem, changed filename from code.py ... Solved the problem!

**Comment by adele-php** [comment]
> @R0b4 Both `csv.py` and `code.py` clash with modules from python standard library.
> Placing them in the working directory messes `tensorflow` import.

巨感谢，目录有个csv.py改名后，我又可以愉快的玩耍了

**Comment by alexbruy** [comment]
I can confirm issue with import statements. Just installed tensorflow on the clean system using pip (Python 3.7.0), this installs tensorflow 2.0.

When I try to execute my code I get

```
ModuleNotFoundError: No module named 'tensorflow.python.tools'; 'tensorflow.python' is not a package
```

Looking in the site-packages, it seems directory layout in tensorflow 2.0 was changed and now there is no `tensorflow.python` but there is `tensorflow_core.python`. And this is the reason for this import error.

**Comment by mihaimaruseac** [comment]
There is supposed to be mapping between `tensorflow.python` and `tensorflow_core.python` to make thie layout change transparent.

I implemented that, so I'll try to see why it doesn't work, if I can reproduce.

**Comment by kibergus** [comment]
I have the same problem and by adding some prints and breakpoints observe that _LazyLoader for `tensorflow.python` kicks in and starts executing `tensorflow_core/python/__init__.py` it gets to the following line:
```
from tensorflow.python import keras
```
Which throws `AttributeError("type object 'scipy.interpolate.interpnd.array' has no attribute '__reduce_cython__'")` But this exception is not preserved or logged and instead we see `ModuleNotFoundError: No module named 'tensorflow.python.tools'; 'tensorflow.python' is not a package`.

I see two problems here:

 * _LazyLoader does not handle import errors properly. They need to be delivered to the CLI. We need to see original error.
 * Something wrong with `scipy`. May be a version mismatch.

**Comment by kibergus** [comment]
In my case the problem was solved by `sudo apt install --reinstall python*-decorator`. It was induced by a corrupted scipy. But this does not cancel the fact that tensorflow does not report an underlying error properly.

**Comment by kibergus** [comment]
I do not think that the problem has been resolved. The error reporting is still broken and investigation of a simple problem has cost me hours of my life.

**Comment by mihaimaruseac** [comment]
Reopened to have TF work on better error messages. But the root cause is not a TF failure.

**Comment by tensorflowbutler** [comment]
It has been 14 days with no activity and the `awaiting response` label was assigned. Is this still an issue?

**Comment by singhstack** [comment]
My file is not named 'csv.py' or 'code.py' but I am still receiving this error.

Infact, simply using 'import tensorflow' in the shell, gives me this error. 

Can anyone help me resolve this?

**Comment by rezakarbasi** [comment]
> @R0b4 ,
> can you please make sure that both `python` and `tensorflow` are installed in the same path where you are trying to execute `py folder/code.py` ?Thanks!

i can't believe that filename is the problem :laughing:

**Comment by hregua** [comment]
You may have different paths for your python package. One from AppData/Locals and the other is from AppData/Roaming. Removing the python package in AppData/Roaming solves my problem.

**Comment by Black-Behemoth** [comment]
> @R0b4 Both `csv.py` and `code.py` clash with modules from python standard library.
> Placing them in the working directory messes `tensorflow` import.

Thanks a bunch! Though in my case, it was Google Colab that allowed me to download "csv.py" from their example library and thus cause this unnecessary mess.

**Comment by rahulsdhar** [comment]
I had the same issue but soon resolved it.
I have realized that the problem existed because I have a file named imp.py in the same directory where I have my main.py (where I have imported keras module).
I have renamed my imp.py to impxyz.py and the problem disappeared.

**Comment by AshishGusain17** [comment]
Definitely, the error is due to the usage of a file name that is already used in tensorflow. Just change your file names.

**Comment by tcoppex** [comment]
Hey all, 
I just had a similar issue due to completely different causes - mainly versioning and pip binary aliases - so I figured I'll share what worked for me :

```bash
python3 --version
python3 -m pip install --upgrade pip
python3 -m pip install tensorflow
```
On my system `python3` links to version `3.6.9`, just be sure to have a compatible one.

Cheers :+1:

**Comment by bhavints** [comment]
Still having this issue. None of my files are named something generic that could conflict (unless lr_finder.py??).

**Comment by AshishGusain17** [comment]
@bhavints I prefer change all your files name and see if you get some result.

**Comment by MesterRudi** [comment]
As mentioned above, renaming my files worked for me. I had a file named 'cmd.py' that caused the issue.

**Comment by bharathsudharsan** [comment]
> @R0b4,
> I had the same problem when I unimaginatively named file for the tutorial I was following `csv.py`.
> 
> It broke the execution of another tutorial `example.py` in the same directory with described symptomes.
> 
> After renaming `csv.py` problem resolved.

Yes! Thanks. renaming the file solved the problem
