### ISSUE TITLE
25X slower in-graph vs out-of-graph training loop on GPU in TF2.0 

### ISSUE THREAD

**Issue by huyng** [tensorflow/tensorflow#35165]
**Describe the current behavior**

When training using a fully in-graph training loop for a custom model ([as described in the documentation](https://www.tensorflow.org/guide/function#define_the_training_loop)), training is 25x slower than when training the same model with an out-of-graph training loop. 

**Describe the expected behavior**

I would think in-graph training should be faster because we are not shuttling data back and forth between the gpu and python runtimes.

**Code to reproduce the issue**
```python
import numpy as np
import tensorflow as tf
import tensorflow.keras as keras
import time
import os

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'


class MyModel(keras.Model):

    def __init__(self):
        super(MyModel, self).__init__()
        self.conv1 = keras.layers.Conv2D(64, [3, 3])
        self.conv2 = keras.layers.Conv2D(64, [3, 3])
        self.flatten = keras.layers.Flatten()

    def call(self, inputs, training):
        images = inputs[0]
        targets = inputs[1]
        x = self.conv1(images)
        x = self.conv2(x)
        x = self.flatten(x)
        loss = tf.reduce_mean(x, axis=1) - tf.reduce_mean(targets, axis=1)
        return loss

def create_dataset():
    X = np.zeros([10, 224, 224, 3], dtype=np.float32)
    Y = np.zeros([10, 1000], dtype=np.float32)
    x_ds = tf.data.Dataset.from_tensor_slices(X)
    y_ds = tf.data.Dataset.from_tensor_slices(Y)
    ds = tf.data.Dataset.zip((x_ds, y_ds))
    ds = ds.batch(32)
    return ds

@tf.function
def train_one_step(model, optim, inputs):
    with tf.GradientTape() as tape:
        loss = model(inputs, training=True)
        loss = tf.reduce_mean(loss)
    grads = tape.gradient(loss, model.trainable_variables)
    grads_and_vars = zip(grads, model.trainable_variables)
    optim.apply_gradients(grads_and_vars)
    return loss


@tf.function
def in_graph_training_loop(model, optim, dataset):
    step = 0
    for inputs in dataset:
        loss = train_one_step(model, optim, inputs)
        step += 1


def out_graph_training_loop(model, optim, dataset):
    step = 0
    for inputs in dataset:
        loss = train_one_step(model, optim, inputs)
        step += 1


def main():
    model = MyModel()
    optim = keras.optimizers.Adam(1e-4)
    dataset = create_dataset()

    for i in range(5):
        t0 = time.time()
        in_graph_training_loop(model, optim, dataset)
        t1 = time.time()
        print('Time for in-graph training loop: %.3f secs' % (t1 - t0))

    print('-' * 20)

    for i in range(5):
        t0 = time.time()
        out_graph_training_loop(model, optim, dataset)
        t1 = time.time()
        print('Time for out-of-graph training loop: %.3f secs' % (t1 - t0))


if __name__ == '__main__':
    main()

```
Output:

```
python train/test.py 
Time for in-graph training loop: 2.064 secs
Time for in-graph training loop: 1.031 secs
Time for in-graph training loop: 1.013 secs
Time for in-graph training loop: 1.018 secs
Time for in-graph training loop: 1.012 secs
--------------------
Time for out-of-graph training loop: 2.079 secs
Time for out-of-graph training loop: 0.014 secs
Time for out-of-graph training loop: 0.041 secs
Time for out-of-graph training loop: 0.041 secs
Time for out-of-graph training loop: 0.041 secs
```

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes but this is minimally divergent from stock examples in documentation
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0
- Python version:  3.6.8
- CUDA/cuDNN version: 10.0

**Comment by gadagashwini** [comment]
Issue is replicating on colab with Tf 2.0.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/b255e6504968e6a8ee824097e78a07f1/untitled314.ipynb). Thanks!

**Comment by huyng** [comment]
Thanks for testing.

**Comment by SummerRainET2008** [comment]
@huyng @gadagashwini This issue is the same with my proposed recently, see https://github.com/tensorflow/tensorflow/issues/35206

I have a temporary solution, add tf.function for all main invoked functions for in_graph_training_loop. In this example, they are MyModel.call and train_one_step.

I suggest you use a large batch size for testing, and for out_graph_training_loop, do not add tf.function to train_one_step.

In  my testing, I enlarge the parameters, then in_graph_training_loop (add all tf.function) takes about **0.23s**, while **0.39s** for in_graph_training_loop (without any tf.function)

**Comment by mdanatg** [comment]
There is a known issue with datasets in for loops in the 2.0 release that was causing unnecessary bouncing to the CPU - #32138. That is fixed in tf-nightly. I'll have a closer look at the measurements.

**Comment by huyng** [comment]
@SummerRainET2008 @mdanatg thanks for the response. I tried modifying and testing my code based on your comments (See below).

---

@SummerRainET2008 , I tried decorating the MyModel.call w/ tf.function and it doesn't seem to resolve the issue. Here are the timings

```
Time for in-graph training loop: 1.478 secs
Time for in-graph training loop: 1.011 secs
Time for in-graph training loop: 1.019 secs
Time for in-graph training loop: 1.046 secs
Time for in-graph training loop: 0.991 secs
--------------------
Time for out-of-graph training loop: 2.412 secs
Time for out-of-graph training loop: 0.014 secs
Time for out-of-graph training loop: 0.016 secs
Time for out-of-graph training loop: 0.016 secs
Time for out-of-graph training loop: 0.016 secs
```

---

@mdanatg I tried adding `iter(dataset)` to my in-graph loop and it helped a lot! However, the in-graph loop is still 2x as slow as the out-of-graph loop:
modification:

```python
@tf.function
def in_graph_training_loop(model, optim, dataset):
    step = 0
    for inputs in iter(dataset):
        loss = train_one_step(model, optim, inputs)
        step += 1
```

timing:
```
Time for in-graph training loop: 2.355 secs
Time for in-graph training loop: 0.031 secs
Time for in-graph training loop: 0.031 secs
Time for in-graph training loop: 0.028 secs
Time for in-graph training loop: 0.031 secs
--------------------
Time for out-of-graph training loop: 0.671 secs
Time for out-of-graph training loop: 0.014 secs
Time for out-of-graph training loop: 0.016 secs
Time for out-of-graph training loop: 0.016 secs
Time for out-of-graph training loop: 0.016 secs
```

I then tried adding `tf.device` context manager but the out-of-graph loop still seems to be fastest.

modification:
```python
@tf.function
def in_graph_training_loop(model, optim, dataset):
    step = 0
    for inputs in iter(dataset):
        with tf.device('/device:GPU:0'):
            loss = train_one_step(model, optim, inputs)
            step += 1
```

timing:
```
Time for in-graph training loop: 2.356 secs
Time for in-graph training loop: 0.031 secs
Time for in-graph training loop: 0.032 secs
Time for in-graph training loop: 0.032 secs
Time for in-graph training loop: 0.032 secs
--------------------
Time for out-of-graph training loop: 0.674 secs
Time for out-of-graph training loop: 0.014 secs
Time for out-of-graph training loop: 0.016 secs
Time for out-of-graph training loop: 0.016 secs
Time for out-of-graph training loop: 0.016 secs
```

**Comment by mdanatg** [comment]
I increased the dataset size so that the training loop runs 10 iterations, rather than just a single one.

So when applying the workaround suggested in #32138 (writing `for inputs in iter(dataset):`), the speed becomes comparable:

```
Time for in-graph training loop: 0.928 secs
Time for in-graph training loop: 0.614 secs
Time for in-graph training loop: 0.624 secs
Time for in-graph training loop: 0.617 secs
Time for in-graph training loop: 0.615 secs
--------------------
Time for out-of-graph training loop: 1.050 secs
Time for out-of-graph training loop: 0.458 secs
Time for out-of-graph training loop: 0.459 secs
Time for out-of-graph training loop: 0.459 secs
Time for out-of-graph training loop: 0.457 secs
--------------------
Time for in-graph training loop using tf.while: 0.750 secs
Time for in-graph training loop using tf.while: 0.531 secs
Time for in-graph training loop using tf.while: 0.532 secs
Time for in-graph training loop using tf.while: 0.533 secs
Time for in-graph training loop using tf.while: 0.530 secs
```

In this case, we'd expect the performance to be comparable because the only difference between the in-graph and the out-of-graph training loops is whether the loop runs in Python or in the TF executor - otherwise, in both cases we have data flowing from one subgraph (the one created by the dataset) to another (the one created by train_one_step).

At head, they run at comparable speeds:

```
Time for in-graph training loop: 0.928 secs
Time for in-graph training loop: 0.614 secs
Time for in-graph training loop: 0.624 secs
Time for in-graph training loop: 0.617 secs
Time for in-graph training loop: 0.615 secs
--------------------
Time for out-of-graph training loop: 1.050 secs
Time for out-of-graph training loop: 0.458 secs
Time for out-of-graph training loop: 0.459 secs
Time for out-of-graph training loop: 0.459 secs
Time for out-of-graph training loop: 0.457 secs
```

@jsimsa @alextp @mhong @jaingaurav FYI
It's interesting to note that the out-of graph loop is still faster, which means that the TF runtime is a little slower than Pyhton at running basic loops. That will hopefully improve in the future.
