### ISSUE TITLE
Tensorflow 2.1.0 - DLL load failed

### ISSUE THREAD

**Issue by ReinforcedMan** [tensorflow/tensorflow#35618]
### System information
- **OS Platform and Distribution**: Windows 10
- **TensorFlow installed from (source or binary)**: pip install tensorflow-gpu==2.1.0rc2
- **TensorFlow version (use command below)**: 2.1.0rc2
- **Python version**: 3.7.4
- **CUDA/cuDNN version**: CUDA 10.1, cuDNN 7.6.5 associated with CUDA 10.1
- **GPU model and memory**: GTX 1060 6GB

### Describe the problem
I installed the pre-release using `pip install tensorflow-gpu==2.1.0rc2`. I installedCUDA 10.1 with cuDNN 7.6.5. When running `import tensorflow`, I get a 

> ImportError: DLL load failed: The specified module could not be found.

It probably means there is an issue with the CUDA installation, or a bug somewhere. Tensorflow 2.1.0 is supposed to be compatible with CUDA 10.1. 

In my system environment variables, path contains:

> C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\extras\CUPTI\lib64
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include

### Source code / logs
  ```
File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.2.3\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\johndoe\AppData\Local\Continuum\anaconda3\envs\dummy_env_name\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\johndoe\AppData\Local\Continuum\anaconda3\envs\dummy_env_name\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\johndoe\AppData\Local\Continuum\anaconda3\envs\dummy_env_name\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\johndoe\AppData\Local\Continuum\anaconda3\envs\dummy_env_name\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

```

**Comment by ravikyram** [comment]
@ReinforcedMan 
Did you follow the instruction from [TensorFlow website](https://www.tensorflow.org/install/source_windows). You can have a look on similar issue #22794 and #10033 . let us know if that helps. Looks like you need to add path for CUDA and CuDNN.Thanks!

**Comment by ReinforcedMan** [comment]
@ravikyram 
I did not follow the instructions to build the package. I installed the version on pipy, and couldn't get it to work with any cuda version, even though it is supposed to support cuda 10.1 as stated in the release notes. 

When trying to build the package like you linked, I get an error in the c++ code. 

I don't have any more days to allocate to this and am thus giving up. I'll wait for a clean 2.1.0 release.

**Comment by ReinforcedMan** [comment]
I'm reopening since the problem still appears with the version of tensorflow 2.1.0 on pipy that you get with 

`pip install tensorflow`

I have cuda 10.1 and cudnn 7.6.5 for cuda 10.1. 
In my system path I have bin/, libnvvp/ and CUPTI\lib64, as I did for tensorflow 2.0.0 but adapted for 2.1.

**Comment by mihaimaruseac** [comment]
Can you try using `tensorflow` instead of `tensorflow-gpu`? It should have the GPU build too (and if it works it will point out a failure in the way we release these two)

**Comment by ReinforcedMan** [comment]
I tried both

```
pip install tensorflow
pip install tensorflow-gpu
```

but neither seem to be working for me ...

Also: Maybe something of note is that in the [test build of the pipy version](https://source.cloud.google.com/results/invocations/88229a56-37fe-41cc-947a-787023dce60a/targets/tensorflow%2Fgithub%2Fwindows%2Fgpu_py36_full%2Fcontinuous/log) the CUPTI path is set as pointing to 10.1/../libx64, where it seems to have been renamed to 10.1/../lib64 without the x in the cuda installation.

**Comment by CuspMe** [comment]
i fix this by downgrading to

`pip install tensorflow=2.0`

**Comment by mihaimaruseac** [comment]
@ReinforcedMan can you make a symlink from `CUPT/libx64` to `CUPT/lib64`?

**Comment by ReinforcedMan** [comment]
@mihaimaruseac I already added the two versions in my Path variable, I don't think that's the cause of it. I was just saying that in the tensorflow test build I think you guys might have the wrong path, but it still works as you also give the CUDA/v10.0/../libx64 in addition to the 10.1. 

Sorry for being unclear.

**Comment by nectario** [comment]
I am having the same issue when I pip install tensorflow. I do not have an nvidia graphics card and want to use a CPU tensorflow, NOT GPU. I get:

ImportError: DLL load failed: The specified module could not be found.
Failed to load the native TensorFlow runtime.

**Comment by nectario** [comment]
I am using an HP laptop from 2 years ago.

**Comment by nectario** [comment]
Is there a workaround for this issue??

**Comment by mihaimaruseac** [comment]
@nectario try `tensorflow-cpu` package? If the issue still persists, I would recommend opening a new one and filling in the template as it looks like you have a different issue.

**Comment by nectario** [comment]
This happens even when I install tensorflow-cpu. Below is the complete stack trace:

Traceback (most recent call last):
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Development\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Development\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Development/Projects/TensorFlow_2.0_Hierarchical_Attention/QuestionAnswerContextAttention.py", line 8, in <module>
    import tensorflow as tf
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "C:\Development\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Development\Python\Python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Development\Python\Python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Development\Python\Python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by nectario** [comment]
The issue seems to be the same and it happens on two completely different computers of mine.

**Comment by mihaimaruseac** [comment]
Please identify which DLL fails to load and please open a different issue as they look to be different

**Comment by nectario** [comment]
Done.
Issue: #35749

**Comment by galocen** [comment]
I posted my solution in the @nectario post.
https://github.com/tensorflow/tensorflow/issues/35749#issuecomment-573313402

**Comment by ID-ao** [comment]
The solution proposed by @galocen in #35749 seems to resolve the issue for me.
> I solved it today downloading and installing visual studio 2015-2019 x86 and x64 from [here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)

**Comment by ravikyram** [comment]
@ReinforcedMan 

Please, let us know if the issue still persists. Thanks!

**Comment by aeropia** [comment]
I have the same issue and my laptop is not with GPU. I tried with CPU version but the issue still exists. So, have returned back to 2.0.

**Comment by mihaimaruseac** [comment]
I still don't know what DLL fails to load

**Comment by ReinforcedMan** [comment]
@ravikyram @mihaimaruseac 

The solution proposed by @galocen in #35749 solves the issue for me. So if anyone has this issue,
make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads). 

Thank you all for your help, this issue is now solved, closing it. 

@aeropia: Your issue seems different, feel free to open a new one describing it in more details.

**Comment by NeuralSec** [comment]
A potential solution: upgrading your Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019:
[https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads](https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads).

**Comment by jingweimo** [comment]
@ReinforcedMan Are you using vs2015 or a higher version?

**Comment by jingweimo** [comment]
> @ravikyram @mihaimaruseac
> 
> The solution proposed by @galocen in #35749 solves the issue for me. So if anyone has this issue,
> make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
> 
> Thank you all for your help, this issue is now solved, closing it.
> 
> @aeropia: Your issue seems different, feel free to open a new one describing it in more details.

It also solved my problem!!

**Comment by Ansreng360** [comment]
Installing the redistributable didn't solve the error for me. Does anyone else have the same problem?

**Comment by mihaimaruseac** [comment]
@Ansreng360 

There are at least 4 possible scenarios:

* You need to install the MSVC 2019 redistributable
* Your CPU does not support AVX2 instructions
* Your CPU/Python is on 32 bits
* There is a library that is in a different location/not installed on your system that cannot be loaded.

Please identify which is your case and open a new issue *only if* there is a fifth case

**Comment by bduan007** [comment]
I had similar DLL load failed error when I was importing tensorflow 2.1 in my latest Anaconda environment. I tried several times from creating the virtual environment to installation tensorflow 2.1 without success.  The installation process went through fine without any error message. The tensorflow 2.0 works fine but not tensorflow 2.1.  Thanks for any insight!

**Comment by ravikyram** [comment]
@bduan007 

Can you please raise a new issue by filling [build/installation issue template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md).Thanks!

**Comment by bduan007** [comment]
Sure!  Can you forward me the link that I shared the issue?  I could not easily find my comments and don't want to recreate the wheels.  Thanks! Bin





On Monday, February 10, 2020, 12:25:35 AM EST, ravikyram <notifications@github.com> wrote: 





@bduan007

Can you please raise a new issue by filling build/installation issue template.Thanks!

**Comment by 1vecera** [comment]
> > @ravikyram @mihaimaruseac
> > The solution proposed by @galocen in #35749 solves the issue for me. So if anyone has this issue,
> > make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
> > Thank you all for your help, this issue is now solved, closing it.
> > @aeropia: Your issue seems different, feel free to open a new one describing it in more details.
> 
> It also solved my problem!!



> @ravikyram @mihaimaruseac
> 
> The solution proposed by @galocen in #35749 solves the issue for me. So if anyone has this issue,
> make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
> 
> Thank you all for your help, this issue is now solved, closing it.
> 
> @aeropia: Your issue seems different, feel free to open a new one describing it in more detail.

I don't think this is closed. Tensorflow PyPI distribution should not rely on a manual install of some Microsoft software utility that needs admin rights to install. (Scalability and so)

**Comment by mihaimaruseac** [comment]
We cannot bundle everything ourselves (especially so since some packages have licenses prohibiting bundling together). So you have to install dependencies out of bound.

**Comment by YumainOB** [comment]
I ran through this issue too during an update of mt TF environment. The installation of latest Visual C redistribuable tools solved the issue for me too obviously.
This solution is well documented in build from source for windows [https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2019](https://www.tensorflow.org/install/source_windows#install_visual_c_build_tools_2019)
BUT it should also be documented as a requirement in the PIP based installation process and even better checked during the pip install if it is possible to echoe an explicite warning if msvcp140_1.dll has not been found. It would save time and nerves on many people that are not building from sources.

**Comment by Zaaachary** [comment]
> i fix this by downgrading to
> 
> `pip install tensorflow=2.0`

problem solved!

**Comment by mihaimaruseac** [comment]
Solution is to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).

Locking conversation to prevent spammy "works for me" and fake solutions of "downgrade to TF 2.0"
