### ISSUE TITLE
TensorFlow Feature Columns Fail for Keras Model Functional API

### ISSUE THREAD

**Issue by jeisinge** [tensorflow/tensorflow#36424]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Databricks 6.3- `Linux version 4.4.0-1100-aws (buildd@lgw01-amd64-030) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #111-Ubuntu SMP Wed Dec 4 12:20:15 UTC 2019 (Ubuntu 4.4.0-1100.111-aws 4.4.203)`
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 
```
2020-02-02 17:40:54.646833: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-02-02 17:40:54.648818: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
v2.1.0-rc2-17-ge5bf8de 2.1.0
```
- **Python version**: 3.7.3
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**: GCC 7.3.0
- **CUDA/cuDNN version**: 10.1
- **GPU model and memory**: AWS p2.xlarge
- **Exact command to reproduce**:
```python
source_column = tf.feature_column.numeric_column("source_name")
categorical_column = tf.feature_column.bucketized_column(source_column, [0, 10, 100])
embedding_column = tf.feature_column.embedding_column(categorical_column, 7)
feature_columns = [ embedding_column ]

name_schema = tf.feature_column.make_parse_example_spec(feature_columns)
inputs = {
  name: keras.layers.Input(shape=schema.shape, name=name, dtype=schema.dtype)
  for name, schema in name_schema.items()
}

dense_features = keras.layers.DenseFeatures(feature_columns)
column_tensors = {}
dense_tensor = dense_features(inputs, cols_to_output_tensors=column_tensors)
```

### Describe the problem
> Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

I believe it should be possible to use Feature Columns with Keras Model Functional API.  Most feature columns work, however, it appears that some combinations of feature columns like the above embedding - bucketized - numeric columns fail.

It is not clear how to work around this error or apply the suggested wrapping.

### Source code / logs
> Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

The above code fails with:
```pytb
ValueError                                Traceback (most recent call last)
<command-1166953> in <module>
     12 dense_features = keras.layers.DenseFeatures(feature_columns)
     13 column_tensors = {}
---> 14 dense_tensor = dense_features(inputs, cols_to_output_tensors=column_tensors)

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    803               kwargs.pop('mask')
    804             inputs, outputs = self._set_connectivity_metadata_(
--> 805                 inputs, outputs, args, kwargs)
    806           self._handle_activity_regularization(inputs, outputs)
    807           self._set_mask_metadata(inputs, outputs, input_masks)

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py in _set_connectivity_metadata_(self, inputs, outputs, args, kwargs)
   2012     # This updates the layer history of the output tensor(s).
   2013     self._add_inbound_node(
-> 2014         input_tensors=inputs, output_tensors=outputs, arguments=arguments)
   2015     return inputs, outputs
   2016 

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py in _add_inbound_node(self, input_tensors, output_tensors, arguments)
   2042         input_tensors=input_tensors,
   2043         output_tensors=output_tensors,
-> 2044         arguments=arguments)
   2045 
   2046     # Update tensor history metadata.

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/node.py in __init__(self, outbound_layer, inbound_layers, node_indices, tensor_indices, input_tensors, output_tensors, arguments)
    120       if base_layer_utils.needs_keras_history(
    121           tensor_argument, ignore_call_context=True):
--> 122         base_layer_utils.create_keras_history(tensor_argument)
    123 
    124     # Add nodes to all layers involved.

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in create_keras_history(tensors)
    185     keras_tensors: The Tensors found that came from a Keras Layer.
    186   """
--> 187   _, created_layers = _create_keras_history_helper(tensors, set(), [])
    188   return created_layers
    189 

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    247               constants[i] = backend.function([], op_input)([])
    248       processed_ops, created_layers = _create_keras_history_helper(
--> 249           layer_inputs, processed_ops, created_layers)
    250       name = op.name
    251       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    247               constants[i] = backend.function([], op_input)([])
    248       processed_ops, created_layers = _create_keras_history_helper(
--> 249           layer_inputs, processed_ops, created_layers)
    250       name = op.name
    251       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    247               constants[i] = backend.function([], op_input)([])
    248       processed_ops, created_layers = _create_keras_history_helper(
--> 249           layer_inputs, processed_ops, created_layers)
    250       name = op.name
    251       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    247               constants[i] = backend.function([], op_input)([])
    248       processed_ops, created_layers = _create_keras_history_helper(
--> 249           layer_inputs, processed_ops, created_layers)
    250       name = op.name
    251       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    247               constants[i] = backend.function([], op_input)([])
    248       processed_ops, created_layers = _create_keras_history_helper(
--> 249           layer_inputs, processed_ops, created_layers)
    250       name = op.name
    251       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    221             'Sparse ops are not supported with functional models with built-in '
    222             'layer wrapping. Please wrap the sparse ops in a Lambda layer like'
--> 223             ': \n{lambda_example}\n'.format(lambda_example=lambda_example))
    224 
    225       # Recursively set `_keras_history`.

ValueError: Sparse ops are not supported with functional models with built-in layer wrapping. Please wrap the sparse ops in a Lambda layer like: 

        weights_mult = lambda x: tf.sparse.sparse_dense_matmul(x, weights)
        output = tf.keras.layers.Lambda(weights_mult)(input)
```

**Comment by jeisinge** [comment]
On Tensorflow 1.15, I get the following error:
```pytb
ValueError                                Traceback (most recent call last)
<command-1167185> in <module>
     12 dense_features = keras.layers.DenseFeatures(feature_columns)
     13 column_tensors = {}
---> 14 dense_tensor = dense_features(inputs, cols_to_output_tensors=column_tensors)

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    879               kwargs.pop('mask')
    880             inputs, outputs = self._set_connectivity_metadata_(
--> 881                 inputs, outputs, args, kwargs)
    882           self._handle_activity_regularization(inputs, outputs)
    883           self._set_mask_metadata(inputs, outputs, input_masks)

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py in _set_connectivity_metadata_(self, inputs, outputs, args, kwargs)
   2041     # This updates the layer history of the output tensor(s).
   2042     self._add_inbound_node(
-> 2043         input_tensors=inputs, output_tensors=outputs, arguments=arguments)
   2044     return inputs, outputs
   2045 

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py in _add_inbound_node(self, input_tensors, output_tensors, arguments)
   2071         input_tensors=input_tensors,
   2072         output_tensors=output_tensors,
-> 2073         arguments=arguments)
   2074 
   2075     # Update tensor history metadata.

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/node.py in __init__(self, outbound_layer, inbound_layers, node_indices, tensor_indices, input_tensors, output_tensors, arguments)
    120       if base_layer_utils.needs_keras_history(
    121           tensor_argument, ignore_call_context=True):
--> 122         base_layer_utils.create_keras_history(tensor_argument)
    123 
    124     # Add nodes to all layers involved.

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in create_keras_history(tensors)
    182     keras_tensors: The Tensors found that came from a Keras Layer.
    183   """
--> 184   _, created_layers = _create_keras_history_helper(tensors, set(), [])
    185   return created_layers
    186 

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    229               constants[i] = backend.function([], op_input)([])
    230       processed_ops, created_layers = _create_keras_history_helper(
--> 231           layer_inputs, processed_ops, created_layers)
    232       name = op.name
    233       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    229               constants[i] = backend.function([], op_input)([])
    230       processed_ops, created_layers = _create_keras_history_helper(
--> 231           layer_inputs, processed_ops, created_layers)
    232       name = op.name
    233       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    229               constants[i] = backend.function([], op_input)([])
    230       processed_ops, created_layers = _create_keras_history_helper(
--> 231           layer_inputs, processed_ops, created_layers)
    232       name = op.name
    233       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    229               constants[i] = backend.function([], op_input)([])
    230       processed_ops, created_layers = _create_keras_history_helper(
--> 231           layer_inputs, processed_ops, created_layers)
    232       name = op.name
    233       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    229               constants[i] = backend.function([], op_input)([])
    230       processed_ops, created_layers = _create_keras_history_helper(
--> 231           layer_inputs, processed_ops, created_layers)
    232       name = op.name
    233       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    229               constants[i] = backend.function([], op_input)([])
    230       processed_ops, created_layers = _create_keras_history_helper(
--> 231           layer_inputs, processed_ops, created_layers)
    232       name = op.name
    233       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    229               constants[i] = backend.function([], op_input)([])
    230       processed_ops, created_layers = _create_keras_history_helper(
--> 231           layer_inputs, processed_ops, created_layers)
    232       name = op.name
    233       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    229               constants[i] = backend.function([], op_input)([])
    230       processed_ops, created_layers = _create_keras_history_helper(
--> 231           layer_inputs, processed_ops, created_layers)
    232       name = op.name
    233       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    229               constants[i] = backend.function([], op_input)([])
    230       processed_ops, created_layers = _create_keras_history_helper(
--> 231           layer_inputs, processed_ops, created_layers)
    232       name = op.name
    233       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    229               constants[i] = backend.function([], op_input)([])
    230       processed_ops, created_layers = _create_keras_history_helper(
--> 231           layer_inputs, processed_ops, created_layers)
    232       name = op.name
    233       node_def = op.node_def.SerializeToString()

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    227           else:
    228             with ops.init_scope():
--> 229               constants[i] = backend.function([], op_input)([])
    230       processed_ops, created_layers = _create_keras_history_helper(
    231           layer_inputs, processed_ops, created_layers)

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py in __call__(self, inputs)
   3642     return nest.pack_sequence_as(
   3643         self._outputs_structure,
-> 3644         [x._numpy() for x in outputs],  # pylint: disable=protected-access
   3645         expand_composites=True)
   3646 

/databricks/python/lib/python3.7/site-packages/tensorflow_core/python/keras/backend.py in <listcomp>(.0)
   3642     return nest.pack_sequence_as(
   3643         self._outputs_structure,
-> 3644         [x._numpy() for x in outputs],  # pylint: disable=protected-access
   3645         expand_composites=True)
   3646 

ValueError: Cannot convert a Tensor of dtype resource to a NumPy array.
```

**Comment by jeisinge** [comment]
Creating the `dense_tensor` with `tf.compat.v1.feature_column.input_layer` fails later when used.

The following code runs successfully.
```python
column_tensors = {}
dense_tensor = tf.compat.v1.feature_column.input_layer(
  inputs,
  feature_columns,
  cols_to_output_tensors=column_tensors
)
```

However, the same failure exists when the `dense_tensor` is used:
```python
output_1 = keras.layers.Dense(64, activation='relu')(dense_tensor)
```

Can `feature_columns` be used with Keras models?

**Comment by Saduf2019** [comment]
Could you please refer tho this [link](https://github.com/tensorflow/docs/blob/b4d8d7096099c2b0a7df6a0564bf6eca8c96c4a0/site/en/tutorials/structured_data/feature_cols_keras.ipynb) , in case you are still unable to resolve the issue,

Could you please provide us with simple standalone code to reproduce the issue in our environment, Thanks

**Comment by jeisinge** [comment]
@Saduf2019 , I am a bit confused.  The referenced document is from 2018.  It refers to `tensorflow.python.feature_column.feature_column_v2.FeatureLayer`, which I don't think exists anymore.  A more recent document at https://www.tensorflow.org/tutorials/structured_data/feature_columns#create_a_feature_layer refers to `tf.keras.layers.DenseFeatures`, which I use.

For standalone code, I created a Google Colab at https://colab.research.google.com/drive/1DVfpU6EoEz5vkMqLxH7JTXHALpa3VoOs .  Is that what you were looking for? 

Also, I believe it is important to note that this doesn't work on TensorFlow 2 _and_ TensorFlow 1.  I'll try to add the tag.

**Comment by jvishnuvardhan** [comment]
@jeisinge I ran with `tf-nightly` and it did throw only deprecation warning and clearly mentioned to use new `feature_column` API. For example changing `tf.feature_column.numeric_column` to `feature_column.numeric_column`. Before that we need to import feature_column API as `from tensorflow import feature_column`. Please check the [tutorial](https://www.tensorflow.org/tutorials/structured_data/feature_columns) on TF website.

[Here](https://colab.research.google.com/gist/jvishnuvardhan/14728a5879f016c82e320b165ff64dc3/tensorflow-feature-columns-fail-for-keras-model-functional-api.ipynb) is gist for y/our reference. Thanks!

Please close the issue if it was resolved for you. Thanks!

**Comment by jeisinge** [comment]
@jvishnuvardhan , I am not an expert in Python.  What is the difference between:
```python
import tensorflow as tf

source_column = tf.feature_column.numeric_column("source_name")
...
```
and
```python
from tensorflow import feature_column

source_column = feature_column.numeric_column("source_name")
...
```
?

Are you saying that this defect is fixed in the nightly build?  If so, were you able to reproduce in TF 2.1 or TF 1.15?

**Comment by jeisinge** [comment]
I attempted to install tf-nightly in the colar with `!pip install tf-nightly`.  It also failed.

Also, I did try the `from tensorflow import feature_column`.  That failed as well.

**Comment by jvishnuvardhan** [comment]
@jeisinge did you try running my colab gist? Thanks!

**Comment by jeisinge** [comment]
Yeah. It fails.

**Comment by jvishnuvardhan** [comment]
@jeisinge It is strange. my Colab gist should run without an issue. Can you please share the error you are facing? Are you running my gist as it is or did you modify anything? Are you running it in Chrome or any other browser? Still not sure what is the root-cause. Thanks!

**Comment by jeisinge** [comment]
I reran the gist and it succeeded.  However, it appears to be on TF 1.15 due to a misspelling on _install_.   After upgrading to TF 2 or TF Nightly, it appears to fail on a rerun with the same error:
```pycon
ValueError                                Traceback (most recent call last)

<ipython-input-6-bed319bac6ce> in <module>()
      1 dense_features = keras.layers.DenseFeatures(feature_columns)
      2 column_tensors = {}
----> 3 dense_tensor = dense_features(inputs, cols_to_output_tensors=column_tensors)

10 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/base_layer_utils.py in _create_keras_history_helper(tensors, processed_ops, created_layers)
    220             'Sparse ops are not supported with functional models with built-in '
    221             'layer wrapping. Please wrap the sparse ops in a Lambda layer like'
--> 222             ': \n{lambda_example}\n'.format(lambda_example=lambda_example))
    223 
    224       # Recursively set `_keras_history`.

ValueError: Sparse ops are not supported with functional models with built-in layer wrapping. Please wrap the sparse ops in a Lambda layer like: 

        weights_mult = lambda x: tf.sparse.sparse_dense_matmul(x, weights)
        output = tf.keras.layers.Lambda(weights_mult)(input)
```
This might be due to restarting the Python Interpereter.  I believe you can see the gist at https://colab.research.google.com/gist/jeisinge/90718acccf943c16b61ec80a2ff3cb66/tensorflow-feature-columns-fail-for-keras-model-functional-api.ipynb .

In general, I had to run cell 1.  Click the `Restart` button that appears, rerun everything.

**Comment by saikumarchalla** [comment]
@jeisinge  Could you please check with Nightly version and let us know if the issue still persists.Thanks!

**Comment by jeisinge** [comment]
I just tested on TF 2.3 and TF Nightly.  TF 2.3 fails, but TF Nightly works.  Also, the resulting model can be serialized.  Thank you!
