### ISSUE TITLE
When imports tensorflow, there is an error.

### ISSUE THREAD

**Issue by happypycode** [tensorflow/tensorflow#38522]
```python
>>> import tensorflow as tf
2020-04-14 16:10:32.366842: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-14 16:10:32.385198: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 84, in <module>
    from tensorflow.python import keras
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\__init__.py", line 27, in <module>
    from tensorflow.python.keras import models
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\models.py", line 24, in <module>
    from tensorflow.python.keras import metrics as metrics_module
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\metrics.py", line 37, in <module>
    from tensorflow.python.keras.engine import base_layer
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 51, in <module>
    from tensorflow.python.keras import initializers
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\initializers\__init__.py", line 127, in <module>
    populate_deserializable_objects()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\keras\initializers\__init__.py", line 85, in populate_deserializable_objects
    generic_utils.populate_dict_with_module_objects(
AttributeError: module 'tensorflow.python.keras.utils.generic_utils' has no attribute 'populate_dict_with_module_objects'
```
How can I fix the ploblem? Can you fix it?I'm using the newest version of tensorflow, 2.2.0rc3.

**Comment by Saduf2019** [comment]
@happypycode 
can please tell us know how did you install the tensorflow, did you follow [this link](https://www.tensorflow.org/install/source_windows)

**Comment by happypycode** [comment]
> @happypycode
> can please tell us know how did you install the tensorflow, did you follow [this link](https://www.tensorflow.org/install/source_windows)

Yes. I install tensorflow using pip:
```
pip install tensorflow==2.2.0rc3
```
and got this error. I do this:
```
pip install tensorflow==2.2.0rc2 # this version that I didn't get error
```
But when I imports tensorflow, the same! How can I do?

**Comment by happypycode** [comment]
> @happypycode
> can please tell us know how did you install the tensorflow, did you follow [this link](https://www.tensorflow.org/install/source_windows)

Hey! Just at this moment, I fixed up how to do it:
```
pip install tensorflow==2.1.0
```
However, this error was solved, but I still wonder about how does this error raise?

**Comment by Saduf2019** [comment]
@happypycode 
as the issue is resolved can we move this to resolved status.

**Comment by Saduf2019** [comment]
@happypycode
please update as per above comment

**Comment by happypycode** [comment]
Thank you for warning.
```python
>>> import tensorflow as tf
>>> tf.__version__
'2.2.0-rc3'
```

**Comment by mihaimaruseac** [comment]
Is the issue still happening in 2.2? Can you post output of `pip list` please?

**Comment by Saduf2019** [comment]
@happypycode
please update if this is still an issue
