### ISSUE TITLE
tf.name_scope with spaces does not raise ValueError in eager execution 

### ISSUE THREAD

**Issue by sumanthratna** [tensorflow/tensorflow#38754]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS 10.15.5 Beta
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.8
- Bazel version (if compiling from source):  n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**
In autograph, `tf.name_scope` does not allow spaces in the string argument. In eager execution, `tf.name_scope` *does* allow spaces in the string argument. 

**Describe the expected behavior**
The constraints on `tf.name_scope` should be the same across eager execution and autograph. 

**Standalone code to reproduce the issue**
```python
import tensorflow as tf


# eager execution since there's no @tf.function decorator
def graphcry():
    myscalar = tf.constant(83.2)  # just a random number

    with tf.name_scope('scalaragain scope'):  # doesn't work
        tf.summary.scalar('scalaragain', data=myscalar)

    with tf.name_scope('nospace_scope'):  # works
        tf.summary.scalar('nospace', data=myscalar)

graphcry()
```

**Other info / logs**
CC @jvishnuvardhan, also see #38661

**Comment by jvishnuvardhan** [comment]
@sumanthratna Looks like this was resolved. I checked in `TF2.3` and `tf-nightly`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/5ed9cf685953a339a32f0b465f5ec0f8/untitled.ipynb).

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by sumanthratna** [comment]
Hi @jvishnuvardhan! It looks my reproducibility didn't indicate the difference between JIT and eager.

```python
import tensorflow as tf


# eager execution since there's no @tf.function decorator
def graphcry():
    myscalar = tf.constant(83.2)  # just a random number

    with tf.name_scope('scalaragain scope'):
      print('Scope1: Working')
      tf.summary.scalar('scalaragain', data=myscalar)# doesn't work

    with tf.name_scope('nospace_scope'):  # works
      print('Scope2: Working')
      tf.summary.scalar('nospace', data=myscalar)

graphcry()

@tf.function
def graphcry2():
    myscalar = tf.constant(83.2)  # just a random number

    with tf.name_scope('jit_scalaragain scope'):
      print('Scope1 JIT: Working')
      tf.summary.scalar('scalaragain', data=myscalar)# doesn't work

    with tf.name_scope('jit_nospace_scope'):  # works
      print('Scope2 JIT: Working')
      tf.summary.scalar('nospace', data=myscalar)

graphcry2()
```

results in:
```
Scope1: Working
Scope2: Working
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-182149e1e839> in <module>()
     28       tf.summary.scalar('nospace', data=myscalar)
     29 
---> 30 graphcry2()

8 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    971           except Exception as e:  # pylint:disable=broad-except
    972             if hasattr(e, "ag_error_metadata"):
--> 973               raise e.ag_error_metadata.to_exception(e)
    974             else:
    975               raise

ValueError: in user code:

    <ipython-input-2-182149e1e839>:22 graphcry2  *
        with tf.name_scope('jit_scalaragain scope'):
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:6631 __enter__
        scope_name = scope.__enter__()
    /usr/lib/python3.6/contextlib.py:81 __enter__
        return next(self.gen)
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py:4190 name_scope
        raise ValueError("'%s' is not a valid scope name" % name)

    ValueError: 'jit_scalaragain scope' is not a valid scope name
```
note how no errors occur with eager, but ValueError occurs with JIT. IMO the behavior should be the same for both eager and JIT.

**Comment by mohantym** [comment]
It is still replicating in[ 2.8 version.](https://colab.sandbox.google.com/gist/sachinprasadhs/ae03cc43eb93b9aca7986cbb0bdfbe54/38754.ipynb#scrollTo=1WYW-rQkfCuQ)

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by sumanthratna** [comment]
I re-ran my minimal reproduction sample and this issue still exist on the latest stable TensorFlow. This was the traceback

```
Scope1: Working
Scope2: Working
Traceback (most recent call last):
  File "/private/tmp/i38754.py", line 30, in <module>
    graphcry2()
  File "/private/tmp/venv/lib/python3.11/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/var/folders/l4/r2p4k6bs3j12wkvrpn5l9k180000gn/T/__autograph_generated_filesu9tfyzj.py", line 9, in tf__graphcry2
    with ag__.ld(tf).name_scope('jit_scalaragain scope'):
  File "/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: in user code:

    File "/private/tmp/i38754.py", line 22, in graphcry2  *
        with tf.name_scope('jit_scalaragain scope'):
    File "/opt/homebrew/Cellar/python@3.11/3.11.9_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
        return next(self.gen)

    ValueError: 'jit_scalaragain scope' is not a valid root scope name. A root scope name has to match the following pattern: ^[A-Za-z0-9.][A-Za-z0-9_.\\/>-]*$

```
