### ISSUE TITLE
tf.tpu.experimental.initialize_tpu_system fails to work on nightly builds

### ISSUE THREAD

**Issue by swghosh** [tensorflow/tensorflow#40622]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colaboratory (Linux)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): tf-nightly_v2.3.0.dev20200619
- Python version: v3.6.9
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A
- TPU: Google Colab runtime with TPU accelerator

**Describe the current behavior**
`tf.tpu.experimental.initialize_tpu_system(tpu_cluster_resolver)` raises an unexpected error. The stack trace containing this error is provided underneath. 

The sample notebook that was being used to train an `EfficientNetB0` model with `TPUStrategy` containing the error message is provided [here](https://colab.research.google.com/drive/1twKOkGxWO8NpYIE_SZ2qroVNEyGCxQrS?usp=sharing). 

**Describe the expected behavior**
A ResNet50 model (as EfficientNetB0 is only present in TF-nightly) with similar code is able to run successfully with TPUStrategy and there are no such errors reported while calling `tf.tpu.experimental.initialize_tpu_system`.  A notebook with the corresponding training code for TFv2.2 can be found [here](https://colab.research.google.com/drive/1BPsM3Gh1d6-nXY0urp0AFuSm2WKlYorv?usp=sharing).

**Standalone code to reproduce the issue**
Just calling `tf.tpu.experimental.initialize_tpu_system` using the standard mechanism on a Colab runtime with TPU should suffice.

```python
tpu_url = 'grpc://' + os.environ['COLAB_TPU_ADDR']
tpu_cluster_resolver = tf.distribute.cluster_resolver.TPUClusterResolver(tpu=tpu_url)

tf.config.experimental_connect_to_cluster(tpu_cluster_resolver)
tf.tpu.experimental.initialize_tpu_system(tpu_cluster_resolver)

strategy = tf.distribute.experimental.TPUStrategy(tpu_cluster_resolver)
```

**Other info / logs** 

```python
Running on TPU  ['10.57.138.26:8470']
INFO:tensorflow:Initializing the TPU system: grpc://10.57.138.26:8470

INFO:tensorflow:Initializing the TPU system: grpc://10.57.138.26:8470

INFO:tensorflow:Clearing out eager caches

INFO:tensorflow:Clearing out eager caches

---------------------------------------------------------------------------

InvalidArgumentError                      Traceback (most recent call last)

<ipython-input-4-a42f01f7e70e> in <module>()
      6 
      7 tf.config.experimental_connect_to_cluster(tpu)
----> 8 tf.tpu.experimental.initialize_tpu_system(tpu)
      9 tpu_strategy = tf.distribute.experimental.TPUStrategy(tpu)

3 frames

/usr/local/lib/python3.6/dist-packages/tensorflow/python/tpu/tpu_strategy_util.py in initialize_tpu_system(cluster_resolver)
    101     context.context()._clear_caches()  # pylint: disable=protected-access
    102 
--> 103     serialized_topology = output.numpy()
    104 
    105     # TODO(b/134094971): Remove this when lazy tensor copy in multi-device

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in numpy(self)
   1061     """
   1062     # TODO(slebedev): Consider avoiding a copy for non-CPU or remote tensors.
-> 1063     maybe_arr = self._numpy()  # pylint: disable=protected-access
   1064     return maybe_arr.copy() if isinstance(maybe_arr, np.ndarray) else maybe_arr
   1065 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in _numpy(self)
   1029       return self._numpy_internal()
   1030     except core._NotOkStatusException as e:  # pylint: disable=protected-access
-> 1031       six.raise_from(core._status_to_exception(e.code, e.message), None)  # pylint: disable=protected-access
   1032 
   1033   @property

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: NodeDef expected inputs 'string' do not match 0 inputs specified; Op<name=_Send; signature=tensor:T -> ; attr=T:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>; NodeDef: {{node _Send}}
```

Typically, this bug is prevalent only on nightly builds (master branch) and not on TF v2.2 release.

/cc: @tanzhenyu

**Comment by bjourne** [comment]
I have seen this issue on TF 2.2.0. I think there is something lingering on the TPU cores that `initialize_tpu_system` is unable to clear out.

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2 and i am not seeing any issue.However i am seeing this issue with nightly versions(`2.3.0-dev20200621').Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/f1c56122bf30a1bdadb7c72e7700e632/untitled54.ipynb).Thanks!

**Comment by swghosh** [comment]
Yes @ravikyram, thanks for acknowledging.

**Comment by rxsang** [comment]
It is due to a version mismatch between your client and TPU worker. Did you use nightly on both instances?

**Comment by swghosh** [comment]
Hi @rxsang, not sure if it's an error regarding the TPU version mismatch between the worker and the client. I had encountered the error on Colab. (Colab TPU runtimes do not provide for choice of versions for the TPU workers) I might need to try the same on Compute Engine Cloud TPUs for checking operability amongst different TPU worker versions.

AFAIK client and worker versions are interoperable as previously I had used TPU workers running TFv1.15 with TFv2.x, so I think.

Thanks.

**Comment by frankchn** [comment]
@swghosh Yeah, Colab always defaults to the latest stable version of TPUs because of technical limitations. The current version of Colab TPU that runs is version 2.2, so Colab TPUs are only supported with TensorFlow v2.2 by default.

In general, we only support TPUs when the same version is used on both the user TF and on the TPUs. In practice, there is some scope for different versions working together if there are no changes in terms of protocol or op definitions (e.g. no new ops, ops didn't change signature, etc...) but it is not supported.

**Comment by swghosh** [comment]
@frankchn Thanks for the clarification. Much help.

**Comment by feiwofeifeixiaowo** [comment]
> @swghosh Yeah, Colab always defaults to the latest stable version of TPUs because of technical limitations. The current version of Colab TPU that runs is version 2.2, so Colab TPUs are only supported with TensorFlow v2.2 by default.
> 
> In general, we only support TPUs when the same version is used on both the user TF and on the TPUs. In practice, there is some scope for different versions working together if there are no changes in terms of protocol or op definitions (e.g. no new ops, ops didn't change signature, etc...) but it is not supported.

@frankchn 
I found that tf 2.3 has been released, is there an update plan for the tf version on colab?

**Comment by frankchn** [comment]
The Colab roll out process lags the TensorFlow one by a few days, but it is being rolled out right now and TF 2.3 will be usable by the end of this week. When that happens, TF 2.2 will not be usable any more because of the same incompatibility between versions.

**Comment by feiwofeifeixiaowo** [comment]
Ok, thanks frank.

**Comment by feiwofeifeixiaowo** [comment]
still got following error with tf 2.3.0  tpu on colab.
```
tensorflow.python.framework.errors_impl.InternalError: RET_CHECK failure (learning/brain/google/xla/distributed_tpu_rewrite_pass.cc:1413) arg_shape.handle_type != DT_INVALID 
2020-08-06 01:47:30.383712: W ./tensorflow/core/distributed_runtime/eager/destroy_tensor_handle_node.h:57] Ignoring an error encountered when deleting remote tensors handles: Invalid argument: Unable to find the relevant tensor remote_handle: Op ID: 36311, Output num: 0
Additional GRPC error information from remote target /job:worker/replica:0/task:0:
:{"created":"@1596678450.383612323","description":"Error received from peer ipv4:10.81.58.138:8470","file":"external/com_github_grpc_grpc/src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Unable to find the relevant tensor remote_handle: Op ID: 36311, Output num: 0","grpc_status":3}
```
Please, find the [gist ](https://colab.research.google.com/gist/feiwofeifeixiaowo/a7ef19b4cb13517a18eec4c6786ac6e0/tpu-train-delf.ipynb#scrollTo=jmU5sTUR9Gxw)here.Thanks!

**Comment by rxsang** [comment]
From the trace, it seems you enabled tf summary inside TPU computation. Can you try calling `tf.config.set_soft_device_placement(True)` at the beginning, so outside compilation can be enabled?

**Comment by PeterCha90** [comment]
Now, it seems to initialize well with 2.3.0 and nightly with Colab. However, whenever I run gcloud ai-platform training scripts it always produce the same error whatever version of tf I use.. It is really frustrating. There is any single clue for solution anywhere even in Tensorflow official document.

**Comment by rxsang** [comment]
I'm not familiar with the `gcloud ai-platform` scripts, which TF and TPU version do that script use? @gagika Gigik, anyone from Cloud TPU team could help with that?

**Comment by gagika** [comment]
For choosing matching Tensorflow version on TPU in colab and kaggle you can use the code below (see [here](https://stackoverflow.com/questions/63180202/invalidargumenterror-while-initializing-ttpu/63271669#63271669))

```
!pip install cloud-tpu-client

import tensorflow as tf
from cloud_tpu_client import Client
print(tf.__version__)

Client().configure_tpu_version(tf.__version__, restart_type='ifNeeded')
```

For using training on TPUs on ai platform you can follow the steps [here](https://cloud.google.com/ai-platform/training/docs/using-tpus). At the moment AI supports TF versions `1.13, 1.14, 1.15, 2.1, and 2.2 `.

**Comment by Lawrence-Krukrubo** [comment]
> @swghosh Yeah, Colab always defaults to the latest stable version of TPUs because of technical limitations. The current version of Colab TPU that runs is version 2.2, so Colab TPUs are only supported with TensorFlow v2.2 by default.
> 
> In general, we only support TPUs when the same version is used on both the user TF and on the TPUs. In practice, there is some scope for different versions working together if there are no changes in terms of protocol or op definitions (e.g. no new ops, ops didn't change signature, etc...) but it is not supported.

You don't really understand how frustrating it's becoming using some Tensorflow packages. I practice on Colab and do more work in Kaggle. In Kaggle the line `from tensorflow.keras.preprocessing import image_dataset_from_directory` only works in tf==2.3, while it works in default 2.2 in Colab.

Also in Kaggle initiating TPU fails in tf 2.3, but works in 2.2.... It's just a bunch of annoying upgrades and downgrades and a real mess to fully enjoy tensorflow packages.

**Comment by gagika** [comment]
> > @swghosh Yeah, Colab always defaults to the latest stable version of TPUs because of technical limitations. The current version of Colab TPU that runs is version 2.2, so Colab TPUs are only supported with TensorFlow v2.2 by default.
> > In general, we only support TPUs when the same version is used on both the user TF and on the TPUs. In practice, there is some scope for different versions working together if there are no changes in terms of protocol or op definitions (e.g. no new ops, ops didn't change signature, etc...) but it is not supported.
> 
> You don't really understand how frustrating it's becoming using some Tensorflow packages. I practice on Colab and do more work in Kaggle. In Kaggle the line `from tensorflow.keras.preprocessing import image_dataset_from_directory` only works in tf==2.3, while it works in default 2.2 in Colab.
> 
> Also in Kaggle initiating TPU fails in tf 2.3, but works in 2.2.... It's just a bunch of annoying upgrades and downgrades and a real mess to fully enjoy tensorflow packages.

Right now Kaggle is using tf 2.3 and Colab tf 2.4, so the issue should be resolved on both.
Please let me know if it still there.

**Comment by gagika** [comment]
> Now, it seems to initialize well with 2.3.0 and nightly with Colab. However, whenever I run `gcloud ai-platform` training scripts, it always produces the same error whatever version of tf I use.. It is really frustrating. If it is all about the version mismatch, I can't find any single clue for solution anywhere.

`gcloud ai-platform` now [supports](https://cloud.google.com/ai-platform/training/docs/using-tpus#tpu-runtime-versions) TF 2.3, so the issue should be resolved.

**Comment by Lawrence-Krukrubo** [comment]
> > > @swghosh Yeah, Colab always defaults to the latest stable version of TPUs because of technical limitations. The current version of Colab TPU that runs is version 2.2, so Colab TPUs are only supported with TensorFlow v2.2 by default.
> > > In general, we only support TPUs when the same version is used on both the user TF and on the TPUs. In practice, there is some scope for different versions working together if there are no changes in terms of protocol or op definitions (e.g. no new ops, ops didn't change signature, etc...) but it is not supported.
> > 
> > 
> > You don't really understand how frustrating it's becoming using some Tensorflow packages. I practice on Colab and do more work in Kaggle. In Kaggle the line `from tensorflow.keras.preprocessing import image_dataset_from_directory` only works in tf==2.3, while it works in default 2.2 in Colab.
> > Also in Kaggle initiating TPU fails in tf 2.3, but works in 2.2.... It's just a bunch of annoying upgrades and downgrades and a real mess to fully enjoy tensorflow packages.
> 
> Right now Kaggle is using tf 2.3 and Colab tf 2.4, so the issue should be resolved on both.
> Please let me know if it still there.

Same trouble on Kaggle,

Can't install or upgrade to TensorFlow 2.4

See details
```
Installing tensorflow==2.4...
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
osmnx 0.15.1 requires geopandas>=0.7, but you have geopandas 0.6.3 which is incompatible.
kubernetes 10.1.0 requires pyyaml~=3.12, but you have pyyaml 5.3.1 which is incompatible.
kmeans-smote 0.1.2 requires imbalanced-learn<0.5,>=0.4.0, but you have imbalanced-learn 0.7.0 which is incompatible.
kmeans-smote 0.1.2 requires numpy<1.16,>=1.13, but you have numpy 1.19.5 which is incompatible.
kmeans-smote 0.1.2 requires scikit-learn<0.21,>=0.19.0, but you have scikit-learn 0.23.1 which is incompatible.
jupyterlab-git 0.10.0 requires nbdime<2.0.0,>=1.1.0, but you have nbdime 2.0.0 which is incompatible.
hypertools 0.6.2 requires scikit-learn<0.22,>=0.19.1, but you have scikit-learn 0.23.1 which is incompatible.
google-cloud-pubsub 1.4.3 requires google-api-core[grpc]<1.17.0,>=1.14.0, but you have google-api-core 1.17.0 which is incompatible.
bokeh 2.1.1 requires tornado>=5.1, but you have tornado 5.0.2 which is incompatible.
astroid 2.3.3 requires wrapt==1.11.*, but you have wrapt 1.12.1 which is incompatible.
```

**Comment by Lawrence-Krukrubo** [comment]
The entire version mismatches surrounding Tensorflow is absolutely
frustrating! Can't te very many Google Engineers synchronise versions and
modules all at once?



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
01/22/21,
01:01:55 PM

**Comment by eyildiz-ugoe** [comment]
> @swghoshThe current version of Colab TPU that runs is version 2.2, so Colab TPUs are only supported with TensorFlow v2.2 by default.

I've installed 2.2 and I still face the problem, it's super frustrating.

**Comment by MotiBaadror** [comment]
> not

Not working
