### ISSUE TITLE
Keras optional Input with default value

### ISSUE THREAD

**Issue by tanguycdls** [tensorflow/tensorflow#40997]
**System information**
- TensorFlow version (you are using): 2.3.rc0
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**
For one of my models i have multiple inputs with some of them only used at inference time and with a default value to 1 during training. 
To support that i currently create two models with the functional api, one with those optional inputs and one connected to a constant but it's quite complex to put in place. 

**Will this change the current api? How?**
We could add a new parameter to Input(default_value=) we would need to pass the shape and type as well and make sure the default matches the condition. 
It exists in Tensorflow here: https://www.tensorflow.org/api_docs/python/tf/compat/v1/placeholder_with_default

**Who will benefit with this feature?**
Users with models with a large number of inputs with some features not used during either inference or training.

**Any Other info.**

**Comment by ravikyram** [comment]
@tanguycdls 

Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

**Comment by tanguycdls** [comment]
> @tanguycdls
> 
> Do you have any use case that requires the feature you are interested in? Please feel free to submit a PR if you have use cases that supports that feature.Thanks!

Hi Thanks for your response. 
My use case is for an embedding with https://www.tensorflow.org/api_docs/python/tf/nn/safe_embedding_lookup_sparse that we implemented as a Keras layer taking a ragged input. 

During training all the weights are set to 1 so we dont even feed them to the function while at inference we want to control the weight of each contribution so we feed it also with a ragged of same shape (same len of len). 

```
class Embedd(tf.keras.layers.Embedding):
    def __init__(self, input_dim, output_dim, combiner='sum', **kwargs):
        self.output_dim = output_dim
        self.combiner = combiner
        super().__init__(input_dim, output_dim, **kwargs)

    def get_config(self):
        config = super().get_config()
        return {**config, 'combiner': self.combiner}

    def call(self, inputs):
        out = list(inp.to_sparse() for inp in inputs)
        if len(out) == 1:
          sparse_ids, weight = out[0], None
        else:
          sparse_ids, weight = out
        return tf.nn.safe_embedding_lookup_sparse(self.embeddings,
                                                  sparse_ids=sparse_ids,
                                                  sparse_weights=weight,
                                                  combiner=self.combiner)

    def build(self, inputs):
        super().build(inputs[0])

    def compute_output_shape(self, input_shape):
        batch_size = input_shape[0][0]
        return tf.TensorShape((batch_size, self.output_dim))
````

I would be happy to do a PR however i have no idea how i could do that without two distinct functional models!

**Comment by tongtong1990** [comment]
+1 to this feature request. This is a very important feature. It is common to see feature missing when we feed data to the model for both training and inference. We prefer setting the default value of a input tensor *inside* the model not outside, and now with Keras API we need to either setting up default value in our dataset parser, or use some very tricky workarounds such as always take in sparse inputs and convert to dense to set up default value.

**Comment by owenliang** [comment]
TF 1.x has this feature, it's very useful for end-to-end production.

**Comment by tanguycdls** [comment]
I found out about tf.OptionalSpec: https://www.tensorflow.org/api_docs/python/tf/OptionalSpec that could work for that usage. But I dont think it's currently compatible with Keras.

**Comment by BenoitLeguay** [comment]
Hello everyone, 
I'm still unable to set a default value to any layers in keras/ tensorflow. 
For production purpose, I find it more convenient to save these features' default value directly in the model. In this way, there is one source of truth during inference (that is defined when the model is built/ trained). 

Is this issue planned ?
Thank you and have a good day :)

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by BenoitLeguay** [comment]
Hey ! This issue is quite old but maybe it can help: 
here is a way to handle NaN value directly in a keras model:

```
class DefaultValueLayer(keras.layers.Layer):
    """
    Keras Layer subclass that applies a default value. It only works on float features
    """
    def __init__(self, default_value: float, name: str):
        super(DefaultValueLayer, self).__init__(name=name)
        self.default_value = default_value

    def call(self, inputs, *args, **kwargs):
        """
        Check if NaN are present and replace them with the default value

        :param inputs: input tensor
        :return: input tensor freed from NaN
        """

        return tf.where(
            condition=tf.math.is_nan(inputs),
            x=tf.multiply(
                tf.ones_like(inputs),
                self.default_value
            ),
            y=inputs,
            name=f"{self.name}_where"
        )
```
