### ISSUE TITLE
Debug .dll build with CUDA support on Windows fails to link

### ISSUE THREAD

**Issue by MikhailStartsev** [tensorflow/tensorflow#41118]
**System information**
- OS Platform and Distribution: Windows 10 Enterprise 1809
- TensorFlow installed from: source
- TensorFlow version: v2.2.0
- Python version: 3.5.6
- Bazel version (if compiling from source): 2.0.0
- Compiler version (if compiling from source): MSVC 14.26.28801
- CUDA/cuDNN version: CUDA 10.1 / cuDNN 7.6.5.32
- GPU model and memory: NVIDIA Titan Xp

After [some issues](https://github.com/tensorflow/tensorflow/issues/39905), a "default" build for the Tensorflow dll on my finally machine succeeded (i.e. with a command not unlike `bazel build --jobs=8 --define=no_tensorflow_py_deps=true -c opt //tensorflow:tensorflow.dll`).

Now I tried to build the same dll in debug mode: `bazel build --jobs=8 --define=no_tensorflow_py_deps=true` **-c opt -c dbg** `--config=c++17 //tensorflow:tensorflow.dll`.

This causes several issues, which are at least somewhat solvable, thought probably still not great:

1. Errors of the kind "error C4716: 'xla::HloInstruction::unique_indices': must return a value" -> solved by adding `--copt=/wd4716` to build:windows in .bazelrc
2. It cannot compile with multiple jobs (get multiple - as many as --jobs - error windows with messages like "Debug errror! Program ...\x64_windows-dbg\bin\external\llvm-project\llvm-tblgen: abort() has been called", and messages in the terminal like "Assertion failed: !Ptr && !DeleterFn && !Next && "Partially initialized ManagedStatic!?", file external/llvm-project/llvm/lib/Support/ManagedStatic.cpp, line 51". 

The latter actually does not go away once it shows up - i.e. a repeat of the build command (with 1 or multiple jobs, does not matter) does not go any further, but adding `--define=with_xla_support=false` to the build command helped (I used to add it before because of the issue 1 above, then found out that that problem is not just inside xla::* but also arises for some other code in the repo, and found another workaround there). ~~Not sure if xla is to blame here, maybe adding the flag just triggered some re-do in the build chain...~~  **UPDATE:** without the  `--define=with_xla_support=false` option, this appears on a clean one-job build as well.

3. Another issue of the similar kind: Getting errors like "'C:\users\mikhail.startsev\_bazel_mikhail.startsev\3watukzj\execroot\org_tensorflow\vc140.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS"" -> adding `--copt=/FS` **does not help**, no idea why, still had to run with `--jobs=1` to make it work.

And _after all that_, it fails to link with **a lot** of undefined externals and a ton warnings to boot. I attach a full subcommand log (with `-s --verbose_failures`): [link_log.txt](https://github.com/tensorflow/tensorflow/files/4877528/link_log.txt)

Examples of unresolved symbols:

- void __cdecl **tensorflow::ConcatGPU**<unsigned __int64>(class tensorflow::OpKernelContext *,class std::vector<class std::unique_ptr<class Eigen::TensorMap<class Eigen::Tensor<unsigned __int64 const ,2,1,__int64>,16,struct Eigen::MakePointer>,struct std::default_delete<class Eigen::TensorMap<class Eigen::Tensor<unsigned __int64 const ,2,1,__int64>,16,struct Eigen::MakePointer> > >,class std::allocator<class std::unique_ptr<class Eigen::TensorMap<class Eigen::Tensor<unsigned __int64 const ,2,1,__int64>,16,struct Eigen::MakePointer>,struct std::default_delete<class Eigen::TensorMap<class Eigen::Tensor<unsigned __int64 const ,2,1,__int64>,16,struct Eigen::MakePointer> > > > > const &,class tensorflow::Tensor *,class Eigen::TensorMap<class Eigen::Tensor<unsigned __int64,2,1,__int64>,16,struct Eigen::MakePointer> *)
- public: void __cdecl **tensorflow::functor::SpaceToDepthOpFunctor**<struct Eigen::GpuDevice,bool,1>::operator()(struct Eigen::GpuDevice const &,class Eigen::TensorMap<class Eigen::Tensor<bool const ,4,1,__int64>,16,struct Eigen::MakePointer>,int,class Eigen::TensorMap<class Eigen::Tensor<bool,4,1,__int64>,16,struct Eigen::MakePointer>)" (??R?$SpaceToDepthOpFunctor@UGpuDevice@Eigen@@_N$00@functor@tensorflow@@QEAAXAEBUGpuDevice@Eigen@@V?$TensorMap@V?$Tensor@$$CB_N$03$00_J@Eigen@@$0BA@UMakePointer@2@@4@HV?$TensorMap@V?$Tensor@_N$03$00_J@Eigen@@$0BA@UMakePointer@2@@4@@Z) referenced in function "public: virtual void __cdecl tensorflow::SpaceToDepthOp<struct Eigen::ThreadPoolDevice,bool>::Compute(class tensorflow::OpKernelContext *)
- public: void __cdecl **tensorflow::functor::DenseUpdate**<struct Eigen::GpuDevice,class tensorflow::Variant,2>::operator()(struct Eigen::GpuDevice const &,class Eigen::TensorMap<class Eigen::Tensor<class tensorflow::Variant,1,1,__int64>,16,struct Eigen::MakePointer>,class Eigen::TensorMap<class Eigen::Tensor<class tensorflow::Variant const ,1,1,__int64>,16,struct Eigen::MakePointer>)

Warnings seem to be of 2 kinds:

1. libdebug_ops_gpu.lo(debug_ops_gpu.cu.o) : **warning LNK4099: PDB 'vc140.pdb' was not found** with 'libdebug_ops_gpu.lo(debug_ops_gpu.cu.o)' or at 'C:\users\mikhail.startsev\_bazel_mikhail.startsev\3watukzj\execroot\org_tensorflow\bazel-out\x64_windows-dbg\bin\tensorflow\vc140.pdb'; linking object as if no debug info
2. LINK : warning LNK4286: symbol '??0Status@tensorflow@@QEAA@W4Code@error@1@Vstring_view@absl@@@Z (public: __cdecl tensorflow::Status::Status(enum tensorflow::error::Code,class absl::string_view))' defined in 'libstatus.a(status.o)' is imported by 'libenv.a(env.o)'

There are plenty of both to go around...

Will try to building from scratch with 1 job from the very beginning, thought that might take a while. 

Any help is appreciated :)

**Comment by MikhailStartsev** [comment]
Finished the run of the following: `bazel --output_user_root=D:\SMV\build build -s --verbose_failures --jobs=1 --define=no_tensorflow_py_deps=true -c opt -c dbg --define=with_xla_support=false //tensorflow:tensorflow.dll`, see attched log: [link_log_2.txt](https://github.com/tensorflow/tensorflow/files/4883436/link_log_2.txt). The warning and error types look the same to me...

**Comment by gunan** [comment]
I do not think we have ever successfully built a debug binary for TF on windows.
I can take a look at the linker failures, but I cannot promise a result, as I tried to do this a while ago, and miserably failed myself.

**Comment by MikhailStartsev** [comment]
@gunan Thanks to taking a look! But without a debug build, how does one build the standalone app in debug mode? I tried just using the non-debug .dll and .lib files, and got the weirdest runtime errors about heap corruption when vectors of TF-related objects go out of scope (i.e. in the vector<tensorflow::something>::~vector<tensorflow::something>call). Is this a sort of known side-effect, or should I reproduce it again and make a new issue about _that_?

**Comment by MikhailStartsev** [comment]
@gunan Okay, the linking problem is narrowing down. (1) If I build a no-CUDA-support dll, only the errors related to ensorflow::functor::SpaceToDepthOpFunctor and ensorflow::functor::DepthToSpaceOpFunctor remain, so that's something. 
(2) I think I pinpointed where this comes from, but not sure, whether this is something that is on a logical level "wrong".  I am right now talking about just 4 files in tensorflow/core/kernels: [depthtospace_op.h](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/core/kernels/depthtospace_op.h), [depthtospace_op.cc](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/core/kernels/depthtospace_op.cc), [spacetodepth_op.h](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/core/kernels/spacetodepth_op.h), and [spacetodepth_op.cc](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/core/kernels/spacetodepth_op.cc).

While compiling a **CPU** version of tensorflow.dll, all of the undefined external symbols are `SpaceToDepthOpFunctor` or `DepthToSpaceOpFunctor` templated with the first argument of `Eigen::GpuDevice`, because the `SpaceToDepthOp` class (note, no `Functor` at the end), even if with the first template argument of `Eigen::ThreadPoolDevice`, which is the typedef for **`CPU`**`Device`, manages to require a GPUDevice in the arguments of `SpaceToDepthOpFunctor` that it uses externally. 

More specifically, I am talking about lines [115-130](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/core/kernels/depthtospace_op.cc#L115) in depthtospace_op.cc and lines [129-149](https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/core/kernels/spacetodepth_op.cc#L129) in spacetodepth_op.cc.

Even though `if (std::is_same<Device, GPUDevice>::value)` would not actually evaluate to true for any _actaully_ instantiated `DepthToSpaceOp` class template parametrization (for all the missing symbols, they are parameterized with  `Eigen::ThreadPoolDevice`), this `if` **is not a compile-time operation**, so the class _technically_ requires the GPUDevice-template-parametrized functors! If I comment out the code that would not be executed anyway, the linking of the dll step does not crash with the errors that these symbols are not found, at least not yet (it used to stop after about 10 minutes, has been running for about 7 hours now....)

....which is actually a question in its own right... Should it take quite so long? I think this is actually all due to collecting the right .pdb file. I think at some point I tried to pass /DEBUG:NONE to linker for the .dll linking step, and just toss in _some_ tensorflow.pdf while it was compiling to make sure bazel's alarms don't go off in the expectation of the .pdb, and the step then completed successfully much quicker. I will give it a night to keep linking, in case it is actually doing something useful, and then try this trick again tomorrow morning...

Regarding the linking issue causes themselves, this seems to be like something solvable by partial template specialization for the CPUDevice?...

**Comment by MikhailStartsev** [comment]
Update #2: (1) I might have been wrong about the non-compile-time nature of std::is_same, but at least inside of that `if` it is definitely seems like it will end up as `if(true)` or `if(false)` for each instantiated class, with the code of the `if` still being linked and compiled. This actually would explain the debug/release difference: in release this `if(false)` body would be optimized away.

I made a hopefully generic fix for the issue by specializing the class for the GPUDevice type (the only case where the "infamous" if would be actually evaluated), where only the appropriate code is kept. The generic class template definition is then left with all the original code but without the `if` block that would be evaluated to `if(false)` in the non-specialized case anyway. I managed to build the .dll (thought with a sleight of hand to circumvent the uber-lengthy creation of the tensorflow.pdb) in the end! and so far only for the no-CUDA case. 

I will first test (1) the integration of the dll with other code and (2) release build with CUDA, then probably submit a merge request, if it all works. CUDA-enabled debug dll will likely still be a problem (I got other linking errors with it, too), but we'll see.

**Comment by amahendrakar** [comment]
@MikhailStartsev,
Any updates regarding this issue? Please feel free to close the issue if resolved. Thanks!

**Comment by MikhailStartsev** [comment]
@amahendrakar The merge request that was merged did not solve the issue (that is, it solved one linker issue but caused another similar one). I [mentioned](https://github.com/tensorflow/tensorflow/pull/42307#issuecomment-673954495) this in the merge thread before it was accepted, but it still got approved... 

The initially proposed solution (i.e. up to commit 287d074, this being the main change diff: https://github.com/tensorflow/tensorflow/pull/42307/commits/132e8af2e90446a6f856b9ac3d793611517a5d36) links when building without CUDA, but it involved code duplication, which I'm not very sure how to get around here: One function of a templated class needs to be specialized for the GPUDevice as its template parameter; the rest of the functions can stay exactly the same. My initial solution specialized the whole class while duplicating the code for the unchanged functions.

**Comment by amahendrakar** [comment]
> I was planning to take a look whether I can link the dll for the CUDA-case as well within the next couple of weeks, and thought of making the code less duplicating at the same time.

@MikhailStartsev,
Any updates? Did you get a chance to work on this? Thanks!

**Comment by MikhailStartsev** [comment]
@amahendrakar Thank you for following up on this, but unfortunately other issues took priority, as the absence of a CUDA-enabled debug DLL turned out not to be as critical, and building just a TF DLL in debug mode was resolved by my initial proposed change.

In this light, I propose to wrap up this thread by integrating the changes that make the DLL link under Windows _without_ CUDA, and if I ever come manage to build a CUDA-enabled version, I will submit a pull request to this thread later.

To this end, could I ask you or someone else to take a look at the initially proposed changes that _do_ work - the main changes seen in this commit: https://github.com/tensorflow/tensorflow/commit/132e8af2e90446a6f856b9ac3d793611517a5d36 - and suggest a specific way around code duplication, which was the main point of the [pull request discussion](https://github.com/tensorflow/tensorflow/pull/42307#discussion_r470412920)), which would be acceptable for you? I am not that deep into the TF codebase, just saw the problem that can be solved, but am not sure what refactoring would be most appropriate here. In the pull request discussion @sanjoy suggested, as far as I remember now, taking all but the operator() out of the struct, but I am not sure what else would need to be changed in this case...

**Comment by SuryanarayanaY** [comment]
Hello @MikhailStartsev ,

Starting from Tf2.10 CUDA builds on Windows not officially supported. You need to install WSL2 to enable CUDA support.
Please refer official documentation [source](https://www.tensorflow.org/install/source_windows#install_gpu_support_optional) for same.

You can test it on wsl2 now with any latest TF version and let us know if still have problem. Thanks!
