### ISSUE TITLE
tf.keras cannot weight classes when using multiple outputs

### ISSUE THREAD

**Issue by maxpv** [tensorflow/tensorflow#41448]
This post is a mirror of https://github.com/keras-team/keras/issues/11735, showing the need to handle class weight for multiple outputs.

Version 2.2.0 used.

------
 
This is a minimal source code, by @GalAvineri, to reproduce the issue (please comment/uncomment the class weight line):

````python3
from tensorflow.python.keras.models import Model
from tensorflow.python.keras.layers import Input, Dense
from tensorflow.python.data import Dataset
import tensorflow as tf
import numpy as np


def preprocess_sample(features, labels):
    label1, label2 = labels
    label1 = tf.one_hot(label1, 2)
    label2 = tf.one_hot(label2, 3)
    return features, (label1, label2)


batch_size = 32

num_samples = 1000
num_features = 10

features = np.random.rand(num_samples, num_features)
labels1 = np.random.randint(2, size=num_samples)
labels2 = np.random.randint(3, size=num_samples)

train = Dataset.from_tensor_slices((features, (labels1, labels2))).map(preprocess_sample).batch(batch_size).repeat()

# Model
inputs = Input(shape=(num_features, ))
output1 = Dense(2, activation='softmax', name='output1')(inputs)
output2 = Dense(3, activation='softmax', name='output2')(inputs)
model = Model(inputs, [output1, output2])

model.compile(loss='categorical_crossentropy', optimizer='adam')
class_weights = {'output1': {0: 1, 1: 10}, 'output2': {0: 5, 1: 1, 2: 10}}
model.fit(train, epochs=10, steps_per_epoch=num_samples // batch_size,
         #  class_weight=class_weights
          )
````

Uncommenting yields this error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-38-d137ff6fb3f9> in <module>
     33 class_weights = {'output1': {0: 1, 1: 10}, 'output2': {0: 5, 1: 1, 2: 10}}
     34 model.fit(train, epochs=10, steps_per_epoch=num_samples // batch_size,
---> 35            class_weight=class_weights
     36           )

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67 
     68     # Running inside `run_distribute_coordinator` already.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    813           workers=workers,
    814           use_multiprocessing=use_multiprocessing,
--> 815           model=self)
    816 
    817       # Container that configures and calls `tf.keras.Callback`s.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in __init__(self, x, y, sample_weight, batch_size, steps_per_epoch, initial_epoch, epochs, shuffle, class_weight, max_queue_size, workers, use_multiprocessing, model)
   1115     dataset = self._adapter.get_dataset()
   1116     if class_weight:
-> 1117       dataset = dataset.map(_make_class_weight_map_fn(class_weight))
   1118     self._inferred_steps = self._infer_steps(steps_per_epoch, dataset)
   1119     self._dataset = strategy.experimental_distribute_dataset(dataset)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py in _make_class_weight_map_fn(class_weight)
   1233         "Expected `class_weight` to be a dict with keys from 0 to one less "
   1234         "than the number of classes, found {}").format(class_weight)
-> 1235     raise ValueError(error_msg)
   1236 
   1237   class_weight_tensor = ops.convert_to_tensor_v2(

ValueError: Expected `class_weight` to be a dict with keys from 0 to one less than the number of classes, found {'output1': {0: 1, 1: 10}, 'output2': {0: 5, 1: 1, 2: 10}}
````

**Comment by ravikyram** [comment]
I am able to reproduce the issue in colab with TF versions 2.2,2.3-rc1,nightly version(`2.4.0-dev20200716`), when we uncomment the class weight line.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/fd621368c2e4ef185093d3dc1a1ced58/untitled.ipynb).Thanks!

**Comment by rambleRamblePie** [comment]
Has anyone found a solution to this issue?

**Comment by kevinashaw** [comment]
Class weights with multiple outputs is important to us.  Any updates?

**Comment by keunwoochoi** [comment]
+1 this is important!

**Comment by rarazac** [comment]
Also stuck with this issue, any updates?

**Comment by MareSeestern** [comment]
Any progress? +1

**Comment by ericvoots** [comment]
checking in on this as well

**Comment by niki-j** [comment]
Working with TF 2.4.1, same issue. Any resolution?

**Comment by celhannah** [comment]
Any progress?

**Comment by vcucu** [comment]
Still interested in an update on this!

**Comment by sushreebarsa** [comment]
I tried this using TF 2.5 version ,please check the gist [here](https://colab.research.google.com/gist/sushreebarsa/ff1c4e1eb2a33cbdc05c9601d130ba7d/untitled112.ipynb?authuser=1)..Thanks !

**Comment by vcucu** [comment]
I ended up solving this with a custom loss function that weights the classes the way I need. Still would appreciate having this built within Keras!

**Comment by sushreebarsa** [comment]
Closing this issue as it is fixed in latest version of TensorFlow. Please feel free to reopen the issue if you still have a concern. Thanks!

**Comment by michaeldietz** [comment]
> 
> 
> Closing this issue as it is fixed in latest version of TensorFlow. Please feel free to reopen the issue if you still have a concern. Thanks!

In which version is this fixed? I'm using TF 2.5.0 and the issue is still present there.

**Comment by nibydlo** [comment]
Same problem,  TF 2.5.0

Expected `class_weight` to be a dict with keys from 0 to one less than the number of classes, found {'output_1': ...}

**Comment by LanderMoerkerke** [comment]
Any progress on this issue?

**Comment by kevinashaw** [comment]
@sushreebarsa Can we get an update?  I note that you closed this issue stating that "it is fixed in latest version of TensorFlow".  However, others have noted no improvement in TF2.5. 
We are doing training with imbalanced classes and have a strong need for this.
Can we get an update?  Thanks!

**Comment by sushreebarsa** [comment]
@maxpv  @kevinashaw  Sorry for the late response! This issue is not fixed in TF v2.5 .I tried to run the code on tf-nightly 2.7.0-dev20210810 and was able to replicate the issue as reported .Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/592aba2b176d84464536ae8e3ba313b6/untitled373.ipynb#scrollTo=pd8xz8hOEszk) for reference . Could you please have a look at the [link1](https://www.tensorflow.org/tutorials/structured_data/imbalanced_data) , [link2](https://github.com/keras-team/keras/issues/11735) , [link3](https://datascience.stackexchange.com/questions/41698/how-to-apply-class-weight-to-a-multi-output-model) and let us know if it helps? Thank you!

**Comment by kevinashaw** [comment]
Apparently Keras thinks this issue is fixed: https://keras.io/examples/structured_data/imbalanced_classification/

**Comment by kevinashaw** [comment]
@sushreebarsa Was this issue closed on purpose?

**Comment by vikranth94** [comment]
Wish this issue will be resolved soon. Shouldn't it be an easy fix since it worked in version 2.1.0?

**Comment by NoBetterThanNoise** [comment]
> Apparently Keras thinks this issue is fixed: https://keras.io/examples/structured_data/imbalanced_classification/

this example uses a single output. the problem happens when using multiple output models in keras. i believe the issue is still ongoing

**Comment by mtorabirad** [comment]
I wonder if this has to do something with what is mentioned here https://www.tensorflow.org/api_docs/python/tf/keras/Model

"If the model has multiple outputs, you can use a different loss on each output by passing a dictionary or a list of losses. The loss value that will be minimized by the model will then be the sum of all individual losses, unless loss_weights is specified."

**Comment by OpenWaygate** [comment]
Refer to this [guide](https://www.tensorflow.org/guide/keras/train_and_evaluate#passing_data_to_multi-input_multi-output_models), there are 3 weights: `class_weight`, `sample_weight`, `loss_weight`.

I can set `loss_weight` in `model.compile` to weight more in **hard task**, but I also want use `class_weight` to weight more in **rare labels** in **both task**.

Especially when generate data, how to set `sample_weight`? A list or dictionary?

```python
import tensorflow.data.Dataset as tfds

calss_weight = {
  "hard_task": {0: 1, 1: 2, 2: 3, 3: 4, 4: 5},
  "easy_task": {0: 1, 1: 2, 2: 3}}

def gen_date(df):
  def gen():
    for _, row in df.iterrows():
      x = row["feature"]
      y = {
        "hard_task": row["y1"],
        "easy_task": row["y2"]}
      # list or dict?
      sample_weight1 = [calss_weight["hard_task"][df["y1"]], calss_weight["easy_task"][df["y2"]]]
      sample_weight2 = {
        "hard_task": calss_weight["hard_task"][df["y1"]],
        "easy_task": calss_weight["easy_task"][df["y2"]]}
      yield x, y, sample_weight
  return gen

dataset_train = tfds.from_generator(gen_data(df_train), output_signature).batch(256).prefetch(1)
dataset_valid = tfds.from_generator(gen_data(df_valid), output_signature).batch(256).prefetch(1)

loss = {
  "hard_task": CategoricalCrossentropy(from_logits=True),
  "easy_task": CategoricalCrossentropy(from_logits=True)}
metric = {
  "hard_task": CategoricalAccuracy("accuracy"),
  "easy_task": CategoricalAccuracy("accuracy")}

model.compile(
    optimizer=Adam(),
    loss=loss,
    metrics=metric,
    loss_weights={"hard_task": 2, "easy_task": 1})

model.fit(
    dataset_train,
    validation_data=dataset_valid,
    calss_weight=calss_weight)
```

**Comment by abdulbasitds** [comment]
Has anyone got solution to this issue?

**Comment by Drlilou** [comment]
any updates?

**Comment by pstrybol** [comment]
Progress updates?

**Comment by kstamatiou** [comment]
Any updates on this? Thanks!

**Comment by pltnk** [comment]
The issue is still present in TF 2.8.0.

**Comment by abdulbasit312** [comment]
Hi is there any update on this issue, seems to be around since the past 3 years and no fix yet! Would really appreciate if you could solve this soon.

**Comment by iamkashish** [comment]
> I ended up solving this with a custom loss function that weights the classes the way I need. Still would appreciate having this built within Keras!

Hey Veronica,
Can you share your code on the custom loss function to handle 3+ class weights ?
It will help others.

**Comment by gaganmalhotra** [comment]
Seems like a lot of people are waiting for resolution here, is there a way to upvote in github?

**Comment by pati-dev** [comment]
It has been over 2 years (w00t?!) since this issue was open, and sadly it's still unresolved. Can the team please provide any update on this?

P.S.: Have other folks found any reasonable solution to this as the team doesn't really seem to care about fixing this one anytime soon.

**Comment by Sougata10** [comment]
Any solution to this problem?

**Comment by pati-dev** [comment]
Since the TF doesn't care _enough_ about providing a solution to this, the least I can do is share the workaround that I used. Assuming that you have 4 classes that you want to train your model on, discretionary devs can use the below snippet that might help them:

```py
def weighted_loss(weights):
    def compute_loss(y_true, y_pred):
        true_idx = tf.cast(tf.argmax(y_true, axis=2), dtype=tf.int32)

        table = tf.lookup.StaticHashTable(
            initializer=tf.lookup.KeyValueTensorInitializer(
                keys=tf.constant([0, 1, 2, 3]),
                values=weights
            ), default_value=1.)

        weight_sample_class = table.lookup(true_idx)
        cce = tf.keras.losses.CategoricalCrossentropy()
        loss = cce(y_pred, y_true, sample_weight=weight_sample_class)
        return loss
    return compute_loss
```

**Comment by marlon-shiftone** [comment]
It is a scandal that there is no solution to this problem yet.

**Comment by Sougata10** [comment]
Can you show how to implement the loss function in the code? I am stuck in
an image segmentation problem.

**Comment by marlon-shiftone** [comment]
@Sougata10, this way:

`model.compile(optimizer=opt, loss=WeightedSCCE(class_weight), metrics=['sparse_categorical_accuracy'])`

`class_weight`must be a list of floats.

**Comment by marygracemoesta** [comment]
@marlon-shiftone in the case of multi-task learning (with binary outputs) would we just instantiate an instance for each output task, i.e.:
```model.compile(
optimizer = opt,           
            loss = {task1_loss: WeightedSCCE(task_1_class_weights), 
                                 task2_loss: WeightedSCCE(task_1_class_weights),
                                  ...
                                },
             metrics = ["sparse_categorical_accuracy']
)
```

**Comment by SuryanarayanaY** [comment]
I have replicated the issue with versions 2.10V and nightly and attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/2c7e6b3d708025f2333fa1169bd2680d/41448.ipynb#scrollTo=cELeqD7ZcRYL) here.
To add more to the context i have refereed keras code and i observed the below line there.Please refer source from [keras](https://github.com/keras-team/keras/blob/902bd2ab98d32ef33c60ec9d5eab1e2383bc193f/keras/engine/data_adapter.py#L1615).

`" 'class_weight' is only supported for Models with a single output."`

Same also reflecting in TensorFlow code also.Please refer [TF source](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/engine/data_adapter.py#L1428).

Referring to above I feel that this is not a bug but might be a Potential Feature Request.

Requesting all to provide their thoughts and valuable inputs.

Thankyou!

**Comment by ma7555** [comment]
Will this be implemented?

**Comment by sakthi-geek** [comment]
Any updates on supporting class weights for multi_ouput?

**Comment by hlreicha** [comment]
I am having the same issue in TensorFlow 2.6.5. I am sure they will fix it any year now.

**Comment by NicoCoallier** [comment]
Likewise

**Comment by Pengling2022** [comment]
When it can be resolved?

**Comment by frytoli** [comment]
Bumping this. Any plans for an update? Thanks!

**Comment by fyangwang** [comment]
Still an issue in 2.16. Do the team has plan about it?

**Comment by EEvangelisti** [comment]
Any update on this?

**Comment by chriscarollo** [comment]
Any update on this?  It's literally been years, and this used to work.
