### ISSUE TITLE
Can not load workspace.bzl

### ISSUE THREAD

**Issue by rizar** [tensorflow/tensorflow#4216]
I have a project that I want to build with Bazel, which includes Python code and C++ files. I am trying to use the same approach as in [Syntaxnet](https://github.com/tensorflow/models/tree/master/syntaxnet) from the model zoo. I add `tensorflow` as a submodule to my repository and put the following snippet to my `WORKSPACE` file:

```
local_repository(
  name = "org_tensorflow",
  path = __workspace_dir__ + "/tensorflow",
)

load('//tensorflow/tensorflow:workspace.bzl', 'tf_workspace')
tf_workspace("tensorflow/", "@org_tensorflow")
```

which results in an error

```
ERROR: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '': Extension file not found. Unable to load package for '//third_party/gpus:cuda_configure.bzl': BUILD file not found on package path.
```

The source of the error is clear to me: [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L3) contains a `load` call with a hard-coded path. SyntaxNet uses an older version of Tensorflow that does not contain this line. 

My question is if this is a bug or not. Is this a recommended way of organizing the project that should be compiled with Tensorflow, and if not, should it be used in Syntaxnet model? Or should I just copy the `WORKSPACE` from Tensorflow's root directory?

**Comment by rizar** [comment]
In addition, I highly suspect that https://github.com/tensorflow/serving is incompatible with the latest Tensorflow for the same reason, see [this line](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/workspace.bzl#L4)

**Comment by tatatodd** [comment]
@martinwicke might be able to shed some light on whether this is a bug or not.

**Comment by martinwicke** [comment]
These dependent files need to be upgraded to work with TensorFlow at head. @calberti @kirilg you should update the files. I don't think this should be fixed in tensorflow/tensorflow but we'll see.

@damienmg what is the proper way to use TensorFlow as a dependency in a workspace now?

**Comment by damienmg** [comment]
This is the correct way (although the two parameters of tf_worskpace are going away) Unfortuntately, https://github.com/tensorflow/tensorflow/pull/4055 got rolled-back because of an internal breakage. I've rolled it forward as cl/131951691 but it does seems to have hit the github repository yet.

**Comment by martinwicke** [comment]
I do see your changes to workspace.bzl and the empty //BUILD file though. I
think it is in then.

**Comment by damienmg** [comment]
Oh good let me try then.

**Comment by damienmg** [comment]
Ok I still have a bug on my side.  I will investigate tomorrow and update https://github.com/tensorflow/serving/pull/166 as it goes.

**Comment by johndpope** [comment]
@rizar did you ever progress this?

**Comment by johndpope** [comment]
I got it working with some help on this ticket 
https://github.com/dsindex/syntaxnet/issues/10


You can try this build script https://gist.github.com/johndpope/fc1c2327a4ae255d9c44dda9b67b5288
(just remove the first line  cd / if you're not running on docker)

the difference being a git checkout commit

# checkout proper version of serving
git checkout 89e9dfbea055027bc31878ee8da66b54a701a746
git submodule update --init --recursive

**Comment by gunan** [comment]
Looks like the issue was resolved in the end.
Closing.
