### ISSUE TITLE
Tensorflow 2.3.0 is much slower than PyTorch 1.4.0 in backward propagation. (20 times slower)

### ISSUE THREAD

**Issue by TAIYISONG** [tensorflow/tensorflow#42475]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
   Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   Win10
- CUDA/cuDNN version: 
   CUDA 10.1/cuDNN 7
- TensorFlow version (use command below): 
   2.3.0
- Python version: 
   3.7.4
- GPU model and memory: 
   Geforce GTX 1660Ti (6GB)

**Describe the current behavior**

- I tried to use both TF2 and PyTorch to train SkipGram model with negative sampling. But notice a huge training speed difference. 
- TF2 takes ~0.5s to finish one step while PyTorch takes ~0.01s. One step refers to use 1 batch data to do forward and backward and update the weights. 
- The main difference is in backward propagation. 
- **More specifically, 'apply_gradients()' in TF2 is much slower than counterpart 'step()' in PyTorch. Does anyone know why?**

- Notes:
1. Both versions use GPU.
2. tf.function is used.
3. Training batch size and data is exactly the same.
4. Model size (vocab_size, emb_size) is the same.

- TF2:

```
@tf.function
def train_step_tf(pos_w, pos_v, neg_v):
    print('-'*50)
    with tf.GradientTape() as tape:  
        loss = skip_gram_model_tf(pos_w, pos_v, neg_v)
    
    start_time = time.time()
    variables = skip_gram_model_tf.trainable_variables
    print('getting variables time = {}'.format(time.time() - start_time))

    start_time = time.time()
    gradients = tape.gradient(loss, variables)
    print('init gradient time = {}'.format(time.time() - start_time))

    start_time = time.time()
    optimizer.apply_gradients(zip(gradients, variables))  # !!!!! this is where the major speed difference happens!!!!!
    print('apply gradient time = {}'.format(time.time() - start_time))
    
    print('-'*50)

    return loss
```

- PyTorch:

```
def train_step_torch(pos_w, pos_v, neg_v):  
    print('-'*50)
    start_time = time.time()
    optimizer_torch.zero_grad()
    loss = skip_gram_model_torch.forward(pos_w, pos_v, neg_v)
    print('getting variables time = {}'.format(time.time() - start_time))

    start_time = time.time()
    loss.backward()
    print('init gradient time = {}'.format(time.time() - start_time))
    
    start_time = time.time()
    optimizer_torch.step() # !!!!this is fast!!!!
    print('apply gradient time = {}'.format(time.time() - start_time))
    print('-'*50)

    return loss
```

**Describe the expected behavior**
I expect the performance shouldn't be that different. Is there anything I miss to use in TF2?

**Standalone code to reproduce the issue**
Colab link of full code:
https://colab.research.google.com/drive/17QsTkV271LPvo6aJf1QOGuumdU8OXmVj?usp=sharing

**Comment by WindQAQ** [comment]
Hi @TAIYISONG , I make some changes and see the speed is the same. Please ignore the first step because tensorflow allocates optimizer's variable slots in this step.

1. You use adam for tf and sgd for pytorch: adam is much more time-consuming than sgd.
2. remove `tf.function` decorator: I'm not sure why removing this is faster.

https://colab.research.google.com/drive/1a__vqNBplMV8SvQpjfTlACFJsjwqsFn3?usp=sharing

**Comment by TAIYISONG** [comment]
> Hi @TAIYISONG , I make some changes and see the speed is the same. Please ignore the first step because tensorflow allocates optimizer's variable slots in this step.
> 
> 1. You use adam for tf and sgd for pytorch: adam is much more time-consuming than sgd.
> 2. remove `tf.function` decorator: I'm not sure why removing this is faster.
> 
> https://colab.research.google.com/drive/1a__vqNBplMV8SvQpjfTlACFJsjwqsFn3?usp=sharing

Hi @WindQAQ , thanks for helping me out! (What is the 'first step' you are referring to?)

Your suggestion works. **But** I test out some scenarios on my own machine (1660Ti) following your idea: 
  
  1. **TF-SGD-without@tf.function** takes 0.009s.
  2. **Torch-SGD** takes 0.009s.
  3. **TF-SGD-with@tf.function** takes 0.09s
   (same as in @WindQAQ notebook and findings)
  4. **TF-Adam-without@tf.function** takes 0.9s
  5. **TF-Adam-with@tf.function** takes 0.5s
  6. **Torch-Adam** takes 0.03s

and **find**:
  A. Compare (1 vs 3) and (4 vs 5); 
      **Why @tf.function works to accelerate Adam, but not SGD (even 10 times slower)?**
  B. Compare (5 vs 6);
      **Why TF is ~20 times slower than PyTorch in terms of using Adam?** (original question)
  C. Compare (1 vs 4):
      **Different optimizer and tf.function usage can make 100 times training speed difference?!**
  D. Compare (2 vs 6):
      **PyTorch is more stable in terms of switching optimizer. (yes Adam is much more time-consuming than SGD.)**    

What is the black magic behind the scene? 
It's kind of awkward if TF is much less stable than PyTorch in terms of switching and testing different optimizer.

**Comment by dathudeptrai** [comment]
@WindQAQ @WindQAQ maybe this issue related with (https://github.com/tensorflow/tensorflow/issues/38287).

**Comment by TAIYISONG** [comment]
> @TAIYISONG @WindQAQ maybe this issue related with (#38287).

@dathudeptrai 
Yes it seems similar, and this issue is more on optimizer side #42475. Both are about unacceptable slow training speed.

**Comment by mdanatg** [comment]
@TAIYISONG this is an interesting comparison. There are a few things which are probably not obvious, and I think this issue highlights some of them. Let me detail the differences first, and then I'll look into making the necessary modifications so that we can measure the actual performance of tf.function.

First, I should note that `@tf.function` is more similar to TorchScript than it it to PyTorch. When comparing TensorFlow directly with PyTorch, it's more of an apples-to-apples comparison to run the TF code eagerly. So in this case, you should remove the `@tf.function`.

Of course, the same code (or something similar) should work with `tf.function` as well, but in this case it's running into problem of excessive retracing. I'll add a separate comment about that.

Once I removed `@tf.function` on the original code, TF was actually faster in the limit:

TF Eager:
```
1 step takes 0.4307682514190674 s
1 step takes 0.013715505599975586 s
1 step takes 0.013556718826293945 s
```

PyTorch:
```
1 step takes 0.21025729179382324 s
1 step takes 0.010649442672729492 s
1 step takes 0.015627145767211914 s
```

I'll modify the code in your colab a bit to demonstrate how to effectively run it with `@tf.function` as well, for comparison. Will post an update in a few hours with that.

**Comment by mdanatg** [comment]
I had a chance to have a closer look at the `tf.function` instance. I see the latest version of the colab does avoid excessive retracing, which is good. It's still significantly slower than PyTorch, and we need to have a closer look why.

I had a suspicion that it's because the GPU placement is inefficient, so I re-ran the tests on CPU:

5. TF-Adam-without@tf.function takes ~ 0.71s
6. TF-Adam-with@tf.function takes ~ 0.44s
7. Torch-Adam takes ~ 0.69s
6. TF-Adam-with@tf.function(experimental_compile=True) takes ~ 0.06s

So, the TF tests are slower on GPU than on CPU, which is a strong indication that some part of the computation is placed on the CPU, causing massive slowdown due to the relatively slow CPU->GPU transfers.

Another observation - if I enable XLA with `tf.function(experimental_compile=True)`, it's way faster than all three. But, that errors out on GPU, yielding a hint to the problem: `Trying to access resource skip_gram_model_tf_18/w_emb/embeddings_34250 located in device /job:localhost/replica:0/task:0/device:CPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0`.

This is a sure indication that the embedding is incorrectly placed on the CPU, slowing everything down.

@tomerk @fchollet @omalleyt12  for more thoughts on why the embedding might be misplaced

**Comment by mdanatg** [comment]
**Update**: I re-ran all tests on GPU, in **tf-nightly**. Things seem to be much improved, and only the Eager version is slow (which is somewhat expected):

TF-Adam-without@tf.function takes ~ 0.7s
TF-Adam-with@tf.function takes ~ 0.082s
Torch-Adam takes ~ 0.095s
TF-Adam-with@tf.function(experimental_compile=True) takes ~ 0.0005s (@cheshire FYI)

So it seems that the slowdown issue is resolved at head. @TAIYISONG does that match your observations?

**Comment by TAIYISONG** [comment]
> @TAIYISONG this is an interesting comparison. There are a few things which are probably not obvious, and I think this issue highlights some of them. Let me detail the differences first, and then I'll look into making the necessary modifications so that we can measure the actual performance of tf.function.
> 
> First, I should note that `@tf.function` is more similar to TorchScript than it it to PyTorch. When comparing TensorFlow directly with PyTorch, it's more of an apples-to-apples comparison to run the TF code eagerly. So in this case, you should remove the `@tf.function`.
> 
> Of course, the same code (or something similar) should work with `tf.function` as well, but in this case it's running into problem of excessive retracing. I'll add a separate comment about that.
> 
> Once I removed `@tf.function` on the original code, TF was actually faster in the limit:
> 
> TF Eager:
> 
> ```
> 1 step takes 0.4307682514190674 s
> 1 step takes 0.013715505599975586 s
> 1 step takes 0.013556718826293945 s
> ```
> 
> PyTorch:
> 
> ```
> 1 step takes 0.21025729179382324 s
> 1 step takes 0.010649442672729492 s
> 1 step takes 0.015627145767211914 s
> ```
> 
> I'll modify the code in your colab a bit to demonstrate how to effectively run it with `@tf.function` as well, for comparison. Will post an update in a few hours with that.

@mdanatg Hi, thanks for the reply. 

If I'm correct I notice you change the optimizer from Adam() to Adagrad() to get the above result. 
I rerun the colab with optimizer changed back to Adam() and still see my original question3: "In terms of using Adam, why TF is ~20 times slower than PyTorch ? (original question)".

**Comment by TAIYISONG** [comment]
> **Update**: I re-ran all tests on GPU, in **tf-nightly**. Things seem to be much improved, although the non-XLA version is still significantly slower:
> 
> [TF-Adam-without@tf.function](mailto:TF-Adam-without@tf.function) takes ~ 0.7s
> [TF-Adam-with@tf.function](mailto:TF-Adam-with@tf.function) takes ~ 0.082s
> Torch-Adam takes ~ 0.0095s
> [TF-Adam-with@tf.function](mailto:TF-Adam-with@tf.function)(experimental_compile=True) takes ~ 0.0005s (@cheshire FYI)
> 
> Note that for a comparison should also include a TorchScript version.
> 
> **Edit**: fixed wrong numbers and conclusion.



> **Update**: I re-ran all tests on GPU, in **tf-nightly**. Things seem to be much improved, although the non-XLA version is still significantly slower:
> 
> [TF-Adam-without@tf.function](mailto:TF-Adam-without@tf.function) takes ~ 0.7s
> [TF-Adam-with@tf.function](mailto:TF-Adam-with@tf.function) takes ~ 0.082s
> Torch-Adam takes ~ 0.0095s
> [TF-Adam-with@tf.function](mailto:TF-Adam-with@tf.function)(experimental_compile=True) takes ~ 0.0005s (@cheshire FYI)
> 
> Note that for a comparison should also include a TorchScript version.
> 
> **Edit**: fixed wrong numbers and conclusion.

It seems in **1st** case TF still doesn't perform well on Adam() without **tf.function**, compared to **3rd** torch case.

And I tried to use _Lookahead(RAdam(0.02))_ optimizer in TF, it's worse than Adam() case in both with/without tf.function() cases.
I will try upgrading to **tf-nightly** to see if this kind of more advanced optimizer is supported well in TF.

Thanks again for your testing. I will keep an eye on this for any updates.

**Comment by mdanatg** [comment]
Thanks. I don't think I have access to the original colab so I made some copies. But indeed I forgot to change `SGD` back to `Adam` in my colab. I fixed the results. Here are the colabs as well:

* [CPU](https://colab.research.google.com/drive/1v3lOdA0wIS_q7xWJcRdSRH7roEp8Wh29)
* [GPU](https://colab.research.google.com/drive/1SMAzg6F05iNkTFbw0tqy8NwcG02xGnbB#scrollTo=IMl1XRfotLmV)

So it seems that even in nightly, TF is still >20 x slower than PyTorch, and judging from the CPU-only results, it seems that TF doesn't properly use the GPU in this case.

**Comment by TAIYISONG** [comment]
> Thanks. I don't think I have access to the original colab so I made some copies. But indeed I forgot to change `SGD` back to `Adam` in my colab. I fixed the results. Here are the colabs as well:
> 
> * [CPU](https://colab.research.google.com/drive/1v3lOdA0wIS_q7xWJcRdSRH7roEp8Wh29)
> * [GPU](https://colab.research.google.com/drive/1SMAzg6F05iNkTFbw0tqy8NwcG02xGnbB#scrollTo=IMl1XRfotLmV)
> 
> So it seems that even in nightly, TF is still >20 x slower than PyTorch, and judging from the CPU-only results, it seems that TF doesn't properly use the GPU in this case.

I set the original colab as "Anyone on the internet with this link can edit". I don't have access to above 2 new colabs either, but not a big deal lol.

**Is there any plan under way to 'fix' this issue in TF?** As Skip-Gram is the simplest model.

Still I would like to use the most advanced optimizer in my work. RANGER optimizer, which refers to the combo of newly introduced optimizers LOOKAHEAD and RADAM, is even worse than Adam in our tests above. 

Just out of interest sake, why difference optimizers could make such big difference in performance in TF? 
Is it because Adam is not supported well in GPU?

**Comment by mdanatg** [comment]
Yes, this is a significant bug and we definitely plan to fix it, though I couldn't give an exact timeline. We're currently discussing a few solutions internally.

The choice of optimizer influences performance so much is due to the nature of the bug: essentially, we have some computations that are executed on the CPU (likely the embedding lookups). That causes data transfers between CPU and GPU, which are very slow. Different optimizers result in different numbers of such transfers, and that would explain why results vary so wildly. 

P.S. I just realized I edited your original colab - that was not intentional, sorry about it!

**Comment by cheshire** [comment]
For more context, this is explicit CPU placement in the embeddings layer: https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/python/keras/layers/embeddings.py;l=141?q=layers%2Fembeddings.py%20file:tensorflow

**Comment by fridex** [comment]
Is this bug specific only to tensorflow==2.3.0 or does it apply also to older versions?

**Comment by mdanatg** [comment]
The explicit placement was done two years ago, so it probably applies to all versions of `kers.layers.Embedding`. That said, it might go unnoticed in practice if for example the embedding table is too large to fit the GPU memory, or if the model is large enough to dominate the compute time.

**Comment by TAIYISONG** [comment]
Thanks @mdanatg, good to know more about TF schema behind the scene and you guys are planning to update it. Looking forward to seeing the issue go away. :)

**Comment by jvishnuvardhan** [comment]
@TAIYISONG Looks like this was resolved in recent TF versions. I ran your code with `TF2.7` and the computation times are similar. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/c8ddfaadda2ae1bfb75e8b3cd8bf01e2/training_speed_dif_tf2_vs_torch.ipynb). Thanks!

**Comment by TAIYISONG** [comment]
@jvishnuvardhan Thanks for the update. So glad to see the issue is resolved in 2.7.0! 
@mdanatg Thanks for taking this issue previously, also many thanks to the engineers who fixed this!
