### ISSUE TITLE
make -f tensorflow/contrib/makefile/Makefile for iOS is failing

### ISSUE THREAD

**Issue by shrnjad** [tensorflow/tensorflow#4252]
Probably related to [issue 2896](https://github.com/tensorflow/tensorflow/issues/2896)

I am trying to build tensorflow on a mac for iOS. The first two commands work well:
`tensorflow/contrib/makefile/download_dependencies.sh`
and
`compile_ios_protobuf.sh`

However, when I call
`make -f tensorflow/contrib/makefile/Makefile \
 TARGET=IOS \
 IOS_ARCH=ARM64`

I receive a linker error:

> Undefined symbols for architecture x86_64:
  "tensorflow::io::InputStreamInterface::SkipNBytes(long long)", referenced from:
      vtable for tensorflow::io::ZlibInputStream in zlib_inputstream.o
  "tensorflow::io::RandomAccessInputStream::RandomAccessInputStream(tensorflow::RandomAccessFile*)", referenced from:
      tensorflow::io::RecordReader::RecordReader(tensorflow::RandomAccessFile*, tensorflow::io::RecordReaderOptions const&) in record_reader.o
  "typeinfo for tensorflow::io::InputStreamInterface", referenced from:
      typeinfo for tensorflow::io::ZlibInputStream in zlib_inputstream.o
  "vtable for tensorflow::io::InputStreamInterface", referenced from:
      tensorflow::io::InputStreamInterface::InputStreamInterface() in zlib_inputstream.o
  NOTE: a missing vtable usually means the first non-inline virtual member function has no definition.
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/senad/repos/tensorflow2/tensorflow/contrib/makefile/gen/host_bin/proto_text] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'armv7 compilation failed.'
armv7 compilation failed.
+ exit 1

I tried it with the current master commit `f71cc62f71cc62`. After reading the discussion of issue 2896, I also tried it with the commit `582e6c8582e6c8`. This is the one that supposedly fixed the issue in the other ticket.

**Comment by aaalgo** [comment]
I see the same issue when using makefile to produce Linux binary.  Indeed similar to issue 2896.

**Comment by tatatodd** [comment]
Indeed this looks similar to #2896

@petewarden might have clues as to why this is happening.

**Comment by shrnjad** [comment]
Another confusing thing I noticed after looking through the source code: 
`RandomAccessInputStream` class does not call the method `SkipNBytes(long long)` from anywhere in the code.

How can it than appear like that in the call stack in the error message?

**Comment by petewarden** [comment]
I have a fix on my local branch of the Makefile at https://github.com/petewarden/tensorflow/blob/master/tensorflow/contrib/makefile/Makefile#L435, but unfortunately it's part of a bigger change. Adding that line to exclude zlib source files from the build should fix this though.

**Comment by shrnjad** [comment]
I added the line to my makefile that excludes `zlib*`. I still get the same error though. I think the class causing the error is in `random_inputstream.ccrandom_inputstream.cc`?

That one will still get built.

**Comment by EnlightenedCSF** [comment]
Having exactly the same problem here, the solution @petewarden suggested didn't work, unfortunately.

**Comment by petewarden** [comment]
I have a pending fix in PR #4287, could you confirm that fixes your issue?

**Comment by EnlightenedCSF** [comment]
Yes, sir, it does help, thank you!

**Comment by tatatodd** [comment]
Excellent, closing this out.  If you still have issues just ping this thread.
