### ISSUE TITLE
getting an error as 'tuple' object has no attribute 'apply_gradients'

### ISSUE THREAD

**Issue by ThatGuyDV** [tensorflow/tensorflow#43582]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): kaggle environment
- TensorFlow version (use command below): 2.3.0
- Python version: 3.6+ 

I'm a beginner in the field of deep learning and getting hands on working with bert implementation for the classification problem using tensorflow. However I have encountered this error as mentioned in the title.  This is [link ](https://www.kaggle.com/dv1453/notebook3d0337bd04?scriptVersionId=43629422) to my kaggle notebook.  I referred some other notebooks to create train function as below:
`
def train_step(model, token_ids, masks, labels):
    
    labels = tf.dtypes.cast(labels, tf.float32)
    
    with tf.GradientTape() as tape:
        
        predictions = model(token_ids, attention_mask=masks)
        
        loss = loss_object(labels, predictions)
    
    
    gradients = tape.gradient(loss, model.trainable_variables)
    
    optimizer.apply_gradients(zip(gradients, model.trainable_variables), name = 'gradients')
    
    train_loss(loss)

    for i, auc in enumerate(train_auc_metrics):
        
        auc.update_state(labels[:,i], predictions[:,i])
        
def validation_step(model, token_ids, masks, labels):
    
    labels = tf.dtypes.cast(labels, tf.float32)

    predictions = model(token_ids, attention_mask=masks, training=False)
    
    v_loss = loss_object(labels, predictions)

    validation_loss(v_loss)
    
    for i, auc in enumerate(validation_auc_metrics):
        
        auc.update_state(labels[:,i], predictions[:,i])

seeds = [0]

for seed in range(len(seeds)):
    
    print('=' * 50, f"CV {seed+1}", '=' * 50)
    
    model = BertClassifier(TFBertModel.from_pretrained(bert_model_name), len(label_cols))
    
    labels =  train_df[label_cols].values
    
    train_inputs, validation_inputs, train_labels, validation_labels = train_test_split(input_ids, labels, random_state=seed, test_size = 0.2)

    train_masks, validation_masks = train_test_split(attention_masks, random_state=seed, test_size=0.2)

    train_size = len(train_inputs)

    validation_size = len(validation_inputs)

    train_dataset = create_dataset((train_inputs, train_masks, train_labels), batch_size=BATCH_SIZE,train=True)

    validation_dataset = create_dataset((validation_inputs, validation_masks, validation_labels), batch_size=BATCH_SIZE,train=False)
    
    
    steps_per_epoch = train_size // (BATCH_SIZE)

    #  Loss Function
    loss_object = tf.keras.losses.BinaryCrossentropy(from_logits=False)

    train_loss = tf.keras.metrics.Mean(name='train_loss')

    validation_loss = tf.keras.metrics.Mean(name='val_loss')

    #  Optimizer (with 1-cycle-policy)
    warmup_steps = steps_per_epoch // 3

    total_steps = steps_per_epoch * NR_EPOCHS - warmup_steps

    optimizer = create_optimizer(init_lr=2e-5, num_train_steps=total_steps, num_warmup_steps=warmup_steps)

    # Gradients
    
    gradients = 0
    
    #  Metrics
    train_auc_metrics = [tf.keras.metrics.AUC() for i in range(len(label_cols))]

    validation_auc_metrics = [tf.keras.metrics.AUC() for i in range(len(label_cols))]

    for epoch in range(NR_EPOCHS):

        print('=' * 50, f"EPOCH {epoch+1}", '=' * 50)

        start = time.time()

        for batch_no, (token_ids, masks, labels) in enumerate(tqdm(train_dataset)):

            train_step(model, token_ids, masks, labels)

            if batch_no % 100 == 0:

                    print(f'\nTrain Step: {batch_no}, Loss: {train_loss.result()}')

                    for i, label_name in enumerate(label_cols):

                        print(f"{label_name} roc_auc {train_auc_metrics[i].result()}")

                        train_auc_metrics[i].reset_states()

        for batch_no, (token_ids, masks, labels) in enumerate(tqdm(validation_dataset)):

            validation_step(model, token_ids, masks, labels)

        print(f'\nEpoch {epoch+1}, Validation Loss: {validation_loss.result()}, Time: {time.time()-start}\n')

        for i, label_name in enumerate(label_cols):

            print(f"{label_name} roc_auc {validation_auc_metrics[i].result()}")

            validation_auc_metrics[i].reset_states()
`
however I got the error as fallowing:

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-11f3f3661ec3> in <module>
     60         for batch_no, (token_ids, masks, labels) in enumerate(tqdm(train_dataset)):
     61 
---> 62             train_step(model, token_ids, masks, labels)
     63 
     64             if batch_no % 100 == 0:

<ipython-input-14-d39f9869214e> in train_step(model, token_ids, masks, labels)
     12     gradients = tape.gradient(loss, model.trainable_variables)
     13 
---> 14     optimizer.apply_gradients(zip(gradients, model.trainable_variables), name = 'gradients')
     15 
     16     train_loss(loss)

AttributeError: 'tuple' object has no attribute 'apply_gradients'`

**Comment by bhack** [comment]
https://stackoverflow.com/questions/64074872/tensorflow-2-attributeerror-tuple-object-has-no-attribute-apply-gradients

**Comment by bhack** [comment]
The notebook link It is not working.

**Comment by ThatGuyDV** [comment]
Hi , I have updated the link. It should be working now.

**Comment by amahendrakar** [comment]
@ThatGuyDV,
On running the code, I am facing an error stating `FileNotFoundError: [Errno 2] No such file or directory: '../input/eda-and-baseline/processed_train.csv'`

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!

**Comment by ThatGuyDV** [comment]
My apologies, earlier I added that from one of private kaggle notebook. I have updated the dataset and tested from other account to generate same error. I request you to please take a look once again. Thank you.

**Comment by bhack** [comment]
The Kaggle notebook still doesn't run. 
But your problem is that in the third_party Transformer library when you call [`create_optimizer`](https://huggingface.co/transformers/main_classes/optimizer_schedules.html#transformers.create_optimizer)   
`return optimizer, lr_schedule` and instead `apply_gradients` is an optimizer method.

Please ask for Transformers library support at https://discuss.huggingface.co/

**Comment by ThatGuyDV** [comment]
Yep the problem was with third party transformer. When I used keras' optimizer, then my training is working properly. Thanks a lot for the advice. I guess Hugging Faces' create_optimizer does not support apply gradient method for now. I will add this issue to their forum. Thanks a lot once again.

**Comment by amahendrakar** [comment]
> Yep the problem was with third party optimizer. When I used keras' optimizer, then my training is working properly.

@ThatGuyDV,
Thank you for the update. Marking this issue as closed, please feel free to re-open the issue if necessary.

**Comment by LIUZHENGYU2019** [comment]
Could someone leave more details about how to use the keras's optimizer instead of transformer's create_optimizer(). Forgive me for asking such a stupid question, I am just a beginner .

**Comment by Alberto-Hache** [comment]
@jackfromeast , not sure it will solve your problem, but what they mean is that create_optimizer() returns a tuple with two elements: the optimizer itself and an LR scheduler. This causes the error if you use apply_gradients(...) on it.

A simple solution is to change this:
optimizer = create_optimizer(init_lr=2e-5, num_train_steps=total_steps, num_warmup_steps=warmup_steps)

for this (so the optimizer is properly set):
optimizer, lr = create_optimizer(init_lr=2e-5, num_train_steps=total_steps, num_warmup_steps=warmup_steps)

However, I get a new error later on that I'm currently trying to get my head around: :(

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-30-d2a78d55f49c> in <module>()
     82 
     83 
---> 84 train(model, train_dataset, validation_dataset, train_steps_per_epoch=steps_per_epoch, val_steps_per_epoch=validation_steps, epochs=NR_EPOCHS)

9 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    992           except Exception as e:  # pylint:disable=broad-except
    993             if hasattr(e, "ag_error_metadata"):
--> 994               raise e.ag_error_metadata.to_exception(e)
    995             else:
    996               raise

ValueError: in user code:

    <ipython-input-29-d2a78d55f49c>:40 train_step  *
        optimizer.apply_gradients(zip(gradients, model.trainable_variables), 1.0)
    /usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:660 apply_gradients  **
        apply_state)
    /usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:698 _distributed_apply
        with name_scope_only_in_function_or_graph(name or self._name):
    /usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:90 name_scope_only_in_function_or_graph
        return tf.name_scope(name)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/ops.py:6691 __init__
        raise ValueError("name for name_scope must be a string.")

    ValueError: name for name_scope must be a string.

**Comment by engsbk** [comment]
I have also faced the same problem, but I'm using TF v2.7 does that mean I should use another version of transformers?
