### ISSUE TITLE
Unable to fit against and batch ragged output in Keras.

### ISSUE THREAD

**Issue by Izzette** [tensorflow/tensorflow#44112]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Reproduced on Arch Linux & macOS Catalina.
- TensorFlow installed from (source or binary): Binary(?) with pip.
- TensorFlow version (use command below): v2.3.0-rc2-23-gb36436b087
- Python version: 3.8.6

**Describe the current behavior**

I'm working on a text autoencoder in tensorflow to reduce the dimensionality of large text files (> 50000 chars, > 100000 vocab). I feel like I've got what should be a working solution, but run into `ValueError: TypeError: object of type 'RaggedTensor' has no len()`. My program also can't function when using a batch size of greater than 1, instead producing `tensorflow.python.framework.errors_impl.InvalidArgumentError: PartialTensorShape: Incompatible shapes during merge`. It seems that this kind of use case has been supported in Tensorflow for a long time, and I'm rather confused as to why I've been running into so much difficulty with ragged tensors. My code is linked in Google Colab below. Am I doing something wrong, is this a bug in Tensorflow, or unimplemented functionality? Thanks in advance.

**Describe the expected behavior**

Tensorflow fits happily against ragged truths and is able to batch ragged outputs.

**Standalone code to reproduce the issue**

https://colab.research.google.com/drive/13yYGVDAsf8sfoPrbYPtEsrJxZz8OSoVU?usp=sharing

**Exception logs**

[batched-log.txt](https://github.com/tensorflow/tensorflow/files/5395543/batched-log.txt)
[unbatched-log.txt](https://github.com/tensorflow/tensorflow/files/5395544/unbatched-log.txt)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/8bd24ebef91577830bda50cd2178b1d7/44112.ipynb). 

On running the code with [TF-nightly](https://colab.research.google.com/gist/amahendrakar/9fc55134d980288283df0c4e163b216e/44112-tf-nightly.ipynb#scrollTo=1FkK0JPRS2cd), the error changes to `AttributeError: module 'tensorflow' has no attribute 'python'`. Please find the attached gist. Thanks!

**Comment by pedro-r-marques** [comment]
@amahendrakar In the gist that you attached, the issue is with the user defined code in RepeatNVectors.call. It should just use ```tf.shape(x)``` instead of ```tf.python.ops.array_ops.shape```. The original issue was trigged by attempting to convert a ragged tensor to a standard tensor in the loss function utils. I believe it should be addressed by PR #45015

**Comment by Izzette** [comment]
> @amahendrakar In the gist that you attached, the issue is with the user defined code in RepeatNVectors.call. It should just use `tf.shape(x)` instead of `tf.python.ops.array_ops.shape`. The original issue was trigged by attempting to convert a ragged tensor to a standard tensor in the loss function utils. I believe it should be addressed by PR #45015

Nice!  Thanks for getting back to me on this, and thanks for the fix-in-progress :)

**Comment by foxik** [comment]
Note that supporting RaggedTensors as targets (e.g., in `model.fit`) is a frequent request, see #44988, #44112, #43591, #43093, #42320, #41810.

Some partial progress is in pull requests #45060 and #45015, which will allow using custom losses in Keras model (but existing losses like MSE or (S)CE will still not work).

**Comment by foxik** [comment]
Note that I created a new feature request #45403 to support RaggedTensors in standard Keras loss functions.

**Comment by Izzette** [comment]
I think there's also an issue of documentation, it seems to suggest that ragged tensors should mostly just work out-of-the-box in Keras.  This is probably why these are incoming as bugs rather than feature request.

See https://www.tensorflow.org/guide/ragged_tensor#what_you_can_do_with_a_ragged_tensor
> Ragged tensors are supported by many TensorFlow APIs, including Keras, Datasets, tf.function, SavedModels, and tf.Example. For more information, see the section on TensorFlow APIs below.

and https://www.tensorflow.org/guide/ragged_tensor#tensorflow_apis
>  Ragged tensors may be passed as inputs to a Keras model by setting ragged=True on tf.keras.Input or tf.keras.layers.InputLayer. Ragged tensors may also be passed between Keras layers, and returned by Keras models.

While it only says "returned by Keras models" (which seems to be true), it doesn't mention the inability use keras APIs to train a model returning ragged tensors (with or without a custom loss function).

**Comment by Saduf2019** [comment]
I ran the code shared and issue exists on tf-nightly [2.5.0-dev20210114], please find the [gist here](https://colab.research.google.com/gist/Saduf2019/9b48a4c108534eb00bf655e26f7fdfdf/untitled499.ipynb#scrollTo=_IpQoLNDHgyt)

**Comment by Izzette** [comment]
@Saduf2019 you should note that my original code made a mistake (leveraging an internal API) causing the apparent error in TF >= 2.4.  Quoting @pedro-r-marques:

>  It should just use tf.shape(x) instead of tf.python.ops.array_ops.shape

To actually retest against the nightly build, the gist needs to be updated to use `tf.shape` instead of `tf.python.ops.array_ops.shape`.  However, the original "real" error experienced in TF 2.3.0rc2 is not expected to be fixed until at least https://github.com/tensorflow/tensorflow/issues/45403 is merged.

**Comment by sachinprasadhs** [comment]
The issue still exists in Tf Nightly 2.6, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/f4a959ac6be19f5a30cd23c5dfa104ce/44112.ipynb). Thanks!

**Comment by pedro-r-marques** [comment]
@sachinprasadhs The gist that you point to has the following issues:
- ```tf.python.ops.array_ops``` is not allowed; the symbols should be ```tf.shape()```
- In order for a loss to be able to operate on RaggedTensors both values must be RaggedTensors... in this gist, the model output is a dense tensor.

After making this [changes](https://colab.research.google.com/gist/sachinprasadhs/f4a959ac6be19f5a30cd23c5dfa104ce/44112.ipynb) the model executes... however the model itself seems to have design issues. For instance the output is a single value per timestep and that is being compared with a character... that doesn't seem correct to me.

**Comment by Izzette** [comment]
> @sachinprasadhs The gist that you point to has the following issues:
> 
> * `tf.python.ops.array_ops` is not allowed; the symbols should be `tf.shape()`
> * In order for a loss to be able to operate on RaggedTensors both values must be RaggedTensors... in this gist, the model output is a dense tensor.
> 
> After making this [changes](https://colab.research.google.com/gist/sachinprasadhs/f4a959ac6be19f5a30cd23c5dfa104ce/44112.ipynb) the model executes... however the model itself seems to have design issues. For instance the output is a single value per timestep and that is being compared with a character... that doesn't seem correct to me.

I'm absolutely sure it has some design issues.  If the model executes, IMHO the issue is fixed (and I am no longer using this approach, personally, I just bought a GPU with more memory and did a bunch of padding).
