### ISSUE TITLE
AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'

### ISSUE THREAD

**Issue by YANxu-666** [tensorflow/tensorflow#44882]
I have a problem with the conversion model using template code.
I am running on Jupyter Notebook
This is the template code：

# Convert the model to the TensorFlow Lite format without quantization
converter = tf.lite.TFLiteConverter.from_saved_model(MODEL_TF)
model_no_quant_tflite = converter.convert()

# Save the model to disk
open(MODEL_NO_QUANT_TFLITE, "wb").write(model_no_quant_tflite)
# Convert the model to the TensorFlow Lite format with quantization
def representative_dataset():
  for i in range(500):
    yield([x_train[i].reshape(1, 1)])
# Set the optimization flag.
converter.optimizations = [tf.lite.Optimize.DEFAULT]
# Enforce integer only quantization
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
# Provide a representative dataset to ensure we quantize correctly.
converter.representative_dataset = representative_dataset
model_tflite = converter.convert()

# Save the model to disk
open(MODEL_TFLITE, "wb").write(model_tflite)

Output result：

AttributeError                            Traceback (most recent call last)
<ipython-input-50-0b17c299ecad> in <module>()
     18 # Provide a representative dataset to ensure we quantize correctly.
     19 converter.representative_dataset = representative_dataset
---> 20 model_tflite = converter.convert()
     21 
     22 # Save the model to disk

F:\anaconda3\lib\site-packages\tensorflow\lite\python\lite.py in convert(self)
    745         self.inference_input_type, self.inference_output_type)
    746     if flags_modify_model_io_type:
--> 747       result = _modify_model_io_type(result, **flags_modify_model_io_type)
    748 
    749     if self._experimental_sparsify_model:

F:\anaconda3\lib\site-packages\tensorflow\lite\python\util.py in modify_model_io_type(model, inference_input_type, inference_output_type)
    833     return model
    834 
--> 835   model_object = _convert_model_from_bytearray_to_object(model)
    836 
    837   if len(model_object.subgraphs) > 1:

F:\anaconda3\lib\site-packages\tensorflow\lite\python\util.py in _convert_model_from_bytearray_to_object(model_bytearray)
    570 def _convert_model_from_bytearray_to_object(model_bytearray):
    571   """Converts a tflite model from a bytearray into a parsable object."""
--> 572   model_object = schema_fb.Model.GetRootAsModel(model_bytearray, 0)
    573   model_object = schema_fb.ModelT.InitFromObj(model_object)
    574   model_object = copy.deepcopy(model_object)

AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'
I want to know the reason

**Comment by wangtz** [comment]
Hi Yan,

Which version are you running? Could you provide a list steps to reproduce your issue?
Also if possible, please also check if tensorflow/lite/python/schema_py_generated file under dist packages exists or have Model class defined.

Thanks,

Hi Maghna,

I re-assign this bug to you in case you have seen similar issues. Feel free to reassign.

Thanks,

**Comment by MeghnaNatraj** [comment]
This issue should be fixed with the latest TF code (tf-nightly). Could you try with that let us know if it works?

eg:
`` `
pip install tf-nightly
```

(you need to restart your runtime if you are using [https://colab.research.google.com])

**Comment by YANxu-666** [comment]
> Hi Yan,
> 
> Which version are you running? Could you provide a list steps to reproduce your issue?
> Also if possible, please also check if tensorflow/lite/python/schema_py_generated file under dist packages exists or have Model class defined.
> 
> Thanks,
> 
> Hi Maghna,
> 
> I re-assign this bug to you in case you have seen similar issues. Feel free to reassign.
> 
> Thanks,

Firstly,thank you very much for your message.
What I run in jupyter notebook is   :   ! pip install tensorflow==2.4.0rc0 , so tensorflow should be version 2.4.0and python is 3.7.0
The source code of the model I run:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/hello_world/create_sine_model.ipynb
Chapter title is " Generate a TensorFlow Lite Model"

AttributeError                            Traceback (most recent call last)
<ipython-input-23-448f10b1b0c8> in <module>()
     18 # Provide a representative dataset to ensure we quantize correctly.
     19 converter.representative_dataset = representative_dataset
---> 20 model_tflite = converter.convert()
     21 
     22 # Save the model to disk

AttributeError: module 'tensorflow.lite.python.schema_py_generated' has no attribute 'Model'
But my schema_py_generated file has no code.
I am looking forward to your reply

**Comment by wangtz** [comment]
Hi Yan,

As Meghna mentioned, please try tf-nightly instead of the RC version for now.

https://pypi.org/project/tf-nightly/

**Comment by YANxu-666** [comment]
> Hi Yan,
> 
> As Meghna mentioned, please try tf-nightly instead of the RC version for now.
> 
> https://pypi.org/project/tf-nightly/

My tf-nightly is already 2.5.0 dev version, but still the same problem

**Comment by YANxu-666** [comment]
I need the code under the schema_py_generated file

**Comment by MeghnaNatraj** [comment]
@YANxu-666 I was able to run this on tf-nightly with version `2.5.0-dev20201117` (as of today). It also worked for `2.4.0rc0` Here is the link: https://colab.research.google.com/drive/1tE3bJNXOv1NW1OPncgpLfPb1bk8RZnAE?usp=sharing

(Change EPOCH=1 to EPOCH=500 to exactly get the same results as the hello_world example.)

If it helps, you can use the [schema_py_generated.py.zip](https://github.com/tensorflow/tensorflow/files/5556749/schema_py_generated.py.zip) attached here.

Marking issue as resolved.

**Comment by YANxu-666** [comment]
> @YANxu-666 I was able to run this on tf-nightly with version `2.5.0-dev20201117` (as of today). It also worked for `2.4.0rc0` Here is the link: https://colab.research.google.com/drive/1tE3bJNXOv1NW1OPncgpLfPb1bk8RZnAE?usp=sharing
> 
> (Change EPOCH=1 to EPOCH=500 to exactly get the same results as the hello_world example.)
> 
> If it helps, you can use the [schema_py_generated.py.zip](https://github.com/tensorflow/tensorflow/files/5556749/schema_py_generated.py.zip) attached here.
> 
> Marking issue as resolved.

I ran it in jupyter notebook according to the link you provided, and the same error still appeared.

**Comment by hhass** [comment]
I had the same problem and found that schema_py_generated.py did exist in my tensorflow installation, but was empty.
And it was independent of installing freshly or with --upgrade via pip, and for both nightly (several dates) and 2.4 (both rc).
Is there a problem with the pip config?

Anyway, thanks @MeghnaNatraj  for the file, this solved the issue for me

Btw., I think #44725 is a duplicate of this one

**Comment by MeghnaNatraj** [comment]
The problem was with TF release itself (due to a change that was rolled out). However it was fixed soon after - refer to #41846 

The latest builds do not have this issue. (or at-least I am unable to reproduce this issue). If you face this issue even now, please create a new issue or post a comment in #41846 so we can look into it.

**Comment by wqcsim** [comment]
I got this error too.
tensorflow: 2.4.1
window 10 
python 3.7

**Comment by wqcsim** [comment]
This issue is fixed on 2.4.1 ?

**Comment by MeghnaNatraj** [comment]
@wqcsim Trye downloading tf-nightly. `pip install tf-nightly`

**Comment by demconpeter** [comment]
I had the exact same problem using TensorFlow 2.4.1 with python 3.7 on Windows 10, and unzipping the above-mentioned schema_py_generated.py.zip to replace an existing but 0-byte file schema_py_generated.py in my python 3.7 installation subfolder Python37\Lib\site-packages\tensorflow\lite\python fixed the problem. I'd rather not use nightly versions unless I really have to.

Thanks!

**Comment by havefun007** [comment]
> I had the exact same problem using TensorFlow 2.4.1 with python 3.7 on Windows 10, and unzipping the above-mentioned schema_py_generated.py.zip to replace an existing but 0-byte file schema_py_generated.py in my python 3.7 installation subfolder Python37\Lib\site-packages\tensorflow\lite\python fixed the problem. I'd rather not use nightly versions unless I really have to.
> 
> Thanks!

it works!

**Comment by PeterBorisenko** [comment]
It works, but it's just a duct tape!
Why it is not generated?
