### ISSUE TITLE
SubProcess ended with return code: 4294967295 with tensorflow-gpu 2.4.0rc cuda11.0 cudnn8.0.2 on windows 10

### ISSUE THREAD

**Issue by SilenceEagle** [tensorflow/tensorflow#45170]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: --
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0rc3
- Python version: 3.8.5
- Bazel version (if compiling from source): --
- GCC/Compiler version (if compiling from source): -- 
- CUDA/cuDNN version: CUDA11.0 cudnn-11.0-windows-x64-v8.0.2.39 graphics driver version: 457.30
- GPU model and memory: RTX 3070 8G

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
A lot of **I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295** are printed when run tf code on windows 10.
**Describe the expected behavior**
I have no idea of what the meaning of these logs. And when I ran the same code on other machines with RTX2070s or RTX 2080Ti or GTX1080Ti and tensorflow-gpu 2.3,   these logs hadn't been shown.

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

physical_devices = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(physical_devices[0], True)

x = np.random.normal(size=(100, 28, 28, 1)).astype(np.float32)
y = np.zeros([100, 10], dtype=np.float32)
y[:, 1] = 1.

train_ds = tf.data.Dataset.from_tensor_slices((x, y)).shuffle(buffer_size=100).batch(32)
num_classes = 10

model = Sequential([
  layers.Conv2D(16, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),
  layers.Conv2D(32, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),
  layers.Conv2D(64, 3, padding='same', activation='relu'),
  layers.MaxPooling2D(),
  layers.Flatten(),
  layers.Dense(128, activation='relu'),
  layers.Dense(num_classes)
])
model.compile(optimizer='adam',
              loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
epochs=3
history = model.fit(
  train_ds,
  epochs=epochs
)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Here is the logs:
```
C:\Users\dell\Anaconda3\envs\tf24rcpy38\python.exe F:/python_ws/helloworld/main.py
2020-11-25 13:14:29.035547: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-11-25 13:14:31.301152: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2020-11-25 13:14:31.301719: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2020-11-25 13:14:31.330039: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:65:00.0 name: GeForce RTX 3070 computeCapability: 8.6
coreClock: 1.815GHz coreCount: 46 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-11-25 13:14:31.330233: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-11-25 13:14:31.338262: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-11-25 13:14:31.338376: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-11-25 13:14:31.341810: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-11-25 13:14:31.342848: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-11-25 13:14:31.350072: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2020-11-25 13:14:31.352437: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-11-25 13:14:31.353100: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-11-25 13:14:31.353270: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2020-11-25 13:14:31.357024: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-25 13:14:31.357735: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:65:00.0 name: GeForce RTX 3070 computeCapability: 8.6
coreClock: 1.815GHz coreCount: 46 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 417.29GiB/s
2020-11-25 13:14:31.357961: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2020-11-25 13:14:31.358056: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-11-25 13:14:31.358145: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-11-25 13:14:31.358240: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2020-11-25 13:14:31.358335: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2020-11-25 13:14:31.358452: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2020-11-25 13:14:31.358577: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2020-11-25 13:14:31.358702: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-11-25 13:14:31.358878: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2020-11-25 13:14:32.004910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-11-25 13:14:32.005024: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2020-11-25 13:14:32.005085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2020-11-25 13:14:32.005286: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6177 MB memory) -> physical GPU (device: 0, name: GeForce RTX 3070, pci bus id: 0000:65:00.0, compute capability: 8.6)
2020-11-25 13:14:32.006266: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Epoch 1/3
2020-11-25 13:14:32.533116: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2020-11-25 13:14:32.625497: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2020-11-25 13:14:33.613410: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2020-11-25 13:14:33.619608: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2020-11-25 13:14:35.296892: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 0

2020-11-25 13:14:35.310216: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295

2020-11-25 13:14:35.310607: W tensorflow/stream_executor/gpu/redzone_allocator.cc:314] Internal: ptxas exited with non-zero error code -1, output: 
Relying on driver to perform ptx compilation. 
Modify $PATH to customize ptxas location.
This message will be only logged once.
2020-11-25 13:14:35.320291: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295

2020-11-25 13:14:35.331970: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295

# ...(lots of SubProcess ended with return code: 4294967295)

2020-11-25 13:14:36.014622: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295

2020-11-25 13:14:36.230275: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295

2020-11-25 13:14:36.231899: I tensorflow/stream_executor/cuda/cuda_blas.cc:1838] TensorFloat-32 will be used for the matrix multiplication. This will only be logged once.
2020-11-25 13:14:36.289355: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295

2020-11-25 13:14:36.302906: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295

2020-11-25 13:14:36.315136: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295

# ...(lots of SubProcess ended with return code: 4294967295)

1/4 [======>.......................] - ETA: 16s - loss: 2.3410 - accuracy: 0.0000e+002020-11-25 13:14:37.514428: I tensorflow/core/platform/windows/subprocess.cc:308] SubProcess ended with return code: 4294967295

# ...(lots of SubProcess ended with return code: 4294967295)

4/4 [==============================] - 7s 591ms/step - loss: 1.7706 - accuracy: 0.5053
Epoch 2/3
4/4 [==============================] - 0s 6ms/step - loss: 0.0604 - accuracy: 1.0000
Epoch 3/3
4/4 [==============================] - 0s 5ms/step - loss: 8.0053e-05 - accuracy: 1.0000

Process finished with exit code 0
```

I use **...(lots of SubProcess ended with return code: 4294967295)** to represents many lines of "SubProcess ended with return code: 4294967295" for saving space.

**Comment by garveytao** [comment]
I have the same problem

**Comment by garveytao** [comment]
I have the same problem
System information:
Python version: 3.6.8
tf-nightly-gpu 2.5.0
CUDA11.1
GPU RTX 3070 8G
windows 10

**Comment by Mamsie97** [comment]
same for me on RTX 3070, testet with cuda 11.0 and 11.1

**Comment by ThibaultJousse** [comment]
I have the same error code when a module packaged with pyinstaller 4.1 is spawned as a node child process.

It never goes beyond that line :
```python
model = tf.keras.models.load_model(model_path)
```

No error is displayed but the exit code shows that there is a problem :
```
child process exited with code 4294967295
```
- python 3.7.9
- tensorflow-cpu 2.3.1
- Windows 10 20H2
    Version	19042.630
    Windows Feature Experience Pack 120.2212.31.0

**Comment by Klettermaxl92** [comment]
I had the same problem on my system with an RTX 3070.

I solved the issue for me as follows:
- delete the cuda v.10.1 variable value and change to v.11.1 in the variable name: $Path
- after this my pycharm asks for cusolver64_10.dll
- I simply copied this from v10.1 to v11.1
now my system is running

**Comment by xldrx** [comment]
The `SubProcess ended with return code: 4294967295` error is most likely relates to PTX compiler (ptxas.exe) not supporting your GPU (sm_86) in CUDA <= 11.0.

This issue is tracked at https://github.com/tensorflow/tensorflow/issues/44750 including some workarounds.

**Comment by sanjoy** [comment]
@cheshire can you PTAL (also see the internal bug).

**Comment by SilenceEagle** [comment]
@xldrx Thanks, it works.
I follow the suggestions at [#44750](https://github.com/tensorflow/tensorflow/issues/44750) and the [article](https://dobromyslova.medium.com/making-work-tensorflow-with-nvidia-rtx-3090-on-windows-10-7a38e8e582bf):
>copy C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\ptxas.exe into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\ptxas.exe.

The _SubProcess ended with return code: 4294967295_ error has gone.

**Comment by SilenceEagle** [comment]
But after replacing the cuda11.0's ptxas.exe with cuda11.1's ptxas.exe, sometimes a error will be raised, then the process end with non zero exit code, here is the log:
```
2020-12-02 17:19:39.715059: F .\tensorflow/core/kernels/reduction_gpu_kernels.cu.h:847] Non-OK-status: GpuLaunchKernel(CleanupSegments<T*, OUT_T, Op>, new_grid_dim, block_dim, 0, cu_stream, (T*)temp_storage.flat<int8_t>().data(), out, extent_x, extent_y, grid_dim.y, op, init) status: Internal: unspecified launch failure
2020-12-02 17:19:39.715176: E tensorflow/stream_e
Process finished with exit code -1073740791 (0xC0000409)
```

**Comment by lvyong1943** [comment]
@SilenceEagle Thanks,I solved the problem according to your method!!!

**Comment by lvyong1943** [comment]
> @xldrx Thanks, it works.
> I follow the suggestions at [#44750](https://github.com/tensorflow/tensorflow/issues/44750) and the [article](https://dobromyslova.medium.com/making-work-tensorflow-with-nvidia-rtx-3090-on-windows-10-7a38e8e582bf):
> 
> > copy C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\ptxas.exe into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\ptxas.exe.
> 
> The _SubProcess ended with return code: 4294967295_ error has gone.

Thanks,I solved the problem according to your method!!!

**Comment by rmothukuru** [comment]
@SilenceEagle,
Closing the issue as it has been resolved. Thanks!

**Comment by rpsantosa** [comment]
> > @xldrx Thanks, it works.
> > I follow the suggestions at [#44750](https://github.com/tensorflow/tensorflow/issues/44750) and the [article](https://dobromyslova.medium.com/making-work-tensorflow-with-nvidia-rtx-3090-on-windows-10-7a38e8e582bf):
> > > copy C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\ptxas.exe into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\ptxas.exe.
> > 
> > 
> > The _SubProcess ended with return code: 4294967295_ error has gone.
> 
> Thanks,I solved the problem according to your method!!!

worked! Better, would be using the 11.1 cuda version and remove the 11.0.

**Comment by abdeali88** [comment]
> I had the same problem on my system with an RTX 3070.
> 
> I solved the issue for me as follows:
> 
> * delete the cuda v.10.1 variable value and change to v.11.1 in the variable name: $Path
> * after this my pycharm asks for cusolver64_10.dll
> * I simply copied this from v10.1 to v11.1
>   now my system is running

Hey Can you please email me cusolver64_10.dll file to abdealiarsiwala888@gmail.com. I have cusolver64_11.dll but it asks for 10.

Please it's urgent. Thanks!!

**Comment by mes0419** [comment]
> @xldrx Thanks, it works.
> I follow the suggestions at [#44750](https://github.com/tensorflow/tensorflow/issues/44750) and the [article](https://dobromyslova.medium.com/making-work-tensorflow-with-nvidia-rtx-3090-on-windows-10-7a38e8e582bf):
> 
> > copy C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\ptxas.exe into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin\ptxas.exe.
> 
> The _SubProcess ended with return code: 4294967295_ error has gone.

wow!! thanks!! I solve the problem!!!

**Comment by OrangeeJi** [comment]
> The `SubProcess ended with return code: 4294967295` error is most likely relates to PTX compiler (ptxas.exe) not supporting your GPU (sm_86) in CUDA <= 11.0.
> 
> This issue is tracked at #44750 including some workarounds.

Thanks! It solved my problem!
But my logs still show 'SubProcess ended with return code: 0'
Is there any solution to this problem?
Thank you!

**Comment by lseongjoo** [comment]
> > The `SubProcess ended with return code: 4294967295` error is most likely relates to PTX compiler (ptxas.exe) not supporting your GPU (sm_86) in CUDA <= 11.0.
> > This issue is tracked at #44750 including some workarounds.
> 
> Thanks! It solved my problem!
> But my logs still show 'SubProcess ended with return code: 0'
> Is there any solution to this problem?
> Thank you!

I think 'return code: 0' means successfully ended the process.

**Comment by xc597** [comment]
@xldrx 按照这个方法，我的问题还是没得到解决
