### ISSUE TITLE
Barrier in implementing demo: SHAPE -> STRIDED_SLICE impossible?

### ISSUE THREAD

**Issue by EliZucker** [tensorflow/tensorflow#45256]
@tensorflow/micro

**System information**
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 4d2124d19daffa088aca8c2485b56c8f1717ec0e
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): ESP32

**Describe the problem**

After training/converting a Keras MobileNetV1 model, running inference on the ESP32 produces this error:
```
Type INT32 (2) not supported.
Processing Node STRIDED_SLICE (number 34) failed to invoke with status 1
Node STRIDED_SLICE (number 34) failed to invoke with status 1
```

**Please provide the exact sequence of commands/steps when you ran into the problem**

Steps are based on the [person detector](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/person_detection/training_a_model.md
) tutorial. 

I build the model with keras: 
```model = tf.keras.applications.mobilenet.MobileNet(weights=None, input_shape=(96, 96, 1), alpha = 0.25, classes=6)```

Then successfully convert:
```
converter = tf.lite.TFLiteConverter.from_saved_model("...")
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_dataset_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8] # removing these lines does not fix the error
converter.inference_input_type = tf.int8 # removing these lines does not fix the error
converter.inference_output_type = tf.int8 # removing these lines does not fix the error
tflite_model = converter.convert()
open("model_out.tflite", "wb").write(tflite_model)
```

And finally run:
```
xxd -i model_out.tflite > custom_model_data.cc
```

I am running a slightly modified version of the person_detection demo project. Some additional layers need to be registered compared to the demo code (not sure why):
```
static tflite::MicroMutableOpResolver<10> micro_op_resolver(error_reporter);
  micro_op_resolver.AddAveragePool2D();
  micro_op_resolver.AddConv2D();
  micro_op_resolver.AddDepthwiseConv2D();
  micro_op_resolver.AddPad();
  micro_op_resolver.AddMean();
  micro_op_resolver.AddShape();
  micro_op_resolver.AddStridedSlice();
  micro_op_resolver.AddPack();
  micro_op_resolver.AddReshape();
  micro_op_resolver.AddSoftmax();
```

Any inference attempts result in the original error I posted above. I believe that this is the inevitable result of a SHAPE layer layer (which outputs an int32 type), followed by a STRIDED_SLICE layer (which doesn't support int32 as input). 

Is there any way to get around this? Or alternatively, how did the authors of the tutorial successfully produce a mobilenetv1 model that required such few operations to be registered? I am taking the same quantization steps, and believe the model is the same.

Thanks!

**Comment by EliZucker** [comment]
@advaitjain Any suggestions for getting feature-parity with demo results? It looks like you're working in this area. I'm debating re-writing my project to use TF Slim for the small chance that it will somehow fix this. Can't find many other differences with the demo training info.

**Comment by EliZucker** [comment]
Update: I believe networks produced with ```tf.keras.applications.MobileNet```, specifically while using a non-default ```classes``` parameter value, are not supported with TF Micro. Not sure what TF Slim is doing for binary image classification but it must be different.

**Comment by LambisElef** [comment]
I have kind of a similar issue. While both my TF saved model and TF Lite model work when running in the PC, when running it on ESP32 I get the same error. I noticed that there is an issue with the Reshape Layer, being converted into Shape -> Strided Slice -> Pack -> Reshape in TF Lite (used Netron to visualize it), and because of the Pack Layer outputting an int32, TF Lite Micro outputs an error. The described situation occured while using TF 2.3.1. 

The problem was solved when running an older TF version (2.2.1). Now the Reshape Layer is converted into just a TF Lite Reshape Layer (no extras) and the model works fine in ESP32.

**Comment by t123yh** [comment]
> Kind of a similar issue occured to me too. While both my TF saved model and TF Lite model work when running in the PC, when running it on ESP32 I get the same error. I noticed that there is an issue with the Reshape Layer, being converted into Shape -> Strided Slice -> Pack -> Reshape in TF Lite (used Netron to visualize it), and because of the Pack Layer outputting an int32, TF Lite Micro outputs an error. The described situation occured while using TF 2.3.1.
> 
> The problem was solved when running an older TF version (2.2.1). Now the Reshape Layer is converted into just a TF Lite Reshape Layer (no extras) and the model works fine in ESP32.

It seems that `int8` support for input and output is added in tf2.3, so unfortunately `converter.inference_input_type = tf.int8` doesn't work in tf2.2.

**Comment by AIWintermuteAI** [comment]
Anyone is working on this issue? I can reproduce the problem with tf 2.4 using new converter. 
I found a workaround by removing Reshape layer all together - I had it right after Input and it turns out tf micro doesn't need the input to be explicitly reshaped, e.g.

```
  int8_t x_quantized[72];
  float x[72] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0};        

  for (byte i = 0; i < 72; i = i + 1) {
        input->data.int8[i] = x[i] / input->params.scale + input->params.zero_point;
  }
```

the above code works with the following network (input shape = batch_size, 24, 3)

```
input = Input(shape=(window_size, 3, ))
x = Conv1D(8, 3, activation='relu', padding='same')(input)
x = AveragePooling1D(2)(x)
x = Conv1D(16, 3, activation='relu', padding='same')(x)
x = AveragePooling1D(2)(x)
x = Conv1D(32, 3, activation='relu', padding='same')(x)
x = AveragePooling1D(2)(x)
x = Conv1D(32, 3, activation='relu', padding='same')(x)
x = Conv1D(64, 3, activation='relu', padding='same')(x)
#x = GlobalAveragePooling1D()(x)
x = Dropout(0.25)(x)
x = Flatten()(x)
type_out = Dense(len(labels), activation="softmax", name="type")(x)
precip_out = Dense(1, activation="sigmoid", name="precip")(x)
```

**Comment by jpiat** [comment]
Here is how i adapted Keras MobileNetV1 model to work in tensorflow micro 

```
from tensorflow.keras.applications import MobileNet
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Softmax, Dropout

model = MobileNet(include_top = False, weights=None, input_shape=(96, 96, 1), pooling='avg', alpha=0.25, dropout=0.001 )
top_layer = Dropout(0.001)(model.output)
top_layer = Dense(2)(top_layer)
top_layer = Softmax()(top_layer)
model = Model(model.input, top_layer)
```

it still does not have the exact same behavior in training as the default model, but performs fine.

**Comment by Nickjgniklu** [comment]
I was looking for a solution to this problem and found this.
https://stackoverflow.com/questions/64850356/error-with-strided-slice-in-tensorflow-lite/66223851#66223851
It appears that editing tensorflow\lite\micro\kernels\strided_slice.cc to have an extra case that assumes int32 can be treated as int8 can work in at least some cases. (It worked for me; I have trained my model with tf 2.4.2 and built tf-micro with tf 2.4.2 source)
```
case kTfLiteInt32:
  reference_ops::StridedSlice(op_params,
  tflite::micro::GetTensorShape(input),
  tflite::micro::GetTensorData<int8_t>(input),
  tflite::micro::GetTensorShape(output),
  tflite::micro::GetTensorData<int8_t>(output));
 break;
```

If someone has any ideas on why this works / ideas for a proper fix I would like to learn more about this.
I am going to attach the modified strided_slice.cc if anyone would like to try and replace theirs with it.
[strided_slice.zip](https://github.com/tensorflow/tensorflow/files/6845050/strided_slice.zip)

**Comment by Saduf2019** [comment]
@EliZucker 
Could you please let us know if this is still an issue in latest stable TF v2.6.0 ?Thank you!

**Comment by hlc1209** [comment]
I have to say that this problem stil exist in the latest version of tensorflow (colab 2.7.0)

It prevents me from generating a working model on the Arduino 33 ble.

This is a serious problem because we cannot even run this [official demo](https://www.tensorflow.org/lite/performance/post_training_integer_quant)

**Comment by maartenvds** [comment]
> I have to say that this problem stil exist in the latest version of tensorflow (colab 2.7.0)
> 
> It prevents me from generating a working model on the Arduino 33 ble.
> 
> This is a serious problem because we cannot even run this [official demo](https://www.tensorflow.org/lite/performance/post_training_integer_quant)

I can confirm this is still not fixed in tensorflow 2.8.0. @[Saduf2019](https://github.com/Saduf2019) Can you please re-open this issue, it has been there for over a year now and I still need to avoid reshape layers...

**Comment by Nickjgniklu** [comment]
I was looking at the source code for tensorflow micro and believe a fix may have been implemented. However, in order to receive the fix you would have build the library from source instead of downloading it through the arduino package manager.

**Comment by advaitjain** [comment]
Can you please try the instructions from https://github.com/tensorflow/tflite-micro-arduino-examples and let us know if that helps.

**Comment by gaetanbahl** [comment]
This is still a problem in tensorflow 2.9.1.

**Comment by jdsalmonson** [comment]
This is still a problem in tensorflow 2.15.0.  The model with the Shape->StridedSlice->Reshape transformation can be run fine on my ESP32 as long as the operators are provided in the C++ code:

```
  static tflite::MicroMutableOpResolver<9> micro_op_resolver;
  // ...
  micro_op_resolver.AddShape();
  micro_op_resolver.AddStridedSlice();
  micro_op_resolver.AddPack();

but it would be nice to know how to keep these operations from being injected in the first place.
