### ISSUE TITLE
Fill only currently supports int32, int64, float32, bool, string for input 1, got 9.Node number 5 (FILL) failed to invoke.

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#45933]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.5.0-dev20201222
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

I have been able to successfully convert the [Boundless model](https://arxiv.org/pdf/1908.07007.pdf) with full integer quantization but it fails during inference. I have made sure to scale the inputs w.r.t. quantization i.e. the following - 

```python
if quantization=="integer":
    input_img = preprocess_image("test_image.jpg")
    input_scale, input_zero_point = input_details[0]["quantization"]
    input_img = input_img / input_scale + input_zero_point
    input_img = input_img.astype(input_details[0]["dtype"])
```

I am running into - 

```python
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-35-1e81bd6daa76> in <module>()
      2 interpreter.set_tensor(input_details[0]['index'], input_img)
      3 start = time.time()
----> 4 interpreter.invoke()
      5 print(f"Inference took: {time.time()-start} seconds")

/usr/local/lib/python3.6/dist-packages/tensorflow/lite/python/interpreter.py in invoke(self)
    758     """
    759     self._ensure_safe()
--> 760     self._interpreter.Invoke()
    761 
    762   def reset_all_variables(self):

RuntimeError: Fill only currently supports int32, int64, float32, bool, string for input 1, got 9.Node number 5 (FILL) failed to invoke.
```

**Describe the expected behavior**

Currently, it's not clear to me why it is failing. Essentially, I would expect it to work. 

**Standalone code to reproduce the issue**
Colab Notebook: https://colab.research.google.com/github/sayakpaul/Adventures-in-TensorFlow-Lite/blob/master/Boundless_TFLite.ipynb.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by abattery** [comment]
Currently, TFLite Fill op does not support INT8 inputs. However, it looks like the quantization tool added Fill op node for INT8 inputs. @daverim @teijeong could you take a look?

**Comment by sayakpaul** [comment]
Hey folks.

Any updates on this?

**Comment by thaink** [comment]
Should it be fixed in runtime side?

**Comment by thaink** [comment]
A fix is landed in the master branch.
Please feel free to reopen if you still have this issue.

**Comment by sayakpaul** [comment]
@thaink should I test the fix with nightly?

**Comment by thaink** [comment]
@sayakpaul I believe it is included in the latest nightly.

**Comment by sayakpaul** [comment]
Just tested with `2.5.0-dev20210112` and the issue still persists. Will look again tomorrow. Anything else I should note?

**Comment by thaink** [comment]
No. Please let me know the result tomorrow.
