### ISSUE TITLE
Minor issues with C++ custom ops documentation

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#4727]
I was following the instructions below to define a custom op called `zero_out`.

https://github.com/tensorflow/tensorflow/blob/aaeb50c55427350841f7a0c226af9db174397d55/tensorflow/g3doc/how_tos/adding_an_op/index.md

I found a few issues:
1. You cannot load a `so` file without giving an absolute path (or prefixing with `./`). 
2. The zero_out_module has no zero_out component. 

---

```
In [1]: import tensorflow as tf

In [2]: zero_out_module = tf.load_op_library('zero_out.so')
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-2-e4878fcfc44f> in <module>()
----> 1 zero_out_module = tf.load_op_library('zero_out.so')

/home/hholst/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
     73           return _OP_LIBRARY_MAP[library_filename]
     74       # pylint: disable=protected-access
---> 75       raise errors._make_specific_exception(None, None, error_msg, error_code)
     76       # pylint: enable=protected-access
     77   finally:

NotFoundError: zero_out.so: cannot open shared object file: No such file or directory

In [3]: zero_out_module = tf.load_op_library('./zero_out.so')

In [4]: 

```

![image](https://cloud.githubusercontent.com/assets/6200749/19033213/9620c9ec-895d-11e6-8f4e-db477b4b5397.png)

**Comment by hholst80** [comment]
OK. I fixed the latter issue due to a mistake on my side (I did not call `REGISTER_OP` only `REGISTER_KERNEL_BUILDER`) but the load still requires `./` prefix.

There are some other minor things with formatting (escaped symbols in code) which I could make a PR for if it is welcome?

**Comment by concretevitamin** [comment]
@hholst80 Yes, we'd very much appreciate a PR for this!

**Comment by malzantot** [comment]
I can work on this.

**Comment by tenstep** [comment]
I met the same problem and still not understand your solution to the latter issue. What do you mean by `I did not call REGISTER_OP`?, I have added `REGISTER_OP("ZeroOut").Input.....` in zero_out.cc but the issue still exists. Or do you mean adding something like `REGISTER_OP(zero_out)......`? But what is the input and output? Or do I need some additional command to call  `REGISTER_OP`? Thanks in advance!
