### ISSUE TITLE
CMake config for TensorFlow Lite C API for Windows builds debug target (not release target as expected)

### ISSUE THREAD

**Issue by barabanus** [tensorflow/tensorflow#48021]
**System information**
- Microsoft Windows 10 Pro Insider Preview 10.0.21337 Build 21337
- Microsoft Visual Studio Community 2019 Version 16.9.1
- TensorFlow master 42d9939623f7792ef01b9750df4cd91e5a4b26fa

**Describe the problem**
When I try to build TensorFlow Lite C API dynamic library for Windows using MSVC 2019 compiler with CMake config I get debug target compiled (not release target as expected).

**Provide the exact sequence of commands / steps that you executed before running into the problem**
- install Microsoft Visual Studio Community 2019 with CMake, git and command prompt tools components
- run `x86 Native Tools Command Prompt for VS 2019`
- run the following commands within the terminal:
```
git clone --depth 1 https://github.com/tensorflow/tensorflow.git
cmake tensorflow/tensorflow/lite/c -DTFLITE_C_BUILD_SHARED_LIBS=ON -Bbuild
cmake --build build -j 8
```
After the compilation there's `build/Debug/tensorflowlite_c.dll` which is built as debug target. It doesn't help to provide `-DCMAKE_BUILD_TYPE=Release` - CMake still builds debug target.

Expected behavior is that CMake builds release target.

**Any other info / logs**
Here's full log from the commands above: [cmake-msvc-win.txt](https://github.com/tensorflow/tensorflow/files/6191359/cmake-msvc-win.txt)

**Comment by wangtz** [comment]
Hi Terry, 

Could you help on this CMake issue?

Thanks,
Tiezhen

**Comment by barabanus** [comment]
@Saduf2019 
I confirm that this's still an issue for v2.7.0
After compilation we've got `build/Debug/tensorflowlite_c.dll`

**Comment by ohadlights** [comment]
You can build Release with this command:
cmake --build build -j 8 --config Release

**Comment by misterBart** [comment]
Bumped into the same problem. It could be CMake problem, e.g. see https://gitlab.kitware.com/cmake/cmake/-/issues/19401

It could also be TfLite problem. That is, not at configure time the build type is determined, but at build time the build type is determined. The advantage of this: you can generate multiple build types from one configuration. See for more info at https://issuehint.com/issue/Azure/azure-sdk-for-cpp/3600

The TfLite documentation (https://www.tensorflow.org/lite/guide/build_cmake) seems to imply the build type is determined at configure time, but the required use of `cmake --build . --config Release` seems to imply the build type is determined at build time. In any case, the TfLite documentation should be fixed.

**Comment by pkgoogle** [comment]
Hi barabanus, generally speaking, windows is better support via bazel than cmake. Does using Bazel help you with your issue?

**Comment by barabanus** [comment]
@pkgoogle If we declare CMake to be a valid build system we should either support it according to documentation, or fix the documentation ¯\_(ツ)_/¯

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

**Comment by mirko796** [comment]
The issue is still here even in current master branch ( commit 5128d4068f0fac931c52c1a9c4eaf9c248f9be24 )

Here are steps to reproduce (same is happening with any combination of `TFLITE_ENABLE_*` params, they are not important but I provided them since it is the way I built the lib

```sh
# from the root folder of the repo
mkdir build_ruy
cd build_ruy
cmake ../tensorflow/lite/c -DTFLITE_ENABLE_MMAP=OFF -DTFLITE_ENABLE_GPU=OFF -DTFLITE_ENABLE_NNAPI=OFF -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=TRUE -DTFLITE_ENABLE_XNNPACK=ON -DTFLITE_ENABLE_RUY=ON -DCMAKE_BUILD_TYPE=Release

# invoking build as instructed by documentation on  https://www.tensorflow.org/lite/guide/build_cmake#build_tensorflow_lite_c_library
cmake --build . -j 8
# and now we have debug version of library under build_ruy/Debug subfolder

# everything works fine if build is invoked with the following line
cmake --build . -j 8 --config Release
# and now we have release version of library under build_ruy/Release subfolder
```

Can you please at least update the documentation (by including `--config Release` part) at:
  - https://www.tensorflow.org/lite/guide/build_cmake#build_tensorflow_lite_c_library

Thank you!

**Comment by pkgoogle** [comment]
Hi @mirko796, https://github.com/tensorflow/tensorflow/pull/60752, actually updated the note to describe the Windows default behavior, we can update the documentation to better reflect this and include instructions on how to build the release library.

**Comment by pkgoogle** [comment]
Current PR here: https://github.com/tensorflow/tensorflow/pull/63739

**Comment by mirko796** [comment]
Thanks, I've just added one comment to the PR (library is placed to `Release` folder when built correctly)

One question - these changes would be eventually propagated to the following page https://www.tensorflow.org/lite/guide/build_cmake#build_tensorflow_lite_c_library ?

I am asking this because I was not aware that there was a documentation under `tensorflow/lite/g3doc/guide/` in the repo (which is my bad but other users might overlook it too)

**Comment by pkgoogle** [comment]
@mirko796, correct in fact if you want to improve the documentation yourself, you are freely able to update/create a PR.

**Comment by pkgoogle** [comment]
Hi @mirko796, the documentation is now updated, please let us know if you are satisfied w/ the resolution. https://www.tensorflow.org/lite/guide/build_cmake#build_tensorflow_lite_c_library

**Comment by mirko796** [comment]
@pkgoogle - much better now (far less confusing comparing to how it looked before), the only nitpicking I have is that Windows binary is not generated "in the current directory", it is generated under the "Release" sub-directory.
However I don't think that this will cause bigger problems to anyone since it is standard practice on Windows
Thanks!

**Comment by pkgoogle** [comment]
Closing as the reason for reopening has been resolved.
