### ISSUE TITLE
Recurrent layers fail on (at least some) Linuxes where use_bias=True, succeeds on Macos

### ISSUE THREAD

**Issue by zoxoi** [tensorflow/tensorflow#48195]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom code
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04 (AWS Deep Learning AMI)
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3, 2.4.1, several 2.5 and 2.6-nightly samples
- Python version: 3.6
- CUDA/cuDNN version: 11
- GPU model and memory: NVIDIA Corporation GV100GL [Tesla V100 SXM2 16GB]; BUT also occurs on CPU wheels

Creating a subclass model with a~~n LSTM~~ recurrent layer when `use_bias=True` (i.e. the default) fails. The code can be found in the following gist:

https://gist.github.com/zoxoi/9c331f9df1fa22112e061638ea200ec8

Note that the model

```python
class FailModel(Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.lstm = layers.LSTM(64, use_bias=True)

    def call(self, input, training=False):
        return self.lstm(input)
```

is the only important bit, as far as I know. The rest is a minor bit of supporting code just to trigger the issue such as compiling the model and creating a dummy dataset generator. The full traceback is in the included gist, to save space, but the ultimate error given is:

```    
ValueError: Shape must be at least rank 3 but is rank 2 for '{{node BiasAdd}} = BiasAdd[T=DT_FLOAT, data_format="NCHW"](add, bias)' with input shapes: [?,256], [256].
```

A few facts I've noticed:
- It doesn't seem to fail when *calling* the model, this behavior is limited to things such as `model.fit()`. Explicitly calling `model(tf.zeros(1, 96, 100))` works fine from my testing.
- The value given in the error `ValueError: Shape must be at least rank 3 but is rank 2 for '{{node BiasAdd}} = BiasAdd[T=DT_FLOAT, data_format="NCHW"](add, bias)' with input shapes: [?,256], [256].` seems to always be 4x the number of cells (e.g. for 64 it's 250, 100 it's 400 etc). I don't know if this is surprising or not.
- Since it may be related to NCHW format, I tried changing the `time_major` argument to true, and both leaving the data the same and (more correctly) manually permuting/transposing the input into time major order, no success.
- This bug happens on multiple TF versions, 2.3 was the earliest I can test but persists up to the most recent 2.6 nightly.
- This happens even if you force TF to not discover a GPU, or install tf-cpu instead.
- However, this does NOT happen on my Macos Catalina 10.15.7 laptop, with an integrated GPU (i.e. tf-cpu is automatically installed), the layer works as intended with no errors.

For anybody else dealing with this: a workaround is to set **use_bias=False** when creating the LSTM. This has tradeoffs however, (beyond just the potential mathematical issues with using a bias allowing some correction), since it won't use the cuDNN kernel if use_bias is off which from my testing seems to have a fairly radical speed penalty (it's training more slowly than it is on my laptop CPU by about 40ms/step). 

If you want to test on the **exact** same setup I'm using, I'm experiencing the issue on the AWS Deep Learning AMI Version 42.1.

Further important things I haven't tested:
- ~~If this is limited to LSTM or affects other recurrent layers.~~ [Update: It affects GRU and SimpleRNN as well, updating title]
- If this affects Windows in either configuration
- ~~If, even though it fails on CPU, it's perhaps related to CUDA 11 specifically somehow~~ [Also failed on a GPU-less Linux AMI]
- If this affects the functional API as well, I've only used subclass models

**Comment by Saduf2019** [comment]
@zoxoi 
I ran the code shared on tf 2.4 and face a different error,Please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b1933a7374348ca6034590589a4e5212/untitled575.ipynb).
Could you please share a colab gist with the issue reported.

**Comment by zoxoi** [comment]
I don't know what a collab gist is. I put the entire code in the gist I linked. It needs some supporting code, the code I pasted was just me pointing out the relevant code the error is occurring in.

**Comment by Saduf2019** [comment]
@zoxoi 
I ran the code but still face a differet error, Please find the [gist here](https://colab.research.google.com/gist/Saduf2019/46f92b2166217c75e27cc97a11ca15f8/untitled584.ipynb)

As per the error reported, can you refer to these links and let us know if it helps:[link](https://stackoverflow.com/questions/50162787/valueerror-shape-must-be-rank-2-but-is-rank-3-for-matmul)

**Comment by zoxoi** [comment]
I'm honestly not sure how this isn't clear, it's just a standard micro python project? The `data_loader` is a small module that holds the code the file is under.

I fixed the code in your link by inlining the code:
https://colab.research.google.com/gist/Saduf2019/46f92b2166217c75e27cc97a11ca15f8/untitled584.ipynb#scrollTo=R4gBFl1dMz1-&line=35&uniqifier=1

It runs successfully on the colab gist, but it does NOT run on what appears to be x86_64 Ubuntu 16.04, and possibly other environments. I'm not surprised it runs on whatever the Google Compute backend is, since it's developed and maintained by Google, but the error triggers under different architectures.

I searched numerous SO answers and such when researching this to make sure there isn't another problem. Including the one you linked. The issue here is that on some machines, as you can see, the code runs successfully, as it should since the shape is correct, but it doesn't run on certain architectures. I've tried with two different Ubuntu AWS instances now (one with a GPU and one without) and both failed. I could also try running it locally via a Linux live installation if that's important, but it appears that to reproduce someone on the team will need to do it on an environment other than that gist.

**Comment by Jack-Fawcett** [comment]
For those looking for a workaround this worked for me when trying to load a serialized model.
`tf.keras.backend.set_image_data_format("channels_last")`

**Comment by sushreebarsa** [comment]
@zoxoi We see that you are using older version of tensorflow. Many bugs have been fixed in latest version. We recommend that you upgrade to latest stable version of tensorflow 2.6.0 and let us know if the issue still persists in newer versions .Thanks!

**Comment by zoxoi** [comment]
I'm not going to be able to test this for a bit, but it's on my to-do list. Just to stave off the inactivity autoclose.

**Comment by very-meanly** [comment]
Bumping this to keep it open - still seeing this issue in tensorflow==2.9.1. Same pattern - no issue on MacOS, but as soon as I run on a Sagemaker notebook instance using Amazon Linux 2, the issue happens. The suggestion from @Jack-Fawcett does prevent the error from happening, for anyone else looking for a workaround (`tf.keras.backend.set_image_data_format("channels_last")`)

**Comment by Anirudh-Murali** [comment]
Bumping this to keep it open - still seeing this issue in tensorflow==2.12 ob Sagemaker notebook instance using Amazon Linux 2, the issue happens. As mentioned by @very-meanly  "The suggestion from @Jack-Fawcett does prevent the error from happening, for anyone else looking for a workaround (tf.keras.backend.set_image_data_format("channels_last"))"

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
