### ISSUE TITLE
Missing libtensorflow builds for 2.5.0-rc0 and 2.5.0-rc1

### ISSUE THREAD

**Issue by VivekPanyam** [tensorflow/tensorflow#48550]
There don't appear to be prebuilt binaries for libtensorflow (https://www.tensorflow.org/install/lang_c) for `2.5.0-rc0` and `2.5.0-rc1`.

These binaries exist for 2.3.0 and 2.4.0 (and the corresponding RCs) under https://storage.googleapis.com/tensorflow/libtensorflow/, but none exist for the 2.5.0 RCs.

For example, https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.5.0-rc0.tar.gz is one of the missing files.

Would it be possible to push those binaries/trigger CI builds to generate them?

Thanks!

**Comment by mihaimaruseac** [comment]
We're trying to get them for final release but we had some CI troubles for RC0 and RC1.

**Comment by mihaimaruseac** [comment]
Can you check if they are in RC2 release?

**Comment by VivekPanyam** [comment]
@mihaimaruseac Thanks! Looks like Linux CPU is available, but Linux GPU and Mac CPU are missing.

* Linux CPU: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.5.0rc2.tar.gz
* Linux GPU (missing): https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.5.0rc2.tar.gz
* Mac CPU (missing): https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-darwin-x86_64-2.5.0rc2.tar.gz

(I haven't done any validation yet apart from checking if the files exist)

**Comment by VivekPanyam** [comment]
Also, not sure if it matters, but the previous releases used the format `-x.y.z-rc2` and it seems like 2.5.0 uses `-x.y.zrc2`

**Comment by mihaimaruseac** [comment]
@av8ramit can you take a look?

**Comment by av8ramit** [comment]
I've fixed the issue that caused this and done a manual re-upload. I can now see the previously missing files. Can you please confirm this is resolved @VivekPanyam ?

**Comment by JustinWick** [comment]
I've tested your uploads, and the following are present:
- https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.5.0rc3.tar.gz
- https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.5.0rc3.tar.gz

This is still missing:
- https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-darwin-x86_64-2.5.0rc3.tar.gz

Some of these are missing for earlier release candidates, but I assume people don't care about that.

Note: I'm having the same issue with 2.3.2, as I've reported at #48955.

**Comment by VivekPanyam** [comment]
@av8ramit @mihaimaruseac I confirmed that the files exist (and they match the previous convention of `version-rcX` instead of just `versionrcX`)

RC2:
* Linux CPU: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.5.0-rc2.tar.gz
* Linux GPU: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.5.0-rc2.tar.gz
* Mac CPU: https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-darwin-x86_64-2.5.0-rc2.tar.gz

(Again, I haven't done any validation yet apart from checking if the files exist)

The corresponding files for RC3 are missing though:
* Linux CPU (missing): https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-2.5.0-rc3.tar.gz
* Linux GPU (missing): https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.5.0-rc3.tar.gz
* Mac CPU (missing): https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-darwin-x86_64-2.5.0-rc3.tar.gz

**Comment by av8ramit** [comment]
Okay so I did a manual upload again and all three files that @VivekPanyam lists with the proper convention of `version-rcX` are up. This may be a problem in the release automation upload process. Assigning to @angerson who may know more.

**Comment by angerson** [comment]
Hi @VivekPanyam and @JustinWick, thanks for your reports. There are a few oddities about the system that uploads our binaries, and I'd like to clear them up with your help. I found two causes for the inconsistencies you're seeing:

1. Our auto-uploader uses a static list of renaming instructions and was misconfigured to upload `linux` as `darwin` (this caused https://github.com/tensorflow/tensorflow/issues/48955).
1. Our auto-uploader uses `2.X.0rc0` instead of `2.X.0-rc0`, like our earlier uploads did. For example, in the links you pointed out as missing in https://github.com/tensorflow/tensorflow/issues/48550#issuecomment-834686425, the files are there if you change `2.5.0-rc3` to `2.5.0rc3`.

For (1), I fixed the misconfiguration and added a checker to make sure future uploads can't be misconfigured in the same way. Next we'll re-upload the botched binaries. Have you noticed any other TensorFlow versions with this problem? I'll repeat this in https://github.com/tensorflow/tensorflow/issues/48955.

For (2), this looks like an oversight in the uploader. For consistency with previous releases, I'll update the uploader to use a hyphen. For reference, is this expectation documented somewhere? How were you determining the download links for the release candidates?

**Comment by angerson** [comment]
I've made the changes to the uploader and re-uploaded the -rc3 binaries to make sure they're all present. 

We don't need to re-upload `rc0` and `rc1`, however, as they're soon to be deprecated by the packages for the full release (which were unaffected by this issue, anyway).

**Comment by mihaimaruseac** [comment]
I think this is resolved, right?
