### ISSUE TITLE
No module named 'compat'

### ISSUE THREAD

**Issue by pedro-abundio-wang** [tensorflow/tensorflow#50121]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- TensorFlow installed from (source or binary):binary
- TensorFlow version (use command below):2.x

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
i install conda env(include tensorflow, slim, object-detection etc)
No module named 'compat'

![企业微信截图_16230466543453](https://user-images.githubusercontent.com/50159788/120968328-4ff13c00-c79b-11eb-83b6-73bed46b9ac9.png)

**Describe the expected behavior**

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@pedro-abundio-wang 
Can you verify if:

import tensorflow as tf
print(tf.__version__)  works fine, 
We see that you have not filled in the issue template, please let us know the python version,tf version used, what os are you on is it 64 bit.
You may also refer to similar issues #38800.

**Comment by pedro-abundio-wang** [comment]
> @pedro-abundio-wang
> Can you verify if:
> 
> import tensorflow as tf
> print(tf.**version**) works fine,
> We see that you have not filled in the issue template, please let us know the python version,tf version used, what os are you on is it 64 bit.
> You may also refer to similar issues #38800.

print(tf.version) 
output:
<module 'tensorflow._api.v2.version' from 'H:\\Miniconda3\\lib\\site-packages\\tensorflow\\_api\\v2\\version\\__init__.py'>

(base) H:\models>python --version
Python 3.8.5

os: windows 64bit

**Comment by Saduf2019** [comment]
@pedro-abundio-wang 
Please try on venv and let us know if you still face the issue.

**Comment by pedro-abundio-wang** [comment]
> @pedro-abundio-wang
> Please try on venv and let us know if you still face the issue.

Yes I am able to import tensorflow and all the other functionalities are working fine and I see only .compat.v1 issue for now.
And i met the same problem, on ubuntu-16.04 x64 and conda env, or ubuntu-18.04 x64 tensorflow 2.2 or tf 2.4. or tf 2.5 and conda env

**Comment by pedro-abundio-wang** [comment]
this is my conda env, after i install tensorflow 2.4, .compat.v1 issue have the same problem.

(base) H:\models>conda env export
name: base
channels:
  - defaults
dependencies:
  - brotlipy=0.7.0=py38h2bbff1b_1003
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - cffi=1.14.3=py38hcd4344a_2
  - chardet=3.0.4=py38haa95532_1003
  - conda=4.9.2=py38haa95532_0
  - conda-package-handling=1.7.2=py38h76e460a_0
  - console_shortcut=0.1.1=4
  - cryptography=3.2.1=py38hcd4344a_1
  - idna=2.10=py_0
  - menuinst=1.4.16=py38he774522_1
  - openssl=1.1.1h=he774522_0
  - pip=20.2.4=py38haa95532_0
  - powershell_shortcut=0.0.1=3
  - pycosat=0.6.3=py38h2bbff1b_0
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=pyhd3eb1b0_1
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.5=h5fd99cc_1
  - pywin32=227=py38he774522_1
  - requests=2.24.0=py_0
  - ruamel_yaml=0.15.87=py38he774522_1
  - setuptools=50.3.1=py38haa95532_1
  - six=1.15.0=py38haa95532_0
  - sqlite=3.33.0=h2a8f88b_0
  - tqdm=4.51.0=pyhd3eb1b0_0
  - urllib3=1.25.11=py_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_3
  - wheel=0.35.1=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - wincertstore=0.2=py38_0
  - yaml=0.2.5=he774522_0
  - zlib=1.2.11=h62dcd97_4
  - pip:
    - absl-py==0.12.0
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cachetools==4.2.2
    - colorama==0.4.4
    - cycler==0.10.0
    - decorator==5.0.9
    - defusedxml==0.7.1
    - entrypoints==0.3
    - flatbuffers==1.12
    - gast==0.3.3
    - google-auth==1.30.1
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - ipykernel==5.5.5
    - ipython==7.24.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.12
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.0
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pickleshare==0.7.5
    - pillow==8.2.0
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.18
    - protobuf==3.17.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pywinpty==1.1.1
    - pyzmq==22.1.0
    - qtconsole==5.1.0
    - qtpy==1.9.0
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - send2trash==1.5.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.4.0
    - tensorflow-estimator==2.4.0
    - termcolor==1.1.0
    - terminado==0.10.0
    - testpath==0.5.0
    - tornado==6.1
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
prefix: H:\Miniconda3

**Comment by pedro-abundio-wang** [comment]
it is very strange. the following code can run, and i try both intelliJ and pycharm ide, both have compat.v1 issue.

![16231146173809](https://user-images.githubusercontent.com/50159788/121106844-68179880-c839-11eb-8971-462ddafbbcb2.png)


import tensorflow.compat.v1 as tf
a = tf.random_normal((10, 3))
b = tf.random_normal((10, 3))
c = tf.reduce_sum(tf.square(a - b))
d = tf.square(tf.norm(a - b))
print(c)
print(d)

--------------------------------------------------------------------------------

output: 
2021-06-08 09:04:16.053279: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-06-08 09:04:16.053740: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-06-08 09:04:19.423823: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-08 09:04:19.425956: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-06-08 09:04:19.426321: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-06-08 09:04:19.429629: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: WIN-IPP8JANJS7E
2021-06-08 09:04:19.430092: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: WIN-IPP8JANJS7E
2021-06-08 09:04:19.431193: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-06-08 09:04:19.432110: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
tf.Tensor(60.59104, shape=(), dtype=float32)
tf.Tensor(60.59104, shape=(), dtype=float32)

**Comment by Saduf2019** [comment]
@pedro-abundio-wang 
from the error log above, can you verify the cuda path, and verify "os.add_dll_directory("C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/bin") before importing tensorflow"
and ensure Cuda 11.0 and cudnn 8.0 is present.

**Comment by pedro-abundio-wang** [comment]
> @pedro-abundio-wang
> from the error log above, can you verify the cuda path, and verify "os.add_dll_directory("C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2/bin") before importing tensorflow"
> and ensure Cuda 11.0 and cudnn 8.0 is present.

sorry for delay response.
I retry this problem on linux system(ubuntu), and after i install gpu-driver, cuda-11.2 and cudnn 8.0, the environment information as following.

### **gpu-driver works fine.**

![Screenshot from 2021-06-19 15-20-10](https://user-images.githubusercontent.com/50159788/122634648-e6b1e700-d111-11eb-81ac-229c2a99f368.png)

### **cuda works fine.**

![Screenshot from 2021-06-19 15-22-14](https://user-images.githubusercontent.com/50159788/122634682-27a9fb80-d112-11eb-9a39-2c5b997283e3.png)

### **cudnn works fine.**

(models) pedro@Pedro-Abundio-Wang:~/cudnn_samples_v8/mnistCUDNN$ ./mnistCUDNN 
Executing: mnistCUDNN
cudnnGetVersion() : 8100 , CUDNN_VERSION from cudnn.h : 8100 (8.1.0)
Host compiler version : GCC 5.4.0

There are 1 CUDA capable devices on your machine :
device 0 : sms 10  Capabilities 6.1, SmClock 1784.5 Mhz, MemSize (Mb) 6075, MemClock 4004.0 Mhz, Ecc=0, boardGroupID=0
Using device 0

Testing single precision
Loading binary file data/conv1.bin
Loading binary file data/conv1.bias.bin
Loading binary file data/conv2.bin
Loading binary file data/conv2.bias.bin
Loading binary file data/ip1.bin
Loading binary file data/ip1.bias.bin
Loading binary file data/ip2.bin
Loading binary file data/ip2.bias.bin
Loading image data/one_28x28.pgm
Performing forward propagation ...
Testing cudnnGetConvolutionForwardAlgorithm_v7 ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: -1.000000 time requiring 57600 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: -1.000000 time requiring 178432 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: -1.000000 time requiring 2057744 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: -1.000000 time requiring 184784 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnFindConvolutionForwardAlgorithm ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 0.045056 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.047872 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.119104 time requiring 57600 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.213280 time requiring 178432 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: 3.618592 time requiring 2057744 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: 71.100418 time requiring 184784 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnGetConvolutionForwardAlgorithm_v7 ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: -1.000000 time requiring 2450080 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: -1.000000 time requiring 1433120 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: -1.000000 time requiring 4656640 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: -1.000000 time requiring 2000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: -1.000000 time requiring 128000 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnFindConvolutionForwardAlgorithm ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.083968 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.154624 time requiring 128000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: 0.174944 time requiring 1433120 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.245760 time requiring 4656640 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: 0.702464 time requiring 2450080 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 1.304576 time requiring 2000 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Resulting weights from Softmax:
0.0000000 0.9999399 0.0000000 0.0000000 0.0000561 0.0000000 0.0000012 0.0000017 0.0000010 0.0000000 
Loading image data/three_28x28.pgm
Performing forward propagation ...
Testing cudnnGetConvolutionForwardAlgorithm_v7 ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: -1.000000 time requiring 57600 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: -1.000000 time requiring 178432 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: -1.000000 time requiring 2057744 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: -1.000000 time requiring 184784 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnFindConvolutionForwardAlgorithm ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.045760 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 0.046432 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.088064 time requiring 57600 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: 0.198720 time requiring 184784 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.215072 time requiring 178432 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: 0.223232 time requiring 2057744 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnGetConvolutionForwardAlgorithm_v7 ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: -1.000000 time requiring 2450080 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: -1.000000 time requiring 1433120 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: -1.000000 time requiring 4656640 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: -1.000000 time requiring 2000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: -1.000000 time requiring 128000 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnFindConvolutionForwardAlgorithm ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.059360 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: 0.072704 time requiring 2450080 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 0.074752 time requiring 2000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.116736 time requiring 128000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: 0.129664 time requiring 1433120 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.169984 time requiring 4656640 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Resulting weights from Softmax:
0.0000000 0.0000000 0.0000000 0.9999288 0.0000000 0.0000711 0.0000000 0.0000000 0.0000000 0.0000000 
Loading image data/five_28x28.pgm
Performing forward propagation ...
Resulting weights from Softmax:
0.0000000 0.0000008 0.0000000 0.0000002 0.0000000 0.9999820 0.0000154 0.0000000 0.0000012 0.0000006 

Result of classification: 1 3 5

Test passed!

Testing half precision (math in single precision)
Loading binary file data/conv1.bin
Loading binary file data/conv1.bias.bin
Loading binary file data/conv2.bin
Loading binary file data/conv2.bias.bin
Loading binary file data/ip1.bin
Loading binary file data/ip1.bias.bin
Loading binary file data/ip2.bin
Loading binary file data/ip2.bias.bin
Loading image data/one_28x28.pgm
Performing forward propagation ...
Testing cudnnGetConvolutionForwardAlgorithm_v7 ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: -1.000000 time requiring 28800 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: -1.000000 time requiring 100 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: -1.000000 time requiring 178432 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: -1.000000 time requiring 184784 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: -1.000000 time requiring 2057744 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnFindConvolutionForwardAlgorithm ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.061440 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 0.090720 time requiring 100 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.178272 time requiring 178432 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: 0.183968 time requiring 2057744 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.408576 time requiring 28800 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: 0.441984 time requiring 184784 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnGetConvolutionForwardAlgorithm_v7 ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: -1.000000 time requiring 2000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: -1.000000 time requiring 4656640 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: -1.000000 time requiring 64000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: -1.000000 time requiring 2450080 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: -1.000000 time requiring 1433120 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnFindConvolutionForwardAlgorithm ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.109472 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 0.127744 time requiring 2000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: 0.143360 time requiring 1433120 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.166912 time requiring 64000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: 0.192512 time requiring 2450080 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.263168 time requiring 4656640 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Resulting weights from Softmax:
0.0000001 1.0000000 0.0000001 0.0000000 0.0000563 0.0000001 0.0000012 0.0000017 0.0000010 0.0000001 
Loading image data/three_28x28.pgm
Performing forward propagation ...
Testing cudnnGetConvolutionForwardAlgorithm_v7 ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: -1.000000 time requiring 28800 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: -1.000000 time requiring 100 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: -1.000000 time requiring 178432 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: -1.000000 time requiring 184784 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: -1.000000 time requiring 2057744 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnFindConvolutionForwardAlgorithm ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.049152 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.076672 time requiring 28800 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 0.087680 time requiring 100 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.135520 time requiring 178432 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: 0.150144 time requiring 184784 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: 0.182272 time requiring 2057744 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnGetConvolutionForwardAlgorithm_v7 ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: -1.000000 time requiring 2000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: -1.000000 time requiring 4656640 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: -1.000000 time requiring 64000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: -1.000000 time requiring 2450080 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: -1.000000 time requiring 1433120 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Testing cudnnFindConvolutionForwardAlgorithm ...
^^^^ CUDNN_STATUS_SUCCESS for Algo 0: 0.089088 time requiring 0 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 1: 0.102400 time requiring 2000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 2: 0.150496 time requiring 64000 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 4: 0.159584 time requiring 2450080 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 7: 0.177152 time requiring 1433120 memory
^^^^ CUDNN_STATUS_SUCCESS for Algo 5: 0.237120 time requiring 4656640 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 6: -1.000000 time requiring 0 memory
^^^^ CUDNN_STATUS_NOT_SUPPORTED for Algo 3: -1.000000 time requiring 0 memory
Resulting weights from Softmax:
0.0000000 0.0000000 0.0000000 1.0000000 0.0000000 0.0000714 0.0000000 0.0000000 0.0000000 0.0000000 
Loading image data/five_28x28.pgm
Performing forward propagation ...
Resulting weights from Softmax:
0.0000000 0.0000008 0.0000000 0.0000002 0.0000000 1.0000000 0.0000154 0.0000000 0.0000012 0.0000006 

Result of classification: 1 3 5

Test passed!

### **nvcc check**

(models) pedro@Pedro-Abundio-Wang:~/cudnn_samples_v8/mnistCUDNN$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:08:53_PST_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0

but still in intelliJIdea, 

![Screenshot from 2021-06-19 15-26-02](https://user-images.githubusercontent.com/50159788/122634741-ad2dab80-d112-11eb-823a-1978060a1df1.png)

the conda env list as following

(models) pedro@Pedro-Abundio-Wang:~/deep-learning/models/research$ conda env list
# conda environments:
#
base                     /home/pedro/anaconda3
GANs                     /home/pedro/anaconda3/envs/GANs
atom                     /home/pedro/anaconda3/envs/atom
computer-vision          /home/pedro/anaconda3/envs/computer-vision
d2l-numpy                /home/pedro/anaconda3/envs/d2l-numpy
deep-learning-specialization     /home/pedro/anaconda3/envs/deep-learning-specialization
fastai                   /home/pedro/anaconda3/envs/fastai
image-classification     /home/pedro/anaconda3/envs/image-classification
models                *  /home/pedro/anaconda3/envs/models
natural-language-processing     /home/pedro/anaconda3/envs/natural-language-processing
open-mmlab               /home/pedro/anaconda3/envs/open-mmlab
origin                   /home/pedro/anaconda3/envs/origin
ploutos                  /home/pedro/anaconda3/envs/ploutos
quantum                  /home/pedro/anaconda3/envs/quantum
tensorflow-specialization     /home/pedro/anaconda3/envs/tensorflow-specialization
tfjs-converter           /home/pedro/anaconda3/envs/tfjs-converter
yad2k                    /home/pedro/anaconda3/envs/yad2k

(models) pedro@Pedro-Abundio-Wang:~/deep-learning/models/research$ conda env export
name: models
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.5.25=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.1.1=py38h06a4308_0
  - python=3.8.10=hdb3f193_7
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.12.0
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==21.2.0
    - backcall==0.2.0
    - bleach==3.3.0
    - cachetools==4.2.2
    - cffi==1.14.5
    - chardet==4.0.0
    - decorator==5.0.9
    - defusedxml==0.7.1
    - entrypoints==0.3
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.30.1
    - google-auth-oauthlib==0.4.4
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - idna==2.10
    - ipykernel==5.5.5
    - ipython==7.24.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.2.0
    - jupyter-console==6.4.0
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - keras-nightly==2.5.0.dev2021032900
    - keras-preprocessing==1.1.2
    - markdown==3.3.4
    - markupsafe==2.0.1
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - notebook==6.4.0
    - numpy==1.19.5
    - oauthlib==3.1.1
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandocfilters==1.4.3
    - parso==0.8.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.11.0
    - prompt-toolkit==3.0.18
    - protobuf==3.17.2
    - ptyprocess==0.7.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.9.0
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pyyaml==5.4.1
    - pyzmq==22.1.0
    - qtconsole==5.1.0
    - qtpy==1.9.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.6.3
    - send2trash==1.5.0
    - six==1.15.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==2.5.0
    - tensorflow-estimator==2.5.0
    - termcolor==1.1.0
    - terminado==0.10.0
    - testpath==0.5.0
    - tf-slim==1.1.0
    - tornado==6.1
    - traitlets==5.0.5
    - typing-extensions==3.7.4.3
    - urllib3==1.26.5
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - werkzeug==2.0.1
    - widgetsnbextension==3.5.1
    - wrapt==1.12.1
prefix: /home/pedro/anaconda3/envs/models

**Comment by Saduf2019** [comment]
@pedro-abundio-wang 
As cuda/GPU works as expecred, please move this to closed status as the issue opened is addressed.

**Comment by RyanShun-511** [comment]
https://blog.csdn.net/weixin_45080073/article/details/117034111

import tensorflow._api.v2.compat.v1 as tf
tf.disable_v2_behavior()

**Comment by godshen** [comment]
> https://blog.csdn.net/weixin_45080073/article/details/117034111
> 
> import tensorflow._api.v2.compat.v1 as tf tf.disable_v2_behavior()

While I can solve the problem this way
But I still want to know why this problem occurs ?
And is this solution a fully equivalent replacement ?

**Comment by Anant16** [comment]
> @pedro-abundio-wang As cuda/GPU works as expecred, please move this to closed status as the issue opened is addressed.

Hi, I don't think CUDA/GPU was the poster's issue anyway.
The issue is that inside the IDEA IDE, tensorlfow.compat.v1 gives "No module named 'compat'" error, which was not resolved in this thread.
I am facing the same issue right now.
Is there any update as to how it can be resolved?
Thank you

**Comment by ElchaabiMohamed** [comment]
Hi @Anant16 !

I am getting the same error, did you resolve it ???
