### ISSUE TITLE
Native arm 32 bit compilation

### ISSUE THREAD

**Issue by vmayoral** [tensorflow/tensorflow#502]
Having issues compiling natively TensorFlow. The process fails over and over at this point:
```
erle@erle-brain-2 ~/tensorflow $ ../bazel-0.1.2/output/bazel build -c opt //tensorflow/tools/pip_package:build_pip_package --local_resources 1024,.5,1.0 -s --spawn_strategy=standalone --genrule_strategy=standalone --verbose_failures
.............................................................................................................................................................................................
INFO: Waiting for response from Bazel server (pid 15928)...
WARNING: Sandboxed execution is not supported on your system and thus hermeticity of actions cannot be guaranteed. See http://bazel.io/docs/bazel-user-manual.html#sandboxing for more information. You can turn off this warning via --ignore_unsupported_sandboxing.
ERROR: /home/erle/tensorflow/tensorflow/tensorboard/bower/BUILD:3:1: no such package '@accessibility-developer-tools//': SSL peer shut down incorrectly and referenced by '//tensorflow/tensorboard/bower:bower'.
ERROR: Loading failed; build aborted.
INFO: Elapsed time: 990.385s.
```

Also tried with bazel `0.1.1`. Same result.
Thanks,

**Comment by mrry** [comment]
It looks like things are failing when Bazel tries to build TensorBoard. Have you had any success in getting another TensorFlow target to build? (e.g. Does `bazel test //tensorflow/python:constant_op_test` work?)

**Comment by vmayoral** [comment]
Thanks @mrry for looking into this. [Here's](https://gist.github.com/vmayoral/ec85d8effa13308d5f66) the build output. Failed at the end. 

More useful seems to be the log cited at the end https://gist.github.com/vmayoral/7665cf9ca9056a15167d. Apparently, there's an `ERROR: testTooLargeGraph (__main__.ConstantTest)`.

**Comment by martinwicke** [comment]
These tests check for the correct behavior (the proper exceptions) when
trying to create graphs/constants that are too large for protobuf. The
limit is 2G/tensor. On your platform, you run out of memory trying to
allocate/copy that, which is soft of expected given your address space.

I think those two tests should be fixed to catch MemoryError and not count
that as a failure (since if your system cannot allocate 2G + 2G, you
probably won't be creating graphs that big).

**Comment by vmayoral** [comment]
Thanks @martinwicke for clarifying.
Does that help anyhow with the initial issue? I'm still unable to generate a pip package for tensorflow (which AFAIK is needed to get tensorflow installed from the sources).

**Comment by girving** [comment]
Looks like this fell through the cracks.  Does anyone know if this is still an issue?

**Comment by girving** [comment]
Closing due to lack of response.
