### ISSUE TITLE
Transfer learning tutorial

### ISSUE THREAD

**Issue by FreakTheMighty** [tensorflow/tensorflow#504]
The [image recognitions tutorial](https://www.tensorflow.org/versions/master/tutorials/image_recognition/index.html#usage-with-python-api) suggests exploring transfer learning as an exercise. I would like to see a tutorial dedicated to the topic and would be especially interested in transfer learning using the Inception-V3 model.

**Comment by FreakTheMighty** [comment]
If there is anyone with more knowledge than me, I'd be interested in collaborating on this.

**Comment by alxndrkalinin** [comment]
+1

**Comment by bhack** [comment]
It could be interesting to add something about extension of net archs without scratch retraining if there are plans to introduce [Net2Net](http://arxiv.org/abs/1511.05641) in Tensorflow. There is already an [initial Torch implementation](https://github.com/soumith/net2net.torch).

**Comment by FreakTheMighty** [comment]
I think this Caffe tutorial is a pretty good template http://caffe.berkeleyvision.org/gathered/examples/finetune_flickr_style.html

**Comment by matt-may** [comment]
+1

**Comment by sthomp** [comment]
+1

**Comment by bhack** [comment]
@goodfeli Is there any plan to make a PR of your Net2Net tensorflow implementation?

**Comment by goodfeli** [comment]
@bhack Currently there is no plan in place. Tianqi wrote our Net2Net implementation during his summer internship, before TensorFlow was ready for release. API changes to TensorFlow that preceded the release broke the Net2Net code. I currently don't have time to repair it because I am working full time on the Deep Learning textbook (www.deeplearningbook.org).

Also, Net2Net is "knowledge transfer" which is different from "transfer learning." Transfer learning is when one net does well on two tasks, because it can transfer something it has learned from the first task to the second task. Knowledge transfer is when two nets do well on the same task, because the second net has copied the knowledge of how to do the task from the first.

**Comment by bhack** [comment]
Thank you I did not know this specific sub-differientation. I thought that you can easily mix both: transfer on another task and then let the arch to expand in width and depth to better adapt on the new task.

**Comment by aum12** [comment]
+1

**Comment by martinwicke** [comment]
Check out examples/image_retraining on master. It's not a tutorial yet, but @petewarden is working on it.

**Comment by matt-may** [comment]
@martinwicke This is fantastic! Thanks for alerting us.

**Comment by petewarden** [comment]
To be explicit this is an example of retraining the final layer of Inception and leaving the convolutional weights untouched. We see this as being at one end of the spectrum; it's extremely quick to train (e.g. 30 mins on a single CPU), but won't give quite as good results as fine-tuning all the weights (which takes longer).

We plan to support full retraining too, and training from scratch, but wanted to make this example available as soon as it was complete. We haven't updated the website yet (we're still sorting out the large protobuf loading issue that currently requires hacks to the protobuf lib source - #836) but the usage guide is here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/image_retraining/index.md

**Comment by matt-may** [comment]
@petewarden Pete, this is a great start. Thanks for your work on this.

**Comment by aum12** [comment]
Agreed. Thanks Pete

**Comment by billidani7** [comment]
@petewarden Thank you for this great work. We are waiting full retraining too.

**Comment by billidani7** [comment]
@petewarden  I  follow the instructions in order to retrain the model with new flower photos. I put both  new output files (pb and txt file) to the label image example. I get this error

`E tensorflow/examples/label_image/main.cc:302] Running model failed: Not found: FetchOutputs node softmax: not found`

**Comment by petewarden** [comment]
You need to pass in the name of the new output layer, 'final_output', as the output_layer flag to label_image. I'll update the tutorial documentation to add this info, apologies for the confusion.

**Comment by amansourati** [comment]
+1

**Comment by syed-ahmed** [comment]
Can anyone help me out in modifying the android demo? I successfully trained with the flowers data set and put the .pb and .txt and in the assets folder and did the respective changes to the names of the files in the source code. When I ran it, I didn't see any labelling happening. I tried changing the number of classes in the TensorFlowListener class but that didn't do anything. I believe I have to do something similar to as @petewarden mentioned with the output_layer flag(?!) but I don't know where to do that in the android demo.

**Comment by syed-ahmed** [comment]
@petewarden Hi pete, I also ran the label image example and the --output_layer flag should point to 'final_result' but not 'final_output' as it is defined in the retrain.py

**Comment by syed-ahmed** [comment]
Some more things I tried to do with the android demo were changing the output_tensor_names output:0 to pool_3, pool_3:0, softmax and input tensor name input:0 to Mul, Mul:0. I am confused that in the main.cc of label images example, Mul and pool3 etc. works whereas output:0 and input:0 don't work and this is the opposite case in the android demo.

**Comment by petewarden** [comment]
Apologies for my typo above, I've corrected it to read final_result. I will also be adding examples of how to load the models in label_image and classify_image.py.

The port/without port syntax is confusing too, I'll look into why that's different between the demos. In general we use the bare name to reference an operator, and the port version to grab the output of an op.

**Comment by syed-ahmed** [comment]
@petewarden Hi Pete, thank you for your reply. I have been hammering on this all day and still haven't figured it out. I noticed there is a GraphDefBuilder that creates the nodes for the label_image example. Where is that in the Android Demo? Are the nodes created in some different way? If so, is it possible that not having the GraphDefBuilder is causing the port/without port problem? Ty.

**Comment by petewarden** [comment]
The Android code doesn't use GraphDefBuilder, it just loads the file directly into a GraphDef:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/jni/tensorflow_jni.cc#L91
As long as you make sure you've added your model file as an asset, that should work to load it.

There are some additional parameters you'll need to change, like the input image size and the 'mean' to subtract from all the inputs, and you'll need to add a standard deviation parameter too:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/jni/tensorflow_jni.cc#L45

If you look at the default values for those flags in label_image, that should help.

What's the exact error that you're hitting by the way? That may help be more targeted in my ideas.

**Comment by syed-ahmed** [comment]
@petewarden hi Pete, thanks for your help. The error is that when I load the retrained model with the new label file into the Android demo, I don't see any classification happening when I point the camera to a rose or a tulip.

**Comment by syed-ahmed** [comment]
@petewarden I guess I shouldn't be calling it an error. Thing is I want to replicate your Image_retrain example on the android demo. The part of the tutorial where it says to change --outut_layer = final_result,  I want to do that in the android demo after loading retrained model since I'm assuming the android demo's output layer is not pointing to the final_result.

**Comment by petewarden** [comment]
I've filed #1253 to cover the work involved in updating the Android demo to accept a retrained model. There are no major code changes required, but it is a bit fiddly to find all the places where references are made to input and output layer names and other model-specific attributes. I think it will be easier to code up the changes than to try to explain them all, but I don't have an ETA for when I'll be able to get to this unfortunately.

**Comment by syed-ahmed** [comment]
@petewarden Thanks pete.

**Comment by billidani7** [comment]
We would like to see this tutorial compatible with your new tensor flow serving project. Its very important to use this powerful mechanism remotely and get classification results for images. 

@petewarden I would greatly appreciate it if you could provide us a tutorial on how to send an image to a tensorflow serving server and get a response with the results.

Regards

**Comment by syed-ahmed** [comment]
@petewarden Hi Pete, I was able to load the newer inception model and a retrained version as well in the android demo. I have written a short reply to #1269 . The kernels BUILD file was missing "batch_norm_op" and "check_numerics_op". Adding them, changing the input node and output node to "Mul" and "final_result" (or "softmax" for the newer model), and increasing the protobuf file limit fixed the whole issue.

**Comment by savage7** [comment]
@syed-ahmed 
Is your model just loading or also correctly recognizing your trained images? I looked at the label_image code and there is a difference in mapping rgb->float values in the Android code which I had to change. 
My current model uses a not very good training set so I'm not 100% sure if the solution is correct...

What I did to fix the mapping of the rgb-> float values:

Original label_image code after loading the Images:
`tensorflow::ops::Div(tensorflow::ops::Sub(
                                              input_tensor, tensorflow::ops::Const({g_image_mean}, b.opts()), b.opts()),
                         tensorflow::ops::Const({g_image_mean}, b.opts()),
                         b.opts().WithName("final_result"));`

Original Android code snippet:
 `input_tensor_mapped(0, i, j, 0) =  static_cast<float>(src->red) - g_image_mean;`

What is missing the the div by g_image_mean in mapping of the int->float rgb values:
`input_tensor_mapped(0, i, j, 0) =  (static_cast<float>(src->red) - g_image_mean)/g_image_mean;`

Now my images a recognized correctly.

**Comment by syed-ahmed** [comment]
@savage7 yes, the model is correctly recognizing images. You are right that there is a difference in implementation between the label_image and android demo. I have seen that the android demo doesn't use the division op using the standard dev that is done in the label_image. I guess that is because of the way the input tensor is being filled up (mapping RGB values) in the android demo. 

I tried doing the division you mentioned some days ago but it turned out that wasn't the problem. The BUILD file of the kernels was missing the "batch_norm_op" and the "check_numerics_op".

**Comment by petewarden** [comment]
The division sounds like it will give the correct results, but for the wrong reasons. :)

The key difference between the current Android demo code and the label_image example is that they use different versions of the Inception model. The current Android model requires a divisor of 1, and a subtraction of 117. You can see the image mean defined here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorflowImageListener.java#L51
Since the divisor is 1, it's ignored in the current code.

To load the model that's used in label_image and image_retraining, you need to use a subtraction of 128 and a division of 128. You can see those values as mean and std in the command-line arguments here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/main.cc#L246

**Comment by syed-ahmed** [comment]
@petewarden Hi Pete, so I loaded the newer inception model in the android demo with the input size of 299 and mean of 128. I got "correct recognition" however, I didn't divide the RGB values with 128 in the tensorflow_jni.cc. The division part looks like what we do in standardizing a random variable that is normally distributed? So since I didn't divide it with 128, does it mean that the recognition is still happening but since it's not standardized, it may fail for some cases?

**Comment by oweingrod** [comment]
@petewarden Thank you so much for providing this tutorial. I'm working through it, attempting to use my retrained graph with the image_classify.py file, and I'm having issues with reading the graph back. I get this error:

`KeyError: "The name 'softmax:0' refers to a Tensor which does not exist. The operation, 'softmax', does not exist in the graph."`

Since the "output_graph.pb" file should in theory be the same as the "classify_image_graph_def.pb" file, is there a command that I am missing to make the "output_graph.pb" file readable by the image_classify.py file?

Thanks

Oren

**Comment by syed-ahmed** [comment]
Try "final_result" for the tensor name.

**Comment by oweingrod** [comment]
@syed-ahmed thanks for your help! That got me a little bit farther, but there's a fun new error now:

`Invalid argument: NodeDef mentions attr 'align_corners' not in Op<name=ResizeBilinear`

**Comment by oweingrod** [comment]
I was able to fix this error by updating Tensorflow—however, it does not seem like my new labels are able to be printed. Is there a way to generate a UID lookup file for our new graph?

**Comment by petewarden** [comment]
Sorry you're hitting problems! Are you loading the new labels file with the --labels command line flag? Here's a full example, from https://www.tensorflow.org/versions/master/how_tos/image_retraining/index.html#using-the-retrained-model

```
bazel build tensorflow/examples/label_image:label_image && \
bazel-bin/tensorflow/examples/label_image/label_image \
--graph=/tmp/output_graph.pb --labels=/tmp/output_labels.txt \
--output_layer=final_result \
--image=$HOME/flower_photos/daisy/21652746_cc379e0eea_m.jpg
```

**Comment by oweingrod** [comment]
@petewarden Everything works fantastically if I do it with Bazel, but I'm trying to use the output_graph.pb files and output_labels.txt files with the image_classify.py file, not just the label image example.

**Comment by eldor4do** [comment]
@oweingrod Hi, did you get your code working?

**Comment by oweingrod** [comment]
Yes. You have to manually write the ".pbtxt" file so your UIDs can map with your classes.

**Comment by dhananjaymehta** [comment]
Hi, I am working on retraining Inception's Final Layer for New Categories. I am following steps at - https://www.tensorflow.org/versions/master/how_tos/image_retraining/index.html#training
The build step(bazel build -c opt --copt=-mavx tensorflow/examples/image_retraining:retrain)for the retrainer is working good. But when I try to run the second step -   bazel-bin/tensorflow/examples/image_retraining/retrain --image_dir ~/flower_photos, I encounter below error : -bash: bazel-bin/examples/image_retraining/retrain.py: No such file or directory
I would appreciate some help or suggestions on this. Thanks.

**Comment by martinwicke** [comment]
@dhananjaymehta: I would file a separate bug for that issue.

**Comment by dhananjaymehta** [comment]
@martinwicke Thanks for the suggestion, I will open a new bug for the issue.

**Comment by josefmonje** [comment]
@oweingrod: can you point me to where i can learn how that is done (re: "*.pbtxt")?
got past `KeyError: "The name 'softmax:0' refers to a Tensor which does not exist. The operation, 'softmax', does not exist in the graph."` and it's the key to my next problem.
```
  File "tensorflow/models/image/imagenet/classify_image.py", line 82, in __init__
    self.node_lookup = self.load(label_lookup_path, uid_lookup_path)
  File "tensorflow/models/image/imagenet/classify_image.py", line 125, in load
    name = uid_to_human[val]
KeyError: 'n02119789'
```

**Comment by eldor4do** [comment]
@josefmonje If you're retraining on your own images, then the label files which are generated will also be different. The default code uses two different files to map whatever prediction the model gave, into the human readable form. Is your data set also like that?

**Comment by josefmonje** [comment]
@eldor4do: i have output_graph.pb and output_labels.txt from retraining. i'm missing the .pbtxt file this part of the code is supposed to look for it.

**Comment by eldor4do** [comment]
@josefmonje Check from here, maybe this will be useful. https://github.com/eldor4do/Tensorflow-Examples/blob/master/retraining-example.py#L82
I do not think it needs the .pbtxt file, only the output_labels.txt file should be enough.

**Comment by josefmonje** [comment]
thanks @eldor4do! worked for me. made some edits to work with Python 3 and sent PR 👍

**Comment by petewarden** [comment]
That's a very useful example @eldor4do, thanks! I will update the docs to point to that, if you don't mind?

**Comment by eldor4do** [comment]
@petewarden Sure,  no problem!
@josefmonje welcome! and i merged your PR

**Comment by girving** [comment]
@petewarden: This thread seems to have deviated quite a bit from the original request.  Should we mark it resolved and reopen other issues as required?

**Comment by martinwicke** [comment]
+1

**Comment by girving** [comment]
Resolving for now, please open more specific issues if problems persist, or ask on StackOverflow if  you have questions.

**Comment by Bruczzz** [comment]
@syed-ahmed .
Can you please tell me how you created .pb file from model.ckpt.
Thanks.

**Comment by syed-ahmed** [comment]
@Bruczzz Hi, you can check out this script: [freeze_graph.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py). Also, pete warden has posted a nice documentation on deployment. Check it out: [Graph Transform Tool](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md)

**Comment by Bruczzz** [comment]
Thanks @syed-ahmed .
I tried retraining model specified in https://github.com/tensorflow/models/blob/master/inception/README.md
 and i tried this on CPU version of tensorflow . i can create model.ckpt files and checkpoints. How to convert into .pb file .
And I tired https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/image_retraining/index.md
this way also. gen/head is not declared error occurred ... so i tried running ./configure , this is asking for cuda version and location. but i am not using GPU version. I dont know how to proceed further? Can you Please help?

**Comment by Bruczzz** [comment]
@syed-ahmed  I have figured out the issue. Its running fine now .

**Comment by vishalghor** [comment]
Hi @petewarden ,

Thanks for such a usefull example for retraining inception.
But this sample uses a .pb file for retraining.Is there a method to use .ckpt for retraining?
If so any sample code would be of great help.
There is not much clarity if the same can be done for other opensource models such as Resnet50,101, etc

It would be very kind of you if you could guide on this.

Thank

**Comment by cy89** [comment]
@Bruczzz it sounds like you were able to get around your .ckpt->.pb file problems. Can you please share what the fix was?

**Comment by Syzygy2048** [comment]
@cy89 since I also managed to do transfer learning with checkpoints I might as well chime in.

Note that this is using tf.slim
`import tensorflow as tf
from tensorflow.contrib.slim.nets import inception as nn_architecture
from tensorflow.contrib import slim

with slim.arg_scope(nn_architecture.inception_v3_arg_scope()):
    logits, endpoints = nn_architecture.inception_v3(images, 
                                                     num_classes=10,
                                                     is_training=True)

retrain = ['InceptionV3/Logits', 'InceptionV3/AuxLogits', 'InceptionV3/Mixed_7c', 'InceptionV3/Mixed_7b'] #these nodes are not loaded from the checkpoint and are left uninitialized  
variables_to_restore = slim.get_variables_to_restore(exclude=retrain)  # this checks the current graph, so no custom nodes can be defined at this point, only those from create_network()

sess = tf.Session()
saver = tf.train.Saver(variables_to_restore)
saver.restore(sess, CHECKPOINT_PATH)

variables_to_train = tf.trainable_variables('InceptionV3/Logits') + tf.trainable_variables('InceptionV3/AuxLogits') + tf.trainable_variables('InceptionV3/Mixed_7c') + tf.trainable_variables('InceptionV3/Mixed_7b')

train_step = slim.learning.create_train_op(total_loss, optimizer, variables_to_train=variables_to_train) `
