### ISSUE TITLE
Tensorflow 2.6 built without s3 support.

### ISSUE THREAD

**Issue by bacek** [tensorflow/tensorflow#51583]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian Linux, python 3.7. 
- TensorFlow installed from (source or binary): binary using pip
- TensorFlow version: 2.6.0
- Python version: 3.7, 3.8
- Installed using virtualenv? pip? conda?: venv, conda

**Describe the problem**

tensorflow 2.6.0 built without s3 support however it was made default since 1.4.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

```
$ pip install tensorflow==2.6.0
Collecting tensorflow==2.6.0
  Downloading tensorflow-2.6.0-cp37-cp37m-manylinux2010_x86_64.whl (458.3 MB)
     |████████████████████████████████| 458.3 MB 31 kB/s 
...
Installing collected packages: tensorflow
  Attempting uninstall: tensorflow
    Found existing installation: tensorflow 2.4.1
    Uninstalling tensorflow-2.4.1:
      Successfully uninstalled tensorflow-2.4.1
Successfully installed tensorflow-2.6.0

$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tensorflow.python.lib.io import file_io
2021-08-20 08:47:18.398430: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-08-20 08:47:18.398446: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> print(file_io.stat("s3://bucket/model"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bacek/miniconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 871, in stat
    return stat_v2(filename)
  File "/home/bacek/miniconda3/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 887, in stat_v2
    return _pywrap_file_io.Stat(compat.path_to_str(path))
tensorflow.python.framework.errors_impl.UnimplementedError: File system scheme 's3' not implemented (file: 's3://bucket/model')
>>> 

```

**Comment by mihaimaruseac** [comment]
This is intended. It is part of [modularization project](https://github.com/tensorflow/community/blob/master/rfcs/20190506-filesystem-plugin-modular-tensorflow.md) from 2 years ago and has been announced well in advance.

[SIG IO](https://github.com/tensorflow/io) now has support for these filesystems.

**Comment by mihaimaruseac** [comment]
See also #51032.

**Comment by bacek** [comment]
That PR https://github.com/tensorflow/tensorflow/pull/51432 removed update on Modular Filesystem from `RELEASE.md`.

**Comment by ConverJens** [comment]
@mihaimaruseac Is there any documentation on how to enable S3 support with tfio? I assume dtfio should only need to be installed for this to work but I still get the same error message.

**Comment by yongtang** [comment]
@ConverJens  The way to use s3 is to just import tfio:
```
import tensorflow as tf
import tensorflow_io as tfio

v = tf.io.read_file('s3://1234567')
```

That will give you the s3 access.

**Comment by ConverJens** [comment]
@yongtang Thanks for the clarification!

I'm using TFX from master which recently started depending on TF 2.6, hence I can't (or don't want to/shouldn't) modify the internals. I suspect they will fix this by the next release.

**Comment by yongtang** [comment]
@ConverJens In case of TFX I think you may want to create issue there. @bacek can you confirm the issue is resolved with tfio installation?

**Comment by bacek** [comment]
Yes, installing and explicitly importing tfio fixed this issue. However
RELEASE.md needs updating.

**Comment by w4-hyunseok** [comment]
I reached out to resolve a similar error. 

By using https://github.com/tensorflow/tensorflow/issues/51583#issuecomment-902786636 comment, 
I succeeded to use tf.io.gfile APIs such as tf.io.gfile.exists and so on. 

But tf.io.gfile.rename still failed when I run the below codes. 

```
(py37) hyunseok@poc-gpu1:~/work/w4$ python
Python 3.7.9 (default, May 23 2021, 05:54:20)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-09-08 05:30:51.506696: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-08 05:30:51.506723: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> import tensorflow_io as tfio
>>> tf.io.gfile.exists('s3://aiq-poodle-dev/test/test.txt')
True
>>> tf.io.gfile.rename('s3://aiq-poodle-dev/test/test.txt', 's3://aiq-poodle-dev/test/test-new.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hyunseok/.venv/py37/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 626, in rename_v2
    compat.path_to_bytes(src), compat.path_to_bytes(dst), overwrite)
tensorflow.python.framework.errors_impl.InvalidArgumentError: InvalidRequest: Unable to parse ExceptionName: InvalidRequest Message: You must specify at least one part
>>>
```

**Comment by andrey-klochkov-liftoff** [comment]
@yongtang ,
Importing `tensorflow_io` doesn't always fix it. In my case it doesn't work when I execute from a PEX file. PEX has all the dependencies including tfio, and I do import `tensorflow_io` but I get the error stated in the description. When executed with dependencies installed by pip, it works. What is the mechanism that is used to register S3 support in tensorflow itself? Is there any way I can trigger it explicitly rather than by importing `tensorflow_io`?

**Comment by yongtang** [comment]
@andrey-klochkov-liftoff I don't have experience with PEX file. Can you share a minimal reproducible steps that exposes the issue you mentioned. Also, are you running on Windows or Linux/macOS? Note s3 (and gcs) may not work correctly on Windows yet due to #49515 (which will be fixed if PR #49520 can be merged)

**Comment by andrey-klochkov-liftoff** [comment]
@yongtang , it's hard for me to create a minimal reproducible artifact that'd demo the problem. Still, I think I see why it's happening. The `tensorflow_io_gcs_filesystem==0.20.0` wheel contains file `tensorflow_io/python/ops/__init__.py` that attempts to load library `libtensorflow_io.so` and fails to do so as this library is not included into this wheel package. It seems to me that the intention was to make the gcs package load only `libtensorflow_io_gcs_filesystem.so` and initiate loading of the other tfio libraries from the `tensorflow_io` package, but that's not how it works under certain circumstances. It's hard to pinpoint when exactly `tensorflow_io_gcs_filesystem` starts initializing before `tensorflow_io` and so syspath would contain package `tensorflow.core.ops` pointing to `tensorflow_io_gcs_filesystem`, making it impossible to load the libraries.

**Comment by yongtang** [comment]
@andrey-klochkov-liftoff the `tensorflow_io_gcs_filesystem` will provide an alternative gcs support for tensorflow. However, if you are referring to s3 support then the invocation happens:
https://github.com/tensorflow/io/blob/master/tensorflow_io/python/ops/__init__.py#L96

**Comment by andrey-klochkov-liftoff** [comment]
@yongtang , if you download the `tensorflow_io_gcs_filesystem` wheel and unpack it, and grep for `libtensorflow_io.so`, you'll see that it contains a copy of the source file you're referring to:

```
$ pip download tensorflow_io_gcs_filesystem==0.20.0
Collecting tensorflow_io_gcs_filesystem==0.20.0
Saved ./tensorflow_io_gcs_filesystem-0.20.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Successfully downloaded tensorflow-io-gcs-filesystem

$ unzip ./tensorflow_io_gcs_filesystem-0.20.0-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
# output skipped

$ rg libtensorflow_io.so
tensorflow_io_gcs_filesystem-0.20.0.data/purelib/tensorflow_io/python/ops/__init__.py
94:core_ops = LazyLoader("core_ops", "libtensorflow_io.so")
99:    # Note: load libtensorflow_io.so imperatively in case of statically linking
101:        core_ops = _load_library("libtensorflow_io.so")
102:        plugin_ops = _load_library("libtensorflow_io.so", "fs")
```

**Comment by andrey-klochkov-liftoff** [comment]
@yongtang , the root cause is the way the packages are built. Here are the steps demoing the problem:

1. Build `tensorflow-io` wheel with 

    python setup.py bdist_wheel

2. Build `tensorflow-io-gcs-filesystem`:

    python setup.py bdist_wheel --project tensorflow-io-gcs-filesystem 

3. Check if `tensorflow_io` sources are included in the package (they shouldn't but they are):

    unzip -l dist/tensorflow_io_gcs_filesystem-0.20.0-cp38-cp38-macosx_11_0_x86_64.whl | grep 'tensorflow_io/' | wc -l 
    103
    
If I remove the `build` directory after step (1), then the package created at step (2) wouldn't contain `tensorflow_io` files. From a quick search at stackoverflow and `setuptools` docs, it seems there's no easy way to make `setuptools` do such clean up automatically from `setup.py` but `python setup.py clean -a` can be used between steps. 

That's exactly what was done by #1476 but by some reason the `tensorflow_io_gcs_filesystem==0.20.0` package at pypi.org still has that problem while `0.21.0` doesn't have it. 

I guess no action is necessary. I'm posting all these details for those who can stumble into the same issue.

**Comment by yongtang** [comment]
@andrey-klochkov-liftoff yes the issue was fixed and applied in 0.21.0. For 0.20.0 as pip did not allow updating already published packages so we have to leave as is.

**Comment by w4-hyunseok** [comment]
@yongtang 

Are there any guide to resolve tf.io.gfile.rename issue? https://github.com/tensorflow/tensorflow/issues/51583#issuecomment-914930409 

I tested it both Mac and Linux env with tensorflow-io==0.21.0 by using python3.7 new venv.

**Linux**
```
$ python
Python 3.7.9 (default, May 23 2021, 05:54:20)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2021-09-15 00:44:44.535239: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-09-15 00:44:44.535265: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> import tensorflow_io as tfio
>>> tfio.__version__
'0.21.0'
>>> tf.io.gfile.exists('s3://aiq-poodle-dev/test/test.txt')
True
>>> tf.io.gfile.rename('s3://aiq-poodle-dev/test/test.txt', 's3://aiq-poodle-dev/test/test-new.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hyunseok/.venv/py37/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 624, in rename_v2
    compat.path_to_bytes(src), compat.path_to_bytes(dst), overwrite)
tensorflow.python.framework.errors_impl.InvalidArgumentError: InvalidRequest: Unable to parse ExceptionName: InvalidRequest Message: You must specify at least one part
```

**Mac**
```
(py37) hyunseok:w4$ python
Python 3.7.9 (v3.7.9:13c94747c7, Aug 15 2020, 01:31:08)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> import tensorflow_io as tfio
>>> tfio.__version__
'0.21.0'
>>> tf.io.gfile.exists('s3://aiq-poodle-dev/test/test.txt')
True
>>> tf.io.gfile.rename('s3://aiq-poodle-dev/test/test.txt', 's3://aiq-poodle-dev/test/test-new.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hyunseok/.venv/py37/lib/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 624, in rename_v2
    compat.path_to_bytes(src), compat.path_to_bytes(dst), overwrite)
tensorflow.python.framework.errors_impl.InvalidArgumentError: InvalidRequest: Unable to parse ExceptionName: InvalidRequest Message: You must specify at least one part
```

**Comment by tilakrayal** [comment]
@bacek ,
As per the [comment](https://github.com/tensorflow/tensorflow/issues/51583#issuecomment-919613341) from google developer this issue has resolved. Could you feel free to move this issue to closed status. Thank you!

**Comment by bacek** [comment]
Yes, explicitly adding tfio fixed original issue.

**Comment by shanks0739** [comment]
pip install tensorflow-io  . This package needs to be installed separately

**Comment by rivershah** [comment]
This has been a horrible refactor. `tensorflow-io` is basically abandoned and now no more `s3` support.

**Comment by mihaimaruseac** [comment]
https://etils.readthedocs.io/en/latest/epath.html

This is much simpler than TF's interface and doesn't require you to install TF to use (in almost all cases). It is also supported, and depended upon by a lot of other projects.

To be fair, lately, most changes to TF are on XLA (which was not properly separated, the same changes occur on OpenXLA repo) and to serve separation of other components. Swan song.

**Comment by rivershah** [comment]
This won't work as we need to graph serialise ops. Need underlying tensorflow C++ code to be handling this
