### ISSUE TITLE
GPU not found when using TF 2.5.0 in Google Colab

### ISSUE THREAD

**Issue by sam351** [tensorflow/tensorflow#51724]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.5.0
- Python version: 3.7.11
- CUDA/cuDNN version: V11.0.221
- GPU model and memory: Tesla K80
<br>

**Describe the current behavior**
- I installed `tensorflow 2.5.0` in colab
- After installation, I imported `tensorflow` and checked available GPU device
- However, `tf.config.experimental.list_physical_devices('GPU')` returns an empty list.
- I already checked GPU deivce with `nvidia-smi`
<br>

<ins>Is there any problem the way I ran below code?</ins>
<br>

**Standalone code to reproduce the issue**
```
!pip install tensorflow==2.5.0
import tensorflow as tf
!nvidia-smi
print(f"tf ({tf.__version__})")
print(f"gpus : {tf.config.experimental.list_physical_devices('GPU')}")
```

**Comment by Saduf2019** [comment]
@sam351 
It is working as expected now, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/6e1e708ca606ef8753522e65f9d80567/2_5.ipynb),and [2.5](https://colab.research.google.com/gist/Saduf2019/f63a8fc68e6499862e4cac97bf2a052b/untitled632.ipynb). Please move this to closed status as this is resolved and this repo is only for performance related issues and bugs for tensorflow.

**Comment by DenysMenfredy** [comment]
@Saduf2019 Still not working here... I am able to see a gpu when I put nvidia-smi but when I try to list GPU's using tf.config it returns an empty list... This update to tensorflow 2.6 broke so many things in colab, like saving models using tf.save it's a headache now

**Comment by sam351** [comment]
@Saduf2019 I moved to the link(gist) that you shared, and ran it in colab. However, it's not working as expected, unlike the saved outputs of the notebook that you've shared. Even in your notebook, the first cell doesn't show any available gpu (that is, it shows an empty list)
By the way, if this repo is not for asking this kind of question, where should I ask? I'm not familiar with the conventions about repos, so hope your help to know how to ask appropriate questions in appropriate place.

Thank you in advance :)

**Comment by Saduf2019** [comment]
@sam351 @DenysMenfredy 
I ran the code again and it working as expected.
Can you please create an issue in the colab repo in case it still persist. @sam351 if an issue is not related performance or a tf bug/feature request, you may open it in the tf [discussion forum](https://discuss.tensorflow.org/) as it has a large community to support and respond.
