### ISSUE TITLE
Failing to Quantize for Edge TPU. Requires tf.float32 type for conversion but tf.uint8 for Edge

### ISSUE THREAD

**Issue by nneubert** [tensorflow/tensorflow#52933]
I am attempting to quantize a model post creation for use on a coral product. This requires me to quantize the model, unfortunately quantization throws a significant error. Below is the architecture of my model and associated Colab notebook showing the error. In short, the model successfully converts to a tflite when I allow the input and output to be tf.float32, which renders a TPU useless, but when I code the model to adjust the input and output to tf.uint8 I get a ValueError. 

I have spoken with Coral extensively and they have referred me here. I really hope you can help out!

 1. System information

- Windows 10
- TensorFlow installation Anaconda
- TensorFlow library: 2.6.0

 2. Code

https://colab.research.google.com/drive/1CdjguiaWf-M5VXv9mqmfcbJXrGt7m-xt?usp=sharing

Error log

Log from Edge TPU compiler when input output is allowed to be tf.float32

Edge TPU Compiler version 16.0.384591198
Started a compilation timeout timer of 180 seconds.

Model compiled successfully in 472 ms.

Input model: IVUS_v1.tflite
Input size: 133.24MiB
Output model: IVUS_v1_edgetpu.tflite
Output size: 133.23MiB
On-chip memory used for caching model parameters: 0.00B
On-chip memory remaining for caching model parameters: 0.00B
Off-chip memory used for streaming uncached model parameters: 0.00B
Number of Edge TPU subgraphs: 0
Total number of operations: 81
Operation log: IVUS_v1_edgetpu.log

Model successfully compiled but not all operations are supported by the Edge TPU. A percentage of the model will instead run on the CPU, which is slower. If possible, consider updating your model to use only operations supported by the Edge TPU. For details, visit g.co/coral/model-reqs.
Number of operations that will run on Edge TPU: 0
Number of operations that will run on CPU: 81

Operator                       Count      Status

CONV_2D                        28         Operation is working on an unsupported data type
TRANSPOSE_CONV                 7          Operation is working on an unsupported data type
LOGISTIC                       1          Operation is working on an unsupported data type
FULLY_CONNECTED                1          Operation is working on an unsupported data type
ADD                            1          Operation is working on an unsupported data type
PRELU                          28         Operation is working on an unsupported data type
MAX_POOL_2D                    7          Operation is working on an unsupported data type
CONCATENATION                  7          Operation is working on an unsupported data type
MUL                            1          Operation is working on an unsupported data type
Compilation child process completed within timeout period.
Compilation succeeded!

**Comment by nneubert** [comment]
https://drive.google.com/drive/folders/1Edy4ARMLZOIDuS_3Is4u_bXf6Paa3M97?usp=sharing

This is a link to the data I used.

**Comment by nneubert** [comment]
Update: My model successfully compiles on tensorflow version 2.2.0 but I have to remove the PreReLU activation function.
https://colab.research.google.com/drive/1jR1nRQ1PK2nxUaQFHvYQPVJjs5cki5dI?usp=sharing

**Comment by sachinprasadhs** [comment]
PReLU has some limitations on edge TPU. 
`Alpha must be 1-dimensional (only the innermost dimension can be >1 size). If using Keras PReLU with 4D input (batch, height, width, channels), then shared_axes must be [1,2] so each filter has only one set of parameters.`
Instead you can use RELU which doesn't have any limitations on edge TPU.
For all the limitations, refer [this](https://coral.ai/docs/edgetpu/models-intro/#supported-operations) table.

**Comment by nneubert** [comment]
I am confused, as I have only one value in PReLU. Is there some way I could alter that function to work properly instead of using ReLU?

**Comment by nneubert** [comment]
Also, replacing PReLU alone did not resolve the issue. I have to revert to an older version of Tensorflow.

**Comment by sachinprasadhs** [comment]
Did  you try with nightly version and the details in the above linked document?

**Comment by nneubert** [comment]
I am not sure what you mean by nightly version but I am in compliance with the linked document. I was in conversation with them for several days discussing what to do. They had access to my full architecture.

**Comment by nneubert** [comment]
How do I use the nightly version?

**Comment by sachinprasadhs** [comment]
You can install the nightly version by `pip install tf-nightly` and then import tensorflow by `import tensorflow as tf`

**Comment by nneubert** [comment]
I will try that version. I am making my way up the versions testing each one. Version 2.4.4 works correctly but version 2.5.0 yields the following error: ValueError: The inference_input_type and inference_output_type must be tf.float32.

**Comment by nneubert** [comment]
Also, I have removed all PreReLU functions for now. 

Nightly results in the same error.

**Comment by sachinprasadhs** [comment]
in Tensorflow 2.4.4 does it work perfectly even with PReLU?

**Comment by nneubert** [comment]
In Tensorflow 2.4.4 it quantizes correctly however it does not compile in the Edge compiler. I have found that the latest version to both quantize and compile properly is 2.2.3. This functions properly even with PReLU

**Comment by nneubert** [comment]
This is the working version with tf 2.2.3: https://colab.research.google.com/drive/1jR1nRQ1PK2nxUaQFHvYQPVJjs5cki5dI?usp=sharing

**Comment by nneubert** [comment]
Also of importance is to note that while model quantizes in 2.4.4, interpretation of the model as written in the last block fails.

**Comment by nneubert** [comment]
Beginning in Version 2.3.0 the following error is generated when trying to use a lite interpreter on the quantized model.

Code:

# Load the TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model_path="IVUS_v1.tflite")
interpreter.allocate_tensors()

# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)


Error:

---------------------------------------------------------------------------

RuntimeError                              Traceback (most recent call last)

<ipython-input-18-8e65e7ad1c2d> in <module>()
      1 # Load the TFLite model and allocate tensors.
      2 interpreter = tf.lite.Interpreter(model_path="IVUS_v1.tflite")
----> 3 interpreter.allocate_tensors()
      4 
      5 # Get input and output tensors.

/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/interpreter.py in allocate_tensors(self)
    241   def allocate_tensors(self):
    242     self._ensure_safe()
--> 243     return self._interpreter.AllocateTensors()
    244 
    245   def _safe_to_run(self):

RuntimeError: tensorflow/lite/kernels/conv.cc:334 bias->type != kTfLiteInt32 (INT8 != INT32)Node number 1 (CONV_2D) failed to prepare.

**Comment by nneubert** [comment]
This bug seems to have been forgotten in the pipeline.

**Comment by daverim** [comment]
Hi nneubert@, this can happen when a bias is used in another operator as an input or weight. This issue was fixed in 2.5, so I would suggest you run the tflite converter from 2.5 with representative dataset again on your saved model.

**Comment by nneubert** [comment]
@daverim Thank you for your suggestion. I attempted this code with 2.5.0 and 2.6.0 just today and received the following error twice

INFO:tensorflow:Assets written to: /tmp/tmpk9v24yxv/assets

---------------------------------------------------------------------------

ValueError                                Traceback (most recent call last)

<ipython-input-10-bed7ae94e3d4> in <module>()
     17 converter.inference_input_type = tf.uint8
     18 converter.inference_output_type = tf.uint8
---> 19 tflite_model = converter.convert()
     20 
     21 with open('IVUS_v1.tflite', 'wb') as f:

8 frames

/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/lite.py in _validate_inference_input_output_types(self, quant_mode)
    805     elif (self.inference_input_type not in default_types or
    806           self.inference_output_type not in default_types):
--> 807       raise ValueError("The inference_input_type and inference_output_type "
    808                        "must be tf.float32.")
    809 

ValueError: The inference_input_type and inference_output_type must be tf.float32.

**Comment by nneubert** [comment]
Is anyone looking into this anymore?

**Comment by nneubert** [comment]
> Hi @nneubert, this can happen when a bias is used in another operator as an input or weight. This issue was fixed in 2.5, so I would suggest you run the tflite converter from 2.5 with representative dataset again on your saved model.

Just want to let you know that the issue is not fixed. I can get TF version 2.2.3 to successfully quantize using this code here: https://colab.research.google.com/drive/1jR1nRQ1PK2nxUaQFHvYQPVJjs5cki5dI#scrollTo=NfHYCknyAqvT However it does not quantize in version 2.5 or version 2.7. If there is anything you can do to assist, please help.

**Comment by mohantym** [comment]
Hi @nneubert ! I used inference_input_type and inference_output_type as tf.float32 as the  error suggested. Attaching [Gist](https://colab.sandbox.google.com/gist/mohantym/6edc71631e6e86d39abc2032a87a4f7f/version-2-2-3.ipynb#scrollTo=2qQwyeMHAnZE) for reference. Thanks!

**Comment by mohantym** [comment]
Hi @nneubert !

I could replicate this issue in 2.11 . Attached [gist](https://colab.sandbox.google.com/gist/mohantym/6cc050566fa2820e5c4e3b9e1d275881/unet-edge-tpu.ipynb#scrollTo=nAGL_dzX3QaM) for reference.

Could you check with ReLU layers instead of PreLU and let us know (as I suspect PreLu layers are not fully supported in GPU delegate)
[Ref.](https://github.com/tensorflow/tensorflow/issues/59030)

Thank you!
