### ISSUE TITLE
TensorFlow Lite fails to convert LSTM after upgrading from 2.6.2 to 2.7.0.

### ISSUE THREAD

**Issue by gaonmaor** [tensorflow/tensorflow#53101]
### System information

-   Have I written custom code: yes
-   OS Platform and Distribution: Linux Ubuntu 16.04 (TensorFlow official docker images)
-   TensorFlow installed from binary
-   TensorFlow version : 2.7.0
-   Python version: 3.8.10
-   Exact command to reproduce:

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, LSTM
tf.version.VERSION
model_in = Input(shape=(800,))
model = Model(model_in, LSTM(8)(Embedding(300, 8,)(model_in)))
converter = tf.lite.TFLiteConverter.from_keras_model(model); tflite_model = converter.convert()

### Describe the problem
Tensorflow fails to convert the above model into TensorFlow lite, opposed to how it worked up to this version.

### Source code / logs
The example below shows how it used to work on version 2.6.0 and how it works now. (it was also working fine for 2.6.2)

docker run -it --rm --name tf36 tensorflow/tensorflow:2.6.0 python
Unable to find image 'tensorflow/tensorflow:2.6.0' locally
2.6.0: Pulling from tensorflow/tensorflow
feac53061382: Already exists
beba0652e867: Already exists
c5060c8118ce: Already exists
bfc0178fb9ad: Already exists
18fb3f957dc0: Already exists
cd5d06d0987e: Already exists
7ed4f7cde30b: Already exists
6bda0595411c: Already exists
Digest: sha256:773d5ce09e4ce003db02740c6a372a8a9f43be2bac23544d8f452bfec5347c53
Status: Downloaded newer image for tensorflow/tensorflow:2.6.0
Python 3.6.9 (default, Jan 26 2021, 15:33:00)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> from tensorflow.keras.models import Model
>>> from tensorflow.keras.layers import Input, Embedding, LSTM
>>> tf.version.VERSION
'2.6.0'
>>> model_in = Input(shape=(800,))
>>> model = Model(model_in, LSTM(8)(Embedding(300, 8,)(model_in)))
2021-11-17 18:10:51.093603: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> converter = tf.lite.TFLiteConverter.from_keras_model(model); tflite_model = converter.convert()
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2021-11-17 18:10:59.494222: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:absl:Found untraced functions such as lstm_cell_layer_call_fn, lstm_cell_layer_call_and_return_conditional_losses, lstm_cell_layer_call_fn, lstm_cell_layer_call_and_return_conditional_losses, lstm_cell_layer_call_and_return_conditional_losses while saving (showing 5 of 5). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: /tmp/tmpg9eczqrl/assets
INFO:tensorflow:Assets written to: /tmp/tmpg9eczqrl/assets
2021-11-17 18:11:04.174113: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:351] Ignored output_format.
2021-11-17 18:11:04.174165: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:354] Ignored drop_control_dependency.
2021-11-17 18:11:04.175758: I tensorflow/cc/saved_model/reader.cc:38] Reading SavedModel from: /tmp/tmpg9eczqrl
2021-11-17 18:11:04.203946: I tensorflow/cc/saved_model/reader.cc:90] Reading meta graph with tags { serve }
2021-11-17 18:11:04.203996: I tensorflow/cc/saved_model/reader.cc:132] Reading SavedModel debug info (if present) from: /tmp/tmpg9eczqrl
2021-11-17 18:11:04.287237: I tensorflow/cc/saved_model/loader.cc:211] Restoring SavedModel bundle.
2021-11-17 18:11:04.364667: I tensorflow/cc/saved_model/loader.cc:195] Running initialization op on SavedModel bundle at path: /tmp/tmpg9eczqrl
2021-11-17 18:11:04.412505: I tensorflow/cc/saved_model/loader.cc:283] SavedModel load for tags { serve }; Status: success: OK. Took 236769 microseconds.
2021-11-17 18:11:04.589284: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:210] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
>>>

docker run -it --rm --name tf37 tensorflow/tensorflow:2.7.0 python
Python 3.8.10 (default, Sep 28 2021, 16:10:42)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>> from tensorflow.keras.models import Model
>>> from tensorflow.keras.layers import Input, Embedding, LSTM
>>> tf.version.VERSION
'2.7.0'
>>> model_in = Input(shape=(800,))
>>> model = Model(model_in, LSTM(8)(Embedding(300, 8,)(model_in)))
2021-11-17 18:14:09.592797: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>> converter = tf.lite.TFLiteConverter.from_keras_model(model); tflite_model = converter.convert()
2021-11-17 18:14:18.728660: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:absl:Found untraced functions such as lstm_cell_layer_call_fn, lstm_cell_layer_call_and_return_conditional_losses, lstm_cell_layer_call_fn, lstm_cell_layer_call_and_return_conditional_losses, lstm_cell_layer_call_and_return_conditional_losses while saving (showing 5 of 5). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: /tmp/tmpixyhgbqk/assets
INFO:tensorflow:Assets written to: /tmp/tmpixyhgbqk/assets
2021-11-17 18:14:24.806528: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:363] Ignored output_format.
2021-11-17 18:14:24.806615: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:366] Ignored drop_control_dependency.
2021-11-17 18:14:24.808294: I tensorflow/cc/saved_model/reader.cc:43] Reading SavedModel from: /tmp/tmpixyhgbqk
2021-11-17 18:14:24.823489: I tensorflow/cc/saved_model/reader.cc:107] Reading meta graph with tags { serve }
2021-11-17 18:14:24.823535: I tensorflow/cc/saved_model/reader.cc:148] Reading SavedModel debug info (if present) from: /tmp/tmpixyhgbqk
2021-11-17 18:14:24.898508: I tensorflow/cc/saved_model/loader.cc:210] Restoring SavedModel bundle.
2021-11-17 18:14:25.002491: I tensorflow/cc/saved_model/loader.cc:194] Running initialization op on SavedModel bundle at path: /tmp/tmpixyhgbqk
2021-11-17 18:14:25.091938: I tensorflow/cc/saved_model/loader.cc:283] SavedModel load for tags { serve }; Status: success: OK. Took 283650 microseconds.
2021-11-17 18:14:25.358785: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:237] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
loc(callsite(callsite(callsite(callsite("TensorArrayV2_1@__inference_standard_lstm_654"("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1315:0) at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1280:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1080:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py":216:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1150:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1170:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":761:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":775:0 at "<stdin>":1:0)))))))) at callsite("model/lstm/PartitionedCall@__inference__wrapped_model_927"("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1315:0) at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1280:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1080:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py":216:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1150:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1170:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":761:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":775:0 at "<stdin>":1:0))))))))) at callsite("StatefulPartitionedCall@__inference_signature_wrapper_2825"("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1315:0) at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1280:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1080:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py":216:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1150:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1170:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":761:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":775:0 at "<stdin>":1:0))))))))) at "StatefulPartitionedCall")): error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
loc(callsite(callsite(callsite(callsite("TensorArrayV2_1@__inference_standard_lstm_654"("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1315:0) at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1280:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1080:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py":216:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1150:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1170:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":761:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":775:0 at "<stdin>":1:0)))))))) at callsite("model/lstm/PartitionedCall@__inference__wrapped_model_927"("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1315:0) at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1280:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1080:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py":216:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1150:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1170:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":761:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":775:0 at "<stdin>":1:0))))))))) at callsite("StatefulPartitionedCall@__inference_signature_wrapper_2825"("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1315:0) at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py":1280:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1080:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py":216:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1150:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":1170:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":761:0 at callsite("/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py":775:0 at "<stdin>":1:0))))))))) at "StatefulPartitionedCall")): error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 775, in wrapper
    return self._convert_and_export_metrics(convert_func, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 761, in _convert_and_export_metrics
    result = convert_func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 1170, in convert
    saved_model_convert_result = self._convert_as_saved_model()
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 1152, in _convert_as_saved_model
    return super(TFLiteKerasModelConverterV2,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/lite.py", line 945, in convert
    result = _toco_convert_impl(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 223, in wrapper
    raise converter_error from None  # Re-throws the exception.
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert_phase.py", line 216, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert.py", line 821, in toco_convert_impl
    data = toco_convert_protos(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert.py", line 315, in toco_convert_protos
    raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: /usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py:1315:0: error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py:1315:0: error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
<unknown>:0: note: loc("StatefulPartitionedCall"): called from
<unknown>:0: error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False

>>>

**Comment by sushreebarsa** [comment]
@gaonmaor 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by gaonmaor** [comment]
As I wrote above, this only needed code to simulate it is:

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, LSTM
tf.version.VERSION
model_in = Input(shape=(800,))
model = Model(model_in, LSTM(8)(Embedding(300, 8,)(model_in)))
converter = tf.lite.TFLiteConverter.from_keras_model(model); tflite_model = converter.convert()

I've also shown how to simulate it using docker and the official TensorFlow images...

**Comment by sushreebarsa** [comment]
@jvishnuvardhan Was able to replicate the issue on colab using TF v2.7.0 ,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/1dc65d220c1888563bcceff8c7b2623c/53101.ipynb#scrollTo=eZlo7NPqc-Pe) for reference. Thanks!

**Comment by jvishnuvardhan** [comment]
@gaonmaor Based on the error trace, i have updated two lines and added at the end of your code as shown below. With that modification, model was converted to tflite format.

```
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS] 
converter._experimental_lower_tensor_list_ops = False


# writing tflite model
import pathlib

tflite_models_dir = pathlib.Path("/content/my_lstm_model/")
tflite_models_dir.mkdir(exist_ok=True, parents=True)

# Save the tflite model:
tflite_model_file = tflite_models_dir/"myModel.tflite"
tflite_model_file.write_bytes(tflite_model)
```

Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/fa8604b6aaf2f13a3e61e03be9691edc/53101.ipynb)

**Comment by gaonmaor** [comment]
This is not a solution, I'm intentionally avoiding selected ops, since I'm running with libtensorflowlite alone (no libtensorflow) on the inference machine.

I do it because I need to deploy a very small image l, and if I want to use selected ops I need to add the entire libtensorflow library to the image, which is huge.

In addition this simple model worked just fine up till this version using plain tflite operations. Something went wrong and need to be fixed.

**Comment by jvishnuvardhan** [comment]
Looks like some ops (TensorListFromTensor, TensorListGetItem, TensorListReserve, TensorListSetItem, TensorListStack) are not supported by tflite runtime. [Here](https://colab.research.google.com/gist/jvishnuvardhan/73a96e2319a68497a3fdb327bb0605a3/53101.ipynb) is a gist for reference. Thanks!

```
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select 
TF Select ops: TensorListFromTensor, TensorListGetItem, TensorListReserve, TensorListSetItem, TensorListStack
Details:
	tf.TensorListFromTensor(tensor<800x?x8xf32>, tensor<2xi32>) -> (tensor<!tf_type.variant<tensor<?x8xf32>>>) : {device = ""}
	tf.TensorListGetItem(tensor<!tf_type.variant<tensor<?x8xf32>>>, tensor<i32>, tensor<2xi32>) -> (tensor<?x8xf32>) : {device = ""}
	tf.TensorListReserve(tensor<2xi32>, tensor<i32>) -> (tensor<!tf_type.variant<tensor<?x8xf32>>>) : {device = ""}
	tf.TensorListSetItem(tensor<!tf_type.variant<tensor<?x8xf32>>>, tensor<i32>, tensor<?x8xf32>) -> (tensor<!tf_type.variant<tensor<?x8xf32>>>) : {device = ""}
	tf.TensorListStack(tensor<!tf_type.variant<tensor<?x8xf32>>>, tensor<2xi32>) -> (tensor<?x?x8xf32>) : {device = "", num_elements = -1 : i64}
```

**Comment by gaonmaor** [comment]
We can see that it uses unsupported operations based on the original post. As I've said, it used to work fine up until the previous version (2.6.2). You can try running the above code and see it yourself. It is a degradation  which was introduced on version 2.7.0 and that's why we need to follow it to the relevant TensorFlow development group.

**Comment by sschaetz** [comment]
I am seeing the same problem in my own code with 2.7.0 but it works fine with the tensorflow-nightly build for me.

**Comment by raduslmn** [comment]
We are having the same issue tf 2.7.0 when converting to tflite
`TensorListFromTensor, TensorListGetItem, TensorListReserve, TensorListSetItem, TensorListStack`
We try avoiding selected ops as well as the code runs with tflite alone on the inference machine.

**Comment by mohantym** [comment]
Hi @gaonmaor ! It looks like a [MLIR ](https://www.tensorflow.org/api_docs/python/tf/lite/TFLiteConverter#:~:text=experimental_new_converter)conversion issue .Could you check with these two options and let us know .Thank you!


```
// without select ops 
import tensorflow as tf
print(tf.__version__)

model_file = '/content/mobilenet_v2_1.0_224_frozen_pb'
converter = tf.lite.TFLiteConverter.from_saved_model(model_file)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.experimental_new_converter = True // allows conversion of MLIR operators.
converter.allow_custom_ops = True
tflite_model = converter.convert()
```

```
//with select ops
import tensorflow as tf
print(tf.__version__)
model_file = '/content/mobilenet_v2_1.0_224_frozen_pb' //your model file
converter = tf.lite.TFLiteConverter.from_saved_model(model_file)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS] 
converter.experimental_new_converter = True // allows conversion of MLIR operators.
converter.allow_custom_ops = True
tflite_model = converter.convert()

```

**Comment by JinXiaozhao** [comment]
@mohantym error is consistent
File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/convert.py", line 311, in convert
    raise converter_error
tensorflow.lite.python.convert_phase.ConverterError: /usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py:1325:0: error: 'tf.TensorListReserve' op requires element_shape to be static during TF Lite transformation pass
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py:1325:0: error: failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal
<unknown>:0: note: loc(fused["StatefulPartitionedCall:", "StatefulPartitionedCall"]): called from
<unknown>:0: error: Lowering tensor list ops is failed. Please consider using Select TF ops and disabling `_experimental_lower_tensor_list_ops` flag in the TFLite converter object. For example, converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]\n converter._experimental_lower_tensor_list_ops = False

**Comment by JinXiaozhao** [comment]
@gaonmaor 
Hello, I have the same problem. Do you have any good suggestions?

**Comment by mohantym** [comment]
Hi @JinXiaozhao ! Attached resolved [gist](https://colab.sandbox.google.com/gist/mohantym/7e9d5c90d7c714bbc75b778eba4f9e71/53101.ipynb) for reference.

**Comment by JinXiaozhao** [comment]
@mohantym 
As gaonmaor said,"We can see that it uses unsupported operations based on the original post. As I've said, it used to work fine up until the previous version (2.6.2). You can try running the above code and see it yourself. It is a degradation which was introduced on version 2.7.0 and that's why we need to follow it to the relevant TensorFlow development group."

**Comment by mohantym** [comment]
@JinXiaozhao ! Sorry for the inconvenience. Re-opening this issue as requested. Thank you!

**Comment by JinXiaozhao** [comment]
@mohantym
now default_to_single_batch=false,should it be changed to true
tensorflow-2.6.4:https://github.com/tensorflow/tensorflow/blob/v2.6.4/tensorflow/compiler/mlir/lite/transforms/lower_static_tensor_list.cc#:~:text=begin()%20%26%26%20dim_value%20%3D%3D%20-1)%20%7B-,dim_value,-%3D%201%3B
tensorflow-2.7.0:https://github.com/tensorflow/tensorflow/blob/v2.7.0/tensorflow/compiler/mlir/lite/transforms/lower_static_tensor_list.cc#:~:text=if%20(!-,default_to_single_batch_,-)%20%7B
https://github.com/tensorflow/tensorflow/blob/v2.7.0/tensorflow/compiler/mlir/lite/tf_tfl_passes.cc#:~:text=/*-,default_to_single_batch,-%3D*/false))%3B

**Comment by JinXiaozhao** [comment]
@gaonmaor 
You can add the parameter _experimental_default_to_single_batch_in_tensor_list_ops, when tensorflow==2.7.0.
converter._experimental_default_to_single_batch_in_tensor_list_ops = True

**Comment by andreped** [comment]
Any update? Just observed the same using `tensorflow==2.9.1` and `python 3.7.9` on Win10. Will try to downgrade to `2.6.2` to see if it works there.

**Comment by mohantym** [comment]
Hi @gaonmaor  @andreped !
Was able to convert the above toy model to TFlite using fusion lab and @JinXiaozhao's suggested flag(without adding select ops syntax)
Attached [gist](https://colab.sandbox.google.com/gist/mohantym/ce6feb3c54847769715300832f5c0fe2/untitled417.ipynb) for reference. 
Can we consider this as resolved now ?
Thank you!

**Comment by andreped** [comment]
Just tried @mohantym gist, and it works, even in TF 2.9.1. What seems to be the fix is this:
 `converter._experimental_default_to_single_batch_in_tensor_list_ops = True`

So yes, this issue can likely be closed.

However, I don't see a simple way to do this through the CLI:
`tflite_convert -h`

Would be great if there existed a solution for the CLI as well. Any ideas?

**Comment by jianyuzzz** [comment]
@mohantym @JinXiaozhao 
Could anyone please explain why this fix works? 

If we set default_to_single_batch to True, only tf.lite.OpsSet.TFLITE_BUILTINS will be used, and tf.lite.OpsSet.SELECT_TF_OPS will be ignored. But how is this related to the error? Are TF ops not supported by the converter?

**Comment by blaine-fs** [comment]
I think this should be reopened. Still seeing the issue on 2.10. It seems like `converter._experimental_default_to_single_batch_in_tensor_list_ops = True` removes the error, but since this flag is not documented, I would not count this as a fix.

**Comment by blaine-fs** [comment]
On 2.11, I was able to work around the issue by setting `batch_size=1` on all `Keras.Input` layers. It seems this error only occurs for LSTMs with variable batch sizes.

**Comment by JinXiaozhao** [comment]
@jianyuzzz  I think tflite_ops can't support dynamic  batch; so when the model is converted, TF (Tensorflow>2.7.0) uses tf_ops and tflite_ops. Before, TF(Tensorflw<2.7.0) was default to set dynamic batch to 1.

**Comment by mohantym** [comment]
Ok @blaine-fs @JinXiaozhao !
I tested with 2.10 version today . I can get a working TFlite model with select ops  (but without concrete function and converter._experimental_default_to_single_batch_in_tensor_list_ops = True  flag).

Attached [gist](https://colab.sandbox.google.com/gist/mohantym/ca12a26c8cf5c5baf88d6a62de56d2da/untitled417.ipynb#scrollTo=XZnZjXh3AN48) for reference. 

Will that fix this issue.

Thank you!

**Comment by mohantym** [comment]
@blaine-fs !
Re-opening this issue until It is marked as resolved . Could you check the gist in above [comment](https://github.com/tensorflow/tensorflow/issues/53101#issuecomment-1264847711).
Thank you!

**Comment by reynhardtstef** [comment]
@mohantym : I had the same problem. I fixed it by making use of @blaine-fs suggestion of setting `batch_size=1` as parameter in all `tf.keras.layers` objects. No need for TF ops, I am currently running it on `converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]`. I also did not use any experimental args with the converter object. 

### My **model** is defined as:

`model = Sequential()
model.add(Dense(100, input_shape=(200, 36), **batch_size=1**, activation=None))
model.add(LSTM(100, input_shape=(200, 100), b**atch_size=1**, return_sequences=True))
model.add(LSTM(100, input_shape=(200, 100), **batch_size=1**, return_sequences=True))
model.add(Flatten(input_shape=(200, 100), **batch_size=1**))
model.add(tf.keras.layers.Dropout(.2, input_shape=(1, 20000), **batch_size=1**, trainable=False))
model.add(Dense(len(vocab), input_shape=(1, 20000), **batch_size=1**, activation='softmax'))

model.compile(loss=tf.keras.losses.CategoricalCrossentropy(from_logits=False),
              optimizer=tf.keras.optimizers.Adam(
                  learning_rate=0.000075
              ), metrics=['Accuracy'])`

### My **conversion to TFlite** (fully 8-bit Integer quantized, works with edgeTPU compiler):
_I included the commented code to show what I have tried_

`converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# converter._experimental_lower_tensor_list_ops = False
# converter._experimental_default_to_single_batch_in_tensor_list_ops = True
converter.inference_input_type = tf.int8  # or tf.uint8
converter.inference_output_type = tf.int8

# converter._experimental_lower_tensor_list_ops = False
tflite_model = converter.convert()`

Turns out that if the LSTM (without defining the batch size) gets a batch of inputs (more than 1 inputs), it creates a `While op` that causes the TFlite graph to be _dynamic-sized_, which in turn causes it to not be compiled by (in my case) the edgeTPU compiler. Hope that helps!! And thanks for all the help on this thread!

**Comment by blaine-fs** [comment]
Hi @mohantym , sorry for the late reply. I think whether `SELECT_TF_OPS` resolves the issue depends on the use case. Some compiler backends might only support the builtin TFLite ops, wheres `SELECT_TF_OPS` enables other operations beyond those. In my opinion, `batch_size=1` is a more general solution because it only requires the built-in TFLite ops.

**Comment by pkgoogle** [comment]
Hi @blaine-fs, we currently do not plan to support dynamic input sizes in the near future to keep tf lite performant: https://www.tensorflow.org/lite/guide/inference#run_inference_with_dynamic_shape_model, if you have no more open items regarding this issue, please close as not planned. Thanks.
