### ISSUE TITLE
Read only tensor is mapped as input to IF operation

### ISSUE THREAD

**Issue by ScholliYT** [tensorflow/tensorflow#54488]
### 1. System information

- OS Platform and Distribution: Google Colab Ubuntu 18.04
- TensorFlow installed from binary
- TensorFlow version: 2.8.0

### 2. Code

Colab Notebook: [link](https://colab.research.google.com/drive/16guYzn6go7Sps_5XyVQSELMn5Euwlwpb?usp=sharing)

### 3. Failure after conversion
The read-only tensors containing the weights are mapped as inputs for the `IF` operation in Subgraph `#0`. I agree on the fact that these are indeed inputs for the subgraph but this behavior causes some difficulties in combination with [TFLM](https://github.com/tensorflow/tflite-micro). More specifically, every input tensor is copied over to the "subgraph's execution environment". Especially for these (large) read-only tensors, it's a huge unnecessary overhead because these could be linked to the OPs that use the tensors directly. 

```md
Subgraph#0 main(T#0, T#1) -> [T#4]
  Op#0 IF(T#1, T#3, T#0, T#2, Then: Subgraph#2, Else: Subgraph#1) -> [T#4]

...
T#2(cond_1/input_2) shape:[10, 10], type:FLOAT32 RO 400 bytes
T#3(cond_1/input_0) shape:[10, 10], type:FLOAT32 RO 400 bytes
```
I already posted this issue in the TensorFlow lite micro repository over here https://github.com/tensorflow/tflite-micro/issues/903.

Is there any option besides modifying the .tflite file to get these tensors out of the input tensor list of the `IF` operation?

**Comment by gowthamkpr** [comment]
@ScholliYT As mentioned [here](https://github.com/tensorflow/tflite-micro/issues/903#issuecomment-1074132567), the latest TFLM no longer requires copying back to input. This should be fixed in the latest version of TFLM. Please try and let me know. Thanks!

**Comment by ScholliYT** [comment]
Hi @gowthamkpr, Sorry for my late response to this. I see the following 2 points with the state of this issue:

1. The issue of copying back into read-only memory regions indeed is resolved as @deqiangc pointed out here https://github.com/tensorflow/tflite-micro/issues/903.

2. The overall main problem of unnecessary copying of read-only tensors is not resolved and still exists. For example: with the example linked above 3 tensors each of size 10x10 (x 4 bytes) are copied, i.e. the input, fc1_kernel and fc2_kernel. This happens for both subgraphs.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
