### ISSUE TITLE
Dataset has no attribute load

### ISSUE THREAD

**Issue by Jesse-Kerr** [tensorflow/tensorflow#56229]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Mac

### Python version

3.9

### Current Behaviour?

```shell
Hello, I just upgraded to tensorflow v2.9.1 expecting to be able to use the new dataset methods load and save. But they are not available.
```

### Standalone code to reproduce the issue

```shell
# Load doesn't work
tf.data.Dataset.load('path')
AttributeError: type object 'DatasetV2' has no attribute 'load'

# Save doesn't work
dataset = tf.data.Dataset.range(2)
tf.data.Dataset.save(dataset, path)

AttributeError: type object 'DatasetV2' has no attribute 'save'
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue in tensorflow [v2.9](https://colab.research.google.com/gist/tilakrayal/80131f170679eb64f7e3c87496721baf/untitled416.ipynb), [v2.8](https://colab.research.google.com/gist/tilakrayal/8b51add94ba6d8438f9104934160fc2b/2-8.ipynb) and nightly. Please find the gist of it here.

**Comment by sachinprasadhs** [comment]
The issue has been fixed in `Tf-nightly 2.10.0-dev20220524`. You can use the below code to save and load.

```
import tempfile
import os
import tensorflow as tf
path = os.path.join(tempfile.gettempdir(), "saved_data")
# Save a dataset
dataset = tf.data.Dataset.range(2)
tf.data.Dataset.save(dataset, path)
new_dataset = tf.data.Dataset.load(path)
for elem in new_dataset:
  print(elem)
```

Below points must be considered for saving and loading.
1. datasets saved through [tf.data.Dataset.save](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#save) should only be consumed through [tf.data.Dataset.load](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#load), which is guaranteed to be backwards compatible.
2. If you load previously saved dataset, you need to specify `element_spec --` a type signature of the elements of the saved dataset, which can be obtained via [tf.data.Dataset.element_spec](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#element_spec).

**Comment by Jesse-Kerr** [comment]
Thank you for working on this. I haven't used the nightly version before. I installed using `pip install tf-nightly`, but when I `import tensorflow as tf`, the version is still 2.9.1, and the error still occurs. Can you help me understand what I am doing wrong?

**Comment by Jesse-Kerr** [comment]
Thanks, this works great.
