### ISSUE TITLE
I cannot run a transformer model with token-level output on accelerated hardware in TF Lite

### ISSUE THREAD

**Issue by DerEchteFeuerpfeil** [tensorflow/tensorflow#59232]
# Description of the issue
Okay so to preface this, I have been working on this for over a month. My goal can be explained in one sentence: I want to run my small bert-like model with token-level output on the GPU of my Android phone using the Interpreter API and the GPU delegate. The Task API does unfortunately not offer that.

Please don't hesitate to reach out to me if you are missing any information to understand or reproduce this issue. I really want to get this working!

# System Information
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.10.1

# The model and the TF Lite conversion
I want to use a simple BERT-based model to classify something on token-level. The following code should get you an idea of the model:

```python
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tokenizers import BertWordPieceTokenizer
from transformers import BertTokenizer, TFBertModel, BertConfig


 encoder_config = {
  "attention_probs_dropout_prob": 0.1,
  "model_type": "bert",
  "emb_size": 512,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 128,
  "num_attention_heads": 8,
  "num_hidden_layers": 4,
  "type_vocab_size": 2,
  "vocab_size": 25000
}
configuration = BertConfig.from_dict(encoder_config)  # default parameters and configuration for BERT

def create_model(max_len = 128):
    ## BERT encoder
    encoder = TFBertModel(configuration)

    ## Classification Model
    input_ids = layers.Input(shape=(max_len,), dtype=tf.int64)
    token_type_ids = layers.Input(shape=(max_len,), dtype=tf.int64)
    attention_mask = layers.Input(shape=(max_len,), dtype=tf.int64)

    embedding = encoder(
        input_ids, token_type_ids=token_type_ids, attention_mask=attention_mask
    )[0]

    ## Token-level classification
    relu_layer = layers.Dense(80, activation="relu", name="relu_1")(embedding)
    classification_head = layers.Dense(len(config.get("labels")))(relu_layer)

    model = keras.Model(
        inputs=[input_ids, token_type_ids, attention_mask],
        outputs=[classification_head],
    )

    return model

model = create_model()
```
After I created the model, I converted it to the TF Lite format with the following code:
```python
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS
]
tflite_model = converter.convert()

# Save the model.
with open('../dev/model.tflite', 'wb') as f:
  f.write(tflite_model)
```

The conversion output the following text:
```
WARNING:absl:Found untraced functions such as embeddings_layer_call_fn, embeddings_layer_call_and_return_conditional_losses, encoder_layer_call_fn, encoder_layer_call_and_return_conditional_losses, pooler_layer_call_fn while saving (showing 5 of 216). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: C:\Users\USERNAME\AppData\Local\Temp\tmpb4tsljq3\assets
INFO:tensorflow:Assets written to: C:\Users\USERNAME\AppData\Local\Temp\tmpb4tsljq3\assets
```
But this did not bother me too much as these don't seem to be errors.

# Running the model on Android with hardware acceleration
To not introduce any errors from my side, I decided to use the [pre-built benchmarking app](https://www.tensorflow.org/lite/performance/measurement#android_benchmark_app) that TensorFlow provides. All the following adb commands are taken from that page.

First, I installed the app and pushed my model to the phone, which is in my case, a Pixel 3a.
```
adb install -r -d -g android_aarch64_benchmark_model.apk
adb push model.tflite /data/local/tmp
```

## Running the model on CPU
Then, I ran the model on the CPU to see if everything works:
```
adb shell am start -S -n org.tensorflow.lite.benchmark/.BenchmarkModelActivity --es args '"--graph=/data/local/tmp/model.tflite --num_threads=1"'
```
and get the following output, where everything worked as expected:
```
01-11 23:28:57.758  7651  7651 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model.tflite
01-11 23:28:59.026  7651  7651 I tflite  : Log parameter values verbosely: [0]
01-11 23:28:59.026  7651  7651 I tflite  : Graph: [/data/local/tmp/model.tflite]
01-11 23:28:59.028  7651  7651 I tflite  : Loaded model /data/local/tmp/model.tflite
01-11 23:28:59.028  7651  7651 I tflite  : Initialized TensorFlow Lite runtime.
01-11 23:28:59.034  7651  7651 I tflite  : Created TensorFlow Lite XNNPACK delegate for CPU.
01-11 23:28:59.036  7651  7651 I tflite  : The input model file size (MB): 137.514
01-11 23:28:59.036  7651  7651 I tflite  : Initialized session in 9.34ms.
01-11 23:28:59.036  7651  7651 I tflite  : Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
01-11 23:29:03.662  7651  7651 I tflite  : count=1 curr=1381510
01-11 23:29:03.662  7651  7651 I tflite  : Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
01-11 23:29:24.958  7651  7651 I tflite  : count=50 first=505840 curr=424069 min=421685 max=505840 avg=425911 std=11770
01-11 23:29:24.958  7651  7651 I tflite  : Inference timings in us: Init: 9340, First inference: 1381510, Warmup (avg): 1.38151e+06, Inference (avg): 425911
01-11 23:29:24.958  7651  7651 I tflite  : Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
01-11 23:29:24.958  7651  7651 I tflite  : Memory footprint delta from the start of the tool (MB): init=1.84766 overall=117.375
```

## Running the model on GPU
After the successful run on CPU, I want to make use of hardware acceleration to see whether this would speedup my inference and therefore I ran this command:
```
adb shell am start -S -n org.tensorflow.lite.benchmark/.BenchmarkModelActivity --es args '"--graph=/data/local/tmp/model.tflite --use_gpu=true"'
```
which output this:
```
01-11 23:31:59.519  8399  8399 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model.tflite --use_gpu=true
01-11 23:31:59.706  8399  8399 I tflite  : Log parameter values verbosely: [0]
01-11 23:31:59.706  8399  8399 I tflite  : Graph: [/data/local/tmp/model.tflite]
01-11 23:31:59.707  8399  8399 I tflite  : Use gpu: [1]
01-11 23:31:59.708  8399  8399 I tflite  : Loaded model /data/local/tmp/model.tflite
01-11 23:31:59.709  8399  8399 I tflite  : Initialized TensorFlow Lite runtime.
01-11 23:31:59.713  8399  8399 I tflite  : Created TensorFlow Lite delegate for GPU.
01-11 23:31:59.713  8399  8399 I tflite  : GPU delegate created.
01-11 23:31:59.715  8399  8399 E tflite  : Failed to apply GPU delegate.
```

There is no more information extractable from the benchmarking app, which is why I wrote an app where I can print the stacktrace of the error. And **when I try to create an Interpreter Object with the Interpreter API with a GPU delegate as options**, I get the following error:
```
I/tflite: Created TensorFlow Lite delegate for GPU.
W/System.err: java.lang.IllegalArgumentException: Internal error: Error applying delegate:
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.createInterpreter(Native Method)
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.init(NativeInterpreterWrapper.java:106)
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapper.<init>(NativeInterpreterWrapper.java:58)
W/System.err:     at org.tensorflow.lite.NativeInterpreterWrapperExperimental.<init>(NativeInterpreterWrapperExperimental.java:32)
W/System.err:     at org.tensorflow.lite.Interpreter.<init>(Interpreter.java:197)
W/System.err:     at com.example.mobileinferencedemo.inference.PunctuationInference.<init>(PunctuationInference.kt:115)
W/System.err:     at com.example.mobileinferencedemo.MainActivity.onCreate(MainActivity.kt:28)
W/System.err:     at android.app.Activity.performCreate(Activity.java:8054)
W/System.err:     at android.app.Activity.performCreate(Activity.java:8034)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loopOnce(Looper.java:201)
W/System.err:     at android.os.Looper.loop(Looper.java:288)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7870)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

It is important to note where this application fails. It fails when I try to create an Interpreter Object with the Interpreter API with a GPU delegate as options. I did not run any inference, I just wanted to create the Interpreter. If you're curious, here is the code for that (which I took from [the docs](https://www.tensorflow.org/lite/android/delegates/gpu#use_gpu_with_interpreter_api)):
```kotlin
val compatList = CompatibilityList()

val options = Interpreter.Options().apply{
    if(compatList.isDelegateSupportedOnThisDevice){
        val delegateOptions = compatList.bestOptionsForThisDevice
        this.addDelegate(GpuDelegate(delegateOptions))
    } else {
        this.numThreads = 4
    }
}

try {
    val myInterpreter: Interpreter
    if(options != null){
        myInterpreter = Interpreter(File(path.toString()), options)
    } else {
        myInterpreter = Interpreter(File(path.toString()))
    }

    myInterpreter.close()
} catch (e: Exception) {
    Log.e("tf_load_model",""+e.message)
    e.printStackTrace()
}
```

This try block already fails when trying to create the Interpreter (which I manually confirmed in the Android Studio debugger).

# Steps to reproduce this issue
1. Create the model with the code provided at the start of this issue
2. Convert it to TF lite with the code above
3. Try to run the converted TF lite model on the phone using the pre-built TensorFlow lite benchmarking app and use the `--use_gpu=true` flag
4. Observe the error "Failed to apply GPU delegate"

# Additional information
I really am curious if this is an error from my side or just generally a bug. The steps for reproducing the error should be rather quick, so I hope someone can look into this. There are just almost no resources on this, which makes it really hard to know if someone else succeeded running a token-level transformer model on the GPU using the Interpreter API. If this matter resolves, I would be happy to contribute a resource or guide to this.

## The question of operator support
There is a [list of supported ML operations for GPU](https://www.tensorflow.org/lite/performance/gpu#supported_ops) inference with the GPU delegate.

When printing the operators of my converted TF lite model in python
```python
interpreter = tf.lite.Interpreter(model_path="..\dev\model.tflite")
all_ops = list(map(lambda x: x["op_name"],interpreter._get_ops_details()))
print(np.unique(all_ops))
```
I get this list: 
```
['ADD' 'BATCH_MATMUL' 'CAST' 'CONCATENATION' 'FULLY_CONNECTED' 'GATHER'
 'GELU' 'MEAN' 'MUL' 'PACK' 'REDUCE_PROD' 'RESHAPE' 'RSQRT' 'SHAPE'
 'SOFTMAX' 'SQUARED_DIFFERENCE' 'STRIDED_SLICE' 'SUB' 'TRANSPOSE']
```

I can see that some operators (e.g. GELU) are not in the list of supported operators, but my problem is that there should be an appropriate warning if the graph contains unsupported operators ([as described in the documentation](https://www.tensorflow.org/lite/performance/gpu#troubleshooting_gpu_support)). Furthermore, I did not even come to invoking the model, the creation of the Interpreter object with the GPU delegate option already crashes my application. If I could at least create an Interpreter and then run the model and it fails with these warnings, well then I know that supported ops could be a problem, but I do not even get to that point.

**Comment by DerEchteFeuerpfeil** [comment]
@tiruk007 please let me know when you're working on this. Also if you know of any working repositories where someone got this to work or if you got any other useful ressources please let me know

**Comment by DerEchteFeuerpfeil** [comment]
This error is even easier to reproduce when using a pre-compiled model from the TF-Hub.

# Updated (detailed) steps to reproduce
1. Download [mobilebert](https://tfhub.dev/tensorflow/lite-model/mobilebert/1/metadata/1) from the tf hub
2. Connect Android mobile phone to computer in debugging mode, e.g. with Android Studio
3. (if not already done) Install official [TF Lite benchmarking app](https://www.tensorflow.org/lite/performance/measurement#android_benchmark_app)
4. Copy model onto Android device: `adb push mobilebert_1_default_1.tflite /data/local/tmp`
5. Run the model on the phone using the TensorFlow lite benchmarking app and use the --use_gpu=true flag: `adb shell am start -S -n org.tensorflow.lite.benchmark/.BenchmarkModelActivity --es args '"--graph=/data/local/tmp/mobilebert_1_default_1.tflite --use_gpu=true"'`
6. Inspect error with either `adb logcat | findstr "tflite"` (Windows) or `adb logcat | grep "tflite"` (Linux)

At least with this I get more detailed error messages and actually some information about the operators that are not supported.

# The error
```
01-16 12:26:29.107 23921 23921 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/mobilebert_1_default_1.tflite --use_gpu=true
01-16 12:26:30.306 23921 23921 I tflite  : Log parameter values verbosely: [0]
01-16 12:26:30.306 23921 23921 I tflite  : Graph: [/data/local/tmp/mobilebert_1_default_1.tflite]
01-16 12:26:30.307 23921 23921 I tflite  : Use gpu: [1]
01-16 12:26:30.312 23921 23921 I tflite  : Loaded model /data/local/tmp/mobilebert_1_default_1.tflite
01-16 12:26:30.312 23921 23921 I tflite  : Initialized TensorFlow Lite runtime.
01-16 12:26:30.386 23921 23921 I tflite  : Created TensorFlow Lite delegate for GPU.
01-16 12:26:30.386 23921 23921 I tflite  : GPU delegate created.
01-16 12:26:30.443 23921 23921 E tflite  : Following operations are not supported by GPU delegate:
01-16 12:26:30.443 23921 23921 E tflite  : GATHER: Operation is not supported.
01-16 12:26:30.443 23921 23921 E tflite  : MUL: MUL requires one tensor that not less than second in all dimensions.
01-16 12:26:30.443 23921 23921 E tflite  : RESHAPE: OP is supported, but tensor type/shape isn't compatible.
01-16 12:26:30.443 23921 23921 E tflite  : 2536 operations will run on the GPU, and the remaining 6 operations will run on the CPU.
01-16 12:26:30.446 23921 23921 I tflite  : Replacing 2536 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 2 partitions for the whole graph.
01-16 12:26:30.461 23921 23921 E tflite  : TfLiteGpuDelegate Init: FULLY_CONNECTED: Amount of input channels should match weights width
01-16 12:26:30.462 23921 23921 I tflite  : Created 0 GPU delegate kernels.
01-16 12:26:30.463 23921 23921 E tflite  : TfLiteGpuDelegate Prepare: delegate is not initialized
01-16 12:26:30.463 23921 23921 E tflite  : Node number 2542 (TfLiteGpuDelegateV2) failed to prepare.
01-16 12:26:30.498 23921 23921 E tflite  : Restored original execution plan after delegate application failure.
01-16 12:26:30.532 23921 23921 E tflite  : Failed to apply GPU delegate.
```

**Comment by PINTO0309** [comment]
I dared to try it by converting `tflite -> ONNX -> tflite`, thereby eliminating redundant processing.

The general problem seems to be casting to `INT64` and not supporting the `Gather` OP. It might work if the cast part from INT32 to INT64 could be eliminated from the model structure. Good luck.

https://github.com/PINTO0309/onnx2tf

```bash
python -m tf2onnx.convert \
--opset 11 \
--tflite lite-model_mobilebert_1_metadata_1.tflite \
--output lite_model_mobilebert_1_metadata_1.onnx

onnxsim lite_model_mobilebert_1_metadata_1.onnx lite_model_mobilebert_1_metadata_1.onnx
onnxsim lite_model_mobilebert_1_metadata_1.onnx lite_model_mobilebert_1_metadata_1.onnx
onnxsim lite_model_mobilebert_1_metadata_1.onnx lite_model_mobilebert_1_metadata_1.onnx
onnxsim lite_model_mobilebert_1_metadata_1.onnx lite_model_mobilebert_1_metadata_1.onnx
onnxsim lite_model_mobilebert_1_metadata_1.onnx lite_model_mobilebert_1_metadata_1.onnx

onnx2tf -i lite_model_mobilebert_1_metadata_1.onnx -cotof -cotoa 1e-1 -cgdc

  Op#780 CAST(T#2) -> [T#1604]
GPU COMPATIBILITY WARNING: Not supported Cast case. Input type: INT32 and output type: INT64
  Op#781 LESS(T#2, T#3[0]) -> [T#1605]
  Op#782 RESHAPE(T#0, T#793[1, 384, 1]) -> [T#1606]
  Op#783 CAST(T#1606) -> [T#1607]
GPU COMPATIBILITY WARNING: Not supported Cast case. Input type: INT32 and output type: INT64
  Op#784 LESS(T#1606, T#3[0]) -> [T#1608]
  Op#785 RESHAPE(T#1603, T#793[1, 384, 1]) -> [T#1609]
  Op#786 MUL(T#1609, T#1213) -> [T#1610]
GPU COMPATIBILITY WARNING: MUL requires one tensor that not less than second in all dimensions.
  Op#787 SUB(T#1212, T#1610) -> [T#1611]
  Op#788 MUL(T#1611, T#897) -> [T#1612]
  Op#789 TRANSPOSE(T#1612, T#7[0, 2, 1]) -> [T#1613]
  Op#790 RESHAPE(T#1613, T#811[1, 1, 384, 384]) -> [T#1614]
  Op#791 SELECT_V2(T#1605, T#810[1], T#3[0]) -> [T#1615]
GPU COMPATIBILITY WARNING: Cond must be float type, if, else tensors must be float and either be same shape as output or constant, scalar.
  Op#792 MUL(T#1615, T#12[2]) -> [T#1616]
  Op#793 CAST(T#1616) -> [T#1617]
GPU COMPATIBILITY WARNING: Not supported Cast case. Input type: INT32 and output type: INT64
  Op#794 ADD(T#1604, T#1617) -> [T#1618]
  Op#795 GATHER(T#1215, T#1618) -> [T#1619]
GPU COMPATIBILITY WARNING: Not supported op GATHER
  Op#796 ADD(T#1619, T#1214) -> [T#1620]
  Op#797 SELECT_V2(T#1608, T#810[1], T#3[0]) -> [T#1621]
GPU COMPATIBILITY WARNING: Cond must be float type, if, else tensors must be float and either be same shape as output or constant, scalar.
  Op#798 MUL(T#1621, T#13[30522]) -> [T#1622]
  Op#799 CAST(T#1622) -> [T#1623]
GPU COMPATIBILITY WARNING: Not supported Cast case. Input type: INT32 and output type: INT64
  Op#800 ADD(T#1607, T#1623) -> [T#1624]
  Op#801 GATHER(T#1216, T#1624) -> [T#1625]
GPU COMPATIBILITY WARNING: Not supported op GATHER

GPU COMPATIBILITY WARNING: Subgraph#0 has GPU delegate compatibility issues at nodes 780, 783, 786, 791, 793, 795, 797, 799, 801, 888, 894, 900, 906, 990, 996, 1002, 1008, 1092, 1098, 1104, 1110, 1194, 1200, 1206, 1212, 1296, 1302, 1308, 1314, 1398, 1404, 1410, 1416, 1500, 1506, 1512, 1518, 1602, 1608, 1614, 1620, 1704, 1710, 1716, 1722, 1806, 1812, 1818, 1824, 1908, 1914, 1920, 1926, 2010, 2016, 2022, 2028, 2112, 2118, 2124, 2130, 2214, 2220, 2226, 2232, 2316, 2322, 2328, 2334, 2418, 2424, 2430, 2436, 2520, 2526, 2532, 2538, 2622, 2628, 2634, 2640, 2724, 2730, 2736, 2742, 2826, 2832, 2838, 2844, 2928, 2934, 2940, 2946, 3030, 3036, 3042, 3048, 3132, 3138, 3144, 3150, 3234, 3240, 3246, 3252 with TFLite runtime version 2.10.0

---------------------------------------------------------------
              Model size:   50187876 bytes
    Non-data buffer size:     550595 bytes (01.10 %)
  Total data buffer size:   49637281 bytes (98.90 %)
    (Zero value buffers):         16 bytes (00.00 %)

* Buffers of TFLite model are mostly used for constant tensors.
  And zero value buffers are buffers filled with zeros.
  Non-data buffers area are used to store operators, subgraphs and etc.
  You can find more details from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs
```

**Comment by mohantym** [comment]
Hi @DerEchteFeuerpfeil !

Could you convert the transformer model with [integer quantization ](https://www.tensorflow.org/lite/performance/post_training_integer_quant)with  sample representative dataset, input and output inference type as int32 and let us know.
```
converter.inference_input_type = tf.int32
converter.inference_output_type = tf.int32
```

Would it be possible to share the Colab gist to replicate this issue.

Thank you!

**Comment by DerEchteFeuerpfeil** [comment]
@mohantym does not seem to work when following the "float fallback quantization" tutorial on the link you provided.

![image](https://user-images.githubusercontent.com/57487741/213790246-8d2594c2-8052-4890-b62c-6017994b3ac1.png)
![image](https://user-images.githubusercontent.com/57487741/213790260-e147837a-8abb-4099-a995-1d582f4ca441.png)

The specifcation of input and output type breaks it I think
``

here is a link to the colab I used for this: https://colab.research.google.com/drive/1eTCnWXmEginiHYQtoxgc9uEcVOUtktOD?usp=sharing

**Comment by DerEchteFeuerpfeil** [comment]
@PINTO0309 Very interesting stuff you did! So you replaced the GATHER with primitive operations in ONNX and converted that to TensorFlow lite?

I tried running both tflite models you provided in the .zip, but unfortunately they fail for me when running them on the benchmark app with GPU. See errors below.

**model_float32.tflite:**
```
01-20 19:30:21.811 21310 21310 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model_float32.tflite --num_threads=1
01-20 19:30:22.203 21310 21310 I tflite  : Log parameter values verbosely: [0]
01-20 19:30:22.204 21310 21310 I tflite  : Num threads: [1]
01-20 19:30:22.204 21310 21310 I tflite  : Graph: [/data/local/tmp/model_float32.tflite]
01-20 19:30:22.204 21310 21310 I tflite  : #threads used for CPU inference: [1]
01-20 19:30:22.350 21310 21310 I tflite  : Loaded model /data/local/tmp/model_float32.tflite
01-20 19:30:22.377 21310 21310 I tflite  : Initialized TensorFlow Lite runtime.
01-20 19:30:22.390 21310 21310 I tflite  : Created TensorFlow Lite XNNPACK delegate for CPU.
01-20 19:30:22.390 21310 21310 E tflite  : tensorflow/lite/kernels/concatenation.cc:159 t->dims->data[d] != t0->dims->data[d] (384 != 383)
01-20 19:30:22.390 21310 21310 E tflite  : Node number 9 (CONCATENATION) failed to prepare.
01-20 19:30:22.390 21310 21310 E tflite  : Failed to apply the default TensorFlow Lite delegate indexed at 0.
01-20 19:30:22.390 21310 21310 E tflite  : Failed to allocate tensors!
```

**model_float16.tflite:**
```
01-20 19:32:52.762 22605 22605 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model_float16.tflite --num_threads=1
01-20 19:32:53.071 22605 22605 I tflite  : Log parameter values verbosely: [0]
01-20 19:32:53.071 22605 22605 I tflite  : Num threads: [1]
01-20 19:32:53.071 22605 22605 I tflite  : Graph: [/data/local/tmp/model_float16.tflite]
01-20 19:32:53.071 22605 22605 I tflite  : #threads used for CPU inference: [1]
01-20 19:32:53.074 22605 22605 I tflite  : Loaded model /data/local/tmp/model_float16.tflite
01-20 19:32:53.093 22605 22605 I tflite  : Initialized TensorFlow Lite runtime.
01-20 19:32:53.105 22605 22605 I tflite  : Created TensorFlow Lite XNNPACK delegate for CPU.
01-20 19:32:53.105 22605 22605 E tflite  : tensorflow/lite/kernels/concatenation.cc:159 t->dims->data[d] != t0->dims->data[d] (384 != 383)
01-20 19:32:53.105 22605 22605 E tflite  : Node number 786 (CONCATENATION) failed to prepare.
01-20 19:32:53.105 22605 22605 E tflite  : Failed to apply the default TensorFlow Lite delegate indexed at 0.
01-20 19:32:53.105 22605 22605 E tflite  : Failed to allocate tensors!
```

If you see what the problem here is, please let me know! I unfortunately am not familiar with ONNX, so debugging this is really difficult. Thanks for you work so far, this is all really insightful!

It might has something to do with this part of the graph:
![image](https://user-images.githubusercontent.com/57487741/213794409-2b97a1bf-b0ef-4008-a41f-64685623f98a.png)
Since the errors state that the "(CONCATENATION) failed to prepare" and "(384 != 383)"

**Comment by PINTO0309** [comment]
>Very interesting stuff you did! So you replaced the GATHER with primitive operations in ONNX and converted that to TensorFlow lite?

No. The company is not a member of the National Association of Schools and Colleges of America. For now, I couldn't come up with a good idea to replace `Gather` with a primitive OP, so I removed only `Gather` from the model at once.

There was an error in the conversion of the model input OP, which has been corrected and re-uploaded. Please update the file.
https://s3.ap-northeast-2.wasabisys.com/temp-models/tensorflow_59232/lite_model_mobilebert_1_metadata_1.zip

By the way, I do not understand why this error occurs. The error is occurring even though a `Concatenation` of size `383` should not exist in the model. :thinking: I think it's a bug in GPU Delegate.
```
tensorflow/lite/kernels/concatenation.cc:159 t->dims->data[d] != t0->dims->data[d] (384 != 383)
```
![image](https://user-images.githubusercontent.com/33194443/213830044-63408497-3ffd-4094-a63b-4e76329789a8.png)

**Comment by DerEchteFeuerpfeil** [comment]
@PINTO0309 we are getting close haha, it works on my android phone using the CPU:
```
01-21 18:06:33.459 16604 16604 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model_float32.tflite
01-21 18:06:33.768 16604 16604 I tflite  : Log parameter values verbosely: [0]
01-21 18:06:33.768 16604 16604 I tflite  : Graph: [/data/local/tmp/model_float32.tflite]
01-21 18:06:33.899 16604 16604 I tflite  : Loaded model /data/local/tmp/model_float32.tflite
01-21 18:06:33.918 16604 16604 I tflite  : Initialized TensorFlow Lite runtime.
01-21 18:06:33.930 16604 16604 I tflite  : Created TensorFlow Lite XNNPACK delegate for CPU.
01-21 18:06:33.948 16604 16604 I tflite  : Replacing 2975 node(s) with delegate (TfLiteXNNPackDelegate) node, yielding 98 partitions for the whole graph.
01-21 18:06:34.386 16604 16604 I tflite  : The input model file size (MB): 84.1804
01-21 18:06:34.386 16604 16604 I tflite  : Initialized session in 617.085ms.
01-21 18:06:34.391 16604 16604 I tflite  : Running benchmark for at least 1 iterations and at least 0.5 seconds but terminate if exceeding 150 seconds.
01-21 18:06:35.966 16604 16604 I tflite  : count=1 curr=1574266
01-21 18:06:35.966 16604 16604 I tflite  : Running benchmark for at least 50 iterations and at least 1 seconds but terminate if exceeding 150 seconds.
01-21 18:08:20.651 16604 16604 I tflite  : count=50 first=1556493 curr=1594452 min=1556493 max=3759457 avg=2.09335e+06 std=874648
01-21 18:08:20.653 16604 16604 I tflite  : Inference timings in us: Init: 617085, First inference: 1574266, Warmup (avg): 1.57427e+06, Inference (avg): 2.09335e+06
01-21 18:08:20.653 16604 16604 I tflite  : Note: as the benchmark tool itself affects memory footprint, the following is only APPROXIMATE to the actual memory footprint of the model at runtime. Take the information at your discretion.
```

But GPU fails with this:
```
01-21 18:10:15.346 17296 17296 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model_float32.tflite --use_gpu=true
01-21 18:10:15.437 17296 17296 I tflite  : Log parameter values verbosely: [0]
01-21 18:10:15.437 17296 17296 I tflite  : Graph: [/data/local/tmp/model_float32.tflite]
01-21 18:10:15.437 17296 17296 I tflite  : Use gpu: [1]
01-21 18:10:15.559 17296 17296 I tflite  : Loaded model /data/local/tmp/model_float32.tflite
01-21 18:10:15.559 17296 17296 I tflite  : Initialized TensorFlow Lite runtime.
01-21 18:10:15.569 17296 17296 I tflite  : Created TensorFlow Lite delegate for GPU.
01-21 18:10:15.569 17296 17296 I tflite  : GPU delegate created.
01-21 18:10:15.598 17296 17296 I tflite  : Replacing 3169 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 1 partitions for the whole graph.
01-21 18:10:15.609 17296 17296 E tflite  : TfLiteGpuDelegate Init: STRIDED_SLICE: Output batch don't match
01-21 18:10:15.610 17296 17296 I tflite  : Created 0 GPU delegate kernels.
01-21 18:10:15.610 17296 17296 E tflite  : TfLiteGpuDelegate Prepare: delegate is not initialized
01-21 18:10:15.610 17296 17296 E tflite  : Node number 3169 (TfLiteGpuDelegateV2) failed to prepare.
01-21 18:10:15.627 17296 17296 E tflite  : Restored original execution plan after delegate application failure.
01-21 18:10:15.642 17296 17296 E tflite  : Failed to apply GPU delegate.
```

I think the important error message here is ```TfLiteGpuDelegate Init: STRIDED_SLICE: Output batch don't match```.

**Comment by PINTO0309** [comment]
`TfLiteGpuDelegate Init: STRIDED_SLICE: Output batch don't match`
I could not read from the text which OP this error message refers to.

"Do not slice the first dimension." If this is the case, GPU Delegate seems to be a very difficult mechanism to use. In fact, I recently succeeded in replacing `Gather` with `StridedSlice`, `Reshape` and `Concatenation`, but the constraints of `StridedSlice` were too many for GPU Delegate to be useful. GPU Delegate seems to have the advantage of being cross-platform, but with so many limitations, I believe most models cannot be reasoned with properly.

If your immediate goal is to use the Android GPU, why not try NNAPI once? It appears that `Gather`, `StridedSlice` and `Where` are all supported.

1. https://www.tensorflow.org/lite/android/delegates/nnapi
2. https://developer.android.com/ndk/guides/neuralnetworks#operations

- `StridedSlice`
  ![image](https://user-images.githubusercontent.com/33194443/213907254-cd037f33-486c-434a-9378-62983d78d3af.png)

- `Gather` replace
  ```python
  import os
  import numpy as np
  np.random.seed(0)
  os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
  os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
  import tensorflow as tf
  tf.random.set_seed(0)
  
  
  ######################################################################
  ### params_rank == 3 test data
  input_shape = [30522, 128]
  input_data = np.random.random(input_shape).astype(np.float32)
  input_data = tf.convert_to_tensor(input_data)
  params = tf.keras.Input(
      shape=[384, 1],
      batch_size=1,
      dtype=tf.int32,
  )
  
  ### params_rank == 2 test data
  # input_shape = [2, 512]
  # input_data = np.random.random(input_shape).astype(np.float32)
  # input_data = tf.convert_to_tensor(input_data)
  # params = tf.keras.Input(
  #     shape=[384],
  #     batch_size=1,
  #     dtype=tf.int32,
  # )
  
  ### params_rank == 1 test data
  # input_shape = [2, 512]
  # input_data = np.random.random(input_shape).astype(np.float32)
  # input_data = tf.convert_to_tensor(input_data)
  # params = tf.keras.Input(
  #     shape=[384],
  #     batch_size=1,
  #     dtype=tf.int32,
  # )
  # params = tf.squeeze(params, axis=0)
  ######################################################################
  
  gather_axis=0
  
  gathered_tensor = tf.gather(
      params=input_data,
      indices=params,
      axis=gather_axis,
  )
  
  inputs1 = [params]
  outputs1 = [gathered_tensor]
  model1 = tf.keras.Model(inputs=inputs1, outputs=outputs1)
  run_model = tf.function(lambda *inputs1 : model1(inputs1))
  concrete_func = run_model.get_concrete_function(
      *[tf.TensorSpec(tensor.shape, tensor.dtype) for tensor in model1.inputs]
  )
  converter = tf.lite.TFLiteConverter.from_concrete_functions(
      [concrete_func]
  )
  converter.target_spec.supported_ops = [
      tf.lite.OpsSet.TFLITE_BUILTINS,
      tf.lite.OpsSet.SELECT_TF_OPS,
  ]
  tflite_model = converter.convert()
  with open(f'model_float32_gathered.tflite', 'wb') as w:
      w.write(tflite_model)
  
  #################################################################
  
  gather_axis=0
  input_shape_rank = len(input_shape)
  params_shape = list(params.shape)
  params_dtype = params.dtype
  params_rank = len(params_shape)
  target_gathered_shape = []
  for idx, s in enumerate(input_shape):
      if idx != gather_axis:
          target_gathered_shape = target_gathered_shape + [s]
      else:
          target_gathered_shape = target_gathered_shape + params_shape
  flattened_params = tf.reshape(
      tensor=params,
      shape=[np.prod(params_shape)],
  )
  
  # Workaround for GPU Delegate
  if 3 <= input_shape_rank <= 4:
      # tf.strided_slice supports 3-D and 4-D tensor slices
      pass
  elif input_shape_rank < 3:
      # tf.strided_slice does not support slices of tensors less than 3-D,
      # so it is forced to extend to 3-D
      expand_shape = [1 for _ in range(3 - input_shape_rank)] + input_shape
      input_data = tf.reshape(
          tensor=input_data,
          shape=expand_shape,
      )
      gather_axis = gather_axis + (3 - input_shape_rank)
      input_shape = input_data.shape
      input_shape_rank = len(input_shape)
  else:
      # GPU Delegate unsupported error
      pass
  
  indices = None
  if params_rank == 1:
      i_list = []
      for i in range(params_shape[0]):
          idx = i
          i_list.append(flattened_params[idx:idx+1])
      indices = tf.reshape(tensor=tf.concat(i_list, axis=0), shape=[-1,1])
  elif params_rank == 2:
      i_list = []
      for i in range(params_shape[0]):
          j_list = []
          for j in range(params_shape[1]):
              idx = i*params_shape[1]+j
              j_list.append(flattened_params[idx:idx+1])
          i_list.append(tf.concat(j_list, axis=0))
      indices = tf.reshape(tensor=tf.concat(i_list, axis=0), shape=[-1,1])
  
  elif params_rank == 3:
      i_list = []
      for i in range(params_shape[0]):
          j_list = []
          for j in range(params_shape[1]):
              k_list = []
              for k in range(params_shape[2]):
                  idx = \
                      i*params_shape[1]*params_shape[2] \
                      +j*params_shape[2] \
                      +k
                  k_list.append(flattened_params[idx:idx+1])
              j_list.append(tf.concat(k_list, axis=0))
          i_list.append(tf.concat(j_list, axis=0))
      indices = tf.reshape(tensor=tf.concat(i_list, axis=0), shape=[-1,1])
  
  elif params_rank == 4:
      i_list = []
      for i in range(params_shape[0]):
          j_list = []
          for j in range(params_shape[1]):
              k_list = []
              for k in range(params_shape[2]):
                  l_list = []
                  for l in range(params_shape[3]):
                      idx = \
                          i*params_shape[1]*params_shape[2]*params_shape[3] \
                          +j*params_shape[2]*params_shape[3] \
                          +k*params_shape[3] \
                          +l
                      l_list.append(flattened_params[idx:idx+1])
                  k_list.append(tf.concat(l_list, axis=0))
              j_list.append(tf.concat(k_list, axis=0))
          i_list.append(tf.concat(j_list, axis=0))
      indices = tf.reshape(tensor=tf.concat(i_list, axis=0), shape=[-1,1])
  
  elif params_rank == 5:
      i_list = []
      for i in range(params_shape[0]):
          j_list = []
          for j in range(params_shape[1]):
              k_list = []
              for k in range(params_shape[2]):
                  l_list = []
                  for l in range(params_shape[3]):
                      m_list = []
                      for m in range(params_shape[3]):
                          idx = \
                              i*params_shape[1]*params_shape[2]*params_shape[3]*params_shape[4] \
                              +j*params_shape[2]*params_shape[3]*params_shape[4] \
                              +k*params_shape[3]*params_shape[4] \
                              +l*params_shape[4] \
                              +m
                          m_list.append(flattened_params[idx:idx+1])
                      l_list.append(tf.concat(m_list, axis=0))
                  k_list.append(tf.concat(l_list, axis=0))
              j_list.append(tf.concat(k_list, axis=0))
          i_list.append(tf.concat(j_list, axis=0))
      indices = tf.reshape(tensor=tf.concat(i_list, axis=0), shape=[-1,1])
  
  else:
      # not yet implemented error
      pass
  
  # Slicing
  sliced_input_datas = []
  for idx in indices:
      """
      paddings:
          [1,2,3], axis:0 -> [[0,2]]
          [1,2,3], axis:1 -> [[1,1]]
          [1,2,3], axis:2 -> [[2,0]]
  
          [1,2,3,4,5], axis:0 -> [[0,4]]
          [1,2,3,4,5], axis:1 -> [[1,3]]
          [1,2,3,4,5], axis:2 -> [[2,2]]
          [1,2,3,4,5], axis:3 -> [[3,1]]
          [1,2,3,4,5], axis:4 -> [[4,0]]
      """
      padded_begin = tf.pad(
          tensor=idx,
          paddings=[[gather_axis,input_shape_rank-gather_axis-1]],
      )
      padded_end = tf.pad(
          tensor=idx+1,
          paddings=[[gather_axis,input_shape_rank-gather_axis-1]],
      )
      mask = sum([2**dim for dim in range(input_shape_rank)]) - 2**gather_axis
      sliced_input_data = tf.strided_slice(
          input_=input_data,
          begin=padded_begin,
          end=padded_end,
          begin_mask=mask,
          end_mask=mask,
      )
      sliced_input_datas.append(sliced_input_data)
  sliced_concated_input_datas = tf.concat(
      values=sliced_input_datas,
      axis=gather_axis,
  )
  gathered_input_datas = tf.reshape(
      tensor=sliced_concated_input_datas,
      shape=target_gathered_shape,
  )
  
  
  inputs2 = [params]
  outputs2 = [gathered_input_datas]
  model2 = tf.keras.Model(inputs=inputs2, outputs=outputs2)
  run_model = tf.function(lambda *inputs2 : model2(inputs2))
  concrete_func = run_model.get_concrete_function(
      *[tf.TensorSpec(tensor.shape, tensor.dtype) for tensor in model2.inputs]
  )
  converter = tf.lite.TFLiteConverter.from_concrete_functions(
      [concrete_func]
  )
  converter.target_spec.supported_ops = [
      tf.lite.OpsSet.TFLITE_BUILTINS,
      tf.lite.OpsSet.SELECT_TF_OPS,
  ]
  tflite_model = converter.convert()
  with open(f'model_float32_gather_stridedslice.tflite', 'wb') as w:
      w.write(tflite_model)
  
  
  converter.target_spec.supported_types = [tf.float16]
  tflite_model = converter.convert()
  with open(f'model_float16_gather_stridedslice.tflite', 'wb') as w:
      w.write(tflite_model)
  
  tf.lite.experimental.Analyzer.analyze(
      model_content=tflite_model,
      gpu_compatibility=True,
  )
  
  
  ######################################################################
  ### params_rank == 3 test data
  val_data = np.random.randint(0, 100, params_shape, dtype=np.int32)
  ### params_rank == 2 test data
  # val_data = np.random.randint(0, 1, params_shape, dtype=np.int32)
  ### params_rank == 1 test data
  # val_data = np.random.randint(0, 1, params_shape, dtype=np.int32)
  ######################################################################
  
  model1_outputs = model1(val_data)
  model2_outputs = model2(val_data)
  
  print(f'{np.allclose(model1_outputs, model2_outputs)}')
  ```

**Comment by DerEchteFeuerpfeil** [comment]
@PINTO0309 I unfortunately cannot provide more detail on that error message as this is the only output I have.

## NNAPI related

We have tried NNAPI. When checking different models with the benchmmarking app, I get different errors on my Pixel 3a phone. I will post some examples here.

Our bert-encoder-only model:
```
01-23 16:53:50.590 27002 27002 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model_punctuation.tflite --use_nnapi=true
01-23 16:53:50.660 27002 27002 I tflite  : Log parameter values verbosely: [0]
01-23 16:53:50.660 27002 27002 I tflite  : Graph: [/data/local/tmp/model_punctuation.tflite]
01-23 16:53:50.661 27002 27002 I tflite  : Use NNAPI: [1]
01-23 16:53:50.674 27002 27002 I tflite  : NNAPI accelerators available: [qti-default,qti-dsp,qti-gpu,paintbox,nnapi-reference]
01-23 16:53:50.727 27002 27002 I tflite  : Loaded model /data/local/tmp/model_punctuation.tflite
01-23 16:53:50.727 27002 27002 I tflite  : Initialized TensorFlow Lite runtime.
01-23 16:53:50.728 27002 27002 I tflite  : Created TensorFlow Lite delegate for NNAPI.
01-23 16:53:50.729 27002 27002 I tflite  : NNAPI delegate created.
01-23 16:53:50.729 27002 27002 E tflite  : Failed to apply NNAPI delegate.
```

When running your "model_float32.tflite", I get the following errors:
```
01-23 16:52:43.391 26547 26547 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model_float32.tflite --use_nnapi=true
01-23 16:52:43.698 26547 26547 I tflite  : Log parameter values verbosely: [0]
01-23 16:52:43.698 26547 26547 I tflite  : Graph: [/data/local/tmp/model_float32.tflite]
01-23 16:52:43.698 26547 26547 I tflite  : Use NNAPI: [1]
01-23 16:52:43.707 26547 26547 I tflite  : NNAPI accelerators available: [qti-default,qti-dsp,qti-gpu,paintbox,nnapi-reference]
01-23 16:52:43.892 26547 26547 I tflite  : Loaded model /data/local/tmp/model_float32.tflite
01-23 16:52:43.910 26547 26547 I tflite  : Initialized TensorFlow Lite runtime.
01-23 16:52:43.918 26547 26547 I tflite  : Created TensorFlow Lite delegate for NNAPI.
01-23 16:52:43.918 26547 26547 I tflite  : NNAPI delegate created.
01-23 16:52:43.924 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.605 26547 26547 I tflite  : Replacing 2491 node(s) with delegate (TfLiteNnapiDelegate) node, yielding 581 partitions for the whole graph.
01-23 16:53:10.806 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.807 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.807 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.808 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.809 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.809 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.809 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.810 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.811 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.811 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.812 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.813 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.814 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.815 26547 26547 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 16:53:10.997 26547 26547 E tflite  : NN API returned error ANEURALNETWORKS_BAD_DATA at line 4676 while completing NNAPI compilation.
01-23 16:53:10.997 26547 26547 E tflite  : Node number 3170 (TfLiteNnapiDelegate) failed to prepare.
01-23 16:53:11.079 26547 26547 E tflite  : Restored original execution plan after delegate application failure.
01-23 16:53:11.113 26547 26547 E tflite  : Failed to apply NNAPI delegate.
```

When running a [quantized mobilebert](https://tfhub.dev/iree/lite-model/mobilebert/int8/1), I get the following error:
```
01-23 17:00:42.416 29779 29779 I tflite_BenchmarkModelActivity: Running TensorFlow Lite benchmark with args: --graph=/data/local/tmp/model_mobilebert_int8.tflite --use_nnapi=true
01-23 17:00:42.879 29779 29779 I tflite  : Log parameter values verbosely: [0]
01-23 17:00:42.880 29779 29779 I tflite  : Graph: [/data/local/tmp/model_mobilebert_int8.tflite]
01-23 17:00:42.880 29779 29779 I tflite  : Use NNAPI: [1]
01-23 17:00:42.967 29779 29779 I tflite  : NNAPI accelerators available: [qti-default,qti-dsp,qti-gpu,paintbox,nnapi-reference]
01-23 17:00:43.150 29779 29779 I tflite  : Loaded model /data/local/tmp/model_mobilebert_int8.tflite
01-23 17:00:43.172 29779 29779 I tflite  : Initialized TensorFlow Lite runtime.
01-23 17:00:43.194 29779 29779 I tflite  : Created TensorFlow Lite delegate for NNAPI.
01-23 17:00:43.194 29779 29779 I tflite  : NNAPI delegate created.
01-23 17:00:43.210 29779 29779 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 17:00:43.299 29779 29779 W tflite  : NNAPI SL driver did not implement SL_ANeuralNetworksDiagnostic_registerCallbacks!
01-23 17:00:53.873 29779 29779 I tflite  : Replacing 1920 node(s) with delegate (TfLiteNnapiDelegate) node, yielding 3 partitions for the whole graph.
01-23 17:02:47.049 29779 29779 E tflite  : NN API returned error ANEURALNETWORKS_OP_FAILED at line 4676 while completing NNAPI compilation.
01-23 17:02:47.051 29779 29779 E tflite  : Node number 1923 (TfLiteNnapiDelegate) failed to prepare.
01-23 17:02:47.119 29779 29779 E tflite  : Restored original execution plan after delegate application failure.
01-23 17:02:47.152 29779 29779 E tflite  : Failed to apply NNAPI delegate.
```

These errors made us curious if it was even worth it trying to fix them, so we tried the [TFLite Task API](https://www.tensorflow.org/lite/inference_with_metadata/task_library/overview) with this [example app](https://github.com/tensorflow/examples/tree/master/lite/examples/text_classification/android) to see what speedup is even possible. When we ran the examples, running mobilebert with NNAPI was on average 4x - 10x slower (depends on the specific mobile phone model) than using the CPU... that is why we hoped GPU inference might bring a speedup.

So overall, it's a really frustrating developer experience. I can't believe that it is that hard (or impossible) to get an encoder-only transformer to run on accelerated mobile hardware. What a pain.

## Note to you, PINTO

Thank you so much for your effort, I really appreciate that you took the time for this.
You helped me understand much more about GPU compatibility, even though the outcome might not be satisfying. If there is anything else I can do or should try, let me know. Otherwise let's hope that the tensorflow people can give me some answers and/or directions..

**Comment by pkgoogle** [comment]
Hi @DerEchteFeuerpfeil,

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress [here](https://github.com/google-ai-edge/LiteRT/issues/134).

Let us know if you have any questions. Thanks.
