### ISSUE TITLE
TFLite undefined symbol when cross-compiling for android on linux 

### ISSUE THREAD

**Issue by turgut-baba** [tensorflow/tensorflow#59692]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.12

### Custom Code

Yes

### OS Platform and Distribution

Debian 11 

### Mobile device

Android NDK 25

### Python version

3.9.2

### Bazel version

Tried on 7.0.0 and 6.0.0

### Current Behaviour?

I'm trying to cross compile TFLite on my linux machine to be compatible with android machines so I can use it on my c++ code that runs on android devices.

I've tried 3 different bazel builds with 3 different issues.

Also tried the 'build with cmake for arm' section with errors.

More details can be found here:

https://stackoverflow.com/questions/75457043/build-tflite-c-lib-for-android-with-ndk-25-with-bazel

https://stackoverflow.com/questions/75435665/errno-8-exec-format-error-on-tflite-cmake-build-for-arm64-v8a
 
How can I fix this or are there any pre-compiled so files?

### Standalone code to reproduce the issue

First I ran `./configure` and skipped over the `configure ./WORKSPACE` part since I'm using ndk version 25 and can't give the path.

First command tried: 
`bazel build -c opt --config=elinux_aarch64 //tensorflow/lite:libtensorflowlite.so --fat_apk_cpu=arm64-v8a`

Second command:
`bazel build -c opt --config=android_arm64 //tensorflow/lite:libtensorflowlite.so`

Third command (not right but I've tried it anyways):
`bazel build -c opt --config=elinux_aarch64 //tensorflow/lite:libtensorflowlite.so`

I've also tried running the `cross compilation with cmake for arm` by doing:
 - Clone to tensorflow_src
 - Create tensorflow_build in the same place as src
 - Run `curl -LO https://storage.googleapis.com/mirror.tensorflow.org/developer.arm.com/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz`
 - Run `mkdir -p ${HOME}/toolchains`
 - Run `tar xvf gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu.tar.xz -C ${HOME}/toolchains`
 - go to tensorflow_build dir
 - Run `ARMCC_PREFIX=${HOME}/toolchains/gcc-arm-8.3-2019.03-x86_64-aarch64-linux-gnu/bin/aarch64-linux-gnu-` && `ARMCC_FLAGS="-funsafe-math-optimizations"`
 - And finally `cmake -DCMAKE_C_COMPILER=${ARMCC_PREFIX}gcc   -DCMAKE_CXX_COMPILER=${ARMCC_PREFIX}g++   -DCMAKE_C_FLAGS="${ARMCC_FLAGS}"   -DCMAKE_CXX_FLAGS="${ARMCC_FLAGS}"   -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON   -DCMAKE_SYSTEM_NAME=Linux   -DCMAKE_SYSTEM_PROCESSOR=aarch64   ../tensorflow_src/tensorflow/lite/`
 My cmake looks like this:
```cmake
set(TENSORFLOW_SOURCE_DIR "" CACHE PATH
        "~/Desktop/tensorflow/tensorflow_build" )
if(NOT TENSORFLOW_SOURCE_DIR)
        get_filename_component(TENSORFLOW_SOURCE_DIR
                "~/Desktop/tensorflow/tensorflow_src" ABSOLUTE)
endif()

add_subdirectory(
        "${TENSORFLOW_SOURCE_DIR}/tensorflow/lite"
        "${CMAKE_CURRENT_BINARY_DIR}/tensorflow-lite" EXCLUDE_FROM_ALL)
...
target_link_directories(
...
tensorflow-lite
)
```

### Relevant log output
Output of the first command:
I get the .so, get the relevant header files from r1.11 branch
`C/C++: ld: error: undefined symbol: tflite::impl::Interpreter::Invoke()`

Second one I get:
When I try to compile with bazel I get this:

```shell
...
INFO: Found applicable config definition build:android_arm64 in file /home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --config=android --cpu=arm64-v8a --fat_apk_cpu=arm64-v8a
INFO: Found applicable config definition build:android in file /home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --crosstool_top=//external:android/crosstool --host_crosstool_top=@bazel_tools//tools/cpp:toolchain --noenable_platform_specific_config --copt=-w --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --define=with_xla_support=false
INFO: Build options --copt, --cpu, --crosstool_top, and 2 more have changed, discarding analysis cache.
ERROR: /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm64-v8a'
ERROR: /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/local_config_cc/BUILD:47:19: Analysis of target '@local_config_cc//:toolchain' failed
ERROR: Analysis of target '//tensorflow/lite:libtensorflowlite.so' failed; build aborted: 
INFO: Elapsed time: 0.238s
INFO: 0 processes.
ERROR: Build did NOT complete successfully
```

Third one, as expected:
`C/C++: ld: error: /home/tb/Desktop/proj/cmake/android/../../third-party/libs/tflite/arm64-v8a/libtensorflowlite.so is incompatible with aarch64linux`

The result I got when I run with the cmake attempt:
When compiling:
```
In file included from /home/tb/Desktop/tensorflow/tensorflow_src/tensorflow/lite/python/interpreter_wrapper/python_utils.cc:16:
/home/tb/Desktop/tensorflow/tensorflow_src/tensorflow/lite/python/interpreter_wrapper/python_utils.h:19:10: fatal error: 'Python.h' file not found
```

When I give the path for python manually cmake it gives a bunch of more errors related to python, it's a rabbit hole.

Note: My project REQUIRES  ndk versions above 25 so I have to find a way to build it like that and it's the reason why I can't say yes to `configure ./WORKSPACE` when running `./configure
`

**Comment by pjpratik** [comment]
@turgut-baba Thanks for reporting the issue.

I've tried running the commands 

`bazel build -c opt --config=elinux_aarch64 //tensorflow/lite:libtensorflowlite.so --fat_apk_cpu=arm64-v8a`
and
`bazel build -c opt --config=elinux_aarch64 //tensorflow/lite:libtensorflowlite.so` on Linux/Ubuntu 20.04, with Bazel 5.3.0 and was able to build successfully. Please find the [gist](https://colab.research.google.com/gist/pjpratik/eda786aa4b7b0471a09465a4b19561c7/-59692.ipynb#scrollTo=D2pgHogEk3O0) here. 

Have you tried with Android NDK 19c which is [recommended](https://www.tensorflow.org/lite/android/lite_build#set_up_build_environment_without_docker). Thanks!

**Comment by turgut-baba** [comment]
Hello,  I will try it with bazel 5.3.0 and update you, however due to my projects needs, I can't use NDK versions below 25.

**Comment by turgut-baba** [comment]
Running `bazel build -c opt --config=elinux_aarch64 //tensorflow/lite:libtensorflowlite.so --fat_apk_cpu=arm64-v8a` with bazel 5.3.0 causes this error on the `v2.12.0-rc0` branch :
```
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'build' from /home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
  'build' options: --define framework_shared_object=true --define tsl_protobuf_header_only=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false --incompatible_enforce_config_setting_visibility
INFO: Reading rc options for 'build' from /home/tb/Desktop/tensorflow/tensorflow_src/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env PYTHON_LIB_PATH=/usr/lib/python3/dist-packages --python_path=/usr/bin/python3
INFO: Reading rc options for 'build' from /home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file /home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:elinux_aarch64 in file /home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --config=elinux --cpu=aarch64 --distinct_host_configuration=true
INFO: Found applicable config definition build:elinux in file /home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --crosstool_top=@local_config_embedded_arm//:toolchain --host_crosstool_top=@bazel_tools//tools/cpp:toolchain
INFO: Found applicable config definition build:linux in file /home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --host_copt=-w --copt=-Wno-all --copt=-Wno-extra --copt=-Wno-deprecated --copt=-Wno-deprecated-declarations --copt=-Wno-ignored-attributes --copt=-Wno-array-bounds --copt=-Wunused-result --copt=-Werror=unused-result --copt=-Wswitch --copt=-Werror=switch --copt=-Wno-error=unused-but-set-variable --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --define=PROTOBUF_INCLUDE_PATH=$(PREFIX)/include --cxxopt=-std=c++17 --host_cxxopt=-std=c++17 --config=dynamic_kernels --distinct_host_configuration=false --experimental_guard_against_concurrent_changes
INFO: Found applicable config definition build:dynamic_kernels in file /home/tb/Desktop/tensorflow/tensorflow_src/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Analyzed target //tensorflow/lite:libtensorflowlite.so (89 packages loaded, 10700 targets configured).
INFO: Found 1 target...
ERROR: /home/tb/Desktop/tensorflow/tensorflow_src/tensorflow/lite/kernels/internal/BUILD:864:11: Compiling tensorflow/lite/kernels/internal/mfcc.cc failed: (Exit 1): aarch64-none-linux-gnu-gcc failed: error executing command /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/bin/aarch64-none-linux-gnu-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections ... (remaining 52 arguments skipped)
In file included from /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/bits/specfun.h:46,
                 from /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/cmath:1935,
                 from /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/math.h:36,
                 from tensorflow/lite/kernels/internal/mfcc.cc:16:
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/limits:1673:7: internal compiler error: Illegal instruction
 1673 |       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
      |       ^~~
0x7f1c93401d5f ???
	./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
ERROR: /home/tb/Desktop/tensorflow/tensorflow_src/tensorflow/lite/kernels/internal/BUILD:864:11: Compiling tensorflow/lite/kernels/internal/mfcc_dct.cc failed: (Exit 1): aarch64-none-linux-gnu-gcc failed: error executing command /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/bin/aarch64-none-linux-gnu-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections ... (remaining 52 arguments skipped)
In file included from /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/bits/specfun.h:46,
                 from /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/cmath:1935,
                 from /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/math.h:36,
                 from tensorflow/lite/kernels/internal/mfcc_dct.cc:18:
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/limits:1673:7: internal compiler error: Illegal instruction
 1673 |       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
      |       ^~~
0x7ff7ee25dd5f ???
	./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
ERROR: /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/ruy/ruy/BUILD:189:11: Compiling ruy/tune.cc failed: (Exit 1): aarch64-none-linux-gnu-gcc failed: error executing command /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/bin/aarch64-none-linux-gnu-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections ... (remaining 62 arguments skipped)
In file included from /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/chrono:41,
                 from external/ruy/ruy/time.h:19,
                 from external/ruy/ruy/tune.h:48,
                 from external/ruy/ruy/tune.cc:16:
/home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/aarch64-none-linux-gnu/include/c++/11.3.1/limits:1673:7: internal compiler error: Illegal instruction
 1673 |       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
      |       ^~~
0x7f82f4e2dd5f ???
	./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
ERROR: /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/XNNPACK/BUILD.bazel:5371:19: Compiling src/subgraph/static-constant-pad.c failed: (Exit 1): aarch64-none-linux-gnu-gcc failed: error executing command /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/bin/aarch64-none-linux-gnu-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections ... (remaining 93 arguments skipped)
In file included from external/XNNPACK/src/xnnpack/compute.h:14,
                 from external/XNNPACK/src/xnnpack/operator.h:18,
                 from external/XNNPACK/src/subgraph/static-constant-pad.c:6:
external/XNNPACK/src/xnnpack/math.h: In function 'min':
external/XNNPACK/src/xnnpack/math.h:35:3: internal compiler error: Illegal instruction
   35 |   return XNN_UNPREDICTABLE(b < a) ? b : a;
      |   ^~~~~~
0x7f0820113d5f ???
	./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7f08200fed09 __libc_start_main
	../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
ERROR: /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/XNNPACK/BUILD.bazel:5371:19: Compiling src/subgraph/global-average-pooling.c failed: (Exit 1): aarch64-none-linux-gnu-gcc failed: error executing command /home/tb/.cache/bazel/_bazel_tb/f8bd8a53c316ccb93548129bbd0ade7a/external/aarch64_linux_toolchain/bin/aarch64-none-linux-gnu-gcc -fstack-protector -g0 -O2 -DNDEBUG -ffunction-sections -fdata-sections ... (remaining 93 arguments skipped)
In file included from external/XNNPACK/src/xnnpack/compute.h:14,
                 from external/XNNPACK/src/xnnpack/operator.h:18,
                 from external/XNNPACK/src/subgraph/global-average-pooling.c:13:
external/XNNPACK/src/xnnpack/math.h: In function 'min':
external/XNNPACK/src/xnnpack/math.h:35:3: internal compiler error: Illegal instruction
   35 |   return XNN_UNPREDICTABLE(b < a) ? b : a;
      |   ^~~~~~
0x7ffb93661d5f ???
	./signal/../sysdeps/unix/sysv/linux/x86_64/sigaction.c:0
0x7ffb9364cd09 __libc_start_main
	../csu/libc-start.c:308
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <https://bugs.linaro.org/> for instructions.
Target //tensorflow/lite:libtensorflowlite.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 88.774s, Critical Path: 26.47s
INFO: 210 processes: 177 internal, 33 local.
FAILED: Build did NOT complete successfully

```

**Comment by pjpratik** [comment]
@turgut-baba Thanks for the update.

@sachinprasadhs Could you please look into this. Thank you.

**Comment by turgut-baba** [comment]
@pjpratik On a side note, I've found some pre-compiled versions of the library on the internet from 2021, it runs just fine on it's own but when I use it inside my project, which uses threading on android, it gives out an error. (I've set `setnumThreads` to 2.). I assume this issue is addressed in the newer releases but since I can't compile it on my own I'm stuck. Also: If I compile the .so files with NDK 19, can I use that in my NDK 25 > project?

**Comment by fergushenderson** [comment]
> C/C++: ld: error: undefined symbol: tflite::impl::Interpreter::Invoke()

That symbol is supposed to be defined in the file tensorflow/lite/core/interpreter.cc.

There have been a few changes related to this recently, with the implementation of this method recently moving
(a) from the "tflite" namespace to the "tflite::impl" namespace and
(b) from tensorflow/lite/interpreter.cc to tensorflow/lite/core/interpreter.cc

I suspect the problem may be related to one of those, probably (b).

**Comment by turgut-baba** [comment]
@fergushenderson Do you have any suggestions I can try in the meantime? Which branch do you suggest I use?

**Comment by sachinprasadhs** [comment]
Hi, Could you please try to build against the latest stable branch `2.11` and let us know if it is working for you.
`2.12` is not yet released, till `2.12` is available you could build it against the last stable branch which is `2.11`. Thanks!

**Comment by AIWintermuteAI** [comment]
@sachinprasadhs the issue was not fixed since then it seems
this commit https://github.com/tensorflow/tensorflow/commit/734de9e767fdd81d67bd47a14a1281b9736c8544#diff-7456c1d9f62f2c8c05621072dba61fc0db513a09331f60f9601d2e610c114dda updated the ARM toolchain to 11.3 Rel1 - however, according to 
https://bugs.linaro.org/show_bug.cgi?id=5825#c34
```
The issues was only fixed in the baremetal builds with 11.3 Rel1. Unfortunately the aarch64-none-linux-gnu and arm-none-linux-gnueabihf targets are still affected by the same underlying issue in that release.
```
so I'm assuming it is still broken on latest master - but it is definitely broken in 2.12rc0, which is what I'm trying to build.

I'm trying swapping the toolchain to arm-gnu-toolchain-12.3.rel1-aarch64-arm-none-linux-gnueabihf, the build seems to be progressing as of now.

If it builds and runs, would you like me to make a PR? Do you have a CI test for this in place?

**Comment by sachinprasadhs** [comment]
You can go ahead and make the changes.
