### ISSUE TITLE
Error message for running tf.nn.max_pool_with_argmax() on CPU

### ISSUE THREAD

**Issue by 0bserver07** [tensorflow/tensorflow#6035]
Running `tf.nn.max_pool_with_argmax()` on CPU gives a very obscure error:

`tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'MaxPoolWithArgmax' with these attrs.  Registered devices: [CPU], Registered kernels:
`  <no registered kernels>

From this line:

https://github.com/tensorflow/tensorflow/blob/bc64f05d4090262025a95438b42a54bfdc5bcc80/tensorflow/core/kernels/maxpooling_op.cc#L672

I think it's useful to mention `tf.nn.max_pool_with_argmax()` is only implemented for GPU instead.

**Comment by poxvoculi** [comment]
Rather than trying to fix this one Op, it might be better to have a solution where on an error like this the feasible device implementations are listed.  Opening internal bug, but it may not be acted on soon.

**Comment by 0bserver07** [comment]
Perhaps it's about having this registered with the CPU as well. [tf.nn.max_pool_with_argmax](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard9/tf.nn.max_pool_with_argmax.md)

```python
REGISTER_KERNEL_BUILDER(Name("MaxPoolWithArgmax")
                            .Device(DEVICE_GPU)
                            .TypeConstraint<int64>("Targmax")
                            .TypeConstraint<float>("T"),
                        MaxPoolingWithArgmaxOp<Eigen::GpuDevice, float>);
REGISTER_KERNEL_BUILDER(Name("MaxPoolWithArgmax")
                            .Device(DEVICE_GPU)
                            .TypeConstraint<int64>("Targmax")
                            .TypeConstraint<Eigen::half>("T"),
MaxPoolingWithArgmaxOp<Eigen::GpuDevice, Eigen::half>);
```

This might be somehow useful and related as well [Missing gradient for tf.nn.max_pool_with_argmax #1793](https://github.com/tensorflow/tensorflow/issues/1793)

**Comment by tfboyd** [comment]
I believe this is fixed and I see there also was a PR.

**Comment by lujian9328** [comment]
Is there an alternative for tf.nn.max_pool_with_argmax? Because now I only want to test my trained model on CPU env.

**Comment by bhack** [comment]
@MilesZhao @lujian9328 I think it is better to open a new issue for CPU support.

**Comment by zhenbangchen** [comment]
@tfboyd seems still not working on CPUs. Can you reopen this?

**Comment by dibenedetto** [comment]
@tfboyd any chance to have it available also on CPU? I'd like to contribute if I could, but I never worked on tensorflow source code.
Should this issue be reopen or should we file a new one?

**Comment by asimonov** [comment]
Yes, would be great to have tf.nn.max_pool_with_argmax working on CPU. 

This ops seems to be very useful for fast encoder-decoder architectures (I see it two segmentation networks -- ENet and SegNet)  which were designed for 'real time' image segmentation. So supposedly people look at performance with a view of running these networks on CPUs or mobile.

**Comment by dibenedetto** [comment]
Great to see attention to this issue!

maybe is it better to open a new issue with a proper title as simple as, e.g., "max_pool_with_argmax unavailable on CPU" rather than this one that, actually, refers to an error message?

@tfboyd if you agree I'll open a new issue so you can close this one.

**Comment by asimonov** [comment]
Great idea!

I have tried to express maxpool with argmax through operations available on CPU but so far did not succeed. Anyone has simple ideas? 

_____________________________
Kind Regards,
Alexey Simonov

**Comment by ronrest** [comment]
I would like to get this function to work on CPU as well. I am trying to implement Segnet and E-net.

**Comment by BogdanRuzh** [comment]
It's a very important Op for my model. Hope it will be solved soon.

**Comment by tanabics** [comment]
It would be useful for me too....

**Comment by shadySource** [comment]
I was able to make a workaround for CPU.
Warning: it is slow, bloated, and basically a last resort. But I can get ENet to run on my cpu at 5s/image...
Right now it is only for 2x2 maxpooling, but you could change the numbers and add things to expand upon this example.
```python
net_main, pooling_indices = tf.nn.max_pool_with_argmax(inputs,
                                                                   ksize=[1,2,2,1],
                                                                   strides=[1,2,2,1],
                                                                   padding='SAME',
                                                                   name=scope+'_main_max_pool')
```
becomes
```python
net_main = tf.nn.max_pool(inputs,
                        ksize=[1,2,2,1],
                        strides=[1,2,2,1],
                        padding='SAME',
                        name=scope+'_main_max_pool')

input_shape = inputs.get_shape().as_list()
mask_shape = [input_shape[0], input_shape [1]/2,input_shape[2]/2, input_shape[3]]
pooling_indices = tf.zeros(mask_shape, dtype=tf.int64)
for n in range(mask_shape[0]):
    for i in range(mask_shape[1]):
        for j in range(mask_shape[2]):
            in_indices = [ [n, w, h] for w in range(i*2, i*2+2) for h in range(j*2, j*2+2)]
            slice = tf.gather_nd(inputs, in_indices)
            argmax = tf.argmax(slice, axis=0)
            indices_location = [[n, i, j, d] for d in range(input_shape[3])]
            sparse_indices = tf.SparseTensor(indices=indices_location, values=argmax, dense_shape=mask_shape)
            pooling_indices = tf.sparse_add(pooling_indices, sparse_indices)
```

Also, that part of the gpu kernel is on [this line](https://github.com/tensorflow/tensorflow/blob/40eef4473bda90442bb55fcc67842f097c024580/tensorflow/core/kernels/maxpooling_op_gpu.cu.cc#L88). Simply copying that code from the gpu kernel to the cpu kernel may not be so bad for this operation. It is a nice operation to have, and even without optimization, it would probably still be much faster than what I ended up doing :stuck_out_tongue:

**Comment by saeed68gm** [comment]
I may submit a workaround for this soon

**Comment by mmpinso** [comment]
Hello, also need this op for CPU, vital to my project to run on mobile.
@shadySource , when I apply your workaround and try to retrain the model, the training seems to be launched on my CPU instead of my GPU and fails (the GPU device for training is not created, as it is with the original code, and the process eventually kills itself).

**Comment by shadySource** [comment]
@mmpinso 
I think all of the ops for my workaround ended up using multiple gigs of memory simply with ENet. There is a pretty good chance it would not fit in a gpu (or even system ram) during training. Definitely would not fit in most mobile devices, and it is pretty slow.

In the mean time, I might try to make a lightweight segmentation architecture which uses features from the downsampling layers to guide the upsampling layers. Maybe an architecture like this already exists...

Anyway, anyone want to learn [how to make ops](https://www.tensorflow.org/extend/adding_an_op)?

**Comment by saeed68gm** [comment]
@shadySource  @mmpinso  I actually just copied the operation from GPU to CPU and was able to load the model and run it. I don't know if tensorflow will take my pull request as it looks hacky. But I can provide the patch directly for you to try if you want.

**Comment by mmpinso** [comment]
@saeed68gm that would be great

**Comment by imransalam** [comment]
@saeed68gm , would it be possible if you could give the link to PR or write down the steps for the fix ?
Thanks.

**Comment by saeed68gm** [comment]
@mmpinso here is the patch for TF version 1.4. It is very hacky but it should help you load up your model into tensoflow. May I ask which model you are trying to integrate into the phone? For me I had to add a workout for another operation as well.

@imransalam The steps are basically what @shadySource shared above in the tensorflow documentation for adding your own op.

if anybody actually implemented these operations please share you solution. Thank you.

diff --git a/tensorflow/core/kernels/maxpooling_op.cc b/tensorflow/core/kernels/maxpooling_op.cc
index e2cf605..5cdbe8d 100644
--- a/tensorflow/core/kernels/maxpooling_op.cc
+++ b/tensorflow/core/kernels/maxpooling_op.cc
@@ -54,6 +54,114 @@ const int kInvalidMaxPoolingIndex = -1;
 template <typename Device, typename T>
 static void SpatialMaxPoolWithArgMaxHelper(
     OpKernelContext* context, Tensor* output, Tensor* output_arg_max,
+    const Tensor& tensor_in,const PoolParameters& params, const Padding& padding) {
+  typedef Eigen::Map<const Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic>>
+      ConstEigenMatrixMap;
+  typedef Eigen::Map<Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic>>
+      EigenMatrixMap;
+  typedef Eigen::Map<Eigen::Matrix<int64, Eigen::Dynamic, Eigen::Dynamic>>
+      EigenIndexMatrixMap;
+
+  ConstEigenMatrixMap in_mat(
+      tensor_in.flat<T>().data(), params.depth,
+      params.tensor_in_cols * params.tensor_in_rows * params.tensor_in_batch);
+  EigenMatrixMap out_mat(
+      output->flat<T>().data(), params.depth,
+      params.out_width * params.out_height * params.tensor_in_batch);
+  EigenIndexMatrixMap out_arg_max_mat(
+      output_arg_max->flat<int64>().data(), params.depth,
+      params.out_width * params.out_height * params.tensor_in_batch);
+
+  const DeviceBase::CpuWorkerThreads& worker_threads =
+      *(context->device()->tensorflow_cpu_worker_threads());
+
+  // The following code basically does the following:
+  // 1. Flattens the input and output tensors into two dimensional arrays.
+  //    tensor_in_as_matrix:
+  //      depth by (tensor_in_cols * tensor_in_rows * tensor_in_batch)
+  //    output_as_matrix:
+  //      depth by (out_width * out_height * tensor_in_batch)
+  //
+  // 2. Walks through the set of columns in the flattened tensor_in_as_matrix,
+  //    and updates the corresponding column(s) in output_as_matrix with the
+  //    max value.
+  auto shard = [&params, &in_mat, &out_mat, &out_arg_max_mat,
+                &output_arg_max](int64 start, int64 limit) {
+
+    const int32 depth = params.depth;
+    const int32 in_rows = params.tensor_in_rows;
+    const int32 in_cols = params.tensor_in_cols;
+    const int32 pad_rows = params.pad_rows;
+    const int32 pad_cols = params.pad_cols;
+    const int32 window_rows = params.window_rows;
+    const int32 window_cols = params.window_cols;
+    const int32 row_stride = params.row_stride;
+    const int32 col_stride = params.col_stride;
+    const int32 out_height = params.out_height;
+    const int32 out_width = params.out_width;
+
+    {
+      // Initializes the output tensor with MIN<T>.
+      const int32 output_image_size = out_height * out_width * depth;
+      EigenMatrixMap out_shard(out_mat.data() + start * output_image_size, 1,
+                               (limit - start) * output_image_size);
+      out_shard.setConstant(Eigen::NumTraits<T>::lowest());
+      EigenIndexMatrixMap out_arg_max_shard(
+          out_arg_max_mat.data() + start * output_image_size, 1,
+          (limit - start) * output_image_size);
+      out_arg_max_shard.setConstant(kInvalidMaxPoolingIndex);
+    }
+
+    for (int64 b = start; b < limit; ++b) {
+      for (int h = 0; h < in_rows; ++h) {
+        for (int w = 0; w < in_cols; ++w) {
+          // (h_start, h_end) * (w_start, w_end) is the range that the input
+          // vector projects to.
+          const int hpad = h + pad_rows;
+          const int wpad = w + pad_cols;
+          const int h_start =
+              (hpad < window_rows) ? 0 : (hpad - window_rows) / row_stride + 1;
+          const int h_end = std::min(hpad / row_stride + 1, out_height);
+          const int w_start =
+              (wpad < window_cols) ? 0 : (wpad - window_cols) / col_stride + 1;
+          const int w_end = std::min(wpad / col_stride + 1, out_width);
+          // compute elementwise max
+          const int64 in_index = (b * in_rows + h) * in_cols + w;
+          for (int ph = h_start; ph < h_end; ++ph) {
+            const int64 out_index_base = (b * out_height + ph) * out_width;
+            for (int pw = w_start; pw < w_end; ++pw) {
+              const int64 out_index = out_index_base + pw;
+              /// NOTES(zhengxq): not using the eigen matrix operation for
+              /// now.
+              for (int d = 0; d < depth; ++d) {
+                const T& input_ref = in_mat.coeffRef(d, in_index);
+                T& output_ref = out_mat.coeffRef(d, out_index);
+                int64& out_arg_max_ref = out_arg_max_mat.coeffRef(d, out_index);
+                if (output_ref < input_ref ||
+                    out_arg_max_ref == kInvalidMaxPoolingIndex) {
+                  output_ref = input_ref;
+                  int64 input_offset = in_index * depth + d;
+                  out_arg_max_ref = input_offset;
+                }
+              }
+            }
+          }
+        }
+      }
+    }
+
+  };
+
+  const int64 shard_cost = params.tensor_in_rows * params.tensor_in_cols *
+                           params.depth * params.window_rows *
+                           params.window_cols;
+  Shard(worker_threads.num_threads, worker_threads.workers,
+        params.tensor_in_batch, shard_cost, shard);
+}
+
+template <typename Device, typename T>
+static void SpatialMaxPoolWithArgMaxHelper(
+    OpKernelContext* context, Tensor* output, Tensor* output_arg_max,
     Tensor* input_backprop, const Tensor& tensor_in, const Tensor& out_backprop,
     const PoolParameters& params, const Padding& padding) {
   typedef Eigen::Map<const Eigen::Matrix<T, Eigen::Dynamic, Eigen::Dynamic>>
@@ -902,8 +1010,8 @@ class MaxPoolingWithArgmaxOp : public OpKernel {
     Tensor* argmax = nullptr;
     OP_REQUIRES_OK(context, context->allocate_output(1, out_shape, &argmax));
 
-    LaunchMaxPoolingWithArgmax<Device, T>::launch(context, params, tensor_in,
-                                                  output, argmax);
+    SpatialMaxPoolWithArgMaxHelper<CPUDevice, T>(
+        context, output, argmax, tensor_in, params, padding_);
   }
 
  private:
@@ -957,9 +1065,9 @@ class MaxPoolingGradWithArgmaxOp : public OpKernel {
     Tensor* grad_out = nullptr;
     OP_REQUIRES_OK(context, context->forward_input_or_allocate_output(
                                 {1}, 0, out_shape, &grad_out));
-
-    LaunchMaxPoolingGradWithArgmax<Device, T>::launch(context, params, grad_in,
-                                                      argmax, grad_out);
+    // SpatialMaxPoolWithArgMaxHelper<CPUDevice, T>(
+    //     context, grad_out, &argmax, grad_in, params, padding_);
   }
 
  private:
@@ -1189,6 +1297,109 @@ class MaxPoolingNoMaskV2Op<GPUDevice, T> : public OpKernel {
   bool use_dnn_;
 };
 
+template <typename Device, typename T>
+class MaxPoolingWithArgmaxOp : public OpKernel {
+ public:
+  explicit MaxPoolingWithArgmaxOp(OpKernelConstruction* context)
+      : OpKernel(context) {
+    OP_REQUIRES_OK(context, context->GetAttr("ksize", &ksize_));
+    OP_REQUIRES(context, ksize_.size() == 4,
+                errors::InvalidArgument("Sliding window ksize field must "
+                                        "specify 4 dimensions"));
+    OP_REQUIRES_OK(context, context->GetAttr("strides", &stride_));
+    OP_REQUIRES(context, stride_.size() == 4,
+                errors::InvalidArgument("Sliding window stride field must "
+                                        "specify 4 dimensions"));
+    OP_REQUIRES_OK(context, context->GetAttr("padding", &padding_));
+    OP_REQUIRES(context, ksize_[0] == 1 && stride_[0] == 1,
+                errors::Unimplemented(
+                    "Pooling is not yet supported on the batch dimension."));
+
+    TF_CHECK_OK(ReadBoolFromEnvVar("TF_ENABLE_MAXPOOL_NANPROP", false,
+                                   &propagate_nans_));
+  }
+
+  void Compute(OpKernelContext* context) override {
+    const Tensor& tensor_in = context->input(0);
+
+    PoolParameters params{context,  ksize_,      stride_,
+                          padding_, FORMAT_NHWC, tensor_in.shape()};
+    if (!context->status().ok()) {
+      return;
+    }
+
+    TensorShape out_shape({params.tensor_in_batch, params.out_height,
+                           params.out_width, params.depth});
+    Tensor* output = nullptr;
+    OP_REQUIRES_OK(context, context->allocate_output(0, out_shape, &output));
+    Tensor* argmax = nullptr;
+    OP_REQUIRES_OK(context, context->allocate_output(1, out_shape, &argmax));
+
+    LaunchMaxPoolingWithArgmax<Device, T>::launch(
+        context, params, tensor_in, output, argmax, propagate_nans_);
+  }
+
+ private:
+  std::vector<int32> ksize_;
+  std::vector<int32> stride_;
+  Padding padding_;
+  bool propagate_nans_;
+};
+
+template <typename Device, typename T>
+class MaxPoolingGradWithArgmaxOp : public OpKernel {
+ public:
+  explicit MaxPoolingGradWithArgmaxOp(OpKernelConstruction* context)
+      : OpKernel(context) {
+    string data_format_str;
+    auto status = context->GetAttr("data_format", &data_format_str);
+    if (status.ok()) {
+      OP_REQUIRES(context, FormatFromString(data_format_str, &data_format_),
+                  errors::InvalidArgument("Invalid data format"));
+    }
+
+    OP_REQUIRES_OK(context, context->GetAttr("ksize", &ksize_));
+    OP_REQUIRES(context, ksize_.size() == 4,
+                errors::InvalidArgument("Sliding window ksize field must "
+                                        "specify 4 dimensions"));
+    OP_REQUIRES_OK(context, context->GetAttr("strides", &stride_));
+    OP_REQUIRES(context, stride_.size() == 4,
+                errors::InvalidArgument("Sliding window stride field must "
+                                        "specify 4 dimensions"));
+    OP_REQUIRES_OK(context, context->GetAttr("padding", &padding_));
+    OP_REQUIRES(context, ksize_[0] == 1 && stride_[0] == 1,
+                errors::Unimplemented(
+                    "Pooling is not yet supported on the batch dimension."));
+  }
+
+  void Compute(OpKernelContext* context) override {
+    const Tensor& tensor_in = context->input(0);
+    const Tensor& grad_in = context->input(1);
+    const Tensor& argmax = context->input(2);
+
+    PoolParameters params{context,  ksize_,      stride_,
+                          padding_, FORMAT_NHWC, tensor_in.shape()};
+    if (!context->status().ok()) {
+      return;
+    }
+
+    TensorShape out_shape({params.tensor_in_batch, params.tensor_in_rows,
+                           params.tensor_in_cols, params.depth});
+    Tensor* grad_out = nullptr;
+    OP_REQUIRES_OK(context, context->forward_input_or_allocate_output(
+                                {1}, 0, out_shape, &grad_out));
+
+    LaunchMaxPoolingGradWithArgmax<Device, T>::launch(context, params, grad_in,
+                                                      argmax, grad_out);
+  }
+
+ private:
+  std::vector<int32> ksize_;
+  std::vector<int32> stride_;
+  Padding padding_;
+  TensorFormat data_format_;
+};
+
 template <typename T>
 struct LaunchMaxPoolingNoMask<Eigen::GpuDevice, T> {
   static void launch(OpKernelContext* context, const PoolParameters& params,
@@ -1296,6 +1507,16 @@ struct LaunchMaxPoolingGradGradWithArgmax<Eigen::GpuDevice, T> {
 
 // Below kernels implemented only for CPU device.
 #define REGISTER_CPU_ONLY_POOL_KERNELS(T)                          \
+  REGISTER_KERNEL_BUILDER(Name("MaxPoolWithArgmax")                \
+                            .Device(DEVICE_CPU)                    \
+                            .TypeConstraint<int64>("Targmax")      \
+                            .TypeConstraint<T>("T"),               \
+                        MaxPoolingWithArgmaxOp<CPUDevice, T>);     \
+  REGISTER_KERNEL_BUILDER(Name("MaxPoolGradWithArgmax")            \
+                            .Device(DEVICE_CPU)                    \
+                            .TypeConstraint<T>("T")                \
+                            .TypeConstraint<int64>("Targmax"),     \
+                        MaxPoolingGradWithArgmaxOp<CPUDevice, T>); \
   REGISTER_KERNEL_BUILDER(                                         \
       Name("MaxPool").Device(DEVICE_CPU).TypeConstraint<T>("T"),   \
       MaxPoolingOp<CPUDevice, T>);                                 \

**Comment by mmpinso** [comment]
Thanks a lot @saeed68gm , I'm trying to run [ENet](https://github.com/kwotsin/TensorFlow-ENet) on Android. What was the other op you had to add?
To get the mobile working version of this workaround should do as following or am I missing something?

1. [Apply](https://www.tensorflow.org/extend/adding_an_op) the changes to my local tensorflow source code
2. [Compile](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android) libtensorflow_inference.so with Bazel with the updated tensorflow local source code
3. Remaining usual steps

**Comment by saeed68gm** [comment]
@mmpinso awesome. That is correct. Just make sure you include that in your lib files in android and you are all set. For me I had to add MaxPoolGradWithArgmax to CPU as well, but I couldn't get it working so it is a blank op. MaxPoolGradWithArgmax was only used for training so I need the op to load the model and freeze it, after freezing it I did not need that op anymore.

**Comment by liangxiao05** [comment]
@saeed68gm，thanks,I will follow your instructions next. 
@mmpinso ,same with you,I'm doing work with ENet on Android. So how's the latency you run it on your mobile ?

**Comment by DenisN03** [comment]
@mmpinso, @liangxiao05 why do you run enet instead of segnet? Did you run enet on cpu?

**Comment by saeed68gm** [comment]
@mmpinso Sure, I can share it in a bit. Did you make sure you are on tensorflow version 1.4? the patch should apply seamlessly. Just change the extension to .patch and apply using the command git apply max_pool_1.4.patch

**Comment by mmpinso** [comment]
@saeed68gm that was it, I was on the main/default branch. Changed to cuda 8 & cudnn 6 also and recompiling tensorflow now; thanks !!

**Comment by DenisN03** [comment]
@saeed68gm, @mmpinso I tried to apply the command "git apply max_pool_1.4.patch" but got the error "fatal: the patch is corrupted on line 143"

**Comment by mmpinso** [comment]
@DenisN03 , @saeed68gm I had this same error so I ended applying it manually. It compiled, but I'm afraid I might introduced some kind of fault. It would help a lot to have the full .cc file

**Comment by saeed68gm** [comment]
@mmpinso @DenisN03 
Not sure why you get that error, it is pretty strange.
I am uploading the full file here. I have to change the extension to .txt to upload on github, maybe that introduces issues?
Either way, let me know if this helps! sounds like you both have very interesting projects going on :)

[maxpooling_op.txt](https://github.com/tensorflow/tensorflow/files/1626793/maxpooling_op.txt)

**Comment by saeed68gm** [comment]
@mmpinso  Hmmm... I am not sure why you are getting that. Maybe your config is not correct? I only compiled it for android after that so could be because you are trying to compile it for cuda as well. As far as I know, you do not need the extra arguments when you are compiling the android inference library.

**Comment by mmpinso** [comment]
@saeed68gm Ok I think I understood the context: I should be using this custom tf version only to obtain the android inference library and run the model on the phone. So I'll install it in a separate env and keep my usual tf installation in another one for the trainings and everything else. I reviewed the config accordingly and now it compiles.
( @liangxiao05 I haven't forgot regarding the inference time )

**Comment by mmpinso** [comment]
@liangxiao05 did you get the following error? No OpKernel was registered to support Op '**ScatterNd**' with these attrs.

[[Node: ENet/unpool/ScatterNd = ScatterNd[T=DT_FLOAT, Tindices=DT_INT32](ENet/unpool/transpose, ENet/unpool/Reshape_2, ENet/unpool/ScatterNd/shape)]]

**Comment by liangxiao05** [comment]
@DenisN03，hi, cuz ENet seems to be  mush faster then segnet on Desktop，if I try to run it  on android in real time ,latency is the most important thing.
@mmpinso Yor are ahead of me ,  I haven't succeeded to run ENet on CPU even on my Desktop . I just see the full maxpooling_op.cc  shared by @saeed68gm，there are some differences between mine . I will try more in the next few days ,once there's some progress, and I'll be in sync :)

**Comment by saeed68gm** [comment]
@mmpinso No, if you look at the code, the LaunchMaxPoolingWithArgmax function will call the cuda code to compute maxPoolingWithArgmax on GPU. The problem is the unpooling operation that uses the scatter function and looks like everybody need the unpooling operation. Can somebody maybe implement this operation for CPU and share the code?

Here is a sample in python, we need to create it in CPP:
`def unpool(pool, ind, ksize=[1, 2, 2, 1], scope='unpool'):
    
	with tf.variable_scope(scope):
		input_shape = pool.get_shape().as_list()
		output_shape = (input_shape[0], input_shape[1] * ksize[1], input_shape[2] * ksize[2], input_shape[3])

		flat_input_size = np.prod(input_shape)
		flat_output_shape = [output_shape[0], output_shape[1] * output_shape[2] * output_shape[3]]

		pool_ = tf.reshape(pool, [flat_input_size])
		batch_range = tf.reshape(tf.range(output_shape[0], dtype=ind.dtype), shape=[input_shape[0], 1, 1, 1])
		b = tf.ones_like(ind) * batch_range
		b = tf.reshape(b, [flat_input_size, 1])
		ind_ = tf.reshape(ind, [flat_input_size, 1])
		ind_ = tf.concat([b, ind_], 1)

		ret = tf.scatter_nd(ind_, pool_, shape=flat_output_shape)
		ret = tf.reshape(ret, output_shape)
		return ret`

**Comment by DenisN03** [comment]
@saeed68gm, @mmpinso, @liangxiao05 what enet implementation are you using? I use this -
 https://github.com/fregu856/segmentation.

**Comment by saeed68gm** [comment]
@DenisN03  I am not trying to run ENet. I am using it for matting here:
https://github.com/Joker316701882/Deep-Image-Matting

I may try to implement unpooling. It seems pretty straightforward, but multithreading is a bit of challenge for me.

**Comment by mmpinso** [comment]
@DenisN03 the version you use also uses max_pool_with_argmax as [Kwotsin's](https://github.com/kwotsin/TensorFlow-ENet).
@liangxiao05 , @saeed68gm , we are trying the following approach: 
- replace max_pool_with_argmax by simple max_pool, without getting the indices
- unpool with resize_nearest_neighbor or resize_bilinear
The first tests show no apparent loss on our application, dont know yet regarding the inference time on CPU.

If this workaround finally does not suit our needs, we'll probably just switch to Caffe2...

**Comment by DenisN03** [comment]
@mmpinso, did you manage to cope with the mistake related with ScatterNd?

**Comment by mmpinso** [comment]
@DenisN03 We applied the solution I mentioned before and we have it running. Inference time is around 3 seconds on a Huawei P10 Lite.

**Comment by saeed68gm** [comment]
@mmpinso did have to retrain your model to achieve that?

**Comment by liangxiao05** [comment]
@mmpinso 3s seems to be too long for mobiles applications . In your opition , is it feasible to be optimized in a short term?

**Comment by mmpinso** [comment]
@liangxiao05 we got 3s on 320x320 images. We'll try using a smaller size like 200x200 + quantize the model and see what we get.

**Comment by nio1814** [comment]
As @mmpinso noted, SpatialMaxPoolWithArgMaxHelper in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/maxpooling_op.cc actually does the max pool and argmax calculations on the CPU.

Currently, it's only used for the gradient calculation. I'm working on also calling it from MaxPoolingWithArgmaxOp::Compute for the CPU.

https://github.com/nio1814/tensorflow/tree/maxpoolwithargmax-cpu

**Comment by saeed68gm** [comment]
@nio1814 My patch does what you want to do I believe. Give it a read and let me know what you think

**Comment by nio1814** [comment]
Yeah, looks pretty similar. Sorry. I didn't realize you had already started working on this. 

Are you planning on doing a PR? I think people would find it useful.
If there's a branch your working from I could go ahead and add the gradient op. It should just be another call to SpatialMaxPoolWithArgMaxHelper.

**Comment by DenisN03** [comment]
@mmpinso, @liangxiao05, did you succeed in coloring the result after processing the image with a neural network? If so, how do you do this? I'm trying to implement a function from the examples of the opencv - colorizeSegmentation library in the Java language, but so far it has not turned out.

**Comment by mmpinso** [comment]
@DenisN03 yes, we did it with TF itself. FYI, in our project we do binary segmentation, so we replaced the softmax by sigmoid. Then:

`
            predictions = tf.cast(tf.round(probabilities), tf.int32, name='output')


            #=============PAINTED OUTPUT=============
            #Compute an inverse of the output mask
            predictions_inverse = tf.cast(tf.subtract(tf.ones([inputs_shape[1], inputs_shape[2], inputs_shape[3]], tf.int32), predictions), tf.float32)

            #Remove the original object to detect from the images by applying the mask
            holes = tf.multiply(images, predictions_inverse) * 255

            #Transform the output mask into a color mask with 3 channels, according to the rgb input value.
            color_mask = tf.concat([predictions * color[0], predictions * color[1], predictions * color[2]], axis=3)

            #Fill the holes with the color mask
            painted_output = tf.add(color_mask, holes, name='painted_output')`

**Comment by DenisN03** [comment]
@mmpinso, that is, you segment only two classes? How long does it take to process one image? what resolution do you use? you managed to find faster architectures?

**Comment by mmpinso** [comment]
@DenisN03 , one class + background.
It took around 1.6 seconds with quantization on a Huawei P10 Lite with 200*200 images. With smaller images, quality was very bad.
We are currently trying [MobileUNet](https://github.com/akirasosa/mobile-semantic-segmentation). First results show 0.86 seconds without quantization and 224*224 images.
We would also like to try Mask RCNN at some point.

**Comment by saeed68gm** [comment]
@nio1814 I have a couple of items on my hand, but I am down to maybe create a pull request for this some time soon. I would appreciate your feedback on the code as well.

@mmpinso @DenisN03 Mobilenet v2 seems very promising for this task as well. The results published are really good and it's even faster than mobilenet v1. But I have yet to get my hands on the pretrained waits (it was published Jan 2018). If you guys investigate I would like to know as well.

**Comment by NPetsky** [comment]
Someone should close this issue, since it has been merged on 6. Apr in #18145 (see above)

**Comment by suharshs** [comment]
Closed based on @NPetsky 's comment. Thanks!
