### ISSUE TITLE
Failing to build version 2.14.0 with numa

### ISSUE THREAD

**Issue by fgava90** [tensorflow/tensorflow#63080]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14.0

### Custom code

No

### OS platform and distribution

linux rocky8

### Python version

3.8.7

### Bazel version

6.1.0

### GCC/compiler version

gcc 11.3.0

### CUDA/cuDNN version

cuda 11.8.0

### Current behavior?

tensorflow v2.14.0 seems to fail configuring when adding --config=numa 
```
bazel' '--nohome_rc' '--nosystem_rc' '--output_user_root=/tmp/spackweoy5szc' 'build' '--color=no' '--jobs=10' '--config=opt' '--verbose_failures' '--config=dynamic_kernels' '--config=cuda' '--config=noaws' '--config=nogcp' '--config=nohdfs' '--config=numa' '--config=v2' '//tensorflow/tools/pip_package:build_pip_package'
...
ERROR: Config value 'numa' is not defined in any .rc file
```

### Standalone code to reproduce the issue

```shell
bazel' '--nohome_rc' '--nosystem_rc' '--output_user_root=/tmp/spackweoy5szc' 'build' '--color=no' '--jobs=10' '--config=opt' '--verbose_failures' '--config=dynamic_kernels' '--config=cuda' '--config=noaws' '--config=nogcp' '--config=nohdfs' '--config=numa' '--config=v2' '//tensorflow/tools/pip_package:build_pip_package'
```

**Comment by tilakrayal** [comment]
@fgava90,
From the information provided, I can see that you are trying to install the tensorflow v2.14 with python 3.8.7 and gcc 11.3.0 which are incompatible. Tensorflow v2.14 is compatible with python v3.9-3.11 and compiler Clang 16.0.0.

Could you please try to follow the tested build configurations from the official document for the smooth installation of tensorflow.
https://www.tensorflow.org/install/source#tested_build_configurations

Thank you!

**Comment by fgava90** [comment]
Sorry, my bad. It wasn't python 3.8.7 but python 3.11.6. 
Compiler was gcc 11.3.0

**Comment by fgava90** [comment]
This command:
```bazel --nohome_rc --nosystem_rc --output_user_root=/tmp/spackd8v53qm6 build --color=no --jobs=16 --config=opt --verbose_failures --config=dynamic_kernels --config=cuda --config=noaws --config=nogcp --config=nohdfs --config=numa --config=v2 //tensorflow/tools/pip_package:build_pip_package```
produces:
```ERROR: Config value 'numa' is not defined in any .rc file```

This command:
```bazel --nohome_rc --nosystem_rc --output_user_root=/tmp/spackd8v53qm6 build --color=no --jobs=16 --config=opt --verbose_failures --config=dynamic_kernels --config=cuda --config=noaws --config=nogcp --config=nohdfs --config=v2 //tensorflow/tools/pip_package:build_pip_package```
(which is the same without `--config=numa`) passes the configuration stage.

Trying to grep for `numa` in the sources directory yelds:
```console
$ grep  numa *
configure.py:  config_info_line('numa', 'Build with NUMA support.')
RELEASE.md:    *   Removing the `experimental_numa_aware` option from `tf.data.Options`.
$ grep numa .bazel*
```

Up to version 2.13.1, this was present in `.bazelrc` and is no longer present in 2.14
```
# Options extracted from configure script
build:numa --define=with_numa_support=true
```

Does this means that `--config=numa` is no longer supported from version 2.14 and that the following line should be removed from `configure.py`?
```python
 config_info_line('numa', 'Build with NUMA support.')
```
(it's still present in 2.15 but same stuff missing in `.bazelrc`)

I thinks all this is independent from python or compiler type/version as we are still in bazel configuration and haven't started building anything yet.

**Comment by tilakrayal** [comment]
@fgava90,
Apologies for the delay. Could you please try to install the tensorflow with the latest version 2.16.1(~2.16.0)  from the below commit https://github.com/tensorflow/tensorflow/commit/5bc9d26649cca274750ad3625bd93422617eed4b and let us know if you are facing the same issue. Most of the bugs are resolved in the latest version. Thank you!

**Comment by fgava90** [comment]
@tilakrayal 
I will try to do it ASAP, but the incongruency between `.bazerc` and `configure.py` is still there (also in `master`) 

I guess we need to understand which one of these possibility is correct:

- the `numa` option is now active by default and doesn't need to be passed by configure arguments, so the line in `configure.py` is superflous
- the `numa` option has been deprecated and can no longer be used, so the line in `configure.py` is wrong and should be removed
- nothing changed WRT the `numa` option, so there is a missing line in `.bazelrc` 

As you can imagine, I do not have the necessary knowledge of the code to answer this

**Comment by tilakrayal** [comment]
@fgava90,
Could you please provide the update if you were tried installing the tensorflow latest stable v2.16 and facing the same error/issue. Thank you!

**Comment by fgava90** [comment]
Hello @tilakrayal .
Sorry, i have been busy and couldn't work on this for a bit. I have just tested the commit youo suggested and the issue persist.

**Comment by fgava90** [comment]
I have tried as an experiment to pass `--config=xxx` and i get the same error as with `--config=numa`:
```
bazel' '--nohome_rc' '--nosystem_rc' '--output_user_root=/tmp/spack1nfqzayk' 'build' '--color=no' '--jobs=16' '--config=opt' '--verbose_failures' '--config=dynamic_kernels' '--config=cuda' '--config=noaws' '--config=nogcp' '--config=nohdfs' '--config=xxx' '--config=v2' '//tensorflow/tools/pip_package:build_pip_package'
...
Starting local Bazel server and connecting to it...
ERROR: Config value 'xxx' is not defined in any .rc file
```

So either `--config=numa` have been removed at some point, or there's something missing in the .bazelrc file (see my comments above)

**Comment by fgava90** [comment]
@kanglant Tagging you here because i found this commit which removes the numa config:
https://github.com/tensorflow/tensorflow/commit/ffd06c0782a31766b15b6730aac48d124cdf4a11

**Comment by tilakrayal** [comment]
@fgava90,
Could you please check with the latest build or the tf-nightly build, and let us know if you are facing the same build error. As per the above mentioned commit it might be resolved in the latest versions. Thank you!

**Comment by adamjstewart** [comment]
The above mentioned commit is the cause of the issue, not the fix.

**Comment by tilakrayal** [comment]
//cc @learning-to-play

**Comment by learning-to-play** [comment]
Have you tried updating to TF 2.16 as suggested [above](https://github.com/tensorflow/tensorflow/issues/63080#issuecomment-2006533553)? Unfortunately TF 2.14 isn't supported any more. FYI, new TF 2.17 release and patch TF 2.16.2 release are scheduled for early July.

**Comment by fgava90** [comment]
Hi @learning-to-play ,

Yes, i had tried also 2.16. 

The issue is caused by this commit https://github.com/tensorflow/tensorflow/commit/ffd06c0782a31766b15b6730aac48d124cdf4a11 which removes the numa config (and many others) from the bazelrc.
If you diff the bazelrc from that commit onwards you'll see it has never been put back.

Now it would be interesting to understand why numa (and the other options) has been removed from the bazelrc.
Is it because it is always implicitly active? Is it automatically detected? Was the corresponding feature removed completely? 
As it is still present in the configure.py, making the two files incoherent with each other, this is pretty confusing and the comment of the mentioned commit does not explain why they are deemed no longer relevant.

**Comment by kanglant** [comment]
Hi @fgava90 , 

Apologies for the delayed response. We removed the NUMA configuration because it was enabled by default in TensorFlow's BUILD (and later refactored to tsl/BUILD in this [commit](https://github.com/tensorflow/tensorflow/commit/dc2bfae69be58eea63927ffa5900d70b349d1638)), and we didn't find any instances where it was explicitly used. That's why we removed it, and we apologize for not updating the configure.py script to reflect this change. The feature is still supported.

If you'd like to enable NUMA support explicitly, you can add `--define=with_numa_support=true` to your bazel build command or include it in an [user-specified RC file](https://bazel.build/run/bazelrc#bazelrc-file-locations). If you've previously run configure.py, it should have generated a .tf_configure.bazelrc file that's imported into TensorFlow's .bazelrc; you can add the configuration there as well.

If you think the `numa` configuration flag should be added back to TensorFlow's .bazelrc file, could you please let us know why?

**Comment by adamjstewart** [comment]
@kanglant if I understand correctly, for TF 2.13 and older, the correct flag to control NUMA support was:
```
--config=numa
```
and for TF 2.14+ it is now:
```
--define=with_numa_support=true
```
Is that correct? If so, we'll update our [Spack](https://spack.io) package recipe for TF.

**Comment by kanglant** [comment]
Yes. The `--config=numa` flag was used as a convenient shorthand for grouping options related to NUMA support, initially containing just the `--define=with_numa_support=true` option. If we anticipate adding more NUMA-specific options in the future, it would make sense to reintroduce the `--config=numa` flag for improved usability.

**Comment by Kayyuri** [comment]
Hi @fgava90, Apologies for the delayed response. 

Could you please confirm if the issue has been resolved on your end? If so, please feel free to close it.
Big thanks to @adamjstewart for raising the [PR](https://github.com/spack/spack/pull/44607) to address this issue. We truely appreciate the effort.

Thanks!

**Comment by fgava90** [comment]
Hello, 
Thank all for the PR.
I haven't been able to compile py-tensorflow with spack 1.1.0 recently (independently of +numa or not) so i can't verify it, hower the PR code seems sensible and i'm happy to close the issue.
Shall I have any problem with it, i'll reopen.
