### ISSUE TITLE
Gradients of non-scalars (higher rank Jacobians)

### ISSUE THREAD

**Issue by zackchase** [tensorflow/tensorflow#675]
Currently if you call gradients(ys, xs), it will return the sum of dy/dx over all ys for each x in xs. I believe this doesn't accord with an a priori mathematical notion of the derivative of a vector. I'd like the way to take the derivative of ys wrt xs where both are vectors and have a Jacobian matrix returned. By extension, I'd like to take the derivative of a vector wrt a matrix and get back a 3-tensor. There doesn't seem to be a convenient tensorflow function to compute the Jacobian or higher order derivatives. Am I missing something or is this functionality that we could add?

**Comment by keveman** [comment]
zackchase@, you are right about the current `gradients` function. Currently, you can compute the Jacobian of, say, a vector, by calling `gradients` multiple times, one for every scalar component (obtained by slicing) of the original vector, and reassembling the results. Contributions are welcome to make this nicer and efficient.

**Comment by girving** [comment]
It'd be pretty hard to support gradients of non-scalars with our current setup, since it would require every gradient function to handle extra rank input.  The one possibility I could see would be if we add some sort of map facility to register how to add extra ranks to ops, then compute gradients with respect to extra rank by computing lower rank and calling the registered map transformations.

Someone asked for map a while back, so if anyone wanted to tackle this task that might be the way to go.  Handling it at the gradient function level is probably bad, since it would add required complexity to an existing feature.  Warning: This is a pretty large change, so a good deal of discussion would be in order before starting.

**Comment by zackchase** [comment]
Hi Geoffrey, thanks for taking an interest in this issue. I was initially confused by the use of "rank" to describe the number of dimensions of the array. Should we avoid this name in the thread title and documentation to preempt confusion via overloading the linear algebra notion of rank?

**Comment by girving** [comment]
Tensor rank is very standard terminology: http://mathworld.wolfram.com/TensorRank.html

**Comment by zackchase** [comment]
Cool. The terminology gets funny when we talk about rank-R decompositions of tensors, meaning the tensor can be represented as a sum of R outer products of rank-1 tensors, but probably not a problem for us to solve here.

One thing I thought of is that I would like to compute the frobenius norm of the Jacobian of the log probabilities for use as a smoothness penalty as in a contractive autoencoder. In this case, as we only seek a scalar at the end, is there a more efficient method than separately calculating the derivative of each output with respect to the inputs?

**Comment by girving** [comment]
Are you saying your network has a bunch of outputs, and then you combine them into a single scalar that you are trying to optimize?  In that case, you should differentiate with respect to that single scalar.

**Comment by zackchase** [comment]
Not exactly. I'm saying if one wants to penalize the norm of the Jacobian of the mapping function. 
So optimization objective would be (pseudocode):

cost(y,yhat, X) = loss(y,yhat) + norm(Jacobian(log(yhat), X))

**Comment by girving** [comment]
Ah, sorry for not reading carefully.  You're correct that (as far as I know) there's no easy way to do that in tensorflow.  According to someone more knowledgeable than I, people generally do such contractive autoencoders by writing out the first derivative manually.  Also, they generally restrict to single layer at a time networks for speed issues, since doing the full Jacobian for a multilayer network is quite expensive.

**Comment by zackchase** [comment]
Regardless, it would be good to have a way to call derivatives of vectors and receive gradients of the expected shape.

**Comment by yaroslavvb** [comment]
Differentiating with respect to one variable is similar to how it works in Theano. I agree it may be confusing when TensorFlow automatically turns many variables into one by taking the sum. An alternative would be to fail if there's more than 1 output variable specified, and require the user to specify sum explicitly.

The reason for "one output variable at a time" in TensorFlow (and Theano) is because we do reverse mode AD by default. In reverse AD you have a single target scalar quantity and you propagate sensitivities with respect to that quantity. In contrast, if you we did forward AD instead, we would naturally support multiple output variables, but only compute derivative with respect to one scalar variable at a time. Supporting mixed mode propagation to cover "multiple inputs/multiple outputs" case could be a lot of extra plumbing.

If you have a small number of output variables, standard thing to do is to apply reverse AD with respect to each variable in a loop. This is what Theano recommends to do for compute Hessian for instance: http://deeplearning.net/software/theano/tutorial/gradients.html#computing-the-hessian.

**Comment by tillahoffmann** [comment]
I was hoping to implement higher order derivatives using the map function but am getting an error message I can't quite get my head around. My implementation is (in pseudo code)

```
params = tf.Variable("some initial value")
loss = some_function(params)
grads = tf.gradients(loss, params)[0]
hess = tf.map_fn(lambda grad: tf.gradients(grad, X)[0], grads)
```

When I fetch the hessian, I get the error message

```
InvalidArgumentError: All inputs to node map/while/gradients/map/TensorArrayUnpack_grad/TensorArrayGrad/TensorArrayGrad must be from the same frame.
```

I assumed that tensorflow has an issue because it doesn't know about `params` in the loop (cf. [`non_sequences` in theano `scan`](http://deeplearning.net/software/theano/library/scan.html)), and extended `map_fn` to pass extra arguments to the loop. Unfortunately, the extra arguments get wrapped in an identity transformation and `tf.gradients(params, tf.identity(params))` gives `[None]`, which seems a bit unintuitive.

Looping in python is of course fine but I'd like to avoid introducing an extra node to the graph for every parameter. Any suggestions?

**Comment by girving** [comment]
@yuanbyu: Do you understand this issue with `tf.map_fn`?

**Comment by girving** [comment]
Note for anyone who comes across this thread: `tf.map_fn` is an unrelated thing involving control flow, not something related to mapping over extra rank tensors.

**Comment by yuanbyu** [comment]
We don't support higher-order gradients for while_loop/map_fn/scan/fold. You should see an informative error message if you try to do that.

**Comment by yaroslavvb** [comment]
@vladfi1 I'm no longer at Brain, so I wouldn't know. I would say it is unlikely to ever be part of core TensorFlow. There are >450 ops in TF, so Brain team would have to implement forward AD grad method for all of 450 ops and maintain them forever, or alternatively have to explain why someone's favorite op doesn't have AD support.  It seems more realistic that someone would create a separately maintained library that does forward-AD, and utilizes TensorFlow as backend. Kind of like autograd but using TensorFlow instead of numpy as the backend.

**Comment by myaooo** [comment]
Is `tf.test.compute_gradient` is some kind of funtion that we can get the jacobian matrix (not as a tensor but as a numpy.ndarray) of a vector tensor y w.r.t. a vector tensor x?

**Comment by yaroslavvb** [comment]
There are no built-in jacobians in TensorFlow, instead anything called
'grad' or 'gradient' computes Jacobian-vector product (also called LOp in
theano), see
https://en.wikipedia.org/wiki/Automatic_differentiation#Reverse_accumulation

**Comment by myaooo** [comment]
@yaroslavvb Thanks for your reply. I see why it's expensive to do that.

**Comment by tillahoffmann** [comment]
[Hessians](https://www.tensorflow.org/api_docs/python/tf/hessians) are supported but yes, they are expensive to compute.

**Comment by yaroslavvb** [comment]
@myaooo currently `tf.gradients` gives gradient of function which outputs a scalar. You could call it multiple times for each output. IE, `[tf.gradients(component, var) for component in vector]`. 
There's a trick for computing hessians more efficiently described in https://github.com/tensorflow/tensorflow/issues/4897#issuecomment-253056458

**Comment by el3ment** [comment]
Adding a comment that this was also a bit of a gotcha for me, and simultaenously adding a vote to consider a change to the api. Calling `tf.gradients(matrix, vector, aggregation_method=None)` I would have expected it to return an tensor of the same shape as `matrix`, but it returns `sum(M)` along an axis.

**Comment by yaroslavvb** [comment]
It's a little less surprising when you know that there's no efficient algorithm to compute Jacobian, therefore all neural net frameworks use reverse mode AD which requires target to be a scalar

**Comment by girving** [comment]
@el3ment I consider this a bug.  Unfortunately, I've looked into fixing it, and there's a surprising number of tests within TensorFlow that depend on it.  I didn't get past said piles of tests to see whether there's interesting downstream code in Google that uses it.

**Comment by USTC-Tim** [comment]
@el3ment @girving 
I found this confusion as well.
`x = tf.constant([3], dtype=tf.float32)
y = tf.constant([9,8,7,6,5], dtype=tf.float32)
z = x_mean * y
sess.run(tf.gradients(z, x_mean))`
and I got array([35.])

**Comment by isabeaups** [comment]
Just trying to understand something. I was trying to make a hack of `tf.gradient` that would give, for a `y` of rank (M,N) and an `x` of rank (Q,P) a gradient tensor of rank (M,N,Q,P) as one would naturally expect. However, as mentioned already here, what one gets is a rank (Q,P) which is the grad of the sum of the elements of `y`.  Now what I can't figure out, looking into the tensorflow code is where is that sum over elements of `y`  made? Is it as the beginning or at the end? Could someone help me pinpoint the lines of code where that is done?

**Comment by yaroslavvb** [comment]
Note that "summing ys together" is sort of buried deep in backprop. Note that TensorFlow uses Reverse Mode AD in order to compute gradients, and reverse mode AD only supports a scalar output function. If you have non-scalar output, we don't have any algorithm much better than calling reverse mode AD on each of the components of the output separate.

(there's a trick mentioned by ian [here](https://github.com/tensorflow/tensorflow/issues/4897#issuecomment-253056458) which is a bit better on Python overhead compared to calling gradients many times)

That said, the place where `summation of ys` happens is in line 479-481 in [gradients_impl.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/gradients_impl.py#L479)

First note that `grad_ys` are set to the same value in this line
`grad_ys = _DefaultGradYs(grad_ys, ys, colocate_gradients_with_ops)
`
Later there's this block
```

 # Add the initial gradients for the ys.
    for y, grad_y in zip(ys, grad_ys):
      _SetGrad(grads, y, grad_y)
```

Note that if you had a single y*=y1+y2+y3+..., then the gradients would propagate in the same way -- the same backprop value from y would be copied over to nodes y1,y2,y3, so this block implicitly treats `ys` as being added up into the final sum

**Comment by isabeaups** [comment]
Thanks for your response!

But there are two things which confuse me from your answer:

**(1)** 

> we don't have any algorithm much better than calling reverse mode AD on each of the components of the output separate.

I'm pretty sure that that cannot be the case. If you think of a deep network outputting a vector `y`, then the gradient of `y[0]` is basically the same as that from `y[1]`, they only defer by the last weight matrix elements. i.e. `y[0] = W(0,j) V(j, ...) ` while `y[1] = W(1,j) V(j,...)`.

**(2)**     You say the summation happens at line 479-481 of gradients_impl.py
But just above those lines, there is the following comment in the code: 
# grads: op => list of gradients received on each output endpoint of the
    # op.  The gradients for each endpoint are initially collected as a list.
    # When it is time to call the op's gradient function, for each endpoint we
    # aggregate the list of received gradients into a Add() Operation if there
# is more than one.

And indeed when one looks into the function `_SetGrad` there is no addition, only appending to a list, and all the `y` 's, if I understand correctly, are still kept separate by being different keys to the dictionary `grads`.  

So I am utterly confused by this.

Also thank you very much for Ian's trick, but I don't really understand what he means.

**Comment by yaroslavvb** [comment]
@isabeaups the two gradients can differ significantly when there are non-linear operators, as is the case for neural networks.

As a toy example, suppose there's some operation that when f(x)=1, and you compute gradient, one of the backprop operators overflows and causes NaN, which is a valid float32 value. If you want to backprop from vector [1,2], you are going to have to do full backprop from 1, and from 2. There's no shortcut that'll let you keep same size intermediate matrices and be able to backprop from both values in parallel

**Comment by shoyer** [comment]
I'm reopening this issue since I think it's still a valid feature request -- @yuanbyu comment https://github.com/tensorflow/tensorflow/issues/675#issuecomment-241961454 from last year closing it doesn't make sense to me.

One simple way to implement this in TensorFlow -- though possibly not the most efficient -- is with `tf.reshape`, `tf.map_fn` and `tf.gradients`:
```python
def jacobian(y, x):
  def fn(y_i):
    (result,) = tf.gradients(y_i, x)
    return result
  y_flat = tf.reshape(y, (-1,))
  jacobian_flat = tf.map_fn(fn, y_flat)
  return tf.reshape(jacobian_flat, y.shape.concatenate(x.shape))
```
Example usage:
```
>>> x = tf.ones((3,))
>>> y = x ** 2
>>> jacobian(y, x)
<tf.Tensor 'Reshape_6:0' shape=(3, 3) dtype=float32>
```

Could simply add `tf.jacobian` to the TensorFlow API and keep `tf.gradients` unchanged?

**Comment by harpone** [comment]
@shoyer I can't get your `jacobian` to work (seems like a similar issue to [here](https://github.com/tensorflow/tensorflow/issues/675#issuecomment-215130212)). Here's a minimal example:

```
tf.reset_default_graph()

x = tf.placeholder(tf.float32, shape=[3])
y = x ** 2 / 2

jac = jacobian(y, x)

sess = tf.Session()

x_val = np.random.randn(3).astype(np.float32)

jac_val = sess.run(jac, feed_dict={x: x_val})
```

I get
`InvalidArgumentError: TensorArray map/TensorArray_16@map/while/gradients: Could not write to TensorArray index 1 because it has already been read.`

**Comment by harpone** [comment]
Just a FYI for anyone who happens to stumble here looking for a `tf.jacobian`: this seems to work (props to @yaroslavvb):

```
N = 3

tf.reset_default_graph()

x = tf.placeholder(tf.float32, shape=[N])
y = x ** 2 / 2

y_list = tf.unstack(y)
jacobian_list = [tf.gradients(y_, x)[0] for y_ in y_list]  # list [grad(y0, x), grad(y1, x), ...]
jacobian = tf.stack(jacobian_list)

sess = tf.Session()

x_val = np.random.randn(N)
jacobian_val = sess.run(jacobian, feed_dict={x:x_val})

print(x_val)
print(jacobian_val)
```
Indeed seems pretty slow for bigger values of N... would be nice to get the `map_fn` method to work (if it's going to be faster).

**Comment by shoyer** [comment]
@harpone oops -- good catch! Apologies for posting untested code :). (The version that I actually got working on Friday used a static loop, but then I mistakenly assumed `tf.map_fn` would simplify it.)

**Comment by jjough** [comment]
@shoyer @harpone here's mine -- works for high-dimensional Jacobians (numerator and denominator have >1 dimension), undefined batch sizes, and tensors that are not statically known. 

Remember to use an interactive session, otherwise `tf.get_default_session()` will not be able to find the session.

```python
def tf_jacobian(tensor2, tensor1, feed_dict, sess = tf.get_default_session()):
    """
    Computes the tensor d(tensor2)/d(tensor1) recursively.
    :param tensor2: numerator of Jacobian
    :param tensor1: denominator of Jacobian
    :param feed_dict: input data (need this if tensors are not statically known)
    :return: a tensor of dimension (dim_tensor2 x dim_tensor1)
    """
    # can't do tensor.get_shape() because it doesn't work for undefined batch size
    shape = list(sess.run(tf.shape(tensor2), feed_dict))
    if shape:
        # split tensor2 along first dimension and recur
        # int trick from https://github.com/tensorflow/tensorflow/issues/7754
        tensor2_split = tf.split(axis = 0, num_or_size_splits = int(shape[0]), value = tensor2)
        grad_split = [tf_jacobian(tf.squeeze(M, squeeze_dims = 0), tensor1, feed_dict) for M in tensor2_split]
        return tf.stack(grad_split)
    else:
        # calculate gradient of scalar
        grad = tf.gradients(tensor2, tensor1)
        if grad[0] != None:
            return tf.squeeze(grad, squeeze_dims = [0]) 
        else:
            # replace any undefined gradients with zeros
            return tf.zeros_like(tensor1)
```

And here's one for batched tensors:

```python
def batch_tf_jacobian(tensor2, tensor1, feed_dict, sess = tf.get_default_session()):
    """
    Computes the matrix d(tensor2)/d(tensor1) recursively.
    Tensorflow doesn't really have its own Jacobian operator
    (tf.gradients sums over all dims of tensor2).

    :param tensor2: numerator of Jacobian, first dimension is batch
    :param tensor1: denominator of Jacobian, first dimension is batch
    :param feed_dict: input data (need this if tensors are not statically known)
    :return: batch Jacobian tensor
    """
    shape2 = list(sess.run(tf.shape(tensor2), feed_dict))
    shape1 = list(sess.run(tf.shape(tensor1), feed_dict))
    
    jacobian = tf_jacobian(tensor2, tensor1, feed_dict) 
    batch_size = shape2[0]
    
    batch_jacobian = [tf.slice(jacobian, [i] + [0]*(len(shape2)-1) + [i] + [0]*(len(shape1)-1),  [1] + [-1]*(len(shape2)-1) + [1] + [-1]*(len(shape1)-1)) for i in range(batch_size)]
    batch_jacobian = [tf.squeeze(tensor, squeeze_dims = (0, len(shape2))) for tensor in batch_jacobian]
    batch_jacobian = tf.stack(batch_jacobian)
    return batch_jacobian
```

**Comment by liber145** [comment]
@shoyer Hi. Thanks for your example to compute jocabian. Computing jocabian by gradients in an `for` iteration is quite slow. Is there a way to use `map_fn` method to accelerate computing?

**Comment by alextp** [comment]
There is no current plan to accelerate computing jacobians. Even if while loops were fixed to be differentiable you wouldn't get a substantial speedup after graph building time, I think.

**Comment by jjough** [comment]
Ok, thanks.

**Comment by tillahoffmann** [comment]
I've played a bit with using `while_loop` to build Hessians. The graph build time is significantly reduced (about an order of magnitude). Unfortunately, the evaluation time seems to be worse (about a factor of three worse). Full details here: https://gist.github.com/tillahoffmann/003f3bcb9639a18253ec7854abcbea01 Would be nice if we could get the best of both worlds.

**Comment by oborchers** [comment]
Hey there! I have been going through some of the solutions to compute J, however, all of them seem to be non feasible in a case where the dim of x is large. Even in the small mnist case with only 20 hidden units and a batch size of 32 it is infeasible to compute j(h, x).

**Comment by jeisses** [comment]
@liber145 I have to compute semi-large Jacobians and am also having performance issues using a for loop.

After looking at the code by @tillahoffmann I came up with the following function, which gives a decent speedup for larger N:

``` python
def jacobian(y_flat, x):
    n = y_flat.shape[0]

    loop_vars = [
        tf.constant(0, tf.int32),
        tf.TensorArray(tf.float32, size=n),
    ]

    _, jacobian = tf.while_loop(
        lambda j, _: j < n,
        lambda j, result: (j+1, result.write(j, tf.gradients(y_flat[j], x))),
        loop_vars)

    return jacobian.stack()
```
In my case speed is similar to Theano's [`jacobian`](http://deeplearning.net/software/theano/library/gradient.html#theano.gradient.jacobian) function

**Comment by tillahoffmann** [comment]
@jeisses, the implementation of `hessians` on the `master` branch looks very similar to the one you suggested (see [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/gradients_impl.py#L941)).

**Comment by jeisses** [comment]
@tillahoffmann, yes, I did derive the function directly from that code :smile:. 

But I'm looking for just a Jacobian matrix, doesn't the `hessians` function contain second order derivates, and still use aggregated gradients? Or could I use the `hessians` function for this?

Thanks

**Comment by tillahoffmann** [comment]
@jeisses, of course, my bad. In fact, it would be great if we could integrate your proposed Jacobian implementation and simply implement the hessian as `hessian(y, x) = jacobian(gradient(f, x), x)`.

**Comment by shaifugpt** [comment]
@shoyer  I used your version to compute the value of Jacobian passing y=model.total_loss and x=weights. The value of jacobian for different weights is exactly same as the value of gradients. Why is to so

**Comment by candidj0** [comment]
@shaifugpt take a look to your output function,  the functions here work for a y = [y0, y1, ...], your output is surely [[y0,y1, ...]] so you can try :

```
def jacobian(y, x):
    y_list = tf.unstack(y[0])
    jacobian_list = [tf.gradients(y_, x)[0] for y_ in y_list]  # list [grad(y0, x), grad(y1, x), ...]
    return tf.stack(jacobian_list)
```
or 

```
def jacobian(y, x, size_y):
    n = size_y
    loop_vars = [
        tf.constant(0, tf.int32),
        tf.TensorArray(tf.float32, size=n),
    ]
    _, jacobian = tf.while_loop(
        lambda j, _: j < n,
        lambda j, result: (j+1, result.write(j, tf.gradients(y[0][j], x))),
        loop_vars)
    return jacobian.stack()
```
where size_y is the size of the output of your model.

**Comment by shaifugpt** [comment]
Hi,

I tried the suggestions. But these are errors I get.

In the first one, y_list = tf.unstack(y[0]) gives error. I am computing the
jacobian of model.total_loss wrt model.trainable_weights. So it gives
error: Index out of range using input dim 0; input has only 0 dims for
'strided_slice_4' (op: 'StridedSlice') with input shapes: [], [1], [1], [1]
and with computed input tensors: input[3] = <1>.

In the second one, model.out.shape is (40,10) where 40 is batch size and 10
is dimension. It gives error in syntax: def jacobian(y,
x,(model.output.shape):

**Comment by candidj0** [comment]
Sorry @shaifugpt, try this one : 
``` 
def jacobian(y, x, n):
    y_list = tf.unstack(y, num = n)
    jacobian_list = [[tf.gradients(y_, x)[0][i] for y_ in tf.unstack(y_list[i])] for i in range(n)] # list [grad(y0, x), grad(y1, x), ...]
    return y_list, tf.stack(jacobian_list)
```
n is the batch size.

**Comment by shaifugpt** [comment]
Hi

I tried your code. But I could not understand why did you unstack y i.e
model.total_loss in my case. Your code is giving error: ValueError: Invalid
axis: 0; must be in [0,0) for 'unstack_25' (op: 'Unpack') with input
shapes: []. This is because model.total_loss has shape: <tf.Tensor
'mul_1:0' shape=() dtype=float32>

**Comment by oborchers** [comment]
@jeisses I am somewhat confused by the implementation because of the resulting shape of J.

According to [https://en.wikipedia.org/wiki/Jacobian_matrix_and_determinant](url)
Let f: R^n -> R^m , then the J(f) is a m * n matrix. Given, that the input has a size s, J should be a s * m * n matrix, which the implementation of @candidj0 gives us. (However, it is slow due to the for loop.)

Both solutions require the input size to be determined, i.e. [None, n] doesn't work

Setting s = 1, version one gives (1, 1, 1, 500)  and version two gives (1, 10, 500), whereas an s=20 is outputting (20, 1, 20, 500) and (20, 10, 500).

Have I missed a point somewhere in the implementation (because I really like to get that speedup)?

```
import tensorflow as tf
import numpy as np

def jacobian_1(y_flat, x):
    n = y_flat.shape[0]

    loop_vars = [
        tf.constant(0, tf.int32),
        tf.TensorArray(tf.float32, size=n),
    ]
    _, jacobian = tf.while_loop(
        lambda j, _: j < n,
        lambda j, result: (j+1, result.write(j, tf.gradients(y_flat[j], x))),
        loop_vars)
    return jacobian.stack()


def jacobian_2(y, x, n):
    y_list = tf.unstack(y, num = n)
    jacobian_list = [[tf.gradients(y_, x)[0][i] for y_ in tf.unstack(y_list[i])] for i in range(n)] # list [grad(y0, x), grad(y1, x), ...]
    return tf.stack(jacobian_list)


s = 1
n = 500
m = 10

x = tf.placeholder(tf.float32, [s, n])
w = tf.Variable(tf.truncated_normal([n, m], stddev=0.1))
b = tf.Variable(tf.constant(0.1, shape=[m]))
y = tf.matmul(x, w) + b

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

j = jacobian_1(y, x)
j_out = sess.run(j, feed_dict={x:np.random.rand(s,n)})
print(j_out.shape)

j_2 = jacobian_2(y,x, s)
j_out = sess.run(j_2, feed_dict={x:np.random.rand(s,n)})
print(j_out.shape)
```

**Comment by ModarTensai** [comment]
For me, I prefer computing the Jacobian matrix outside the graph using very lightweight operations.
I compute the Jacobian for each point in batches then I stack them at the end
Here is a running example based on @oborchers example:
```
import time
import numpy as np
import tensorflow as tf


def jacobian(session, y, x, p, batch_size):
    """The Jacobian matrix of `y` w.r.t. `x` at `p`

    Let f(x) be some function that has a Jacobian A at p
    then, f(p) = y = Ap+b
    where A of shape mxn, p of shape nx1 and b of shape mx1

    Args:
        model: A Classifier that has a graph open session
        y: The output tensor
        x: The input tensor
        p: The points of linearization
        batch_size: How many rows of the Jacobian to compute at once

    Returns:
        The Jacobian matrices for the given points
    """
    # add gradient layer to model graph only if it was not added before
    name = y.op.name.replace("/", "_")
    if not hasattr(session, name):
        g = {}
        with session.graph.as_default():
            g["mask"] = tf.placeholder(y.dtype, name="mask_" + name)
            g["grad"] = tf.gradients(g["mask"] * y, x, name="grad_" + name)[0]
            setattr(session, name, g)
    else:
        g = getattr(session, name)

    jacobian_list = []
    for i in range(p.shape[0]):
        # extract the Jacobian matrix for a single point
        batches_list = []
        point = p[i:i + 1, :]
        shape = y.shape.as_list()[1:]
        for mask in masks_batches(shape, batch_size):
            batch_size = mask.shape[0]
            feed = {g["mask"]: mask, x: np.vstack([point] * batch_size)}
            batches_list.append(session.run(g["grad"], feed_dict=feed))
        jac = np.vstack(batches_list)

        # reshape it as a matrix (not necessary but sometimes desirable)
        # you can uncomment the following line if a 2D matrix is required
        # jac = jac.reshape(jac.shape[0], -1)

        jacobian_list.append(jac)

    return np.stack(jacobian_list)


def masks_batches(shape, batch_size):
    """Batches iterator over all possible masks of the given shape

    A mask is a numpy.ndarray of shape `shape` of all zeros except
    for a single position it is one. It is useful to get those masks
    in batches instead of getting them one by one.

    Args:
        shape: The shape of each mask
        batch_size: How many masks to return in each iteration

    Returns:
        A batch of masks of shape [batch_size, *shape]
    """
    num_rows = np.prod(shape)
    if num_rows < batch_size:
        batch_size = num_rows

    _mask = np.zeros((batch_size, *shape))
    mask = _mask.reshape(batch_size, -1)

    num_batches = -(-num_rows // batch_size)
    for i in range(num_batches):
        start = i * batch_size
        end = min(start + batch_size, num_rows)

        # check if last batch is smaller than batch size
        if end - start < batch_size:
            batch_size = end - start
            _mask = np.zeros((batch_size, *shape))
            mask = _mask.reshape(batch_size, -1)

        mask[:, start:end] = np.eye(batch_size)
        yield _mask
        mask[:, start:end] = 0


if __name__ == '__main__':
    n = 500
    m = 10
    s = 20

    x = tf.placeholder(tf.float32)
    w = tf.Variable(tf.truncated_normal([n, m], stddev=0.1))
    b = tf.Variable(tf.constant(0.1, shape=[m]))
    y = tf.matmul(x, w) + b

    init = tf.global_variables_initializer()
    sess = tf.Session()
    sess.run(init)

    start = time.time()
    j_out = jacobian(sess, y, x, np.random.rand(s, n), m)
    w_out = sess.run(w)
    # they should be equal and output ~< 1e-6 (single precision)
    print(np.linalg.norm(w_out.T - np.mean(j_out, axis=0)))
    print(str(int(time.time() - start)) + " Seconds: " + str(j_out.shape))

```

**Comment by candidj0** [comment]
@oborchers i don't check the time but maybe you can try :

```
def body(y, x, i):
    n = tf.shape(y)[0]
    loop_vars = [
        tf.constant(0, tf.int32),
        tf.TensorArray(tf.float32, size=n),
    ]
    _, jacobian = tf.while_loop(
        lambda j, _: j < n,
        lambda j, result: (j+1, result.write(j, tf.gradients(y[j], x)[0][i])),
        loop_vars)
    return jacobian.stack()

def tf_jacobian(y, x, n):
    loop_vars = [
        tf.constant(0, tf.int32),
        tf.TensorArray(tf.float32, size=n),
    ]
    _, jacobian = tf.while_loop(
        lambda i, _: i < n,
        lambda i, result: (i+1, result.write(i, body(y[i], x, i))),
        loop_vars)
    return jacobian.stack()
```

jacobians =  tf_jacobian(y, x, n) where n is the batch size.

**Comment by aribenjamin** [comment]
@ModarTensai this is great! Thank you. 

It produces an error for me, though, when `m=1`. I'd like to use this to produce per-example gradients of a single-valued output, so my application will have `m=1` as well. Is there an easy fix you know of, before I dig in?

**Comment by ModarTensai** [comment]
@aribenjamin If m = 1, w is a vector not a matrix but I fixed and updated the code
all what have been changed is line 53 from 
```python
repeated_point = np.zeros(1)
```
to 
```python
repeated_point = point
```
Thanks for noticing the bug!

**Comment by oborchers** [comment]
@ModarTensai and @candidj0 : Awesome guys! You rock, thank you! I'll test them over the weekend and see how they work on a toy dataset.

**Comment by czhang96** [comment]
> There are no built-in jacobians in TensorFlow, instead anything called
'grad' or 'gradient' computes Jacobian-vector product (also called LOp in
theano),

Sanity checking, but LOp is vector-Jacobian product, not Jacobian-vector product, correct?

**Comment by mholzel** [comment]
Nobody seems to have posted any followup, but the codes proposed by @candidj0 and @jeisses do not work when nested (testing in tensorflow 1.5.0). So computing the hessian by nesting will not work (@tillahoffmann). Let me make this a bit more concrete. I am using the jacobian

```
def map(f, x, dtype=None, parallel_iterations=10):
    '''
    Apply f to each of the elements in x using the specified number of parallel iterations.

    Important points:
    1. By "elements in x", we mean that we will be applying f to x[0],...x[tf.shape(x)[0]-1].
    2. The output size of f(x[i]) can be arbitrary. However, if the dtype of that output
       is different than the dtype of x, then you need to specify that as an additional argument.
    '''
    if dtype is None:
        dtype = x.dtype

    n = tf.shape(x)[0]
    loop_vars = [
        tf.constant(0, n.dtype),
        tf.TensorArray(dtype, size=n),
    ]
    name = str(random.randint(1, 1000000000))
    _, fx = tf.while_loop(
        lambda j, _: j < n,
        lambda j, result: (j + 1, result.write(j, f(x[j]))),
        loop_vars,
        parallel_iterations=parallel_iterations,
        name=name
    )
    return fx.stack()

def jacobian(fx, x, parallel_iterations=10):
    '''
    Given a tensor fx, which is a function of x, vectorize fx (via tf.reshape(fx, [-1])),
    and then compute the jacobian of each entry of fx with respect to x.
    Specifically, if x has shape (m,n,...,p), and fx has L entries (tf.size(fx)=L), then
    the output will be (L,m,n,...,p), where output[i] will be (m,n,...,p), with each entry denoting the
    gradient of output[i] wrt the corresponding element of x.
    '''
    fx_vec = tf.reshape(fx, [-1])
    return map(lambda fxi: tf.gradients(fxi, x, name=name)[0],
               fx_vec,
               dtype=x.dtype,
               parallel_iterations=parallel_iterations)
```

I am using this because it supports dynamic sizes, that is, one of the dimensions can be `None`. 

However, this simple test 

```
    import numpy
    from numpy.random import randn

    numpy.random.seed(0)

    x = randn(3, 3)
    A = randn(2, 3)
    xtf = tf.constant(x, tf.float64)
    Atf = tf.constant(A, tf.float64)
    y = tf.matmul(tf.matmul(Atf, xtf), xtf)
    with tf.Session() as sess:
        # print(sess.run(Ax))
        dydx = jacobian(y, xtf)
        print(sess.run(dydx))
        d2ydx2 = tf.squeeze(jacobian(dydx, xtf))
        print(sess.run(d2ydx2))
```
throws the error 

`ValueError: Cannot use 'while_1/while/gradients/f_count_1' as input to 'while_1/while/gradients/f_count' because they are in different while loops. See info log for more details.
`

Does anybody know the issue here? 
The first jacobian is correct. The second one (essentially the hessian) does not.

**Comment by mholzel** [comment]
I just tested the previous code on the nightly Docker build, and the error remains.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @agarwal-ashish: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @agarwal-ashish: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @agarwal-ashish: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @agarwal-ashish: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dancasas** [comment]
@mholzel I wanted to thank you for that jacobian implementation, seems to work perfectly for a problem I am working on. In my opinion, this capability should be pushed to the main TensorFlow branch, as it is useful in many problems.

**Comment by marcociccone** [comment]
@mholzel Have you found how to nest while loop to make it work?

**Comment by mholzel** [comment]
No. It seems like a really subtle bug in either the gradient or while loop implementation. That requires somebody with a lot more knowledge than me about what is going on there

**Comment by marcociccone** [comment]
damn, thanks anyway... Is there anyone that can help? maybe we can bother @ovrebdo?

**Comment by dancasas** [comment]
@marcociccone in TF 1.4 seems to be working fine, if this is an alternative for you.

**Comment by skye** [comment]
This is indeed a bug in TF. It's caused by taking the gradient(y, x) inside a while loop wrt such that the computation of y from x goes through a different while loop, something like:
```
x = ...
y = while_loop(..., [x])
z = while_loop(..., tf.gradients(y, x), [y])
```

So in @mholzel's script, it's from passing the outcome of one jacobian call to the other jacobian call. (BTW, thanks very much for the easy repro.)

Unfortunately this is quite tricky to fix. I'll try to take another look at it tomorrow and see if I can come up with something.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 16 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by Joshuaalbert** [comment]
@mholzel for the double jacobian, suppose you just map to tf.hessian instead of tf.gradient. Doesn't solve to arbitrary order but it does get the hessian of a tensor wrt variables.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by agarwal-ashish** [comment]
There is now an experimental new approach to doing Jacobians here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/parallel_for/gradients.py#L28

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 32 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @skye: It has been 49 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @agarwal-ashish: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @saxenasaurabh: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by dancasas** [comment]
> There is now an experimental new approach to doing Jacobians here:
> https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/parallel_for/gradients.py#L28

Did anyone compare the performance of the new functionality and the previous solution posted by @mholzel [here](https://github.com/tensorflow/tensorflow/issues/675#issuecomment-362853672)? I am finding the new `jacobian` included in `gradients.py` way slower than @mholzel solution...

**Comment by agarwal-ashish** [comment]
> > There is now an experimental new approach to doing Jacobians here:
> > https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/parallel_for/gradients.py#L28
> 
> Did anyone compare the performance of the new functionality and the previous solution posted by @mholzel [here](https://github.com/tensorflow/tensorflow/issues/675#issuecomment-362853672)? I am finding the new `jacobian` included in `gradients.py` way slower than @mholzel solution...

gradients_test.py in the same file has some benchmarks that show that pfor based jacobian generally works much faster than a while loop based one. Can you share your benchmark ?

**Comment by GJBoth** [comment]
I threw together this function, it uses tf.map_fn and assumes a batch style input, but at least it works for batches. It's pretty high level but seems to adress some of the ideas if the conversation above:
````
def Jacobian(X, y):
    J = tf.map_fn(lambda m: tf.gradients(y[:,:,m:m+1], X)[0], tf.range(tf.shape(y)[-1]), tf.float32)
    J = tf.transpose(tf.squeeze(J), perm = [1,0,2])
    return J
```

**Comment by tensorflowbutler** [comment]
Nagging Assignee @saxenasaurabh: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @saxenasaurabh: It has been 29 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by jvishnuvardhan** [comment]
@zackchase Is this resolved? Please close If it was resolved already. Thanks!

**Comment by agarwal-ashish** [comment]
tf.GradientTape.jacobian and tf.GradientTape.batch_jacobian APIs have been added for computing Jacobians. These are based on experimental pfor logic which can also be disabled to fallback to loop based implementation.
