### ISSUE TITLE
TensorBoard ImportError: No module named werkzeug

### ISSUE THREAD

**Issue by Mazecreator** [tensorflow/tensorflow#7077]
using the current HEAD of tensorflow, I have bumped into an issue when I execute tensorboard.

Version is reported as: 0.12.head
git rev-parse HEAD: a12c7dc3d83049e10c1dca8903d73cc71d3cb7b2
Linux: Linux tensor 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

> 2017-01-25 17:02:36: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcudnn.so.5 locally
2017-01-25 17:02:36: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcufft.so.8.0 locally
2017-01-25 17:02:36: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcuda.so.1 locally
2017-01-25 17:02:36: I tensorflow/stream_executor/dso_loader.cc:125] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 9, in <module>
    load_entry_point('tensorflow', 'console_scripts', 'tensorboard')()
  File "/home/greg/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/greg/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2575, in load_entry_point
    return ep.load()
  File "/home/greg/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2235, in load
    return self.resolve()
  File "/home/greg/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2241, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/greg/tensorflow/_python_build/tensorflow/tensorboard/tensorboard.py", line 26, in <module>
    from werkzeug import serving
ImportError: No module named werkzeug

I see the werkzeug.BUILD file on my system so not sure why it cannot be found.

**Comment by drpngx** [comment]
Just to be clear, you ran configure, built the whl file, installed, and running from there?

/cc @dandelionmane

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/pip_package/setup.py#L38 also lists werkzeug, so it's not clear why pip installing the package would not install werkzeug too.

**Comment by Mazecreator** [comment]
Sorry,

I ran configure and use TensorFlow from source, but don't build the whl, I am setup for "Setting up TensorFlow for Development".  So I use the following:

    # To build with GPU support:
    bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

    mkdir _python_build
    cd _python_build 
    ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/* .
    ln -s ../tensorflow/tools/pip_package/* .
    python setup.py develop

**Comment by vrv** [comment]
I am not super familiar with that style of development: I don't know why calling the setup.py with 'develop' mode doesn't install the required packages.

You should be able to get around this by `pip install werkzeug` manually.

**Comment by Mazecreator** [comment]
I can try the PIP but a little concerned it might cause problems later as the PIP should be bundled with the development install.

Here is the link to the "setting up with TensorFlow for Development":
https://www.tensorflow.org/get_started/os_setup#setting_up_tensorflow_for_development

**Comment by drpngx** [comment]
If you are concerned about polluting your environment, you should run virtualenv. We need `werkzeug` to run.

**Comment by Mazecreator** [comment]
I understand, but wanted to report the break in the current HEAD development build.  This is the first include I have needed to PIP install that appears it should have been installed with bazel.  My only concern is I will not be able to detect when it is corrected in the future.

**Comment by drpngx** [comment]
Right, we are thinking that `setup.py` should have installed it, but for some reason didn't. Is it working for you now?

**Comment by Mazecreator** [comment]
Yes, I will remove the PIP package once you guys determine how to move forward as you could add the package as a prerequisite.

**Comment by drpngx** [comment]
Yes, it looks like it's a documentation issue. According to [stackoverflow](http://stackoverflow.com/questions/28509965/setuptools-development-requirements), the `develop` mode doesn't install the requirements. You have to install them separately. Closing a looping internally to update the doc.

**Comment by TwistedW** [comment]
I also encountered the same problem, but I found the werkzeug package. But still did not solve the problem

**Comment by phipps553** [comment]
I have the same problem with TwistedW ,and still did not solve,too.

**Comment by XiaoxueZang** [comment]
I have the same problem and pip install does not solve it.

**Comment by gunan** [comment]
This is strictly a TB dependency.
You should reach out to tensorboard to look into fixing this dependency in tensorboard pip package.
