### ISSUE TITLE
ld: file not found: -lcudart.8.0 when building CUDA on MacOS and bazel 0.4.4

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#7227]
In today's head https://github.com/tensorflow/tensorflow/commit/b47dc70e548e6958919f87864b83866919473a92, and bazel 0.4.4, bazel building with XLA + CUDA on MacOS fails because it can't find cuda library when linking. I was able to build with the same setup from head from Jan 24 .

```
bazel build --config=cuda --config=opt -k //tensorflow/tools/pip_package:build_pip_package
...
ld: file not found: -lcudart.8.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 0.513s, Critical Path: 0.11s

```

I see `libcudart_static.a` in my `/usr/local/cuda/lib` and similar issue [suggests](http://stackoverflow.com/questions/9633881/usr-bin-ld-cannot-find-lcudart) that linking needs to be done with -L$CUDA_HOME/lib flag, but I can't figure out how to massage that option into bazel config

I also tried building with flags ` --action_env PATH --action_env DYLD_LIBRARY_PATH --action_env LD_LIBRARY_PATH` and copying `libcudart_static.a` to `libcudart.8.0.a`

Note that libcudart dependency dependency exists in CPU-only build as well because of https://github.com/tensorflow/tensorflow/issues/7216

**Comment by normanheckscher** [comment]
I've seen a nearly identical issue. The major difference is that I didn't build with XLA+CUD; I only built with CUDA.

OSX 10.12.3
Retina MacBookPro 10,1 mid 2012.
Nvidia GT 650M
Python 2.7.13 build in a virtual environment from brew with the latest requirements from pip
Latest build requirements from brew (wheel, six, etc)
Latest CUDA 8.0.63
Latest cuDNN 5.1.10

The issue only started after I brew upgraded bazel to 0.4.4 a few days ago.
Reverting my brew install of bazel to 0.4.3 has allowed me to complete compilations and create a pip install package. 

Fixed as follows:
`brew uninstall bazel`
Copy bazel 0.4.3 brew formula from:
https://github.com/Homebrew/homebrew-core/blob/f4c0bf580fc94d31dbe09ddeab35b1ee3ac17c9e/Formula/bazel.rb
Paste this old formula into brew config for bazel:
`brew edit bazel`
Pin this current version of bazel
`brew pin bazel`

The only other issue was that I needed to massage bazel with the following fix:
https://github.com/tensorflow/tensorflow/issues/4187#issuecomment-244722024

For quick reference here is the changelog of bazel:
https://github.com/bazelbuild/bazel/blob/master/CHANGELOG.md

**Comment by hawkinsp** [comment]
I confirmed that this issue is unrelated to XLA --- it's a CUDA on Mac OS X problem:
ERROR: /Users/phawkins/g/tensorflow/tensorflow/python/BUILD:2278:1: Linking of rule '//tensorflow/python:_pywrap_tensorflow.so' failed: link_dynamic_library.sh failed: error executing command external/bazel_tools/tools/cpp/link_dynamic_library.sh no ignored ignored ignored external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -shared -o ... (remaining 432 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
clang: warning: argument unused during compilation: '-pthread'
ld: file not found: -lcublas.8.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by yaroslavvb** [comment]
This problem has been possibly resolved at head, although I won't know for sure until https://github.com/tensorflow/tensorflow/issues/7364 is fixed

**Comment by yaroslavvb** [comment]
I have just checked at head still getting `ld: file not found: -lcudart.8.0` error. when trying to build pip package. The main thing that changed from the last time this build worked was upgrading Bazel to 0.4.4

I notice that your continuous build [failed](https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON3,label=gpu-mac/239/console) with similar error

```
ld: file not found: -lcublas.8.0
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by jhseu** [comment]
This is a Bazel bug. Reported with a simple reproducible test case at https://github.com/bazelbuild/bazel/issues/2526

Building works with Bazel 0.4.3 or below.

**Comment by jhseu** [comment]
Fixed at Bazel head.
