### ISSUE TITLE
A bug with slim.create_global_step

### ISSUE THREAD

**Issue by lsy643** [tensorflow/tensorflow#8190]
When I use **slim.create_global_step** in distributed training, the  **slim.create_global_step** can make the workers freeze just after session has been created.

This can be reproduced by just replacing the `global_step = tf.Variable(0, name="global_step", trainable=False)` with `global_step = slim.create_global_step()` in the **mnist_replica.py** in the [dist_test](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/dist_test/python)

**Comment by linrio** [comment]
This bug has been fixed?

**Comment by prb12** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by lsy643** [comment]
@prb12 The details includes:

1. OS: Ubuntu Server 16.04

2. Hardware: Dell R730 with Tesla K80

3. TensorFlow Version: 1.0 

Besides, the in-graph multi-gpu usage seems to be correct. This is quite strange.

**Comment by lsy643** [comment]
@linrio I just found this bug yesterday, so probably not fixed yet

**Comment by lsy643** [comment]
@prb12 
One thing I forgot to mention is that all my experiments run in nvidia-docker containers. For the distributed training experiment, I create two ps and two workers, so total four containers.

**Comment by lsy643** [comment]
@sguada 
I have run more tests and I think the problem occurs when the **dtype**  of **global_step** is **tf.int64** when **distributed training** is running in **nvidia-docker containers**.

**Comment by sguada** [comment]
Try slim.get_or_create_global_step() instead
Otherwise they are creating different global_step

**Comment by lsy643** [comment]
@sguada 
I have tried slim.get_or_create_global_step(). Still the same problem, the **global_step/sec** just becomes 0 and training freezes just after session created. Since the global_step is created just at the beginning of the graph, it is probably not because different global_step is created

**Comment by wangyum** [comment]
[TensorFlow 1.0.1](https://github.com/tensorflow/tensorflow/releases/tag/v1.0.1) still has this issue.

**Comment by lsy643** [comment]
@wangyum 
I think this may be caused by that the distributed training part can not handle 8-bytes long variables. So just  create a global_step with dtype=tf.int32

**Comment by wangyum** [comment]
@lsy643  Do you mean change [here](https://github.com/tensorflow/tensorflow/blob/0ea7b2bcc2f553b06859b7cbf6962dfc340c868d/tensorflow/python/training/training_util.py#L116) to `dtype=dtypes.int32`?

**Comment by lsy643** [comment]
@wangyum 
Yes, but instead of changing the source code of slim, I just create the global_step myself
```python
global_step` = tf.get_variable(
        'global_step', [], tf.int32,
        initializer=tf.zeros_initializer(), trainable=False)`
```

**Comment by wangyum** [comment]
@lsy643 DataLossError: 
```
  File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

DataLossError (see above for traceback): Invalid size in bundle entry: key global_step; stored size 8; expected size 4
         [[Node: save/RestoreV2_780 = RestoreV2[dtypes=[DT_INT32], _device="/job:ps/replica:0/task:0/cpu:0"](_recv_save/Const_0_S1, save/RestoreV2_780/tensor_names, save/RestoreV2_780/shape_and_slices)]]


        at org.apache.spark.api.python.PythonRunner$$anon$1.read(PythonRDD.scala:193)
        at org.apache.spark.api.python.PythonRunner$$anon$1.<init>(PythonRDD.scala:234)
        at org.apache.spark.api.python.PythonRunner.compute(PythonRDD.scala:152)
        at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:63)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by lsy643** [comment]
@wangyum 
According to you log, `Invalid size in bundle entry: key global_step; stored size 8; expected size 4`
I think there is a dtype mismatch for the global_step variable

**Comment by sguada** [comment]
Re-open if needed

**Comment by maxfiedler** [comment]
I am using TF 1.1 on Ubuntu Xenial 16.04
and I am experiencing the same problem with the new tf.train.get_or_create_global_step() function
When I use it to create my global step variable I get on the following error on executing my MonitoredSession
`tensorflow.python.framework.errors_impl.DataLossError: Invalid size in bundle entry: key global_step/global_step; stored size 4; expected size 8
	 [[Node: save_1/RestoreV2 = RestoreV2[dtypes=[DT_INT64], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2/tensor_names, save_1/RestoreV2/shape_and_slices)]]
	 [[Node: save_1/RestoreV2_4/_3 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_20_save_1/RestoreV2_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
`
When I manually change the dtype in the source of tf.train.get_or_create_global_step() to int32 the error does not show. But this obviously not how it is intended. 

So for now I will go back to creating the global step manually. 

Full error trace: 
`line 107, in main
    step_counter_hook]) as sess:
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 627, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 456, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 800, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 805, in _create_session
    return self._sess_creator.create_session()
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 517, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 393, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/training/session_manager.py", line 256, in prepare_session
    config=config)
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/training/session_manager.py", line 188, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/mfiedler/.tensorflow-venv/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Invalid size in bundle entry: key global_step/global_step; stored size 4; expected size 8`

**Comment by nharada1** [comment]
I'm also running into this bug: If I use `int64` for global_step my training hangs, but if I use `int32` the training runs and the `evaluation_loop` fails when loading the checkpoints because of `Invalid size in bundle entry: key global_step/global_step; stored size 4; expected size 8`

**Comment by nharada1** [comment]
Is there a workaround besides editing the source files in Tensorflow? I'm using the `tensorflow-gpu` package and would prefer not to build from source.

**Comment by nharada1** [comment]
okay, current workaround for me is just to create the `global_step` variable in the evaluation file separately instead of loading it in: `global_step = tf.Variable(0, dtype=tf.int32, name='global_step', trainable=False)`

**Comment by j-wilson** [comment]
Also running into `tf.int32` vs. `tf.int64` issues when using `tf.train.get_or_create_global_step` (this issue seems most closely related). Is there a particular reason why the resulting variable is [hardcoded](https://github.com/tensorflow/tensorflow/blob/0ea7b2bcc2f553b06859b7cbf6962dfc340c868d/tensorflow/python/training/training_util.py#L116) as `tf.int64`? More generally, can the related set of methods be updated to support passing in `dtype` as a keyword argument?

**Comment by wangyum** [comment]
@j-wilson Try Tensorflow 1.2.0.
