### ISSUE TITLE
Linking an Android static library with TFLite GPU using CMake causes undefined symbol errors and can not get the correct install

### ISSUE THREAD

**Issue by alexliyang** [tensorflow/tensorflow#82526]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.18

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04.6 LTS

### Current behavior?

Linking an Android library with libtensorflow-lite.a using CMake with GPU delegate enabled causes undefined symbol errors
and can make install to get a complete include envirment.

### Standalone code to reproduce the issue

```shell
before cmake, do some changes:
tensorflow-2.18.0\tensorflow\lite\tools\cmake\modules\ml_dtypes\cmakelists.txt:
target_include_directories(ml_dtypes INTERFACE
  "
$<BUILD_INTERFACE:$
{ML_DTYPES_SOURCE_DIR}>" "
$<INSTALL_INTERFACE:$
{CMAKE_INSTALL_INCLUDEDIR}>"
  "$<BUILD_INTERFACE:${ML_DTYPES_SOURCE_DIR}/ml_dtypes>" "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/ml_dtypes>")

tensorflow-2.18.0\tensorflow\lite\cmakelists.txt:
change like https://github.com/tensorflow/tensorflow/issues/61312

although do these changes, errors occured like the following log output.

step1:
cmake ../tensorflow-2.18.0/tensorflow/lite -DCMAKE_TOOLCHAIN_FILE=/home/public/tflite/android-ndk-r25c/build/cmake/android.toolchain.cmake \
     -DTFLITE_ENABLE_GPU=ON -DXNNPACK_ENABLE_ARM_BF16=OFF -DANDROID_ABI=arm64-v8a  -DANDROID_PLATFORM=26  \
	 -DTFLITE_HOST_TOOLS_DIR=/home/public/tflite/flatbuffers-master/build/ \
	 -DFLATBUFFERS_FLATC_EXECUTABLE=/home/public/tflite/flatbuffers-master/build/flatc \
     -DTFLITE_ENABLE_INSTALL=ON  -DXNNPACK_ENABLE_ARM_BF16=OFF\
     -DCMAKE_INSTALL_PREFIX=/home/pulic/tflite/local_install
step2: cmake --build . -j
step3: sudo make install
step4: cmake --build . -j -t benchmark_model
```

### Relevant log output

```shell
after step1:
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "eigen" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_flags" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_hash" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_status" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_strings" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_synchronization" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_variant" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "ruy" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "pthreadpool" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_any" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "absl_flat_hash_map" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "xnnpack-delegate" that is not in any export set.
CMake Error: install(EXPORT "tensorflow-liteTargets" ...) includes target "tensorflow-lite" which requires target "XNNPACK" that is not in any export set.

after step4:
[ 97%] Linking CXX executable benchmark_model
ld: error: undefined symbol: eglGetProcAddress
>>> referenced by async_buffers.cc:35 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/async_buffers.cc:35)
>>>               async_buffers.cc.o:(tflite::gpu::AsyncBuffer::MapAHardwareBufferToGlBuffer()) in archive ../../libtensorflow-lite.a
>>> referenced by async_buffers.cc:38 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/async_buffers.cc:38)
>>>               async_buffers.cc.o:(tflite::gpu::AsyncBuffer::MapAHardwareBufferToGlBuffer()) in archive ../../libtensorflow-lite.a
>>> referenced by android_sync.cc:33 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/android_sync.cc:33)
>>>               android_sync.cc.o:((anonymous namespace)::IsGlSupported()::$_0::operator()() const) in archive ../../libtensorflow-lite.a
>>> referenced 3 more times

ld: error: undefined symbol: glGenBuffers
>>> referenced by async_buffers.cc:72 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/async_buffers.cc:72)
>>>               async_buffers.cc.o:(tflite::gpu::AsyncBuffer::AllocateOpenGlBuffer()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: glBindBuffer
>>> referenced by async_buffers.cc:73 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/async_buffers.cc:73)
>>>               async_buffers.cc.o:(tflite::gpu::AsyncBuffer::AllocateOpenGlBuffer()) in archive ../../libtensorflow-lite.a
>>> referenced by async_buffers.cc:85 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/async_buffers.cc:85)
>>>               async_buffers.cc.o:(tflite::gpu::AsyncBuffer::AllocateOpenGlBuffer()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: glBufferData
>>> referenced by async_buffers.cc:83 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/async_buffers.cc:83)
>>>               async_buffers.cc.o:(tflite::gpu::AsyncBuffer::AllocateOpenGlBuffer()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: eglGetDisplay
>>> referenced by android_sync.cc:59 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/android_sync.cc:59)
>>>               android_sync.cc.o:(tflite::gpu::gl::WaitFdGpu(int)) in archive ../../libtensorflow-lite.a
>>> referenced by android_sync.cc:82 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/android_sync.cc:82)
>>>               android_sync.cc.o:(tflite::gpu::gl::CreateFdGpu()) in archive ../../libtensorflow-lite.a
>>> referenced by gl_call.h:84 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/gl_call.h:84)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::Init()) in archive ../../libtensorflow-lite.a
>>> referenced 1 more times

ld: error: undefined symbol: glFinish
>>> referenced by android_sync.cc:97 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/android_sync.cc:97)
>>>               android_sync.cc.o:(tflite::gpu::gl::CreateFdGpu()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: glGetError
>>> referenced by gl_errors.cc:67 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/gl_errors.cc:67)
>>>               gl_errors.cc.o:(tflite::gpu::gl::GetOpenGlErrors()) in archive ../../libtensorflow-lite.a
>>> referenced by gl_errors.cc:71 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/gl_errors.cc:71)
>>>               gl_errors.cc.o:(tflite::gpu::gl::GetOpenGlErrors()) in archive ../../libtensorflow-lite.a
>>> referenced by gl_errors.cc:76 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/gl_errors.cc:76)
>>>               gl_errors.cc.o:(tflite::gpu::gl::GetOpenGlErrors()) in archive ../../libtensorflow-lite.a
>>> referenced 1 more times

ld: error: undefined symbol: eglGetError
>>> referenced by gl_errors.cc:84 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/gl_errors.cc:84)
>>>               gl_errors.cc.o:(tflite::gpu::gl::GetEglError()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: eglBindAPI
>>> referenced by gl_call.h:84 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/gl_call.h:84)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::Init()) in archive ../../libtensorflow-lite.a
>>> referenced by gl_call.h:84 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/gl_call.h:84)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::Init()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: eglGetCurrentContext
>>> referenced by egl_environment.cc:75 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/egl_environment.cc:75)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::Init()) in archive ../../libtensorflow-lite.a
>>> referenced by egl_environment.cc:78 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/egl_environment.cc:78)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::Init()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: eglGetCurrentDisplay
>>> referenced by egl_environment.cc:76 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/egl_environment.cc:76)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::Init()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: eglInitialize
>>> referenced by gl_call.h:84 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/gl_call.h:84)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::Init()) in archive ../../libtensorflow-lite.a
>>> referenced by gl_call.h:84 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/gl_call.h:84)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::Init()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: glDeleteFramebuffers
>>> referenced by egl_environment.cc:59 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/egl_environment.cc:59)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::~EglEnvironment()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: glDeleteTextures
>>> referenced by egl_environment.cc:62 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/egl_environment.cc:62)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::~EglEnvironment()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: glGenFramebuffers
>>> referenced by egl_environment.cc:132 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/egl_environment.cc:132)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::ForceSyncTurning()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: glBindFramebuffer
>>> referenced by egl_environment.cc:133 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/egl_environment.cc:133)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::ForceSyncTurning()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: glGenTextures
>>> referenced by egl_environment.cc:135 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/egl_environment.cc:135)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::ForceSyncTurning()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: glBindTexture
>>> referenced by egl_environment.cc:136 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/egl_environment.cc:136)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::ForceSyncTurning()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: glFramebufferTexture2D
>>> referenced by egl_environment.cc:138 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/egl_environment.cc:138)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::ForceSyncTurning()) in archive ../../libtensorflow-lite.a

ld: error: undefined symbol: glViewport
>>> referenced by egl_environment.cc:144 (/home/public/tflite/tensorflow-2.18.0/tensorflow/lite/delegates/gpu/gl/egl_environment.cc:144)
>>>               egl_environment.cc.o:(tflite::gpu::gl::EglEnvironment::ForceSyncTurning()) in archive ../../libtensorflow-lite.a

ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [tools/benchmark/CMakeFiles/benchmark_model.dir/build.make:682: tools/benchmark/benchmark_model] Error 1
make[2]: *** [CMakeFiles/Makefile2:9168: tools/benchmark/CMakeFiles/benchmark_model.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:9175: tools/benchmark/CMakeFiles/benchmark_model.dir/rule] Error 2
make: *** [Makefile:2652: benchmark_model] Error 2
```

**Comment by alexliyang** [comment]
and when set TFLITE_ENABLE_INSTALL=ON, how to get the full tflite envirment for dev other codes, after exec "sudo make install"?

**Comment by alexliyang** [comment]
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
INFO: Loaded OpenCL library with dlopen.
VERBOSE: Replacing 118 out of 118 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 1 partitions for the whole graph.
ERROR: TfLiteGpuDelegate Init: PRELU: Expected a 3D tensor of shape HxWxC or a 4D tensor of shape 1xHxWxC but got
INFO: Created 0 GPU delegate kernels.
ERROR: TfLiteGpuDelegate Prepare: delegate is not initialized
ERROR: Node number 118 (TfLiteGpuDelegateV2) failed to prepare.
ERROR: Restored original execution plan after delegate application failure.
Could not setup GPU delegate

**Comment by gaikwadrahul8** [comment]
Hi, @alexliyang

I apologize for the delayed response, In Android TensorFlow Lite GPU delegate requires `OpenGL` `ES` and `EGL` for managing the GPU context. To fix the undefined symbol errors you need to make sure that the appropriate `OpenGL` `ES` and `EGL` libraries are linked. This can be done by modifying your `CMakeLists.txt` to include these libraries something like below please refer this similar issue https://github.com/tensorflow/tensorflow/issues/61312 and [TensorFlow Lite C++ minimal example](https://github.com/tensorflow/tensorflow/tree/v2.18.0/tensorflow/lite/examples/minimal) which may help you to solve your issue.


```
target_link_libraries (${PROJECT_NAME}
        PUBLIC
          tensorflow-lite
          GLESv3
          EGL
          android
)
```
If issue still persists or Am I missing something here please let me know ?
Thank you for your cooperation and patience.

**Comment by alexliyang** [comment]
@gaikwadrahul8 Thank you for your response, I refer issue #61312 and other repo to modify the CMakeLists.txt, now I can get the libtensorflow-lite.a , and all ld errors have been fixed.
But I get another error like following , the op PReLu is not supported in tensorflow-lite version 2.18.0?
INFO: Initialized TensorFlow Lite runtime.
INFO: Created TensorFlow Lite delegate for GPU.
INFO: Loaded OpenCL library with dlopen.
VERBOSE: Replacing 118 out of 118 node(s) with delegate (TfLiteGpuDelegateV2) node, yielding 1 partitions for the whole graph.
ERROR: TfLiteGpuDelegate Init: PRELU: Expected a 3D tensor of shape HxWxC or a 4D tensor of shape 1xHxWxC but got
INFO: Created 0 GPU delegate kernels.
ERROR: TfLiteGpuDelegate Prepare: delegate is not initialized
ERROR: Node number 118 (TfLiteGpuDelegateV2) failed to prepare.
ERROR: Restored original execution plan after delegate application failure.
Could not setup GPU delegate
![image](https://github.com/user-attachments/assets/13932146-659f-4a71-9d0a-5994dcebe285)

I check the model, all PReLu are 4D tensor of shape 1xHxWxC. but get the errors.

**Comment by alexliyang** [comment]
I find #39749 discuss this problem, but Now version 2.18.0 is ocurred , how to correct it ?

**Comment by gaikwadrahul8** [comment]
Hi, @alexliyang 
I apologize for the delayed response, I checked the [official documentation](https://ai.google.dev/edge/litert/performance/gpu) and it supports `PRELU` Op if you don't mind could you please give it try by downgrading the TensorFlow version to `2.17.1 or 2.16.1` and see is it working as expected or not ?

If issue still persists please let us know with updated error log for further investigation from our end.

Thank you for your cooperation and patience.

**Comment by alexliyang** [comment]
I check the model, maybe the torch model convert to tflite, prelu op need to be reshaped to hwc or 1hwc . I use flatc to handle the  model ,then the model can be loaded correctly.
thank you very much!
