### ISSUE TITLE
Import Error  Couldn't open CUDA library libcudnn.so.5.

### ISSUE THREAD

**Issue by lunasdejavu** [tensorflow/tensorflow#8898]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
i was installing tensorflow  GPU version on ubuntu x86-64
but I found an error:

` >>> import tensorflow as tf
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: /home/lunasdejavu/Downloads:/usr/local/cuda-8.0/lib64
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3517] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally`

i tried to install again and again follow the instructions 
it is still useless.
I tried the NVIDIA_CUDA-8.0_Samples then make. no error after `all`

can somebody help me... i was working on this setting for almost 24 hours....
### Environment info
Operating System:
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
64 bit
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
i can't use the command

but the packages are cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64.deb
cudnn-8.0-linux-x64-v6.0.tgz

If installed from binary pip package, provide:
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.11.0-cp27-none-linux_x86_64.whl
1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 
 
1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:19:38 2017 (1489666778)
Build timestamp: 1489666778
Build timestamp as int: 1489666778

### What other attempted solutions have you tried?
i searched the manual of th
 cd <installpath>
    export LD_LIBRARY_PATH=`pwd`:$LD_LIBRARY_PATH

    Add <installpath> to your build and link process by adding -I<installpath> to your compile
    line and -L<installpath> -lcudnn to your link line.
### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by aselle** [comment]
From the issue template:
```
Installed version of CUDA and cuDNN:
(please attach the output of ls -l /path/to/cuda/lib/libcud*):
i can't use the command
```
Until you can find out what files are in there, it's going to be hard for you to see if there libcudnn in there, you're going to have difficulty solving the problem. You could install libcudnn in a different directory and add it to your LD_LIBRARY_PATH list.

**Comment by aselle** [comment]
As an aside, this is an error that is covered on the install documentation.
https://www.tensorflow.org/install/install_linux

**Comment by lunasdejavu** [comment]
i still can't fix this problem 
`ls -l /path/to/cuda/lib/libcud*
ls: cannot access '/path/to/cuda/lib/libcud*': No such file or directory
`
but  i knew how to fix the original problem.
Tensorflow  hasn't supported  cudnn 6.0 yet.
so i changed to cudnn5.1. it is working now.

**Comment by PhilJd** [comment]
Just for the sake of completeness regarding the command:
You're supposed to change `/path/to/cuda/lib` to the path on your machine which should be something like `/usr/include/cuda/` or  `/opt/cuda-7.5/` or `/home/username/Downloads/cuda/`.
If everything is working now, you could close the issue.

**Comment by ereli** [comment]
Shouldn't the solution be adding it the permanent library config path? instead of `export LD_LIBRARY_PATH=/usr/local/cuda/lib64/` you can do 
```
sudo sh -c "echo '/usr/local/cuda/lib64\n/usr/local/cuda/lib' >> /etc/ld.so.conf.d/nvidia.conf"

sudo ldconfig
```

**Comment by JT-SV** [comment]
# This is what I did (I think - I've retraced my steps, removing and recreating links and clearing the LD_LIBRARY_PATH in order to reproduce the problem).


(tensorflow)$python
>>>import tensorflow

# Everything breaks loose
[lots of messages]
ImportError: libcudnn.so.5: cannot open shared object file: No such file or directory

# I registered as a developer and downloaded libcudnn.so.6,the latest, as some had suggested. I installed with  dpkg or gdebi (wrapper - cannot remember)
# With these packages/installers things may end up in /etc/alternatives,
or /usr/targets/x86_64/..., with a link to them somewhere not in your paths

# So ... used ln to create a link. I don't care that it's actually libcudnn.so.6 ..
# I'm doing this as an experiment.  Some say 6 works and it's the latest for cuda toolkit 8.

sudo ln -s /etc/alternatives/libcudnn_so /usr/local/cuda/lib64/libcudnn.so.5

# We get this link
# /usr/local/cuda/lib64/libcudnn.so.5 -> /etc/alternatives/libcudnn_so
# Add /usr/local/cuda/lib64 to your LD_LIBRARY_PATH:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64

Then in my tensorflow environment things are quiet

(tensorflow) dude@beauty:~/tensorflow$ python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>>

Hopefully this will work in your system.

**Comment by JT-SV** [comment]
Apologies for the huge text.  I didn't realise it was markdown!!

**Comment by arekaykay** [comment]
I have cudnn7 installed in /opt/cuda/lib64

```
sudo ln -s libcudnn.so.7.0.1 libcudnn.so.5 
```
fixed the 
```
ImportError: libcudnn.so.5: cannot open shared object file: No such file or directory
```

Seems to be working ok. Of course, since cudnn5.1 is the officially supported version, might be setting myself up for future pain!

**Comment by Kevinpsk** [comment]
HI @arekaykay 

I have a strange problem with tensorflow in python3.5. I have cudnn 5.1 in my cuda directory, but tensorflow always complain the following,

`ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory`

I tried to reinstall tensorflow 1.3, but this does not solve my problem. 

I have also tried to create a symbolic link to libcudnn.so.6 by the following,

`sudo ln -s libcudnn.so.5.1.10 libcudnn.so.6`

Although the link was created successfully, but tensorflow still complain the same thing as shown above. 
SO why tensorflow complains not be able to use cudnn 6 when I have cudnn5.1 installed? 

THanks a lot.

**Comment by arekaykay** [comment]
Hi @Kevinpsk ,

What are the contents of the directory where you have you .so files (i.e. output of `ls -al`)?

My workaround was for the case where I had a new version of cudNN (7.0) and tensorflow wanted an old version  (5.1).

Your case seems to be the opposite. TensorFlow wants a version of cudNN (6.0) that is newer than what you have (5.1). Upgrading cudNN might be the answer.

Anyway, I am going to try to upgrade TensorFlow to 1.3 and let you know how it goes. I have cudNN 7.0 installed.

**Comment by arekaykay** [comment]
@Kevinpsk 
After upgrading to `TensorFlow 1.3`, first I got the error
```
ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory
```
Then I did the following
```
cd /opt/cuda/lib64
sudo ln -s libcudnn.so.7.0.1 libcudnn.so.6
```
This fixed the problem. Again, since cudNN 6 is the officially supported version, this might create problems down the line. `TensorFlow 1.4` will be officially on cudNN 7.

So, AFAICT, cudNN upgrade might fix the problem you are seeing.

**Comment by JT-SV** [comment]
If it works, it works.  Nothing is clean or bug free ever.

**Comment by Kevinpsk** [comment]
Hi @arekaykay

Thanks a lot for your help. I remember that I first installed cudnn 6, but neither tensorflow nor theano works. So I switched to cudnn 5.1, and theano works fine with my CNN, but tensorflow complained with the message I posted above. Anyway, since I am training my network now, I will try again with cudnn 6 with tensorflow afterwards. 

Another issue is that it seems that tensorflow 1.3 does not support cudnn 6 (cudnn 5.1 works fine) on windows 7, because it will issue an error. Not sure if this a windows issue or cudnn version issue. 

On tensorflow website, install guide page, it still states that tensorflow requires cudnn5.1, so it will be good if they provide info on which version of tensorflow support which version of cudnn.

Shuokai

**Comment by helxsz** [comment]
when I upgraded the tensorflow 1.3 in ubuntu14.04, I got the same error saying"ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory", while my cudnn is only cudnn5.1. in the path of /usr/local/cuda/lib64, libcudnn.so.5.1.10 is found. what should I do?

**Comment by arekaykay** [comment]
@Kevinpsk 

While the install guide page says that `TensorFlow` requires `cudNN 5.1`,  [release notes for 1.3](https://github.com/tensorflow/tensorflow/blob/r1.3/RELEASE.md) says that all pre-built binaries were built with `cudNN 6`. I suspect the install guide page has not been updated.

@helxsz 
My suggestion would be to upgrade `cudNN 5.1` to `cudNN 6`

**Comment by Kevinpsk** [comment]
@arekaykay and @helxsz

Yeah, upgrading to cudnn v6 solve the problem. 

Thanks

**Comment by VladimirBelov92** [comment]
@Kevinpsk 
hi, it's strange, but even after upgrading to v6 I still get the same error. In cuda/lib64  I have libcudnn.so, libcudnn.so.6 and libcudnn.so.6.0.21 yet same error appears. Is there something which also needs to be changed?

**Comment by Kevinpsk** [comment]
That's strange. There should not be this problem again. Have you tried
create a virtual environment using conda and reinstall python and
tensorflow? Normally this will sort it out.

**Comment by anglil** [comment]
I was using tensor2tensor 1.1.9 on top of tensorflow 1.3.0rc1, and then I upgraded tensor2tensor to 1.2.0 because of a new change I wanted to adopt. However tensor2tensor 1.2.0 installation uninstalled the existing tensorflow and upgraded it to 1.3.0 also. Now tensorflow can't run with the error message

> ImportError: libcudnn.so.6: cannot open shared object file: No such file or directory
while I have libcudnn.so.5.1.10 only. Does upgrading cudnn fix the problem? Or should I create a symln pointing to the existing cudnn?

**Comment by arekaykay** [comment]
Upgrade cudnn to version 6

**Comment by zihuaweng** [comment]
Download the cudnn6 and extract it into lib64 file path, in my case: /usr/local/cuda-8.0/lib64 
Ensure that you append the lib64 file path (/usr/local/cuda-8.0/lib64) to the LD_LIBRARY_PATH environment variable
